### PR TITLE
Move jparse to subdirectory and fix dyn_array bug

### PR DESCRIPTION
**Pull request by xexyl**
This commit involved a lot of changes and it's bound to have some things that might need to be cleaned up or fixed - but not now. It works under both linux and macOS running several different combinations of make all test clobber and the bug_report.sh script (which also has some fixes).

What matter here is that the json parser is now in its own directory jparse with its own Makefile. A few things to note. First is that I had to explicitly disable some warnings - a warning which were already needed before but in the case of CentOS I had to disable it via a different option (it works under macOS also). This is because either the scanner or parser generates a function that is not actually used.

I did NOT move jstrencode or jstrdecode to jparse. I'm not sure if these should be moved over or not. The test scripts still remain in test_ioccc/.

The man pages for run_flex.sh and run_bison.sh have not been moved to jparse/ but they should be and will be in a future commit. This problem might be there for other files including other man pages. If so these will also be fixed later.

This commit also fixes a problem with make test compiling utf8_test.o: namely that I forgot to update the test_ioccc/Makefile to refer to ../dyn_array as a subdirectory so the file dyn_array.o could not be linked in as it was no longer that path. I probably did not have the problem because the object file was still on my system - though that's just a guess.

I had to update the run_flex.sh and run_bison.sh scripts to take a new option which specifies the directory where the grammar file should be in. Defaults to ".". This was needed for bug_report.sh.

A lot more things changed in this commit but it was all done in order to move the json parser to its own directory.

### CODE REVIEW

**Comment by lcn2** [comment]
> I did NOT move jstrencode or jstrdecode to jparse. I'm not sure if these should be moved over or not. The test scripts still remain in test_ioccc/.

Interesting question.  At first glance they are useful to the _JSON parser_ code and directly related to the _IOCCC_ itself.

When you eventually build the _JSON parser repo_, both `jstrencode` and `jstrdecode` should be part of that repo.  Therefore we suggest that both `jstrencode` and `jstrdecode` (plus related src and man pages) be moved under the directory where the _JSON parser_ code will live (i.e., as of the time of this pull request, under `jparse/`.

**NOTE**: We presume that your use of the directory `jparse/` will imply that the _JSON parser repo_ will be called _jparse_.  That is a fine name. nevertheless, there is much importance in a name.  We want to you be sure that is the name of the _JSON parser repo_ you intended to use once it is created as it is easier to rename a directory than a GitHub repo.

> BTW: We hope you see the wisdom of holding off on creating the _JSON parser repo_ for now.  Changes like this, plus bug fixes and testing will very likely impact _JSON parser_ code and related _JSON parser_ test files.  Better to wait until this code is stable.  That event is approaching: our guess is that somewhere after the formal _v1.0 public review of this repo_ and the start of _IOCCCMOCK_ will be a good time for you to finally create the _JSON parser repo_.

We recommend that you follow up this pull request by moving the _JSON parser_ related man pages AND _JSON parser_ test tools under the `jparse/` directory.  You might consider creating `jparse/man/` and `jparse/test_jparse/` for that purpose: in anticipation of the _JSON parser repo_ of you wish.

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl

Sure .. let me know if there's a problem as I somehow anticipate.

**Comment by xexyl** [comment]
> > I did NOT move jstrencode or jstrdecode to jparse. I'm not sure if these should be moved over or not. The test scripts still remain in test_ioccc/.
> 
> Interesting question, @xexyl. At first glance they are useful to the _JSON parser_ code and directly related to the _IOCCC_ itself.
> 

Right.

> When you eventually build the _JSON parser repo_, both `jstrencode` and `jstrdecode` should be part of that repo. Therefore we suggest that both `jstrencode` and `jstrdecode` (plus related src and man pages) be moved under the directory where the _JSON parser_ code will live (i.e., as of the time of this pull request, under `jparse/`.

In that case I will move them over.

> 
> **NOTE**: We presume that your use of the directory `jparse/` will imply that the _JSON parser repo_ will be called _jparse_. That is a fine name. nevertheless, there is much importance in a name. We want to you be sure that is the name of the _JSON parser repo_ you intended to use once it is created as it is easier to rename a directory than a GitHub repo.

Well I only chose that name because you had suggested it.  It's something to think about. Can you think of any other names? I guess json_parser or json_parse or jsonp or some variant of any of those would do as well. But that's a good point - it is easier to rename a directory than a repo.

> 
> > BTW: We hope you see the wisdom of holding off on creating the _JSON parser repo_ for now.  Changes like this, plus bug fixes and testing will very likely impact _JSON parser_ code and related _JSON parser_ test files.  Better to wait until this code is stable.  That event is approaching: our guess is that somewhere after the formal _v1.0 public review of this repo_ and the start of _IOCCCMOCK_ will be a good time for you to finally create the _JSON parser repo_.
> 

I certainly do! It's good for a lot of reasons even besides your points! You think we're approaching that point - but what point do you refer to specifically? The entire mkiocccentry repo being stable?

> We recommend that you follow up this pull request by moving the _JSON parser_ related man pages AND _JSON parser_ test tools under the `jparse/` directory. You might consider creating `jparse/man/` and `jparse/test_jparse/` for that purpose: in anticipation of the _JSON parser repo_ of you wish.

Well some of the man pages at least have already been moved. I have to look at what else has to be moved. I can do that tomorrow (as well as making fixes for anything that might be caused from this move).

Good call on the subdirectory man for that. I didn't think of that. Again assuming jparse is a good enough name. What do you think?

**Comment by lcn2** [comment]
Under macOS 13.0.1, `make clobber all` fails:

```
...
rm -f -f *.o
rm -f -f utf8_test jnum_chk dyn_test
make -C soup clobber
rm -f -f *.o
rm -f -f .soup
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  dbg.c -c
rm -f dbg_test.c
cp -v -f dbg.c dbg_test.c
dbg.c -> dbg_test.c
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  -DDBG_TEST dbg_test.c -c
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  dbg_test.o -o dbg_test
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  dbg_example.c -c
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  dbg_example.o dbg.o -o dbg_example
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  -I.. chk_sem_auth.c -c
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  -I.. chk_sem_info.c -c
cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  -I.. chk_validate.c -c
make: *** No rule to make target `jparse/Makefile', needed by `jparse'.  Stop.
zsh: exit 2     make clobber all
```

BTW: We note the use of a double `-f` as in:

```
...
rm -f -f *.o
rm -f -f utf8_test jnum_chk dyn_test
make -C soup clobber
rm -f -f *.o
rm -f -f .soup
...
```

**Comment by xexyl** [comment]
> Under macOS 13.0.1, `make clobber all` fails:
> 

Hmm... I also have the most recent version of macOS and I don't see this at all. I'll take a look at the output.


> ```
> ...
> rm -f -f *.o
> rm -f -f utf8_test jnum_chk dyn_test
> make -C soup clobber
> rm -f -f *.o
> rm -f -f .soup
> cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  dbg.c -c
> rm -f dbg_test.c
> cp -v -f dbg.c dbg_test.c
> dbg.c -> dbg_test.c
> cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  -DDBG_TEST dbg_test.c -c
> cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  dbg_test.o -o dbg_test
> cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  dbg_example.c -c
> cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  dbg_example.o dbg.o -o dbg_example
> cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  -I.. chk_sem_auth.c -c
> cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  -I.. chk_sem_info.c -c
> cc -std=gnu11 -O0 -g -pedantic -Wall -Wextra -Werror  -I.. chk_validate.c -c
> make: *** No rule to make target `jparse/Makefile', needed by `jparse'.  Stop.
> zsh: exit 2     make clobber all
> ```
> 
> BTW: We note the use of a double `-f` as in:

Good catch!

**Comment by lcn2** [comment]
> I certainly do! It's good for a lot of reasons even besides your points! You think we're approaching that point - but what point do you refer to specifically? The entire mkiocccentry repo being stable?

Perhaps after the general public has had some time (several weeks to a few months - during which time we can shift our attention to the sbiumit server and the web site rebuild) to review the 1.0 release of this repo, and whatever bug fixes and enhancements (if any) have been applied.

**Comment by xexyl** [comment]
> > I certainly do! It's good for a lot of reasons even besides your points! You think we're approaching that point - but what point do you refer to specifically? The entire mkiocccentry repo being stable?
> 
> Perhaps after the general public has had some time (several weeks to a few months - during which time we can shift our attention to the sbiumit server and the web site rebuild) to review the 1.0 release of this repo, and whatever bug fixes and enhancements (if any) have been applied.

Okay.

Well as for the issue you encountered: I have something I need to do and then I'll see if I can figure it out quickly. If I can I'll do a fix .. else I'll fix it tomorrow.

**Comment by lcn2** [comment]
> Good call on the subdirectory man for that. I didn't think of that. Again assuming jparse is a good enough name. What do you think?

The name _jparse_ is a fine name we think.  Nevertheless it will be your repo under your GitHub username.  We think that short names are better.

**Comment by xexyl** [comment]
> > Good call on the subdirectory man for that. I didn't think of that. Again assuming jparse is a good enough name. What do you think?
> 
> The name _jparse_ is a fine name we think. Nevertheless it will be your repo under your GitHub username. We think that short names are better.

Well since we worked on it together and since I don't really have any ideas I'll go with your idea.

**Comment by xexyl** [comment]
As for the double `-f`: an interesting thing is I see it in the bug report I last did (I mean the script) but I don't see it in any other file:

```sh
 grep -r -- '-f -f'                          
./bug-report.20221120.130908.txt:rm -f -f *.o
./bug-report.20221120.130908.txt:rm -f -f utf8_test jnum_chk dyn_test
./bug-report.20221120.130908.txt:rm -f -f *.o
./bug-report.20221120.130908.txt:rm -f -f .soup
```

Well as I said I have to take care of something .. will see if I can look at the other thing soon.

**Comment by xexyl** [comment]
Okay I believe I have the other issue fixed. Not sure why the double `-f` though. Looking at it a bit more and then will do a commit.

**Comment by xexyl** [comment]
... something else...

I left the json semantics table files out of `jparse/` because that's specific to the chkentry code. This is correct, right? Or do we want a rule that makes it also under jparse/?

**Comment by xexyl** [comment]
I don't know _why_ the `-f` is happening but I know how to fix it. I'm looking at the other Makefiles that have it as well and then I'll do a commit to fix the problem you encountered as well as the double `-f`.

**Comment by xexyl** [comment]
For both issues see https://github.com/ioccc-src/mkiocccentry/pull/420/commits/f17c2480b02d9faab3e1dc27391c815ecfc04e3d.

I forgot to say in the log that I also added a `*.o` to the make clobber in the main Makefile. Maybe the others need it too - not sure. If you think so I can do that tomorrow.

Hope you have a good night! Please let me know if you encounter any other problems. I'll be thankful if the above one is all that is there but I'll also be surprised if that's the case! As you pointed out the other day major changes does sometimes lead to problems - there are some risks at times when it comes to this type of thing.

Will be here a bit longer but done for the day.

**Comment by lcn2** [comment]
> ... something else...
> 
> I left the json semantics table files out of `jparse/` because that's specific to the chkentry code. This is correct, right? Or do we want a rule that makes it also under jparse/?

The `soup/chk.*` files are IOCCC specific and do not belong with the _JSON parser_.  However things like `jsem*` and `json_sem.*` and `jstr*` DO belong with the _JSON parser_.

**Comment by xexyl** [comment]
> > ... something else...
> > I left the json semantics table files out of `jparse/` because that's specific to the chkentry code. This is correct, right? Or do we want a rule that makes it also under jparse/?
> 
> The `soup/chk.*` files are IOCCC specific and do not belong with the _JSON parser_. However things like `jsem*` and `json_sem.*` and `jstr*` DO belong with the _JSON parser_.

Even when the parser is moved to its own repo though ?

But of course soup/ won't be there.

**Pull request merged**
