### PR TITLE
Change typeset to declare in *.sh and new version of bug_report.sh (modularise it) + add version to several scripts

### PR DESCRIPTION
**Pull request by xexyl**
It appears that typeset is just an alias for declare so make it declare:

    $ help typeset
    typeset: typeset [-aAfFgiIlnrtux] [-p] name[=value] ...
	Set variable values and attributes.

	A synonym for `declare'.  See `help declare'.

This commit is also part of a test to make sure that my fork is okay as something happened that made me fear that I might have to re-fork.

### CODE REVIEW

**Comment by xexyl** [comment]
... all good with the fork at least but it's still something to keep I think.

**Comment by xexyl** [comment]
With commit https://github.com/ioccc-src/mkiocccentry/pull/366/commits/6a62665e77de2cf0b338b0feca482e8411d6d371 I have modularised bug_report.sh and it is much easier to maintain now. It also helps with exit codes. As I did note though if there is a reason to not have it this way I did think of another way to identify commands (and exit codes). It would not be as modular though.

    Release bug_report.sh version 0.3 - make modular
    
    In order to make the script much easier to maintain it is now much more
    modular. Instead of having to repeat basically the same code over and
    over again it is in a single loop (or two if you count the check for
    execute bit and running -h on each tool). The loop also controls the
    exit code as well as the command number (see below) so that it's easy to
    add a new command in the list even if one of the commands has to be
    somewhere in the list (one would have to update the base codes i.e. the
    index but that wouldn't take much time). To add a command all one has to
    do is add an element to the new COMMANDS array (making sure to double
    quote it) and add a comment as to what it is and its purpose.
    
    This might or might not be called experimental but I think it's a good
    change with perhaps one downside (not sure it is a downside though): you
    can't go to a specific line in the script and determine what command
    will run.  However you can easily identify which command it is in the
    array simply by the index and one could easily update the loop so it
    says what command number it is.
    
    Also the script will say what is about to be run and this seems like
    a vast improvement as it makes the script much easier to maintain and as
    a bonus it's more compact as well. If however there is reason to not
    have it this way I have thought of another way to help with the exit
    code issue as well. It would not be as modular but it would at least
    make it a bit easier to identify the command to run (in fact, as noted
    above, this commit adds what amounts to an identification number for
    each command which I think is also a bonus).
    
    Finally the script now calls ./run_bison.sh -v 1 and ./run_flex.sh -v 1.
    
    I believe that makes comment
    https://github.com/ioccc-src/mkiocccentry/issues/248#issuecomment-1153283608
    almost entirely complete. The only things left to be done (besides the
    things not explicitly stated because they weren't thought of yet) is
    that not all scripts have versions in the help/usage string. These can
    be added later.

I thought of this change sometime last night. And with that I'm going to take a break. Might try resting. I doubt I can sleep but I hope I can at least rest. Hope you're having a good sleep.

**Comment by xexyl** [comment]
... shutting down laptop now. Might return to this later today.

**Comment by xexyl** [comment]
.. with commit https://github.com/ioccc-src/mkiocccentry/pull/366/commits/5f6d0a81c022bb1a17cbc7970f39e3899421aa58 I believe all scripts now have a version except for two cases where there's a problem with this and which I therefore would ask you to address as they're both an issue that I am not sure I can solve. I mean I can solve it but I'd rather not given the scripts in question.

First: iocccsize_test.sh already has a `-V` flag but it runs `./iocccsize -V`.

Second: `jsemcgen.sh` has another problem. Actually two. First of all the help suggests that it prints the version but there is not only no version string but it actually does something else which can be seen in the script:

```sh
    V) CAP_V_FLAG="-V";
       JSEMTBLGEN_ARGS="$JSEMTBLGEN_ARGS -V";
       ;;
```

I'm not sure what to do about this one.

I probably won't do much more for the day I'm afraid. Feeling kind of low. I do think the next thing is to update hostchk to try test compiling a some C code that isn't just a test of system header files. I'm not sure what else has to be added to it and as far as bug report script goes I'm also not sure what else needs to be done.

Anyway doing something else now I think.

**Comment by xexyl** [comment]
Just converted this to a draft because I'm not actually sure of the array. I think it's good for testing purposes and for development purposes but I'm not sure it's a good thing in the end. It does make it easier to add commands but looking at it again I'm not sure. I might want to undo that change and keep the other commits. However as I noted in another comment I'm not feeling well today (another good reason to not work on it now) so I'm going to look at it another time.

If necessary I can either undo it or delete the branch and redo it entirely. I'd like your thoughts on it with these thoughts in mind - experimental and developmental purposes - but for now I don't have the energy to deal with it. This week has been quite difficult. 

I do think that once all commands are added it could then be converted back to the normal way but I'll discuss it with you first. This might just be me doubting myself but I really don't know. Anyway that's why I'm off to do something else for the rest of the day.

**Comment by lcn2** [comment]
> This week has been quite difficult.

Hope your next week will be better.

**Comment by lcn2** [comment]
We suggest you not try to put too many different type of things into a pull request.  Why not build a pull request containing just man page updates and typo fixes?

**Comment by xexyl** [comment]
> > This week has been quite difficult.
> 
> Hope your next week will be better.

Thank you. Was I right to convert it to a draft? If so I'll redo it but not today probably. Going to watch a sitcom I think.

**Comment by xexyl** [comment]
> We suggest you not try to put too many different type of things into a pull request. Why not build a pull request containing just man page updates and typo fixes?

There's that thought too. I'm not sure of how having more than one pull request open at a time will work.

**Comment by lcn2** [comment]
Instead of an array of actions and computed exit code outcomes (which as stated before have their own sets of issues), use a shell function that takes args such as 'command' and 'exit code'?

See `prep.sh` for an example of how to do this.

**Comment by xexyl** [comment]
> > We suggest you not try to put too many different type of things into a pull request. Why not build a pull request containing just man page updates and typo fixes?
> 
> There's that thought too. I'm not sure of how having more than one pull request open at a time will work.

Actually I probably will do that next - man pages and the versions added to the scripts (with he exception of the two I mentioned in an above comment).

**Comment by xexyl** [comment]
> Instead of an array of actions and computed exit code outcomes (which as stated before have their own sets of issues), use a shell function that takes args such as 'command' and 'exit code'?
> 
> See `prep.sh` for an example of how to do this.

I actually thought of that too - well a function doing it. It could I guess take an exit code too though I'm not sure of that.

**Comment by lcn2** [comment]
> > > This week has been quite difficult.
> 
> > 
> 
> > Hope your next week will be better.
> 
> 
> 
> Thank you. Was I right to convert it to a draft? If so I'll redo it but not today probably. Going to watch a sitcom I think.

Yes.

**Comment by xexyl** [comment]
> > > > This week has been quite difficult.
> > 
> > 
> > > 
> > 
> > 
> > > Hope your next week will be better.
> > 
> > 
> > Thank you. Was I right to convert it to a draft? If so I'll redo it but not today probably. Going to watch a sitcom I think.
> 
> Yes.

I thought so. I am glad I looked at it again. Good timing too.

**Comment by lcn2** [comment]
> > We suggest you not try to put too many different type of things into a pull request. Why not build a pull request containing just man page updates and typo fixes?
> 
> 
> 
> There's that thought too. I'm not sure of how having more than one pull request open at a time will work.

Perhaps remove from the pull requests, works in progress and submit the "typo / -V / man page fixes" as a self contained pull request.

**Comment by xexyl** [comment]
> > > We suggest you not try to put too many different type of things into a pull request. Why not build a pull request containing just man page updates and typo fixes?
> > 
> > 
> > There's that thought too. I'm not sure of how having more than one pull request open at a time will work.
> 
> Perhaps remove from the pull requests, works in progress and submit the "typo / -V / man page fixes" as a self contained pull request.

What I meant is I'm not sure if you can merge only one branch or not.

**Comment by lcn2** [comment]
> > Instead of an array of actions and computed exit code outcomes (which as stated before have their own sets of issues), use a shell function that takes args such as 'command' and 'exit code'?
> 
> > 
> 
> > See `prep.sh` for an example of how to do this.
> 
> 
> 
> I actually thought of that too - well a function doing it. It could I guess take an exit code too though I'm not sure of that (which I see you even suggested - that's what I mean though with not working on it now .. just too tired :( ).

This is how `prep.sh` sets the exit codes for the actions.  A similar function could be written that performs the command with an value that can be used to set the exit code for later exiting.

**Comment by xexyl** [comment]
> > > Instead of an array of actions and computed exit code outcomes (which as stated before have their own sets of issues), use a shell function that takes args such as 'command' and 'exit code'?
> > 
> > 
> > > 
> > 
> > 
> > > See `prep.sh` for an example of how to do this.
> > 
> > 
> > I actually thought of that too - well a function doing it. It could I guess take an exit code too though I'm not sure of that (which I see you even suggested - that's what I mean though with not working on it now .. just too tired :( ).
> 
> This is how `prep.sh` sets the exit codes for the actions. A similar function could be written that performs the command with an value that can be used to set the exit code for later exiting.

I remember it yes. I think I'll have to look up how to have commands that have more than one arg (as in not just the command name) passed into a function can be executed as a command but that'll be another time - or maybe not. Maybe it doesn't need to be in functions. Another thought I had is that each set of tests would have a range of exit codes so that for example ones related to cc would be separated from those to do with tar and so on.

But I'll worry about that another time. I'm not even sure if functions are worth it in this case. That being said I will try committing the other things now and then worry about `bug_report.sh` another time - hopefully tomorrow.

**Comment by xexyl** [comment]
Just opened a simpler pull request. The bug_report.sh stuff I'll rethink another day. It won't be at least until tomorrow. 

Enjoy the rest of your weekend.

**Comment by lcn2** [comment]
@xexyl: We hope you rest well and have a better next week, good sir!

**Comment by xexyl** [comment]
> @xexyl: We hope you rest well and have a better next week, good sir!

Thank you very much Landon! The same goes to you of course.

Tomorrow morning I have a zoom meeting but if I do anything here it should be before that. It will depend on how tonight goes. I'll be at the laptop a bit longer and then get ready to sleep.

I hope you have a great rest of your day and sleep well when you do!

**Pull request closed without merging**
