### PR TITLE
Update README and minor JSON parser update

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I'm having an off morning so this might be all I do today - the first two commits. I will be taking a break now and will see how I feel after that. I hope I can do more but we'll see. Good day (and good luck getting your Internet access back up)!

**Comment by lcn2** [comment]
Internet still down in the region.

**Comment by xexyl** [comment]
> Internet still down in the region.

That must be really frustrating. Hopefully they can sort it out soon. 

I hope you’re having a good day anyway. I am having an incredibly slow day. I need to get up and do some things and I think I will do that now. Will be afk a bit and then I will be at the laptop for a couple hours maybe and then be done for the day. 

Good luck with the Internet!

**Comment by lcn2** [comment]
Thank you 🙏 kindly @xexyl. Things are starting to get better, but they are not all the way back to normal.

**Comment by xexyl** [comment]
> Thank you 🙏 kindly @xexyl. Things are starting to get better, but they are not all the way back to normal.

That reminds me of something a while back .. I was having some WiFi problems. I wasn't sure what it was but then I had a friend in England tell me she was having WiFi problems also. Turns out there had been a significant solar flare. Then it calmed down several days later. At the time I had a difficult time loading the json website so I ended up saving the grammar to a pdf file so I could look at that.

Not the same thing I'm sure but it does bring up the interesting fact that we're so reliant on so many things that nature on Earth as well as on the Sun can seriously interfere / shut down / etc.

Good that it's getting better - hopefully by tomorrow it'll be all sorted! I'm here for a bit longer and then will be shutting the laptop down.

**Comment by xexyl** [comment]
That's a very funny reaction! Thank you for that - that was very useful as today has been a really frustrating day!

**Pull request merged**
