### PR TITLE
Improve foo

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Going to try sleeping again .. might be able to do more later but if not this should be good anyway.

**Comment by xexyl** [comment]
I don't expect to do anything after commit https://github.com/ioccc-src/mkiocccentry/pull/294/commits/30b0aba89c4f2e90a39e2f83e8006eb429453dd4. It might happen but I'm going to do other things now.

Hope you have a good day.

**Comment by lcn2** [comment]
Thanks 🙏 for the foo improvement @xexyl

**Comment by xexyl** [comment]
> Thanks 🙏 for the foo improvement @xexyl

Happy to help. Hope you have a good day!

**Comment by lcn2** [comment]
@xexyl please see commit 39c63751125ecb58150cd59e7b71b42c9e3cfdab

    Added more foo to bar

    Check error conditions while fubar-ed and try to be foo.

TODO: Please improve empty comments with foo comments.
          If needed, consider improving the non-empty comments
          in a foo appropriate way.

**Comment by xexyl** [comment]
> @xexyl please see commit [39c6375](https://github.com/ioccc-src/mkiocccentry/commit/39c63751125ecb58150cd59e7b71b42c9e3cfdab)
> 
> ```
> Added more foo to bar
> 
> Check error conditions while fubar-ed and try to be foo.
> ```
> 
> TODO: Please improve empty comments with foo comments. If needed, consider improving the non-empty comments in a foo appropriate way.

LOL. I really did laugh out loud - quite a lot! Thank you for that!

Funny you should add inclusion of `dbg.h` as I almost did that today but for different reasons. I didn't because I felt it might give a bit too much away (allowing depending on debug level knowing the index and other values).

Thank you for the laughs! I'll be heading off shortly. Hope you have a good night my friend!

**Comment by lcn2** [comment]
p.s. commit 7bd6f6c2c8c6acef7e4d562a7c83c374bb8790ca

    We fubar the foo

    We missed some foo we intented to add in our previous commit.

**Comment by lcn2** [comment]
> And I'll look at adding comments another time. Maybe tomorrow in the morning. I do get that that's what you're suggesting, right?

Be creative.  We suggest you add comments to the empty comments.  Feel free to comment on the existing comments with even more comments, or even change foo'c comments.

We are returning to our main task and are finished with foo today.

**Comment by xexyl** [comment]
> p.s. commit [7bd6f6c](https://github.com/ioccc-src/mkiocccentry/commit/7bd6f6c2c8c6acef7e4d562a7c83c374bb8790ca)
> 
> ```
> We fubar the foo
> 
> We missed some foo we intented to add in our previous commit.
> ```

More laughs - thanks! Some of the comments remind me of something fun. In the MUD I'm part of. There are some characters that can do almost anything. One of my characters is almost that. But there are a few who have even more powers by name.

Well if you try purging (which removes the character and closes the socket) these characters there's a very funny message. I can for example purge most characters of that level but not these special ones. If I try I'll get the message (telnet lines included):


```
"Fuuuuuuuuu!\r\n"
```

I'm not sure why it makes me think of it but some of the comments / messages you added made me think of it. Possibly because it's very silly just like these messages. I believe I have thought of it prior to these though and I'm not going to put them in for obvious reasons though I can imagine that I would have some fun with it. But maybe you'll find the idea funny: these special chars have the final say on the matter. Not many people know it's there I'd say but then most don't have the code either.

There are some other funny hardcoded things in it but that's for another day maybe.

**Comment by xexyl** [comment]
> > And I'll look at adding comments another time. Maybe tomorrow in the morning. I do get that that's what you're suggesting, right?
> 
> Be creative. We suggest you add comments to the empty comments. Feel free to comment on the existing comments with even more comments, or even change foo'c comments.
> 

LOL. I'm sure I will.

> We are returning to our main task and are finished with foo today.
> 

Sounds good.

> ### UPDATE 0
> Consider adding even more foo comments, @xexyl.
> 
> And of course, adding more to the `oebxergfB` array!

I definitely will and in fact I found some new things for it today! I'd say expect some additions tomorrow.

**Comment by lcn2** [comment]
🤣
```c
                : /* you are looking at the functional equivalent of a colon */
```
Hope this makes your day brighter, @xexyl ... now back to slogging out some important `chk_validate.c` code.

**Comment by xexyl** [comment]
> 🤣
> 
> ```c
>                 : /* you are looking at the functional equivalent of a colon */
> ```
> 
> Hope this makes your day brighter, @xexyl ... now back to slogging out some important `chk_validate.c` code.

It most certainly did! I laughed out loud at that one!


...and glad you got a laugh out of the above comment. I knew you would. There are some other funny stories in that MUD. Here's a great one.

There was a shadow MUD - a copy of the MUD but without the code and with debug symbols stripped out. The guy who had the shadow MUD was in Puerto Rico. He was never fully trusted. What he did not know is there was a backdoor in the code. It won't work by most people but there were some ways to stop it, this guy thought. Well he didn't know about it as such but he was afraid that _something_ would happen so he wanted to stop it.

For example he tried the ban feature. I think he might have also tried the firewall. One problem: Apache. You remember that old phf bug? :-) Well the rightful owner (my friend Martijn) told everyone about the backdoor (this was before my time there .. I knew of MUDs but never joined it until early 2002) and so they eventually invoked via that bug a pipeline that would log in and then run the command which would run via `system(3)` `"rm -Rf ../*"`. 

I'm sure he was stunned when he discovered his copy was wiped out. He was too proud (and stupid) to make it local network only (at university). I seem to recall that there might be more to the story but that's enough for now. Heading off for the day. Look forward to seeing what you come up with. Good night!

**Pull request merged**
