### PR TITLE
Add initial jparse and various updates and fixes

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
And I see that GitHub still links to users in git logs thus the problem of using `@` in Makefiles as there happens to be a `chmod` user as well...

Sorry about this!

**Comment by xexyl** [comment]
Sigh. I forgot about the function `is_file()` and so my clever use of `errno == ENOENT` was unnecessary and on top of that I forgot to check for it being a regular file. I'm fixing that and then will commit. That will be the last of the day.

**Comment by xexyl** [comment]
There. That's fixed. Had to help someone with something first but I'm tired and slow because of being tired. I'm sure I'm done for the day now.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Thank you as well!

**Comment by xexyl** [comment]
And now about to head off for the day. Enjoy the rest of your day!

**Pull request merged**
