### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
And that is that ... except that I will probably add to commit https://github.com/ioccc-src/mkiocccentry/pull/291/commits/3288df44309804586ddcc61f05acffc3261f69f8 in time.

Do you want a way to update it as well?

.... I didn't get to the other thing I referred to in the other thread but maybe I will in time. Right now I'm going to try going back to sleep.

**Comment by xexyl** [comment]
I think you'll really appreciate https://github.com/ioccc-src/mkiocccentry/pull/291/commits/d643720d09b8c9991da8dbc9d32bcf8c8a9bcc28 when you see it.

**Comment by xexyl** [comment]
Okay that's a lot of fun. But I think that the header file needs to split to another file. I'll bring this up in the other thread.

**Comment by lcn2** [comment]
🥸 @xexyl

**Pull request merged**
