### PR TITLE
Check remaining script files for error messages

### PR DESCRIPTION
**Pull request by xexyl**
With the exceptions noted on GitHub all error messages should be checked.

I did not check these as thoroughly as in the C files (and I very possibly missed some there too) but I did discover a number of issues that were fixed (or else noted on GitHub for discussion).

### CODE REVIEW

**Comment by lcn2** [comment]
Good edits, @xexyl

**Comment by xexyl** [comment]
> Good edits, @xexyl

Thank you.

I"m running out of time before my zoom meeting but I hope to after that at least go through the man pages under soup/. I might not be able to do the others until tomorrow but once I have I think that the documentation item can be ticked as complete.

Once the issues I brought up in the other thread are resolved the error messages item can also probably be marked complete.

**Comment by lcn2** [comment]
> > Good edits, @xexyl
> 
> 
> 
> Thank you.
> 
> 
> 
> I"m running out of time before my zoom meeting but I hope to after that at least go through the man pages under soup/. I might not be able to do the others until tomorrow but once I have I think that the documentation item can be ticked as complete.
> 
> 
> 
> Once the issues I brought up in the other thread are resolved the error messages item can also probably be marked complete.
> 
> 

Thanks .. when an item is ready to mark it complete, please put a note in issue #87 indicating which item is ✅.

**Comment by xexyl** [comment]
> > > Good edits, @xexyl
> > 
> > 
> > Thank you.
> > I"m running out of time before my zoom meeting but I hope to after that at least go through the man pages under soup/. I might not be able to do the others until tomorrow but once I have I think that the documentation item can be ticked as complete.
> > Once the issues I brought up in the other thread are resolved the error messages item can also probably be marked complete.
> 
> Thanks .. when an item is ready to mark it complete, please put a note in issue #87 indicating which item is ✅.

Of course. And the changelog as well.

**Pull request merged**
