### PR TITLE
Typo fix in jprint comment

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
nice progress @xexyl

**Comment by xexyl** [comment]
> nice progress @xexyl

Thank you .. will do more tomorrow.

**Comment by lcn2** [comment]
The `make prep` fails in `make_action 31 test`:

```
test_ioccc/chkentry_test.sh: Notice: chkentry semantic tests failed, see ./test_ioccc/chkentry_test.log for details
test_ioccc/chkentry_test.sh: ERROR: about to exit: 1
./ioccc_test.sh: ERROR: test_ioccc/chkentry_test.sh non-zero exit code: 1

EXIT_CODE set to: 32

FAILED: test_ioccc/chkentry_test.sh

These test(s) failed:

    test_ioccc/chkentry_test.sh non-zero exit code: 1

About to exit: 32

See test_ioccc/test_ioccc.log for more details
```

And `test_ioccc/test_ioccc.log` has:

```
RUNNING: test_ioccc/chkentry_test.sh

test_ioccc/chkentry_test.sh -v 1 -d ./test_ioccc/test_JSON -c ./chkentry

EXIT_CODE set to: 32

FAILED: test_ioccc/chkentry_test.sh

These test(s) failed:

    test_ioccc/chkentry_test.sh non-zero exit code: 1

About to exit: 32
```

**Comment by xexyl** [comment]
> The `make prep` fails in `make_action 31 test`:
> 
> ```
> test_ioccc/chkentry_test.sh: Notice: chkentry semantic tests failed, see ./test_ioccc/chkentry_test.log for details
> test_ioccc/chkentry_test.sh: ERROR: about to exit: 1
> ./ioccc_test.sh: ERROR: test_ioccc/chkentry_test.sh non-zero exit code: 1
> 
> EXIT_CODE set to: 32
> 
> FAILED: test_ioccc/chkentry_test.sh
> 
> These test(s) failed:
> 
>     test_ioccc/chkentry_test.sh non-zero exit code: 1
> 
> About to exit: 32
> 
> See test_ioccc/test_ioccc.log for more details
> ```
> 
> And `test_ioccc/test_ioccc.log` has:
> 
> ```
> RUNNING: test_ioccc/chkentry_test.sh
> 
> test_ioccc/chkentry_test.sh -v 1 -d ./test_ioccc/test_JSON -c ./chkentry
> 
> EXIT_CODE set to: 32
> 
> FAILED: test_ioccc/chkentry_test.sh
> 
> These test(s) failed:
> 
>     test_ioccc/chkentry_test.sh non-zero exit code: 1
> 
> About to exit: 32
> ```

How is that possible when I've not touched it ?

**Comment by xexyl** [comment]
...trying it now ...

**Comment by xexyl** [comment]
I got exit code 31. How is it possible you got 32 but I got 31 ?

**Comment by xexyl** [comment]
Running `make test` gives 32 and:

```
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.quote-null.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.sorted.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.min-whitespace-nonl.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.abstract-with-encoded-NUL.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.array-last.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.test-0.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.max-manifest.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.simple-1.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.good.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.simple-0.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.min-whitespace.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.min-manifest.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.test-1.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.empty-override.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: ERROR: test ./test_ioccc/test_JSON/info.json/good/info.reference.json should pass: chkentry FAIL with exit code: 1
test_ioccc/chkentry_test.sh: debug[1]: all JSON files were valid JSON; however some chkentry semantic tests failed

```

How is that possible? Could it be a change in the json parser causing it?

**Comment by xexyl** [comment]
Oh I know the problem.

It's because `txzchk` had a version change. How do we update these files ?

**Comment by xexyl** [comment]
Oh vermod.sh script. Hang on.

**Comment by xexyl** [comment]
.. still failed. Hmm.

**Comment by xexyl** [comment]
The problem is that the other tools have the old version which is the same as the old version of txzchk.

I can't fix this right now but I can look at it tomorrow if you don't. Sorry.

**Comment by xexyl** [comment]
Just fixed it after all. Leaving for the day now.

**Pull request merged**
