### PR TITLE
Resolve issues #1044, #1045 and #1046

### PR DESCRIPTION
**Pull request by xexyl**
Fix tools for filename length rule (part of rule 17)

Fix mkiocccentry, chkentry and txzchk for the requirement of filenames to be of length > 0 && <= 99 as per rule 17.

This is somewhat involved and required all the JSON test files to be updated (for versions) as well as some new JSON files.

A new macro MAX_FILENAME_LEN had to be added. Then in soup/entry_util.c a new function called test_filename_len() was added. This function is then used in txzchk.c (function check_all_txz_files()), mkiocccentry.c (in the check_*() functions) and then, for chkentry, in chk_validate.c the function chk_extra_file(); it is not necessary in the code that checks for the required files as the functions that test those files check for exact filenames. The function test_extra_file() calls the new function as test_extra_file() does a variety of kinds of tests on the file.

A new bad txzchk test file was also added (with its corresponding .err file).

The mkiocccentry_test.sh script along with txzchk_test.sh (see above) and chkentry_test.sh now test for too long filenames and too short filenames. In the case of mkiocccentry_test.sh a change in the script itself had to be made so the version was updated to "1.0.2 2024-12-30" from "1.0.1 2023-02-05".

Changed SOUP_VERSION to "1.1.2 2024-12-30" from "1.1.1 2024-12-26".

Changed MKIOCCCENTRY_VERSION to "1.1.1 2024-12-30" from "1.1.0 2024-12-28".

Changed TXZCHK_VERSION to "1.0.9 2024-12-30" from "1.0.8 2024-07-11".

Changed CHKENTRY_VERSION to "1.0.3 2024-12-30" from "1.0.2 2024-08-26".

### CODE REVIEW

**Comment by xexyl** [comment]
Now only one more top priority issue .. but that requires a clarification from you.

**Review by lcn2 — APPROVED** [review]
Thanks 👍

**Comment by xexyl** [comment]
> Thanks 👍

You are most welcome! Just waiting on clarification in the last issue ... doing other things again. Can do more tomorrow.

**Comment by lcn2** [comment]
> > Thanks 👍
> 
> You are most welcome! Just waiting on clarification in the last issue ... doing other things again. Can do more tomorrow.

Please remind us what the last issue is again?

**Comment by xexyl** [comment]
> > > Thanks 👍
> 
> > 
> 
> > You are most welcome! Just waiting on clarification in the last issue ... doing other things again. Can do more tomorrow.
> 
> 
> 
> Please remind us what the last issue is again, @xexyl sorry (tm Canada 🇨🇦).

The submit server being ready one.

**Comment by lcn2** [comment]
> > > > Thanks 👍
> > 
> > 
> > > 
> > 
> > 
> > > You are most welcome! Just waiting on clarification in the last issue ... doing other things again. Can do more tomorrow.
> > 
> > 
> > Please remind us what the last issue is again, @xexyl sorry (tm Canada 🇨🇦).
> 
> The submit server being ready one.

The submit server is ready in terms of working well.

The submit server will deny anyone with a login, upload files, right now however, because of a configuration file on the submit server.  So if you try to login with that test account (that we have not yet disabled) you will see a read-only slot file status.

The submit knows when the contest is scheduled to open, and that matches the dates in the current tentative rules (and guidelines).  When the contest is open, the submit server will allow logins and file uploads.

The submit knows when the contest is scheduled to go into the judging state (what from the submit server's perspective it calls "closed").  When that change happens, users will be allowed to login but their slot status will be read only.  This will allow the IOCCC judges to update slot statuses if needed.

So yes, the submit server is ready.

BTW: The guidelines state:

The [submit server](https://submit.ioccc.org/) will become active when the contest is [open](https://www.ioccc.org/status.html#open). Until the contest status becomes [open](https://www.ioccc.org/status.html#open), the [submit server](https://submit.ioccc.org/) may be offline and/or unresponsive.

The last phrase allows us to improve the sever, put it into test mode prior to the contest going into open state.  It also allows us to shutdown the sever when the contest is closed to reduce cost.

**Pull request merged**
