### PR TITLE
Release 1.0.58 2024-03-02 - new IOCCC terms

### PR DESCRIPTION
**Pull request by xexyl**
Address part (possibly all) of the issue of new IOCCC terms (only part because some things need to be decided still especially with file names and related specifics but possibly all if it's decided these should stay the same).

Changed version of txzchk to 1.0.3 2024-03-02.
Changed version of fnamchk to 1.0.1 2024-03-02.
Changed version of mkiocccentry to 1.0.3 2024-03-02. Changed AUTH_VERSION to 1.20 2024-03-02.
Changed INFO_VERSION to 1.15 2024-03-02.

In many cases the word entry was changed to submission. For chkentry and mkiocccentry it has been decided to keep the names. However in text, variable and comments the word is now submission. It is not clear, however, if a submission directory needs to have a different prefix (currently it's entry.). If this is necessary then more changes will have to be made. If it needs to be renamed then changes in fnamchk and txzchk plus data files (at the very least - there might be other places that'd have to be updated) will have to be made.

'winner'/'winners' changed to 'winning author'/'winning authors' (a more thorough check has to be performed to make sure all are caught, see below). A winning submission is an entry and at least in some cases this is now clear. In the case of winner_handle (or even just winner handle) this was not changed. There already exists an author_handle and that's what is in the files but in comments winner_handle also exists. In other words this ambiguity should be addressed.

The json 'past_winner' was changed to 'past_winning_author'. This involved updating some patch files and all the auth json files as well.

Typo fix in bug_report.sh. No version update.

In many cases (not all) the year 2023 was changed to 2024. The IOCCC_YEAR was NOT updated to 2024 as this causes other problems that require a bit more time.

A fun problem to resolve is the text along the lines of 'submit your entry' being changed to 'submit your submission'. In some cases the surrounding text was reworded but not in all. If you like this can be submissions all the way down!

### CODE REVIEW

**Comment by xexyl** [comment]
Forgot to fix the title of the log (in git commit) after fixing the resolve conflicts on my end. It's too much bother to fix again and probably I'm the only one who would care anyway. I'll be doing other things for the rest of the day.

**Comment by xexyl** [comment]
Great ...

Screenshot 2024-03-03 at 14 46 27

**Comment by lcn2** [comment]
Wow, lots of detailed good work here @xexyl .. thanks!

**Comment by xexyl** [comment]
> Wow, lots of detailed good work here @xexyl .. thanks!

You are most welcome. I'm glad the merge went through even though a check failed.

I have more to look at here with the terms but I'll worry about that another time. Hope travels etc. going well!

**Comment by lcn2** [comment]
The `make release` fails.

**Comment by lcn2** [comment]
See:

[bug-report.20240303.144934.txt](https://github.com/ioccc-src/mkiocccentry/files/14474920/bug-report.20240303.144934.txt)

**Comment by xexyl** [comment]
Funny thing is I was just trying it. And I know I tried it before I did the pull request. Looking into it ...

**Comment by lcn2** [comment]
```sh
$ make release
make_action 10 clobber OK
make_action 11 all ERROR exit code 2

make release: ERROR: ./test_ioccc/prep.sh exit code: 11

make release: see build.log for details
make: *** [release] Error 11
zsh: exit 2     make release
```

**Comment by xexyl** [comment]
Is it possible it's on your end? I didn't get that error. See:

```sh
$ make prep
make_action 10 clobber OK
make_action 11 all OK
make_action 12 depend OK
make_action 13 clean_mkchk_sem OK
make_action 14 all_sem_ref OK
make_action 15 mkchk_sem OK
make_action 16 all OK
make_action 18 parser OK
make_action 19 all OK
make_action 20 load_json_ref OK
make_action 21 use_json_ref OK
make_action 22 clean_generated_obj OK
make_action 23 all OK
make_action 24 bug_report-txl -L bug-report.20240303.144933.txt OK
make_action 25 shellcheck OK
make_action 26 seqcexit OK
make_action 27 picky OK
make_action 28 tags OK
make_action 29 check_man OK
make_action 30 all OK
make_action 31 test 
```

**Comment by lcn2** [comment]
> Great ...
> 
> Screenshot 2024-03-03 at 14 46 27

It seems that the check process for GitHub is broken as well.  We saw issues with building man pages causes stuff to dump core.

**NOTE:** This is **NOT** an error on our code side, it is a GitHub process where their utility dumps core.

**Comment by lcn2** [comment]
> Is it possible it's on your end? I didn't get that error. See:
> 
> ```shell
> $ make prep
> make_action 10 clobber OK
> make_action 11 all OK
> make_action 12 depend OK
> make_action 13 clean_mkchk_sem OK
> make_action 14 all_sem_ref OK
> make_action 15 mkchk_sem OK
> make_action 16 all OK
> make_action 18 parser OK
> make_action 19 all OK
> make_action 20 load_json_ref OK
> make_action 21 use_json_ref OK
> make_action 22 clean_generated_obj OK
> make_action 23 all OK
> make_action 24 bug_report-txl -L bug-report.20240303.144933.txt OK
> make_action 25 shellcheck OK
> make_action 26 seqcexit OK
> make_action 27 picky OK
> make_action 28 tags OK
> make_action 29 check_man OK
> make_action 30 all OK
> make_action 31 test 
> ```

See the bug report we just submitted ... looking at things again here,

**Comment by lcn2** [comment]
```
cc -std=gnu11 -O3 -g3 -pedantic -Wall -Wextra  jnum_gen.o ../jparse.a ../../dyn_array/dyn_array.a ../../dbg/dbg.a -lm -o jnum_gen
make[1]: *** No rule to make target `print_test.c', needed by `print_test.o'.  Stop.
make: *** [all_jparse_test] Error 2
zsh: exit 2     make all
```

**Comment by lcn2** [comment]
Train stopped for a bit for refueling at a place with WiFi .. FYI.

**Comment by xexyl** [comment]
> ```
> cc -std=gnu11 -O3 -g3 -pedantic -Wall -Wextra  jnum_gen.o ../jparse.a ../../dyn_array/dyn_array.a ../../dbg/dbg.a -lm -o jnum_gen
> make[1]: *** No rule to make target `print_test.c', needed by `print_test.o'.  Stop.
> make: *** [all_jparse_test] Error 2
> zsh: exit 2     make all
> ```

Maybe make depend problem?

Oh I think I have an idea ... checking.

**Comment by xexyl** [comment]
See if what I just opened does it. I still have the old C file which is why. It happened when I made the mistake of not pulling first. So I did a replace in the Makefile to have the new name. That I hope will solve the problem. If not I'll look at it again.

**Pull request merged**
