### PR TITLE
Slight format improvement in show_submit_url()

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Now it looks like:

```
To submit to the IOCCC, you must be a registered contestant
and have received an IOCCC contest ID (a UUID) and initial
password (via email). To do so, please visit:

    https://www.freelists.org/list/ioccc28-reg

Please also see the FAQ on how to enter the IOCCC:

    https://www.ioccc.org/faq.html#enter

...and the register, password change and submit help pages:

    https://www.ioccc.org/next/register.html
    https://www.ioccc.org/next/pw-change.html
    https://www.ioccc.org/next/submit.html

Please note that you may ONLY register when the contest is in
a PENDING or OPEN status! For the contest status see:

    https://www.ioccc.org/status.html

When the contest is open (see https://www.ioccc.org/status.html),
after you have registered, you must upload into slot 2:

	test_ioccc/test_work/submit.12345678-1234-4321-abcd-1234567890ab-2.1735673676.txz

to the IOCCC submit server:

    https://submit.ioccc.org

For more information, see the FAQ on how to enter at:

    https://www.ioccc.org/faq.html#enter
```

If that seems good I would say that bug is fixed yes.

**Review by lcn2 — APPROVED** [review]
Thank you @xexyl for the quick turnaround on this matter.

**Comment by lcn2** [comment]
We suggest that we declare the top of the master branch to be repo release version 2.3 2024-12-31, @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl for the quick turnaround on this matter.

You are most welcome. I will be going afk now ... might do more at the other repo later today but it might not be until tomorrow. That might be better so I can focus on the grammar of the rules and guidelines.

**Comment by xexyl** [comment]
> We suggest that we declare the top of the master branch to be repo release version 2.3 2024-12-31, @xexyl


Done.

**Comment by xexyl** [comment]
And in case you didn't see the checks have now been done so you can merge.

**Pull request merged**
