### PR TITLE
Sync jparse subdirectory from jparse repo

### PR DESCRIPTION
**Pull request by xexyl**
With recent updates to the jparse repo
(https://github.com/xexyl/jparse) there was a need to sync that repo to
the jparse/ subdirectory. No code changes were made and the only
functionality changes made are that a few more header files are
installed (and now into a subdirectory - /usr/local/include/jparse) and
an uninstall rule was added (for those who wish to deobfuscate their
system a bit :-) ). The uninstall rule in the top level Makefile (this
repo) does not run make uninstall in other directories but perhaps it
should.

Did the following steps to make sure things are okay:

    # to be sure the tree is clean
    git status
    # to see if things can still build and test
    make release
    # to be sure the tree is clean
    make clobber

    make jparse.help
    make jparse.recreate_clone
    make jparse.update_from_clone

    # to see if anything changed
    git status
    # to see if things can still build and test
    make release

.. and all is good.

Updated the repo release version to "1.5.6 2024-08-31".

### CODE REVIEW

**Comment by xexyl** [comment]
This failure is because of the problem being discussed in the other repo, not being able to link in the libraries. Just a FYI.

I have other things I need to do now.

**Comment by xexyl** [comment]
Or actually it was because of missing `-L`. Should be fixed now.

**Review by lcn2 — COMMENTED** [review]
We cannot process this PR  until PR #951 as been removed, @xexyl 

Moreover we will make some changes that may cause some minor conflicts to occur with this PR #952 although we will try to avoid that.

**Comment by xexyl** [comment]
> We cannot process this PR  until PR #951 as been removed, @xexyl 
> 
> 
> 
> Moreover we will make some changes that may cause some minor conflicts to occur with this PR #952 although we will try to avoid that.

Closed it.

**Comment by xexyl** [comment]
If this one has a conflict I will fix it tomorrow.

**Review by lcn2 — CHANGES_REQUESTED** [review]
With commit b44facadcfc443a94838052db6e81a6ccaef280c we have synced dyn_array with dyn_array repo code.

The recent change in the dyn_array repo to eliminate the need for dog to be installed to compile and test, has been added to this repo.  There is **NO** need to access the dbg include files **NOR** a need to link the dbg library in order to compile the dyn_array sub-directory.

Please update your dyn_array code (and you might as well install it just to be complete).

Please update your code base to commit b44facadcfc443a94838052db6e81a6ccaef280c and modify this PR accordingly.

Thank you for your patience, @xexyl, in this matter.

## UPDATE 0a

The conflict resolve to the PR is easy.  Just remove the modification to `dyn_array/Makefile`.

**Comment by xexyl** [comment]
> With commit [b44faca](https://github.com/ioccc-src/mkiocccentry/commit/b44facadcfc443a94838052db6e81a6ccaef280c) we have synced dyn_array with dyn_array repo code.
> 
> The recent change in the dyn_array repo to eliminate the need for dog to be installed to compile and test, has been added to this repo. There is **NO** need to access the dbg include files **NOR** a need to link the dbg library in order to compile the dyn_array sub-directory.
> 
> Please update your dyn_array code (and you might as well install it just to be complete).
> 
> Please update your code base to commit [b44faca](https://github.com/ioccc-src/mkiocccentry/commit/b44facadcfc443a94838052db6e81a6ccaef280c) and modify this PR accordingly.
> 
> Thank you for your patience, @xexyl, in this matter.
> 
> ## UPDATE 0
> Once you have also resolved the conflicts with this PR, we will be happy to consider it.

Do you mean that the jparse Makefiles should not link in `dbg`? I"m not sure what you're after entirely. Oh ... I see. The `dyn_array/Makefile` change slipped in. But why? The only files I committed were jparse and the changelog.

This is so annoying. I can try copying it over and committing it to see if it'll solve the problem.

**Comment by lcn2** [comment]
> > With commit [b44faca](https://github.com/ioccc-src/mkiocccentry/commit/b44facadcfc443a94838052db6e81a6ccaef280c) we have synced dyn_array with dyn_array repo code.
> > The recent change in the dyn_array repo to eliminate the need for dog to be installed to compile and test, has been added to this repo. There is **NO** need to access the dbg include files **NOR** a need to link the dbg library in order to compile the dyn_array sub-directory.
> > Please update your dyn_array code (and you might as well install it just to be complete).
> > Please update your code base to commit [b44faca](https://github.com/ioccc-src/mkiocccentry/commit/b44facadcfc443a94838052db6e81a6ccaef280c) and modify this PR accordingly.
> > Thank you for your patience, @xexyl, in this matter.
> > ## UPDATE 0
> > Once you have also resolved the conflicts with this PR, we will be happy to consider it.
> 
> Do you mean that the jparse Makefiles should not link in `dbg`? I"m not sure what you're after entirely. Oh ... I see. The `dyn_array/Makefile` change slipped in. But why? The only files I committed were jparse and the changelog.
> 
> This is so annoying. I can try copying it over and committing it to see if it'll solve the problem.

No.

**Comment by lcn2** [comment]
Simply do not modify the `dyn_array/Makefile` file in this PR.

**Comment by xexyl** [comment]
Yes it caused a problem but I don't know what. Also why this:


```sh
$ make
clang -std=gnu17 -O3 -g3 -pedantic -Wall -Wextra -Wno-char-subscripts -DINTERNAL_INCLUDE  -UDBG_USE dyn_test.c -c
dyn_test.c:80:12: error: static declaration of 'parse_verbosity' follows non-static declaration
static int parse_verbosity(char const *optarg);
           ^
./../dbg/dbg.h:262:12: note: previous declaration is here
extern int parse_verbosity(char const *optarg);
           ^
1 error generated.
make[1]: *** [Makefile:357: dyn_test.o] Error 1
make: *** [Makefile:474: all_dyn_array] Error 2

```

? maybe the Makefile. I'll check it out again. I might have to close this and try again.

**Comment by xexyl** [comment]
Did what I did in GitHub (web) solve it?

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
You are most welcome. Do you think the issue in the jparse repo can be closed as complete now? If so feel free to close it ... else I can do it.

**Pull request merged**
