### PR TITLE
Initial json flex/bison grammar added

### PR DESCRIPTION
**Pull request by xexyl**
This is very incomplete and there are certainly some things that are
wrong! As I learn more about flex(1)/bison(1) and also get into actually
working on the parsing things will be fixed. I _believe_ I have the case
of terminals/non-terminals correct but even that might be not entirely
the case.

I've not gone through the entire json grammar so both json_parser.l and
json_parser.y are incomplete in that way too (it's also incomplete in
that additional C code has to be written). It's also possible I have
some of the regular expressions wrong and the actions are not complete:
all they do is print what was found and then return the token type
(which might also be incomplete).

I've read only the very beginning of the book Flex and Bison and much
more has to be done there but I wanted these in. This commit involves
some other changes.

First of all the following #defines in json.h have been changed:

    JSON_STRING		-> JSON_CHARS
    JSON_ARRAY_STRING	-> JSON_ARRAY_CHARS
    JSON_NUMBER		-> JSON_NUM
    JSON_NULL		-> JSON_EOT /* EOT = end of table */

The reason is that these are also used in the parser and json.h will
eventually be #included (actually it already is but not yet used as
such).

The Makefile has been updated to run flex and bison on json_parser.l and
json_parser.y respectively but not by default: one has to do `make
json_parser`. This will also compile in the generated code which also
happens to be in the repo so it's probably better that only I do that
for now. There is a slight issue here: the rule has to be split into
two, one to generate the code and the other to compile. This is not a
problem itself but the first one won't work on systems without flex and
bison installed so it cannot be part of the default. Instead whenever I
update the .l/.y files I have to run `make json_parser` and recommit the
files. Eventually I plan on cleaning the output and then the need for
running flex and bison won't be there any more but this is quite a bit
down the road.

.gitignore has also been updated with 'json_parser' added to the list to
ignore.

On the subject of json_parser: right now (if it's not obvious) it is
entirely useless as it doesn't do anything at all. The importance of
this commit is the starting of the grammar and getting the repo in a
state that I can start updating it and working on the actual parser.
Then integrating the generated parser into the tools e.g. jparse,
jinfochk and jauthchk plus any others that might need the parser. I'm
wondering if maybe json_parser should become jparse and so the code in
jparse.c is added to the json_parser (which will be named jparse
instead) so that once the parser is done it will be right there to use.
This however is something I can work out later.

### CODE REVIEW

**Comment by xexyl** [comment]
As for the rest of the day:

I have two virtual meetings today. I might do a bit more reading but I'm not certain of that. I'd like to but it depends on what I have the time and energy for. I'm taking a break now and I won't be done with the break for probably at least an hour but maybe longer than that (though I might have brief moments where I can e.g. look at the book).

What are your thoughts on. making the jparse.c become this parser?

**Comment by xexyl** [comment]
One more thing I forgot to mention in the commit.

For errors (not that any will be generated yet) I use `dbg()` because `seqcexit` does not (I think) parse `.{y,l}` files so I can't run `make seqcexit` on them. It would also mean that the person would have to run flex and bison on the tools again. This might also become a problem if I want to clean up the code and we have to make a change.

What are your thoughts? My thinking is maybe making a new error system that can be used. Perhaps the json error/warning functions I wrote? Please let me know. And now I'm gone for a while!

**Comment by xexyl** [comment]
The comments are to say that this is VERY incomplete and there are errors. I just wanted to get this in as a starting point. There are missing actions and grammar and it's very easy to trigger an error. All one has to do is type something into the program once it's started.

I believe I'm done for the day though. I didn't get much further reading as I decided to spend more time on starting the files. I'll read more tomorrow. I do want to read right now but I'm not clear headed enough so I'm stopping. In a couple hours I have a zoom meeting and later on I have a phone call so I'm just going to take the rest of the time easy.

**Comment by xexyl** [comment]
Going to sleep now. 

I hope tomorrow that I can start getting into the book more. I don’t know how much I will get done but I should be able to get something done anyway. I will be playing with the example programs in the book to get a better idea of how it works and go from there. 

Hope you’re having a nice evening. I guess you will get to this pull request later on but there’s no rush on my behalf. I will commit more changes either way! Good night!

**Comment by lcn2** [comment]
Offline for an issue .. did the merge but have not had a chance to see the change nor had a chance reply your questions, sorry @xexyl

**Comment by xexyl** [comment]
> Offline for an issue .. did the merge but have not had a chance to see the change nor had a chance reply your questions, sorry @xexyl

No worries! I hope everything is okay? As for the question I think right now it's a bit premature but it might be something worth considering when the parser is complete. Since I don't know what the issue is I'll not try summarising it; you'll see it when you see it.

Hope everything is okay and hope you're having a nice sleep!

**Comment by xexyl** [comment]
Making progress! I'm starting to understand a bit more just by playing with it some and enabling more detailed errors.

It seems like having whitespace tokens is a problem because it then expects it when whitespaces are not required so I would have to have a lot of different combinations for each rule.

Now I can input a basic json file and it does not report any errors. It's not complete grammar of course but I'm getting there. I will be taking a break after writing this and I think after that I might see if I can get more grammar done and then call it the day in that way. I'll then continue reading more tomorrow. Will probably make a pull request later on.

Hope the issue you refer to is not serious and I hope it's resolved soon if not already!

**Comment by xexyl** [comment]
> Offline for an issue .. did the merge but have not had a chance to see the change nor had a chance reply your questions, sorry @xexyl

I hope you're okay @lcn2 ... I know I already said that but I wanted to reiterate it. If things are not okay I hope they are resolved soon, whatever they might be.

Cheers! I'll keep working on the code though in what way I don't know. I expect I'll be reading more today but it's still early so not sure. Saturday I won't have as much time as my cousin will be calling here (visiting) again so I will be afk most the day but every other day should be good. Anyway I hope everything is okay.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Of course. Is everything okay now?

**Comment by lcn2** [comment]
Thanks are moving towards stability (helping some folk escape Russia) .. so still a bit busy.

**Comment by xexyl** [comment]
> 

Bless. 

I think it’s so terribly sad and really horrible. It’s bad enough already but it’s even worse during a pandemic. Just like the First World War. 

I know Ilya has wanted out of Russia for some time and quite a long time before the invasion of Ukraine. He was hoping for some job opportunities from after winning the contest as some people have had happen. Is there a way to help him?I just hope he’s okay and can get out safely sooner than later. 

Putin is right that Ukraine has a history of doing awful things but the Second World War ended in May 1945 which is almost 77 years ago. And sure Europeans (and the Americans) treated the survivors horribly but so did the Soviets and as for Soviet Union they are guilty of the worst mass rape of all time not to mention other atrocities so it’s extremely hypocritical of him to bring that up. 

Besides that nobody that participated in the Ukraine collaboration with the Nazis (not that they were the only country to do so) is even alive now and who knows how we would act in times of hardship? Nobody knows themselves in that way no matter how much they want to believe otherwise!

Well I could go on about the Second World War until the Sun dies so I will stop here. Soon I hope to start reading or maybe fix the compilation errors and perhaps send a patch to the author. 

Anyway can you think of a way to help @ilyakurdyukov  ?

I hope you’re having a nice sleep.

**Comment by xexyl** [comment]
Rewriting as I don't think mentioning anyone by name is wise as much as I feel for them. 

The situation with Russia and Ukraine is so tragic and so pointless. It's bad enough as it is but during a pandemic it's even worse. Just like the First World War. Even if they're all vaccinated (and I find that unlikely) as long as people refuse to get vaccinated there will be breakthrough cases and new variants which will only prolong it. War is just a perfect infection vector as history shows (and it's obvious to anyone who thinks about it).

Nobody deserves this. I feel for the Russians and the Ukrainians. And Putin bringing up Ukraine's past I so hypocritical (as Soviet Union also has done horrific things) and it's also irrelevant as those people in the past aren't even alive. But even if they were they don't deserve this and it will affect many other people.

It seems to me that he's so mad for power that he's lost sense. Attacking a nuclear facility is just insanity. Could affect millions of people including his own people including him but he doesn't really care about anyone else.

People tend to say wars will be over quick but why people say this is beyond me even without critical thinking - wars in history tend to last a long time. They do by their very nature. But what's the point? Power? Greed? Those two things and other things but none of which are necessary.

So tragic but I admire very much you helping people out.

**Pull request merged**
