### PR TITLE
Update CHANGES.md + new man page (for prep.sh)

### PR DESCRIPTION
**Pull request by xexyl**
More should be added when more is done (some things I noted were done in the past few days after the change in version was made) or thought of (as I certainly did not note everything since the previous version).

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Sure. I did notice that the `.gitignore` has `man/` which meant I had to do a force add for the man page. Is this intentional? I didn't check if it was `man/` itself or under soup. I'm still not sure why the man page directory was moved to `soup/man` but that can be discussed another time.

Bedtime for me. Good night!

**Comment by lcn2** [comment]
> > Thanks @xexyl
> 
> Sure. I did notice that the `.gitignore` has `man/` which meant I had to do a force add for the man page. Is this intentional? I didn't check if it was `man/` itself or under soup. I'm still not sure why the man page directory was moved to `soup/man` but that can be discussed another time.
> 
> Bedtime for me. Good night!

There is no more top level man directory.  It is constructed as a user convenience directory.  See commit cad4d50a6d68864cc0ea2d0bf483a78b1f0580d4

**Comment by xexyl** [comment]
> > > > Thanks @xexyl
> > > 
> > > 
> > > Sure. I did notice that the `.gitignore` has `man/` which meant I had to do a force add for the man page. Is this intentional? I didn't check if it was `man/` itself or under soup. I'm still not sure why the man page directory was moved to `soup/man` but that can be discussed another time.
> > > Bedtime for me. Good night!
> > 
> > 
> > There is no more top level man directory. It is constructed as a user convenience directory. @xexyl please see commit [cad4d50](https://github.com/ioccc-src/mkiocccentry/commit/cad4d50a6d68864cc0ea2d0bf483a78b1f0580d4)
> 
> Yes I know. That's something I don't understand though. Or do you mean one of the Makefiles will copy the files to that directory? If so I missed that part. That's good if it's there. But there actually are some problems with the man Makefile(s). I'll discuss that soon.

I see that's not the case. My concern is people won't think of looking at soup/man but would expect it to be under man/.

**Pull request merged**
