### PR TITLE
Change -p jparse in jparse_test to -j jparse + typo fixes + new man pages

### PR DESCRIPTION
**Pull request by xexyl**
Since -j was not used it seems like it's more appropriate to use -j for the json parser. I believe that part of why -p was used (if not entirely why) is that earlier on we had jinfochk and jauthchk which used -j and -J and so we used -p for other options though at the time jparse was finished the tools were already renamed (not sure if it was changed to just one tool yet though I - and probably Landon as well - had thought of it being necessary much earlier on).

The man page was updated to account for this.

Tested make test to make sure nothing broke with this change.

It's possible I've missed something but I think everything should be in order. If not I will fix tomorrow or the next day as I will be unable to do so a bit later on today and won't be back until tomorrow.

I did also have some fun with oebxergfB.h at the same time as this commit as well but that doesn't really matter much since only Landon and I can possibly understand it! :-)

### CODE REVIEW

**Comment by xexyl** [comment]
I have a fun quote that I just added but cannot commit yet ... will do so tomorrow as I'm heading off for the day.

Have a great afternoon and evening and I'll be doing more tomorrow I hope! Sleep well when you do!

**Comment by xexyl** [comment]
> I have a fun quote that I just added but cannot commit yet ... will do so tomorrow as I'm heading off for the day.
> 
> Have a great afternoon and evening and I'll be doing more tomorrow I hope! Sleep well when you do!

The quote has been added.

I hope to add some man pages later on. Good day!

**Comment by lcn2** [comment]
Thanks .. @xexyl.

BTW: Let us not keep adding to `oebxergfB.h`. it is probably large enough already.

**Comment by lcn2** [comment]
Two problems with this pull request, @xexyl, we will let it into the master branch, however `make release` now fails:

```sh
$ shellcheck -f gcc -- iocccsize_test.sh jstr_test.sh limit_ioccc.sh mkiocccentry_test.sh vermod.sh prep.sh run_bison.sh run_flex.sh reset_tstamp.sh ioccc_test.sh jparse_test.sh txzchk_test.sh hostchk.sh jsemcgen.sh have_timegm.sh run_usage.sh
jparse_test.sh:49:5: warning: This case is not specified by getopts. [SC2214]
```

Moreover:

```sh
$ ./jparse_test.sh -h
... no mention of -j ...
```

**Comment by xexyl** [comment]
> Two problems with this pull request, @xexyl, we will let it into the master branch, however `make release` now fails:
> 
> ```shell
> $ shellcheck -f gcc -- iocccsize_test.sh jstr_test.sh limit_ioccc.sh mkiocccentry_test.sh vermod.sh prep.sh run_bison.sh run_flex.sh reset_tstamp.sh ioccc_test.sh jparse_test.sh txzchk_test.sh hostchk.sh jsemcgen.sh have_timegm.sh run_usage.sh
> jparse_test.sh:49:5: warning: This case is not specified by getopts. [SC2214]
> ```
> 
> Moreover:
> 
> ```shell
> $ ./jparse_test.sh -h
> ... no mention of -j ...
> ```

Oops. Sorry about that! Thanks for pointing it out. Both have been fixed.

**Comment by xexyl** [comment]
> Thanks .. @xexyl.
> 
> BTW: Let us try to keep from adding much to `oebxergfB.h`. it is probably large enough already.

That's kind of disappointing. That being said though there are some I want to actually remove from it: those that I was not really sure about in the first place. There are quite a few of those so when I do that I'll replace them with something else. That's in time though.

Hope you're having a nice sleep. I slept in till a quarter till 5 which is quite nice for me though I'm still dead tired. Hoping to wake up more in a bit.

On the other hand about the array: you did say _probably_ and not _is_! :-) But no ... I will try limiting it and I will in time remove some of those quotes. Actually I had the fun idea (maybe fun anyway) of sometimes rotating quotes out so that some quotes would no longer be there so that one would have to check the weekly strings to fully get all of them. What do you think of that ?

**Comment by lcn2** [comment]
> > Thanks .. @xexyl.
> 
> > 
> 
> > BTW: Let us try to keep from adding much to `oebxergfB.h`. it is probably large enough already.
> 
> 
> 
> That's kind of disappointing. That being said though there are some I want to actually remove from it: those that I was not really sure about in the first place. There are quite a few of those so when I do that I'll replace them with something else. That's in time though.
> 
> 
> 
> Hope you're having a nice sleep. I slept in till a quarter till 5 which is quite nice for me though I'm still dead tired. Hoping to wake up more in a bit.
> 
> 
> 
> On the other hand about the array: you did say _probably_ and not _is_! :-) But no ... I will try limiting it and I will in time remove some of those quotes. Actually I had the fun idea (maybe fun anyway) of sometimes rotating quotes out so that some quotes would no longer be there so that one would have to check the weekly strings to fully get all of them. What do you think of that ?
> 
> 
> 
> 

We don't think we need to reduce what is there .. it is just that it is probably big enough for now given the priorities we are facing now.   Perhaps it can expand a more as we finalize the code / such as a reward for when we are refactoring the directory structure after we are mostly complete. 

Once the public is invited to try out the repo (pre-IOCCCMOCK) we probably don't want to draw attention to the Easter egg by updating it too often.  So we should be more frugal how often it is updated.

**Comment by lcn2** [comment]
> I had the fun idea (maybe fun anyway) of sometimes rotating quotes out so that some quotes would no longer be there so that one would have to check the weekly strings to fully get all of them. What do you think of that ?

Perhaps the foo.c selection algorithm could be improved (after we get closer to public release/review) to do that. 

We don't want to, especially when we invite public comments to draw too much attention by editing the foo code, and include file too much.   

We doubt that someone will go through the GitHub history extensively let alone review these comments: if they do their welcome to understand the spoilers. Nevertheless, once people start cloning and tracking this repo, we don't want to be drawing attention to this code by modifying it to often.

**Comment by xexyl** [comment]
> > > Thanks .. @xexyl.
> > 
> > 
> > > 
> > 
> > 
> > > BTW: Let us try to keep from adding much to `oebxergfB.h`. it is probably large enough already.
> > 
> > 
> > That's kind of disappointing. That being said though there are some I want to actually remove from it: those that I was not really sure about in the first place. There are quite a few of those so when I do that I'll replace them with something else. That's in time though.
> > Hope you're having a nice sleep. I slept in till a quarter till 5 which is quite nice for me though I'm still dead tired. Hoping to wake up more in a bit.
> > On the other hand about the array: you did say _probably_ and not _is_! :-) But no ... I will try limiting it and I will in time remove some of those quotes. Actually I had the fun idea (maybe fun anyway) of sometimes rotating quotes out so that some quotes would no longer be there so that one would have to check the weekly strings to fully get all of them. What do you think of that ?
> 
> We don't think we need to reduce what is there .. it is just that it is probably big enough for now given the priorities we are facing now. Perhaps it can expand a more as we finalize the code / such as a reward for when we are refactoring the directory structure after we are mostly complete.

That last part sounds good to me!
> 
> Once the public is invited to try out the repo (pre-IOCCCMOCK) we probably don't want to draw attention to the Easter egg by updating it too often. So we should be more frugal how often it is updated.

I was thinking about that too and I had wondered if maybe it would be nice to kind of draw attention to it so it can be enjoyed. But there are valid arguments for both sides. But yes I agree. But if we do so it would only be _just_ drawing attention to it. But part of the reason I have mostly (lately) done it with other commits is for this reason - to not draw attention to it.

**Comment by xexyl** [comment]
> > I had the fun idea (maybe fun anyway) of sometimes rotating quotes out so that some quotes would no longer be there so that one would have to check the weekly strings to fully get all of them. What do you think of that ?
> 
> Perhaps the foo.c selection algorithm could be improved (after we get closer to public release/review) to do that.
> 
> We don't want to, especially when we invite public comments to draw too much attention by editing the foo code, and include file too much.
> 
> We doubt that someone will go through the GitHub history extensively let alone review these comments: if they do their welcome to understand the spoilers. Nevertheless, once people start cloning and tracking this repo, we don't want to be drawing attention to this code by modifying it to often.





> > I had the fun idea (maybe fun anyway) of sometimes rotating quotes out so that some quotes would no longer be there so that one would have to check the weekly strings to fully get all of them. What do you think of that ?
> 
> Perhaps the foo.c selection algorithm could be improved (after we get closer to public release/review) to do that.
> 

That sounds good too though I was specifically thinking that at different times there might be some quotes that are gone. Even so I have a number of times wanted it so that it was not every seven days but N days where N < 7 but what value I do not know (unless we had >= 365 it wouldn't be 1 probably). 

> We don't want to, especially when we invite public comments to draw too much attention by editing the foo code, and include file too much.

Understandable. How about we discuss it in email when we get to this point later on ?
> 
> We doubt that someone will go through the GitHub history extensively let alone review these comments: if they do their welcome to understand the spoilers. Nevertheless, once people start cloning and tracking this repo, we don't want to be drawing attention to this code by modifying it to often.

Sure.

**Pull request merged**
