### PR TITLE
Fix issues #1036, #1035 and #1033

### PR DESCRIPTION
**Pull request by xexyl**
The issues in respective order:

- Typo fix in mkiocccentry.c ('You title must ...' -> 'Your title must
...').
- mkiocccentry UUID type 4 was too strict
- Renamed makefile.local -> Makefile.local. This does NOT address issue #1034!

Updated version of mkiocccentry due to the above changes. For the second
one new macros are in soup/limit_ioccc.h so the soup version has been
updated as well.

Due to the mkiocccentry version change many JSON files were updated so
this is a large commit.

Something that should be pointed out is that the dyn_array and dbg repos
should be updated to match the Makefile changes. This can be done later.
I am too tired to do that now but what this means is that if one were to
sync dbg or dyn_array to here it would roll it back.

Another thing to point out is that another couple commits will likely be
included as a mistake was made on my end and unfortunately that commit
was pushed to my fork. This means I had to do git revert on it.

### CODE REVIEW

**Comment by xexyl** [comment]
Sorry for the three in one pull request. I'm too tired and since at least two are part of the same tool and the other one is a rename of files it's probably not a big deal.

Please note the dbg and dyn_array notes in the above log. I don't have the energy to do that now. I also guess that given that there are several high priority issues it might be something you'll want to do. I'm going to try and (just remembered them) the emails you sent me. Then I probably will have to stop for a while.

**Review by lcn2 — APPROVED** [review]
As expected, lots of stuff was touched as a result of this PR. Thank you @xexyl

**Comment by xexyl** [comment]
> As expected, lots of stuff was touched as a result of this PR. Thank you @xexyl

You are most welcome. Will you take care of the dbg and dyn_array Makefiles?

**Comment by lcn2** [comment]
> > As expected, lots of stuff was touched as a result of this PR. Thank you @xexyl
> 
> 
> 
> You are most welcome. Will you take care of the dbg and dyn_array Makefiles?

Please issue PRs for those two repos.  We are focused on the "other repo" in regards to the **Great Fork Merge**.

**Comment by xexyl** [comment]
> > > As expected, lots of stuff was touched as a result of this PR. Thank you @xexyl
> > 
> > 
> > You are most welcome. Will you take care of the dbg and dyn_array Makefiles?
> 
> Please issue PRs for those two repos. We are focused on the "other repo" in regards to the **Great Fork Merge**.

Done.

**Pull request merged**
