### PR TITLE
Foo fun

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Doing something else now ... probably won't be able to return to this until tomorrow. By this I mean the repo.

Good day!

**Comment by xexyl** [comment]
You should try activating the string now. I think you'll appreciate this one in commit https://github.com/ioccc-src/mkiocccentry/pull/310/commits/6caff391dc3d5e1d63b437cfe9ad0d4c42647297!

I wish I could say it's my creation but it's not. I kept it as it as I originally had it so you'll see invalid C and undefined behaviour too (like `void` for main). Still a great satirical piece though.

**Comment by lcn2** [comment]
Thanks .. however we might want to focus a bit more on non-foo too. :-)

**Comment by xexyl** [comment]
> Thanks .. however we might want to focus a bit more on non-foo too. :-)

That's true of course. These are just fun things to do when I'm not up to the other things though. Even so it seems I now have some additional things to focus on - but not today.

Please do try activating the current string though!

**Comment by lcn2** [comment]
> > Thanks .. however we might want to focus a bit more on non-foo too. :-)
> 
> That's true of course. These are just fun things to do when I'm not up to the other things though. Even so it seems I now have some additional things to focus on - but not today.
> 
> Please do try activating the current string though!

Activate as in:

```sh
 ./chkentry . . 3
```

???

**Comment by xexyl** [comment]
> > > Thanks .. however we might want to focus a bit more on non-foo too. :-)
> > 
> > 
> > That's true of course. These are just fun things to do when I'm not up to the other things though. Even so it seems I now have some additional things to focus on - but not today.
> > Please do try activating the current string though!
> 
> Activate as in:
> 
> ```shell
>  ./chkentry . . 3
> ```
> 
> ???

The usual way. No number needed. Should be satirical code of Windows and some comments from Bill Gates. If it doesn’t work I will make it happen again soon. 

Leaving for now.

**Comment by xexyl** [comment]
> > > > Thanks .. however we might want to focus a bit more on non-foo too. :-)
> > > 
> > > 
> > > That's true of course. These are just fun things to do when I'm not up to the other things though. Even so it seems I now have some additional things to focus on - but not today.
> > > Please do try activating the current string though!
> > 
> > 
> > Activate as in:
> > ```shell
> >  ./chkentry . . 3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ???
> 
> The usual way. No number needed. Should be satirical code of Windows and some comments from Bill Gates. If it doesn’t work I will make it happen again soon.
> 
> Leaving for now.

Did you do this ? Just want to make sure you saw it. I mean eventually you will see it but it’s fun and funny and when I rediscovered it I knew it had to be put in place!

Btw totally unrelated and very OT: today I watched Batman (which I had only seen once many many years ago) and I discovered something fun: in the titles/credits there’s actually a person with a real surname that we know from L.R. (ad Tolkien sometimes abbreviated it): Proudfoot!

Well it’s sleep time for me. Cheers.

**Comment by xexyl** [comment]
> > > > > Thanks .. however we might want to focus a bit more on non-foo too. :-)
> > > > 
> > > > 
> > > > That's true of course. These are just fun things to do when I'm not up to the other things though. Even so it seems I now have some additional things to focus on - but not today.
> > > > Please do try activating the current string though!
> > > 
> > > 
> > > Activate as in:
> > > ```shell
> > >  ./chkentry . . 3
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ???
> > 
> > 
> > The usual way. No number needed. Should be satirical code of Windows and some comments from Bill Gates. If it doesn’t work I will make it happen again soon.
> > Leaving for now.
> 
> Did you do this ? Just want to make sure you saw it. I mean eventually you will see it but it’s fun and funny and when I rediscovered it I knew it had to be put in place!
> 
> Btw totally unrelated and very OT: today I watched Batman (which I had only seen once many many years ago) and I discovered something fun: in the titles/credits there’s actually a person with a real surname that we know from L.R. (as Tolkien sometimes abbreviated it): Proudfoot!
> 
> Well it’s sleep time for me. Cheers.

**Comment by lcn2** [comment]
```sh
./chkentry -- -1 -1
```

:)

**Comment by xexyl** [comment]
> ```shell
> ```shell
> ./chkentry -- -1 -1
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> :)
> ```

But that gives one of my quotes. Did you see the satirical code of Windows 95 ? I guess you did?

**Comment by xexyl** [comment]
Shutting down the laptop for the day now. Hopefully tomorrow I can get more done.

Enjoy the rest of your day!

**Comment by xexyl** [comment]
> ```shell
> ```shell
> ./chkentry -- -1 -1
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> :)
> UPDATE 0
> Yes, we read that output.  :-)
> ```

Thank you for deleting that comment! Glad you saw it in the tool!

When I rediscovered it I knew I had to put it in! But there are a lot of funny and fun strings and this is another reason I want to get the tool to you sometime soon. Everyone else has to come up with their own code but we’re privileged here 😀

Okay really going to sleep now. Have a great day my friend!

**Pull request merged**
