### PR TITLE
Add last two test_ functions: test_rule_2{a,b}_size() + new txzchk version and more foo

### PR DESCRIPTION
**Pull request by xexyl**
I believe this completes the test_ functions for chkentry (note that
these functions are NOT called in mkiocccentry).

### CODE REVIEW

**Comment by xexyl** [comment]
I believe commit https://github.com/ioccc-src/mkiocccentry/pull/322/commits/e487beb4d747d3545d88a85bc3b45b953896dbd1 resolves the comments from the other pull request the other day.

Going to try sleeping again ... probably won't do anything here again today but we'll see.

**Comment by lcn2** [comment]
Sorry @xexyl:

**This branch has conflicts that must be resolved**

**Comment by xexyl** [comment]
> Sorry @xexyl:
> 
> **This branch has conflicts that must be resolved**

I will look at it in a while. Hopefully I can resolve it. 

Not sure how it happened unless you also updated the file but we’ll see.

**Comment by xexyl** [comment]
> > Sorry @xexyl:
> > **This branch has conflicts that must be resolved**
> 
> I will look at it in a while. Hopefully I can resolve it.
> 
> Not sure how it happened unless you also updated the file but we’ll see.

Looked at the diff and it seems like that’s what happened. I will fix in a bit.

**Comment by xexyl** [comment]
Actually I am booting up the laptop and will look at it now. Then do the other things.

**Comment by xexyl** [comment]
Strange ... I did resolve it but not showing up here. Will look at it a bit more.

**Comment by xexyl** [comment]
Leaving for the day .. hope you have a good night.

I made good progress on the cipher tool btw. I don't know if it'll be possible so that we can automatically generate the array but it's closer to that - just a matter of priorities and working it out. I stopped working on it some hours ago but maybe tomorrow I'll continue at it. I am extra tired today so I didn't get much done.

**Comment by xexyl** [comment]
Hope you're okay .. I know you're on holiday so probably that's all it is but anyway just wanted to say I hope you're okay anyway and having a great day!

**Comment by xexyl** [comment]
Well today I had some fun with my tool. As you'll see in the other thread it now allows for generating the array and in fact the header file entirely so I don't have to copy and paste anything. I have added some real gems to the array as well. Once you're home I'll send you the tool again and make it easier for you so you don't even have to make the text file (that's in .gitignore) - just send it your way.

Only thing I just thought of is maybe there needs to be another mode: so that the tool can take the contents of the encrypted array (so in a separate file) and then decrypt it which can then be used as input. This way we could both update the array without the need for us to each have the same text file (which currently is the case). Well I thought of it before but I didn't think to address it. Maybe I can do that tomorrow though we'll see.

Leaving for the day now.

**Comment by lcn2** [comment]
Thanks for the `foo` fun, @xexyl .  We have some `foo` related fun as well (not related to the text but rather to the process), **however** we will only do so after a number of other issues are closed as a _reward_ for getting things done.  :-)

See issue #87

**Comment by xexyl** [comment]
> Thanks for the `foo` fun, @xexyl . We have some `foo` related fun as well (not related to the text but rather to the process), **however** we will only do so after a number of other issues are closed as a _reward_ for getting things done. :-)
> 

That makes sense yes. Look forward to it!  I'm happy to do more on the chkentry tool I just need to know _when_ to do it.

But you might enjoy the texts as well. When you're home I will send you the tool so you can have some fun with it too - even if only for at that point looking at some of the strings.

> See issue #87

Sure but not right now - zoom meeting about to start. After that I'm watching a film and then going offline.

Good day!

**Pull request merged**
