### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by xexyl**
I think you'll find commit https://github.com/ioccc-src/mkiocccentry/commit/d5496de8f072545200b99a0a610f54c07fb6dee7 most useful and interesting.

The others are simple fixes (and similar types of edits).

### CODE REVIEW

**Comment by xexyl** [comment]
And now I need a break. I'm very tired. I was hoping to work on the man pages today but I'm not sure if I'll manage that (I hope you see what I did! :-) ). I'll look at the repo in some form later on but whether I do anything or not I cannot say.

**Comment by xexyl** [comment]
Oh I forgot to mention that I added `jparse.md` as well.

**Comment by lcn2** [comment]
Thanks .. good idea on the man page @xexyl.  We have a idea for improving the fun in the comment that we will ponder :)

**Comment by xexyl** [comment]
> Thanks .. good idea on the man page @xexyl. We have a idea for improving the fun in the comment that we will ponder :)

I certainly look forward to seeing what you come up with!

**Comment by lcn2** [comment]
> > Thanks .. good idea on the man page @xexyl. We have a idea for improving the fun in the comment that we will ponder :)
> 
> I certainly look forward to seeing what you come up with!

See commit d895e6a2c77dde2dfb29c7c326f362f942e981de ... I think we are done with man page comments.

**Comment by xexyl** [comment]
> > > Thanks .. good idea on the man page @xexyl. We have a idea for improving the fun in the comment that we will ponder :)
> > 
> > 
> > I certainly look forward to seeing what you come up with!
> 
> See commit [d895e6a](https://github.com/ioccc-src/mkiocccentry/commit/d895e6a2c77dde2dfb29c7c326f362f942e981de) ... I think we are done with man page comments.

Well personally I think C++ is objectionable even without trying to obfuscate it. I'm curious what you're implying by it? Still the use of the word 'objectionable' reminds me of one of my personal quotes:

>     Objective C is not quite accurately named. Although it is close, I think a more accurate name would be Objectionable C.

But I have also quotes about C++ being obscene as well. Anyway what are you thinking of when you say C++ obfuscation is wrong?

And I think that I'm also done with comments except for a minor fix in `txzchk.1` that I noticed. However I can worry about that another day.

Hope you have a great afternoon!

**Comment by lcn2** [comment]
> But I have also quotes about C++ being obscene as well. Anyway what are you thinking of when you say C++ obfuscation is wrong?

Some say it is redundant. :-)

BTW: The IOCCC has never claimed that C obfuscation is _right_ either.  :-)

**Comment by lcn2** [comment]
Anyway we have put enough distractions into man page comment .. returning to the work needed to reach **IOCCCMOCK** now.

**Comment by xexyl** [comment]
> > But I have also quotes about C++ being obscene as well. Anyway what are you thinking of when you say C++ obfuscation is wrong?
> 
> Some say it is redundant. :-)
> 

That's true! :) So I guess you're being ironic by pointing out that C++ is obfuscated / obscure / ugly simply by existing?

> BTW: The IOCCC has never claimed that C obfuscation is _right_ either. :-)

Yeah of course. That's entirely the point. Or I should say one of the points. Still it's fun.

**Comment by xexyl** [comment]
> Anyway we have put enough distractions into man page comment .. returning to the work needed to reach **IOCCCMOCK** now.

Agree. Like I said I do have to fix a typo (well kind of a typo) but other than that I don't feel like I need add anything else to comments in the man pages. Certainly for now that holds.

**Pull request merged**
