### PR TITLE
Fix make depend and make depend + add chkentry_test.sh

### PR DESCRIPTION
**Pull request by xexyl**
When cooking the soup with commit
b4f76b5671bd64dd111b7773a5f37d2b1475ff01 make depend broke due to changed paths.

The files chkentry.h and soup/chk_validate.h had to have some paths updated.

After the above changes were made I ran make depend.

### CODE REVIEW

**Comment by xexyl** [comment]
BTW in case there is a clash with what you had in mind for a test suite please see the note in the chkentry page where I wrote:

```
## EDIT 0

BTW: since some of the commits changed (deleted) a lot of invalid files it would be better that if you cannot merge individual commits that I just change the script or make it empty (a stub or whatever) so that you can then edit it. That way I can not worry about having to get the commit rights. I hope that that's okay but if not I'll work it out. I have a way to do it but it would be easier otherwise.
```

I will be here for a couple hours but then probably gone for the day. Hopefully there's no issue though or if any requirement is different it can be easily addressed. I did in another comment point out some issues discovered with writing this tool - with test cases. Some were fixed (see two commits here) but there are still some files that might or might not be invalid test case (hopefully that because if they're not invalid it would mean we have a problem with chkentry / json semantics testing).

**Comment by xexyl** [comment]
Also check the contents of commit https://github.com/ioccc-src/mkiocccentry/pull/384/commits/78e785e51a757c032f613857e2b34be914256e14 as I think you'll get a laugh out of it - in a comment of the man page.

**Comment by lcn2** [comment]
There are too many different things in this commit.  Some of which we need, some of which are very useful, others of which are impacting our testing plans.

**Comment by xexyl** [comment]
> There are too many different things in this commit. Some of which we need, some of which are very useful, others of which are impacting our testing plans.

So what do you suggest we do?

**Comment by xexyl** [comment]
If it's just the script that's the problem maybe you could merge it and then replace it? If it's something else I can fix it as well. If nothing else maybe you can look at merging the things that you find useful and need but I don't really know how GitHub handles that part.

**Comment by xexyl** [comment]
> There are too many different things in this commit. Some of which we need, some of which are very useful, others of which are impacting our testing plans.
> 
> ### UPDATE 0
> We are still reviewing this request.

Sure. Like I said I'll be leaving soon but I'd be happy to fix anything that needs to be fixed but it probably cannot happen until tomorrow as I'm getting quite tired.

**Comment by xexyl** [comment]
So it worked out. Great! I hope you have a great night and I will look forward to looking at what you've come up with when I look again.

Have a great night my friend!

**Comment by lcn2** [comment]
OK, probably better to accept this as a while pull request.

It appeared that there were several things going on in this pull request: perhaps some of them could have been in separate pull request .. not sure.  We will have to stash our work and review and perhaps toss some of our stuff and/or replace or something ...

**Comment by xexyl** [comment]
> OK, probably better to accept this as a while pull request.
> 
> It appeared that there were several things going on in this pull request: perhaps some of them could have been in separate pull request .. not sure. We will have to stash our work and review and perhaps toss some of our stuff and/or replace or something ...

I hope it doesn't cause any problems!

But about multiple pull requests: I'm happy to do that in the future if I know the details. Is it just a matter of making another branch and doing a pull request from it? I can try experimenting with that tomorrow if you'd like?

**Comment by lcn2** [comment]
We are concerned about the multiple deletes under test_JSON.  Why was this needed?

**Comment by xexyl** [comment]
> We are concerned about the multiple deletes under test_JSON. Why was this needed?

Because you said it should be for valid JSON files that are invalid for the tool. Previously we had invalid files also. Maybe they could be moved to the general.json ? I didn't think of that because that's more for general files.

**Comment by lcn2** [comment]
> > We are concerned about the multiple deletes under test_JSON. Why was this needed?
> 
> Because you said it should be for valid JSON files that are invalid for the tool. Previously we had invalid files also. Maybe they could be moved to the general.json ? I didn't think of that because that's more for general files.

Yes, that was the idea of `general.json`.

**Comment by xexyl** [comment]
> We are concerned about the multiple deletes under test_JSON. Why was this needed?
> 
> ### UPDATE 0
> Perhaps this has something to do with the test tool you wrote .. and a possible contrast with our testing plans?

Nope. See above. It has only to do with those files were invalid json files and you wanted those directories to have only valid json files.

**Comment by xexyl** [comment]
> > > We are concerned about the multiple deletes under test_JSON. Why was this needed?
> > 
> > 
> > Because you said it should be for valid JSON files that are invalid for the tool. Previously we had invalid files also. Maybe they could be moved to the general.json ? I didn't think of that because that's more for general files.
> 
> Yes, that was the idea of `general.json`.

Well I still have a copy of those files. Want me to quickly move them over ?

**Comment by lcn2** [comment]
> > > > We are concerned about the multiple deletes under test_JSON. Why was this needed?
> > > 
> > > 
> > > Because you said it should be for valid JSON files that are invalid for the tool. Previously we had invalid files also. Maybe they could be moved to the general.json ? I didn't think of that because that's more for general files.
> > 
> > 
> > Yes, that was the idea of `general.json`.
> 
> Well I still have a copy of those files. Want me to quickly move them over ?

Yes please.

**Comment by xexyl** [comment]
> > > > > We are concerned about the multiple deletes under test_JSON. Why was this needed?
> > > > 
> > > > 
> > > > Because you said it should be for valid JSON files that are invalid for the tool. Previously we had invalid files also. Maybe they could be moved to the general.json ? I didn't think of that because that's more for general files.
> > > 
> > > 
> > > Yes, that was the idea of `general.json`.
> > 
> > 
> > Well I still have a copy of those files. Want me to quickly move them over ?
> 
> Yes please.

I need to figure out how to isolate the ones first. Let's see if I can do this easily enough.

**Comment by xexyl** [comment]
Is it okay if it has some duplicates ? Some that are semantically invalid, too, in other words? We could then isolate the two and get rid of any duplicates if necessary.

**Comment by xexyl** [comment]
> Is it okay if it has some duplicates ? Some that are semantically invalid, too, in other words? We could then isolate the two and get rid of any duplicates if necessary.

The reason is I need to get going soon.

**Comment by lcn2** [comment]
> Is it okay if it has some duplicates ? Some that are semantically invalid, too, in other words? We could then isolate the two and get rid of any duplicates if necessary.

If they are invalid JSON, the semantic tests are meaningless as far as `chkentry(1)` is concerned.  So as long as all files under `test_JSON/{auth, info}.json/` are valid JSON, that is fine.  The `test_JSON/general.json/` tree can hold invalid JSON tests and valid JSON tests that are more useful for testing the JSON parser `jparse(1)` and that `chkentry(1)` testing will ignore.

**Comment by xexyl** [comment]
I just might have come up with a way to do it but in order to speed this along I'll do that: any of the bad ones (because they were invalid json) that were deleted will now be under general.json/bad as well. We can then look for duplicates later and delete them.

I hope that will help and apologies for the misunderstanding!

**Comment by xexyl** [comment]
Done. Hope that helps! I'll be here a short bit more but need to get going very soon so I will bid you a good night!

**Comment by xexyl** [comment]
> ### UPDATE 0
> If `chkentry(1)` cannot build a JSON parse tree (i.e., if the JSON is not valid), then `chkentey(1)` exits and does NOT perform any semantical tests. We plan to have a different exit code for _invalid JSON_, BTW. The `chkentry_test.sh` tool can use this exit code to flag, as a test suite mis-feature, any invalid JSON files that it finds.

Sounds good to me. Maybe also look at the old script with the error code checker ? Not sure if we need it or not.

**Comment by lcn2** [comment]
> > ### UPDATE 0
> > If `chkentry(1)` cannot build a JSON parse tree (i.e., if the JSON is not valid), then `chkentey(1)` exits and does NOT perform any semantical tests. We plan to have a different exit code for _invalid JSON_, BTW. The `chkentry_test.sh` tool can use this exit code to flag, as a test suite mis-feature, any invalid JSON files that it finds.
> 
> Sounds good to me. Maybe also look at the old script with the error code checker ? Not sure if we need it or not.

The old error code checker is not needed.  We will edit `chkentry_test.sh` as needed along with `chkentry(1)`.

**Comment by xexyl** [comment]
> > > ### UPDATE 0
> > > If `chkentry(1)` cannot build a JSON parse tree (i.e., if the JSON is not valid), then `chkentey(1)` exits and does NOT perform any semantical tests. We plan to have a different exit code for _invalid JSON_, BTW. The `chkentry_test.sh` tool can use this exit code to flag, as a test suite mis-feature, any invalid JSON files that it finds.
> > 
> > 
> > Sounds good to me. Maybe also look at the old script with the error code checker ? Not sure if we need it or not.
> 
> The old error code checker is not needed. We will edit `chkentry_test.sh` as needed along with `chkentry(1)`.

Sounds good. Shutting down now.

Good night! Look forward to seeing what you come up with. BCNU! :-)

Oh btw: you had a great birthday, right ?

**Comment by xexyl** [comment]
Oh one more thing real quick. I see that the `all_ref.sh` script uses `basename`. Want me to add that to the bug report script tomorrow ?

Anyway shutting down now. Good night!

**Comment by lcn2** [comment]
> Oh one more thing real quick. I see that the `all_ref.sh` script uses `basename`. Want me to add that to the bug report script tomorrow ?
> 
> Anyway shutting down now. Good night!

Yes, and an optional utility.

**Comment by xexyl** [comment]
> > Oh one more thing real quick. I see that the `all_ref.sh` script uses `basename`. Want me to add that to the bug report script tomorrow ?
> > Anyway shutting down now. Good night!
> 
> Yes, and an optional utility.

Do you mean as an optional utility or a utility that you forgot to mention ? I will assume for now it's a requirement because it's used but if you need it to be optional I will change it.

**Comment by lcn2** [comment]
> > > Oh one more thing real quick. I see that the `all_ref.sh` script uses `basename`. Want me to add that to the bug report script tomorrow ?
> 
> > > Anyway shutting down now. Good night!
> 
> > 
> 
> > Yes, and an optional utility.
> 
> 
> 
> Do you mean as an optional utility or a utility that you forgot to mention ? I will assume for now it's a requirement because it's used but if you need it to be optional I will change it. 
> 
> 
> 
> 

It is optional.  The tests are not required to build nor use the tools.

**Comment by xexyl** [comment]
> > > > Oh one more thing real quick. I see that the `all_ref.sh` script uses `basename`. Want me to add that to the bug report script tomorrow ?
> > 
> > 
> > > > Anyway shutting down now. Good night!
> > 
> > 
> > > 
> > 
> > 
> > > Yes, and an optional utility.
> > 
> > 
> > Do you mean as an optional utility or a utility that you forgot to mention ? I will assume for now it's a requirement because it's used but if you need it to be optional I will change it.
> 
> It is optional. The tests are not required to build nor use the tools.

Right. Okay. Will do that. First looking more at that bug. I just have to isolate the files that are in the wrong subdirectory.

I hope you can get some sleep soon!

**Comment by xexyl** [comment]
> > > > > Oh one more thing real quick. I see that the `all_ref.sh` script uses `basename`. Want me to add that to the bug report script tomorrow ?
> > > 
> > > 
> > > > > Anyway shutting down now. Good night!
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Yes, and an optional utility.
> > > 
> > > 
> > > Do you mean as an optional utility or a utility that you forgot to mention ? I will assume for now it's a requirement because it's used but if you need it to be optional I will change it.
> > 
> > 
> > It is optional. The tests are not required to build nor use the tools.
> 
> Right. Okay. Will do that. First looking more at that bug. I just have to isolate the files that are in the wrong subdirectory.
> 
> I hope you can get some sleep soon!

Problem: I already had `basename` in. Why is it a problem? Because you had said it was a required one. Should I change it to optional then?

**Comment by lcn2** [comment]
> > > > > > Oh one more thing real quick. I see that the `all_ref.sh` script uses `basename`. Want me to add that to the bug report script tomorrow ?
> 
> > > > 
> 
> > > > 
> 
> > > > > > Anyway shutting down now. Good night!
> 
> > > > 
> 
> > > > 
> 
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > > Yes, and an optional utility.
> 
> > > > 
> 
> > > > 
> 
> > > > Do you mean as an optional utility or a utility that you forgot to mention ? I will assume for now it's a requirement because it's used but if you need it to be optional I will change it.
> 
> > > 
> 
> > > 
> 
> > > It is optional. The tests are not required to build nor use the tools.
> 
> > 
> 
> > Right. Okay. Will do that. First looking more at that bug. I just have to isolate the files that are in the wrong subdirectory.
> 
> > 
> 
> > I hope you can get some sleep soon!
> 
> 
> 
> Problem: I already had `basename` in. Why is it a problem? Because you had said it was a required one. Should I change it to optional then?

Sorry we forgot where it was used. It should be required.

**Comment by xexyl** [comment]
> > > > > > > Oh one more thing real quick. I see that the `all_ref.sh` script uses `basename`. Want me to add that to the bug report script tomorrow ?
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > > > Anyway shutting down now. Good night!
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > > Yes, and an optional utility.
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > Do you mean as an optional utility or a utility that you forgot to mention ? I will assume for now it's a requirement because it's used but if you need it to be optional I will change it.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > It is optional. The tests are not required to build nor use the tools.
> > 
> > 
> > > 
> > 
> > 
> > > Right. Okay. Will do that. First looking more at that bug. I just have to isolate the files that are in the wrong subdirectory.
> > 
> > 
> > > 
> > 
> > 
> > > I hope you can get some sleep soon!
> > 
> > 
> > Problem: I already had `basename` in. Why is it a problem? Because you had said it was a required one. Should I change it to optional then?
> 
> Sorry we forgot where it was used. It should be required.

Thank you for clarifying. In that case no change is needed. I do want to remind you that I actually wondered if the `bug_report.sh` and `hostchk.sh` could be considered complete besides maybe some clean up but we can discuss that over at the other threads in time.

**Pull request merged**
