### PR TITLE
Add bad test files in test_txzchk/bad and various updates and fixes

### PR DESCRIPTION
**Pull request by xexyl**
Add the following test files to test_txzchk/bad (txzchk must report at
least one issue for each file - which it does and txzchk_test.sh passes
all tests):

    entry.test-0.1652598666.txt
    entry.test-0.9876543210.txt
    entry.test-1.9876543210.txt
    entry.test-10.9876543210.txt
    entry.test-2.1652598666.txt
    entry.test-2.9876543210.txt
    entry.test-3.1652598666.txt
    entry.test-3.9876543210.txt
    entry.test-4.1652598666.txt
    entry.test-4.9876543210.txt
    entry.test-5.1652598666.txt
    entry.test-5.9876543210.txt
    entry.test-6.1652598666.txt
    entry.test-6.9876543210.txt
    entry.test-7.9876543210.txt
    entry.test-9.9876543210.txt

These files are based on the tarballs that were used during development
of txzchk to make sure all issues that txzchk had to detect were in fact
detected. The only difference is that they're now text files and the
timestamp was updated as the MIN_TIMESTAMP has been updated since the
time of the creation of txzchk.

As for the file:

    entry.test-10.9876543210.txt

A point of interest might be that fnamchk will fail so txzchk will
report that the directory name is indeed wrong. You would see an error
like so:

    ERROR[6]: main: second '-' separated token length: 7 != 6: ./test_txzchk/bad/entry.test-10.9876543210.txt

This is because of:

    #define MAX_ENTRY_CHARS (1)             /* characters that represent the maximum entry number */

which is used in fnamchk as:

        if (len != LITLEN("test-")+MAX_ENTRY_CHARS) {
	    /* ... */
	}

and

        if (len != UUID_LEN+1+MAX_ENTRY_CHARS) {
	    /* ... */
	}

Whether fnamchk should print the directory name at this point and then
return an error is I suppose up to discussion: it would allow for
testing more but it might be unnecessary as well given that a badly
named tarball would presumably be disqualified. Even so it might help
uncover some types of problems with txzchk.

TODO add even more tarball listings. I am pretty sure I have some that I
created as well but more can be contrived as well (one or more of the
above might actually be some I created myself but all the invalid
tarballs that were used for development are also included).

As for the typo fix: in txzchk_test.sh it was in a variable name:
EXIT_CODE_FIlE -> EXIT_CODE_FILE.

### CODE REVIEW

**Comment by xexyl** [comment]
An interesting question for you in the log, Landon:

```
Whether fnamchk should print the directory name at this point and then
return an error is I suppose up to discussion: it would allow for
testing more but it might be unnecessary as well given that a badly
named tarball would presumably be disqualified. Even so it might help
uncover some types of problems with txzchk.
```

What do you think?

**Comment by xexyl** [comment]
> An interesting question for you in the log, Landon:
> 
> ```
> Whether fnamchk should print the directory name at this point and then
> return an error is I suppose up to discussion: it would allow for
> testing more but it might be unnecessary as well given that a badly
> named tarball would presumably be disqualified. Even so it might help
> uncover some types of problems with txzchk.
> ```
> 
> What do you think?

Of course depending on where the failure (or failures) is (are) it would be impossible to do this as it uses `strtok`. But in some cases it might be possible? Perhaps it's not really useful though. I will leave that to you.

**Comment by xexyl** [comment]
Heading off for the day. More from me tomorrow. Good day!

**Comment by lcn2** [comment]
> An interesting question for you in the log, Landon:
> 
> ```
> Whether fnamchk should print the directory name at this point and then
> return an error is I suppose up to discussion: it would allow for
> testing more but it might be unnecessary as well given that a badly
> named tarball would presumably be disqualified. Even so it might help
> uncover some types of problems with txzchk.
> ```
> 
> What do you think?

Either way is fine.  The overall `make test` is not rather verbose so having `fnamchk` print the directory name is reasonable.

**Comment by lcn2** [comment]
Thanks for the pull request, @xexyl .

Do you intend to write more tests, or is issue #235 far along along to call it closed?

**Comment by xexyl** [comment]
> Thanks for the pull request, @xexyl .
> 
> Do you intend to write more tests, or is issue #235 far along along to call it closed?

I think I'll be adding more cases but I'm not sure that means that the issue has to be open still. I mean we also have a test suite for the `jinfochk` and `jauthchk` which is closed and we still have added cases so I will go ahead and close it after this.

As for adding test cases I might do the today but not sure. It's a very slow day. I slept in till almost 4 which is great but I'm feeling very fatigued and I also got some sad news that a good friend of mine lost his auntie to Alzheimer's - she died in the last 12 hours or so. 

Most weeks I only have Mondays that are busy at 11 (for about 45 minutes) (and I do this week too) but this week I have three other doctor appointments as well so it might be slower this week. I also have another doctor appointment next week and I'll be discussing surgery that day. I fear it has come to the point where it'll be required and it would remove some stress to just get it over with. 

Anyway I'll go ahead and close that issue. I saw that you were awake a couple hours or maybe few hours ago so I hope you're sleeping by now!

**Pull request merged**
