### PR TITLE
Minor improvement of workflows/test.yml

### PR DESCRIPTION
**Pull request by xexyl**
It now installs checknr as the original did not have an exit code that would indicate failure if there was a problem until I added it (in the repo that was created by Landon for those who do not have access to it).

### CODE REVIEW

**Comment by xexyl** [comment]
If you want me to I can update the CHANGES.md file for these recent changes. I can do that later today if you want. Just let me know.

**Comment by lcn2** [comment]
> If you want me to I can update the CHANGES.md file for these recent changes. I can do that later today if you want. Just let me know.

Please do.

**Review by lcn2 — APPROVED** [review]
Interesting idea, @xexyl

**Comment by xexyl** [comment]
> > If you want me to I can update the CHANGES.md file for these recent changes. I can do that later today if you want. Just let me know.
> 
> Please do.

Hmm .. is this still necessary though? It looks like you took care of it? I would have but I was helping with debugging that problem (and fortunately I did see the `-j4` part and fortunately I had tried it in the past as it was a weird one).

Let me know and if you want me to update the file or anything else I will happily do that. But I guess you got it in order? Though I did make a typo fix in the example remarks file.

**Pull request merged**
