### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by xexyl**
Probably all I'll manage to do today but we'll see.

Hope you had a nice sleep and hope you had a GREAT birthday!

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Of course my friend! I enjoy helping out. I mean I really really enjoy it! It really feels good to be a part of IOCCC history in a different way (compared to winning which of course I am also immensely proud of doing!)!

**Comment by lcn2** [comment]
> > Thanks @xexyl
> 
> Of course my friend! I enjoy helping out. I mean I really really enjoy it! It really feels good to be a part of IOCCC history in a different way (compared to winning which of course I am also immensely proud of doing!)!

Both seem to be excellent experiences .. although as an IOCCC judge I am unfamiliar with the latter :-)

**Comment by xexyl** [comment]
> > > Thanks @xexyl
> > 
> > 
> > Of course my friend! I enjoy helping out. I mean I really really enjoy it! It really feels good to be a part of IOCCC history in a different way (compared to winning which of course I am also immensely proud of doing!)!
> 
> Both seem to be excellent experiences .. although as an IOCCC judge I am unfamiliar with the latter :-)

Poor you! :-) I joke but I'm also serious for it really is a great surprise and joy. But of course you would be unfamiliar with it. Still it seems like I've won many more times now having helped out so much with this repo and for that I'm immensely proud and overjoyed. A funny word really: is there such a thing as too much joy? Depending on how you look at it I'd say no but then some say there is too much of all good things too. I don't know. Still seems a strange word.

Of course that's not what it means but you'd think it would be as other words that have the over- prefix suggest it's too much.

**Pull request merged**
