### PR TITLE
Add Jessica Noll comment to jprint.c main()

### PR DESCRIPTION
**Pull request by xexyl**
... even though technically the tool is not done yet :-)

### CODE REVIEW

**Comment by lcn2** [comment]
👶 @xexyl

**Comment by xexyl** [comment]
> 👶 @xexyl

I've wanted to ask you actually almost since the first time I saw it. how old is Jessica now anyway? I presume that was years ago?

**Comment by xexyl** [comment]
Also do you remember the context of it ?

**Comment by xexyl** [comment]
.. really going to try resting now .. will do more later ...

**Comment by lcn2** [comment]
> > 👶 @xexyl
> 
> 
> 
> I've wanted to ask you actually almost since the first time I saw it. how old is Jessica now anyway? I presume that was years ago?

40

**Comment by xexyl** [comment]
> > > 👶 @xexyl
> > 
> > 
> > I've wanted to ask you actually almost since the first time I saw it. how old is Jessica now anyway? I presume that was years ago?
> 
> 40

Ah. So almost as old as me but my parents were a fair bit older than you when they had me. Thanks.

**Pull request merged**
