### PR TITLE
Various updates, enhancements and fixes

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Leaving for the day now .. will do more tomorrow.

**Comment by lcn2** [comment]
Lots of very good changes here, @xexyl.  While it might be a while before we can test this further, we do plan to look at the new `static_analysis.md` file later.

One question:

The `dbg/dbg.h` file attempted to allow old C compilers to handle a lack of `__attribute__` facility.  We believe this worked reasonable well with older C compilers.  We wonder if some sort of workaround is needed for the new `__attribute__((noreturn))` facility?  It's may be OK as it is now .. we were just wondering.

**Comment by lcn2** [comment]
After the pull request:

On RHEL7.9, `make prep`, @xexyl:

```
...
make_action 24 bug_report-txl OK
make_action 25 shellcheck ERROR exit code 2
make_action 26 seqcexit ERROR exit code 2
make_action 27 picky ERROR exit code 2
make_action 28 tags ERROR exit code 2
make_action 29 check_man OK
make_action 30 all ERROR exit code 2
make_action 31 test OK
One or more tests failed:

	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2

See test_ioccc/test_ioccc.log for more details.

make prep: ERROR: prep.sh exit code: 30

make prep: see build.log for build details

make: *** [prep] Error 30
```

Also a bug: there is no `test_ioccc/test_ioccc.log` file.

We will attach the `build_log` here:

[build.log](https://github.com/ioccc-src/mkiocccentry/files/10416509/build.log)

We will attach `bug-report.20230113.201053.txt` file here:

[bug-report.20230113.201053.txt](https://github.com/ioccc-src/mkiocccentry/files/10416511/bug-report.20230113.201053.txt)

**Comment by lcn2** [comment]
On Debian 10.13, @xexyl, `make prep`:

```
make_action 10 clobber OK
make_action 11 all ERROR exit code 2
make_action 12 depend OK
make_action 13 clean_mkchk_sem OK
make_action 14 all_sem_ref OK
make_action 15 mkchk_sem OK
make_action 16 all ERROR exit code 2
make_action 18 parser OK
make_action 19 all ERROR exit code 2
make_action 20 load_json_ref OK
make_action 21 use_json_ref OK
make_action 22 clean_generated_obj OK
make_action 23 all ERROR exit code 2
make_action 24 bug_report-txl OK
make_action 25 shellcheck ERROR exit code 2
make_action 26 seqcexit ERROR exit code 2
make_action 27 picky ERROR exit code 2
make_action 28 tags ERROR exit code 2
make_action 29 check_man OK
make_action 30 all ERROR exit code 2
make_action 31 test OK
One or more tests failed:

	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2
	make -f ./Makefile non-zero exit code: 2

See test_ioccc/test_ioccc.log for more details.

make prep: ERROR: prep.sh exit code: 30

make prep: see build.log for build details

make: *** [Makefile:547: prep] Error 30
```

Also a bug: there is no test_ioccc/test_ioccc.log file.

We will attach the build_log here:

[build.log](https://github.com/ioccc-src/mkiocccentry/files/10416513/build.log)

After running ./bug_report.sh, here is the `bug-report.20230113.201729.txt` file:

[bug-report.20230113.201729.txt](https://github.com/ioccc-src/mkiocccentry/files/10416517/bug-report.20230113.201729.txt)

**Comment by xexyl** [comment]
Well that’s strange but I will look at it shortly. 

Thanks for reporting it!

If they are the same I should be able to figure it out because CentOS 7 is RH 7. 

Will boot up laptop in a couple minutes and then look at it.

**Comment by xexyl** [comment]
> Lots of very good changes here, @xexyl. While it might be a while before we can test this further, we do plan to look at the new `static_analysis.md` file later.

Thank you and that’s a very good idea! I would actually appreciate that a lot. Seems like it might need it too. 

What I do not understand is why some of those tests failed. For instance why did shellcheck fail? I didn’t modify any scripts that I recall so I wonder if they failed because of earlier commits? 

I will look at that soon. 
> 
> One question:
> 
> The `dbg/dbg.h` file attempted to allow old C compilers to handle a lack of `__attribute__` facility. We believe this worked reasonable well with older C compilers. We wonder if some sort of workaround is needed for the new `__attribute__((noreturn))` facility? It's may be OK as it is now .. we were just wondering.

Well that is a good point. But there were other functions which already had that. 

Perhaps this warning should be ignored then ?

Getting laptop up now.

**Comment by xexyl** [comment]
I noticed another thing that might be part of the problem with RH. Whereas it's not complained about with clang under macOS it must be with gcc under CentOS. This one is an easy fix. But here's the details.

Changing the `quiet` in `jnum_chk.h` to static means it becomes an error since it's not actually used. But why is this? It's an interesting one. I believe it's because I had to include that file in jnum_test.c. And looking at it again I see that is indeed it. Maybe a new header file would be better after all. I'll look at that.

**Comment by xexyl** [comment]
I think I know the problem. I thought I knew it as soon as I tried to run by itself `make shellcheck`. I'm going to do a test and then if it's the case I'll fix it. If so it's a funny one but it raises an interesting question that I'll bring up in the other thread.

**Comment by xexyl** [comment]
I do indeed know the problem. This is quite funny actually. I'll do a fix and then a pull request. Well actually I already fixed it but need to scp it to the laptop and then write a description. I think it might be good to add this information to the static_analysis.md file too.

After that I'll write a comment in the other thread and link to it here as it raises a curious question. You might be surprised to find out that it was a single problem namely that which is in https://github.com/ioccc-src/mkiocccentry/pull/478#issuecomment-1382717614.

**Comment by xexyl** [comment]
This problem has been fixed in https://github.com/ioccc-src/mkiocccentry/pull/479/commits/7c69962080d49df1b23b9dba5f67781d2db2e6fc.

I will be updating this comment once I have added a comment in the other thread about this issue. Stay tuned .. though I hope for your sake you won't care about that part as you're hopefully sleeping right now. :)

**Comment by xexyl** [comment]
> ```
> 
> Also a bug: there is no test_ioccc/test_ioccc.log file.
> 

As far as this goes: great catch! That log file is created by `ioccc_test.sh` but `prep.sh` does not actually use that directly. It does it, of course, through `make test`. But why is the log file not being created? I'll look into this and then update this comment - hopefully I'll make a commit that fixes it too.

**Comment by xexyl** [comment]
I know why the log file is not being created. It's because it abandons prior to creating and writing to the log file if some of the utilities are missing or not executable.

Thus the log file should be created first and then written to if they don't exist. It might be helpful too if it checks for all of them first and if any are missing it then exits. I'll do this.

After that I will probably have to go for a bit (hoping I can finish this before I have to leave). When I'm back after that I hope I can do a bit more on the static analysis .. we shall see.

**Pull request merged**
