### PR TITLE
Bug fixes and var/struct/function renaming

### PR DESCRIPTION
**Pull request by xexyl**
See the git log for details.

### CODE REVIEW

**Comment by xexyl** [comment]
This will be the last of today - after I update the version of all programs. I had a really awful night last night.

**Comment by lcn2** [comment]
Thanks @xexyl  .. shutdown down the laptop and heading to the train.

**Comment by xexyl** [comment]
Thank you Landon! Have a great day! If you reply to any of my other comments I'll try getting back to you but this is all the code I'll do.

**Comment by xexyl** [comment]
> Thanks @xexyl .. shutdown down the laptop and heading to the train.

Have a safe trip!

**Pull request merged**
