### PR TITLE
Add another annoying .DS_Store glob to .gitignore

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Review by lcn2 — APPROVED** [review]
Thanks @xexyl 

# QUESTION

What does `._.DS_Store` do in `.gitignore`?

Is `._.DS_Store` some special `.gitignore` exclude pattern, or are there literally files named `._.DS_Store` that show up from time to time, or ???

**Comment by xexyl** [comment]
> Thanks @xexyl
> 
> # QUESTION
> What does `._.DS_Store` do in `.gitignore`?
> 
> Is `._.DS_Store` some special `.gitignore` exclude pattern, or are there literally files named `._.DS_Store` that show up from time to time, or ???

I'm afraid they sometimes show up yes.

**Comment by xexyl** [comment]
> > Thanks @xexyl
> > # QUESTION
> > What does `._.DS_Store` do in `.gitignore`?
> > Is `._.DS_Store` some special `.gitignore` exclude pattern, or are there literally files named `._.DS_Store` that show up from time to time, or ???
> 
> I'm afraid they sometimes show up yes.

I haven't figured out what causes them to show up .. or the others. It seems almost random. But for instance:

```sh
$ find . -name '._.DS_Store'
./test_ioccc/._.DS_Store
./test_ioccc/test_JSON/._.DS_Store
./test_ioccc/test_JSON/general.json/._.DS_Store
./test_ioccc/test_JSON/info.json/._.DS_Store
./test_ioccc/test_JSON/auth.json/._.DS_Store
./test_ioccc/test_txzchk/._.DS_Store
```

I could swear I have seen there similar names to do with `.DS_Store`. A most annoying thing.

**Comment by SirWumpus** [comment]
`._.DS_Store` is a MacOS thing as I recall.  I've seen in other projects where developers are a using Mac and Windows machines.  Typically I'd ignore it, unless its worth keep for Mac users. No idea what its function.

**Comment by xexyl** [comment]
> `._.DS_Store` is a MacOS thing as I recall. I've seen in other projects where developers are a using Mac and Windows machines. Typically I'd ignore it, unless its worth keep for Mac users. No idea what its function.

Yes it's indeed a macOS thing but usually (not always) it's a `.DS_Store`. It shows up in directories with media type files, last I knew, but maybe there is more to it than that. I have never bothered to use it.

FYI:

```sh
$ file test_ioccc/._.DS_Store
test_ioccc/._.DS_Store: AppleDouble encoded Macintosh file
```

though I'm not sure if that's the same as `.DS_Store` or not. Let's see if I have any....

```sh
$ file .DS_Store 
.DS_Store: Apple Desktop Services Store

```

Thought so. They are different.

**Comment by xexyl** [comment]
But on the subject of Windows here is an old, very old, classic:

<hr>

# Is Windows a Virus?

No, Windows is not a virus. Here's what viruses do:

They replicate quickly - okay, Windows does that.

Viruses use up valuable system resources, slowing down the system as they do so - okay, Windows does that.

Viruses will, from time to time, trash your hard disk - okay, Windows does that too.

Viruses are usually carried, unknown to the user, along with valuable programs and systems. Sigh... Windows does that, too.

Viruses will occasionally make the user suspect their system is too slow (see 2) and the user will buy new hardware. Yup, that's with Windows, too.

Until now it seems Windows is a virus but there are fundamental differences: viruses are well supported by their authors, are running on most systems, their program code is fast, compact and efficient and they tend to become more sophisticated as they mature.

So Windows is not a virus. It's a bug.

<hr>

I will also argue it is Swiss cheese. Which brings up a meme I made back in 2011 but I've shared that a number of times so I won't bother. Still the above is good fun ... if you can have fun with Windows.

**Comment by lcn2** [comment]
Thank you @xexyl, with commit 69bef8add20275e979171fb6bdee68dcab9a3562 on the "other repo" we added `._.DS_Store` to that repo's `.gitignore` file.  In so doing, we discovered a bug in the the tools invoked by `make sort_gitignore` AND improved the `bin/sgi.sh` code to properly canonicalize `.gitignore` files (including `._.DS_Store` lines).

**Comment by xexyl** [comment]
> Thank you @xexyl, with commit 69bef8add20275e979171fb6bdee68dcab9a3562 on the "other repo" we added `._.DS_Store` to that repo's `.gitignore` file. In so doing, we discovered a bug in the the tools invoked by `make sort_gitignore` AND improved the `bin/sgi.sh` code to properly canonicalize `.gitignore` files (including `._.DS_Store` lines).

I did not even think of that repo as I have been so busy here and with jparse! Thanks for taking care of that! I better pull the changes so I don't run into any problems. Thanks for the note.

**Pull request merged**
