### PR TITLE
More foo

### PR DESCRIPTION
**Pull request by xexyl**
I'll be leaving for the day now. Might be able to reply briefly on the phone later on but probably won't bother unless something important comes up so with that in mind I'll wish you a safe and fun holiday!

BCNU! :)

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks and with commit 3832f883ea235f0f7dc8db9cedea0e5b36aa92f4 we sleep (literally) and exit into preparing for vacation mode.

Suggestion: There are some empty comments in `foo.c`:

```c
/*
 */
```

that you might comment on/in.  :-)

Best wishes on sleep .. we have to time shift sleeping schedule by 11 hours while at the same time making sure we packed stuff well and then try to be coherent while navigating thru interesting travel spaces.  We hope you sleep schedule, @xexyl, will are much better.

**Comment by xexyl** [comment]
> Thanks and with commit [3832f88](https://github.com/ioccc-src/mkiocccentry/commit/3832f883ea235f0f7dc8db9cedea0e5b36aa92f4) we sleep (literally) and exit into preparing for vacation mode.
> 
> Suggestion: There are some empty comments in `foo.c`:
> 
> ```c
> /*
>  */
> ```
> 
> that you might comment on/in. :-)
> 

Fun idea!

> Best wishes on sleep .. we have to time shift sleeping schedule by 11 hours while at the same time making sure we packed stuff well and then try to be coherent while navigating thru interesting travel spaces. We hope you sleep schedule, @xexyl, will are much better.

That doesn’t sound like fun but hopefully you manage okay. 

Sleep is never good but some nights are better than others. At least some days lately I have been able to sleep in a bit. 

Have a safe and fun holiday! Until next time! Cheers.

**Comment by xexyl** [comment]
> ### UPDATE 1a:
> The `isascii()` test warning message could be better. It was the best we could do given the time shifting we are undergoing.

Ah. Well when I read it I was with my distance glasses not my reading so which is hard enough on laptop (in fact I never do it) but probably worse on phone (where I was). Also the diff was acting funny with scrolling. I'm not even sure how to describe it. Anyway I thought you had just added a comment to `isalpha()`.
> 
> BTW: In general it is a good idea to test for ASCII first with `isascii()` before using an ASCII sub-setting macro such as `isalpha()`.


Interesting little bit of information to know. I guess it makes sense but would you maybe elaborate why that is when you have a chance? I'm curious if there are subtleties I'm unaware of. Thanks and I hope you're doing well .. not sure where about you are now but I hope if you're in flight it's well and I hope if you're not everything is well too!

**Comment by xexyl** [comment]
> > ### UPDATE 1a:
> > The `isascii()` test warning message could be better. It was the best we could do given the time shifting we are undergoing.
> 
> Ah. Well when I read it I was with my distance glasses not my reading so which is hard enough on laptop (in fact I never do it) but probably worse on phone (where I was). Also the diff was acting funny with scrolling. I'm not even sure how to describe it. Anyway I thought you had just added a comment to `isalpha()`.

I think you'll like my change to it. Not committing for now as I have other things to do and I probably will rest in a bit again but I think you'll appreciate it nonetheless. It refers to an old fun computer quote/joke/wordplay.

**Comment by lcn2** [comment]
> Interesting little bit of information to know. I guess it makes sense but would you maybe elaborate why that is when you have a chance? 

One common implementation for such macros is to index into a table of 128 bytes of 0's and 1's for most of the `isfoo()` calls.  The `isascii()` macro is a simple bounds (`<128`) check on the unsigned cast of the argument.  Thus, `isalpha(128)` behavior is undefined. as is `isalpha(255)` and beyond.  That is why it is important to pre-test with `isascii()`.

**Comment by xexyl** [comment]
> > Interesting little bit of information to know. I guess it makes sense but would you maybe elaborate why that is when you have a chance?
> 
> One common implementation for such macros is to index into a table of 128 bytes of 0's and 1's for most of the `isfoo()` calls. The `isascii()` macro is a simple bounds (`<128`) check on the unsigned cast of the argument. Thus, `isalpha(128)` behavior is undefined. as is `isalpha(255)` and beyond. That is why it is important to pre-test with `isascii()`.

Interesting! So a lot of code is potentially UB. And we all know what that means .. it can HCF. :)

I have some fun comments to commit .. will do soon.

**Comment by lcn2** [comment]
> > > Interesting little bit of information to know. I guess it makes sense but would you maybe elaborate why that is when you have a chance?
> > 
> > 
> > One common implementation for such macros is to index into a table of 128 bytes of 0's and 1's for most of the `isfoo()` calls. The `isascii()` macro is a simple bounds (`<128`) check on the unsigned cast of the argument. Thus, `isalpha(128)` behavior is undefined. as is `isalpha(255)` and beyond. That is why it is important to pre-test with `isascii()`.
> 
> Interesting! So a lot of code is potentially UB. And we all know what that means .. it can HCF. :)
> 
> I have some fun comments to commit .. will do soon.

### OT

It would be nice if this libc screw-up were some form of UTF-8 concern.  But alas:

Sometimes people (allegedly) use their time on a standard committee to bring up certain technical points that, while irreverent on their face, allows the standard committee member to compete as to who is the most technical and to puff of their own ego (allegedly).

All too frequently, a simple matter that has, say,  +95% consensus gets derailed, not because someone finds a serious flaw in a proposal, but because they want to compete as to who in the room, is the most technical engineer.  Unless there are several people to are willing refute what an objector is saying, and are willing to engage in a sometimes long and protracted debate, the reasonable proposal is dropped.

There are many standards members who get their company, University, or organization to send them to standards conference meetings.  Standards members get their travel, lodging and meals paid for by their company, University, or organization.  To appear to be international, the standards conference schedules meetings around the world, often in very nice places.  The standards members work with their travel department to fly on their preferred airline in order to gain "points" and perks with that travel airline.  (And as such they object to traveling to some destination not served by their preferred airline or hotel: avoiding travel to unusual destinations).  So what pretending to "work" at a standards conference meeting (often week long), the get what amounts to a "free" vacation without having to use of vacation days.

While at the standards conference meetings, most people newly always bring their laptop or wireless device and "play".  They might chat on social media, play online games, work on their personal web site or blog, engage in social chat with other standards conference members (about things such as where to go for lunch or dinner).  If they have accumulated enough airline and hotel points, their partner / family might also attend getting a "free ride" as such points (so sometimes they might be gone for a day or two traveling with their family in the local area).  The prefer standards meetings that span Monday they Thursday, so that they can justify leaving the Friday before, enjoy the weekend traveling at the decimation, and leave the following weekend.

So what might seem like a meeting full of technical people working hard, it actually just the chair, the recording secretary, a speaker, and a fraction of people paying attention to what is going on.  Something is said that might catch the ear of someone (who is not paying full attention) and that someone finds an opportunity to justify the expense of their company, University, or organization sending them.  They stop their online play and rise to make a "technical point" .. often with the effect of derailing what is otherwise a reasonable standards proposal.  They resent if someone disagrees with them, preferring instead to be recorded in the minutes as having raised an objection.  Given that nearly everyone else at the meeting has their attention elsewhere, it is often a challenged to lay aside the objectors' comments.

BTW: Even though the chair and the recording secretary have to pay attention during a given meeting, being appointed Chair or secretary is a coveted position: one that helps the person "justify" the expense of sending them to the conference.

While COVID-19 put a damper on some of this "foolery", there were standards committees that still held in-person meetings at nice places: often at a discount because they travel industry was eager to get the business.

So with the above in mind, you can better appreciate what might have happened with a macro such as `isalpha(3)` was kept limited to ASCII characters.  Why it was not extended to even consider handling `[0x80-0xff]` octets with the high bit set (see the language about ASCII in the man page).  You can imagine someone trying to justify their "pad vacation" by objecting to requiring an implemented to cover any 'int' value.  And therefore you can understand the frustration as to why one cannot count on `isalpha(3)` working properly for any input value for which `isascii(3)` is false.

*SIGH*  :(

**Comment by xexyl** [comment]
> > > > Interesting little bit of information to know. I guess it makes sense but would you maybe elaborate why that is when you have a chance?
> > > 
> > > 
> > > One common implementation for such macros is to index into a table of 128 bytes of 0's and 1's for most of the `isfoo()` calls. The `isascii()` macro is a simple bounds (`<128`) check on the unsigned cast of the argument. Thus, `isalpha(128)` behavior is undefined. as is `isalpha(255)` and beyond. That is why it is important to pre-test with `isascii()`.
> > 
> > 
> > Interesting! So a lot of code is potentially UB. And we all know what that means .. it can HCF. :)
> > I have some fun comments to commit .. will do soon.
> 
> ### OT
> It would be nice if this libc screw-up were some form of UTF-8 concern. But alas:
> 
> Sometimes people (allegedly) use their time on a standard committee to bring up certain technical points that, while irreverent on their face, allows the standard committee member to compete as to who is the most technical and to puff of their own ego (allegedly).

Sounds more likely the actual truth than allegedly. But I wouldn't know. My guess was always different but it's an interesting thought - that by being on the committee you can say how important you are though indirectly saying how conceited you are (as well as how unimportant you are elsewhere).

> 
> All too frequently, a simple matter that has, say, +95% consensus gets derailed, not because someone finds a serious flaw in a proposal, but because they want to compete as to who in the room, is the most technical engineer. Unless there are several people to are willing refute what an objector is saying, and are willing to engage in a sometimes long and protracted debate, the reasonable proposal is dropped.

I think this also goes for things outside of voting for standards. Probably in most company meetings too when a decision has to be made.
> 
> There are many standards members who get their company, University, or organization to send them to standards conference meetings. Standards members get their travel, lodging and meals paid for by their company, University, or organization. To appear to be international, the standards conference schedules meetings around the world, often in very nice places. The standards members work with their travel department to fly on their preferred airline in order to gain "points" and perks with that travel airline. (And as such they object to traveling to some destination not served by their preferred airline or hotel: avoiding travel to unusual destinations). So what pretending to "work" at a standards conference meeting (often week long), the get what amounts to a "free" vacation without having to use of vacation days.

Of course.

> 
> While at the standards conference meetings, most people newly always bring their laptop or wireless device and "play". They might chat on social media, play online games, work on their personal web site or blog, engage in social chat with other standards conference members (about things such as where to go for lunch or dinner). If they have accumulated enough airline and hotel points, their partner / family might also attend getting a "free ride" as such points (so sometimes they might be gone for a day or two traveling with their family in the local area). The prefer standards meetings that span Monday they Thursday, so that they can justify leaving the Friday before, enjoy the weekend traveling at the decimation, and leave the following weekend.
> 

Brilliant selection of days.

> So what might seem like a meeting full of technical people working hard, it actually just the chair, the recording secretary, a speaker, and a fraction of people paying attention to what is going on. Something is said that might catch the ear of someone (who is not paying full attention) and that someone finds an opportunity to justify the expense of their company, University, or organization sending them. They stop their online play and rise to make a "technical point" .. often with the effect of derailing what is otherwise a reasonable standards proposal. They resent if someone disagrees with them, preferring instead to be recorded in the minutes as having raised an objection. Given that nearly everyone else at the meeting has their attention elsewhere, it is often a challenged to lay aside the objectors' comments.

Shame.

> 
> BTW: Even though the chair and the recording secretary have to pay attention during a given meeting, being appointed Chair or secretary is a coveted position: one that helps the person "justify" the expense of sending them to the conference.

I imagine it gives them other things too like ego (as above) and other things besides that.

> 
> While COVID-19 put a damper on some of this "foolery", there were standards committees that still held in-person meetings at nice places: often at a discount because they travel industry was eager to get the business.

Of course. Nothing will stop some people whether it's good or bad.

> 
> So with the above in mind, you can better appreciate what might have happened with a macro such as `isalpha(3)` was kept limited to ASCII characters. Why it was not extended to even consider handling `[0x80-0xff]` octets with the high bit set (see the language about ASCII in the man page). You can imagine someone trying to justify their "pad vacation" by objecting to requiring an implemented to cover any 'int' value. And therefore you can understand the frustration as to why one cannot count on `isalpha(3)` working properly for any input value for which `isascii(3)` is false.

I imagine that includes compiler writers that would object to that.

> 
> _SIGH_ :(
> 
> ### UPDATE 0:
> With the above, you might understand some of the moticvation for some of the judge's remarks in `rule_count.c`.

Of course. I love the comments in there. The one about it being renamed to CNC 'C's Not C' is great. That entire comment in fact. It's wonderfully done!

Hope you're having a good holiday! I also hope you got to see the changes (as in decoded plus the comments and new error message(s)) in the pull request you merged a short bit ago.

**Pull request merged**
