### PR TITLE
JSON (including parser/lexer) updates

### PR DESCRIPTION
**Pull request by xexyl**
With commit 7fb36f7f:

```git
    Be more honest in sorry.tm.ca.h
    
    The code generated by flex and bison doesn't just seem ugly and offensive;
    it IS ugly and offensive so I've made this more clear (for those who
    need to be reminded and/or convinced of it! :)) by changing the wording
    to be more blunt and honest.
```

The file now looks like:

```c
/*
 * A programmer's apology
 *
 * Sorry (tm Canada :-)) for the appalling condition of the code below.
 *
 * The people who worked on this repo did NOT write that code.
 * Instead, that code was generated by the bison or flex code generator.
 *
 * We do NOT recommend that you modify this code even though it's incredibly
 * offensive and ugly but instead work on the bison *.y and flex *.l source
 * files. See the Makefile for more information on how this file was generated.
 *
 * Thanks in advance for your understanding, and sorry (tm Canada :-)).
 */
```

I should have pointed out why I made this change in the git log but I neglected to do so so I'll say it here: as **I** (@xexyl) am the one working on the parser and lexer *I want to be **very very clear just how much I object** to the generated code*: I have always found code generated by flex/bison beyond hideous and **it's INCREDIBLY insulting to be associated with it in ANY (!!) form**. IOCCC winning entries are far more beautiful (and I do not just say this as a past winner) and this says a lot.

As for commit f642edc04a4:

```git
    Minor updates to lexer and parser
    
    In the parser I've removed some unused tokens, specifically:
    JSON_LETTER, JSON_SIGN, JSON_DIGIT, JSON_DIGITS and JSON_EXPONENT.
    
    In both the parser and lexer I've changed some comments. In some places
    I've removed some text (that seems no longer needed) and in other places
    I've added some clarifications (which seem useful).
    
    make prep to update and verify that everything works.

```

Finally as for commit 3615593578 I removed a magic number and made naming of JSON code constants/macros more consistently named:

```git
    Ignore JSON code set updates
    
    Added JSON_CODE_INVALID which is defined as:
    
        #define JSON_CODE_INVALID (JSON_CODE_RESERVED_MIN - 1)
    
    which is used in place of -1 when initialising the code set. Currently
    this is -1 because JSON_CODE_RESERVED_MIN is 0 but if for some strange
    reason that value changes this will make it so the invalid value is
    correct (the reserved min - 1). Also this removes the magic number -1
    which by itself is a worthy change.
    
    IGNORE_JSON_CODE_CHUNK -> JSON_CODE_IGNORE_CHUNK. The rationale here is
    that all the other json code constants are prefixed with JSON_CODE_ so
    that it's easier to find. MIN_JSON_CODE reads more naturally than
    JSON_CODE_MIN but this makes the name scheme consistent: all constants
    start with JSON_CODE so that there can be no doubt that it's specific to
    JSON codes.
```

### CODE REVIEW

**Comment by xexyl** [comment]
Related to `make prep`:

It seems (and now that I think on it it makes perfect sense) that GitHub does not allow for server side git hooks so what can we do about trying to get git hooks (specifically pre-commit) to be used? I had a couple thoughts on this but I am not sure about one detail.

The thought was providing a git hook script for developers participating here to install (showing them how) so that they are encouraged to use it prior to commit. The detail I'm not sure about though is if we want them to run `make prep` what will happen if they don't have sufficient `flex` or `bison` versions? Also do we want people who are not working on the lexer/parser to run that rule? I would think not as this could cause some conflicts for me.

So let's break this down into two issues:

First of all can we come up with a hook that encourages developers to use prior to committing? If so what should the script do?

Second (and perhaps more important) can we have a separate rule that does not generate the lexer/parser code (i.e. run `flex` and `bison`) for other people so only I am generating it via `make`? I think that during the development this is something to consider. On the other hand it wouldn't stop them from running `make prep` so if they do have a genuine change they could still do it.

What are your thoughts on these two points?

As for the rest of the day: I think this is probably all I'll end up doing. I'm going to have a lie down after posting this comment and then if I don't get back to anything within a couple hours I won't be doing anything else today. Hopefully I can do more tomorrow though. If not I'm sure I can do more Thursday.

Hope you're having a nice sleep!

**Comment by lcn2** [comment]
> First of all can we come up with a hook that encourages developers to use prior to committing? If so what should the script do?

There may be a place for [GitHub actions](https://docs.github.com/en/actions), although probably not a high priority in this repo at this time. The result of `make prep` run as a background check on a variety of internal GitHub platforms might be useful. 

> BTW: Where such hooks and actions are more needed is in the repo from which the www.ioccc.org web site is built and maintained. That repo will have a wider set of mods and pull requests made to it over time. 

We see this repo converging to a stable release, with possible tweets after lessons learned from **IOCCCMOCK**.  

The JSON parser it likely to be the of the final major missing code chuck still to be added.

After the JSON parser, the most likely need for changes will be:

- Addition more test cases
- Bug fixing test code 🙂 
- Man page and doc improvements 
- Compatibility changes, such as compile warnings, for obscure platforms
- Bug fixes due to previous compatibility changes 😄 
- Improvements to text printed by mkiocccentry
- Bug fixes due to text printing improvements 😁 
- A few more bug fixes 🤪
- Changes needed for the 1st formal release 
- Improvements due to lessons learned from IOCCCMOCK 😱

So yes, running `make prep` as a GitHub background action on a variety of GitHub servers might be something to do as the code base converges. 

#On the larger IOCCC plan:

Outside of this repo: We are mindful that the code for the submit server has not been touched since an Swiss engineer made an initial release. And that we need

- notifications of a submission compressed tarball upload 
- Ability to update submit server to inform contestants of the status or error in their entry
- Password change for submit users
- Code for judges to download and inspect submitted compressed tarballs

There is also the prep for refactoring of the www.ioccc.org web site:

- Finish the process of rebuilding ALL Makefiles for all previous winning entries
- Move files to consistent places on the web site
- Eliminate duplication of remarks about a winning entry 

We need to focus on the above before we can have outside people when with the web site. That is why we hope to refocus, once the `struct string` stuff is done, we can focus mostly on the set of points immediately above.  

Once at work is done and we can again process pull requests, the BIG thing will be to:

- Fix broken web page links
- Improve / fix Makefiles for winning entries
- Fix typos 

We believe that your ability to fix compile issues and spot typos, @xexyl, will be extremely valuable that that the the above item set. 

While typos and Makefiles are being addressed with pull requests, we plan to employ a web designer to improve the web page to help with the web page style.

Then hold the IOCCCMOCK, learn from it and then hold IOCCC28.

**Comment by lcn2** [comment]
> Second (and perhaps more important) can we have a separate rule that does not generate the lexer/parser code (i.e. run flex and bison) for other people so only I am generating it via make? I think that during the development this is something to consider. On the other hand it wouldn't stop them from running make prep so if they do have a genuine change they could still do it.

For someone with a proper bison/flex, there shouldn't be any harm in their running make.  If for some reason they get into a bind (say because `bfok.sh` makes a mistake), they can always use `make use_ref` or restore the reference C code from GitHub.

We can improve the `make parser` rule to no update the reference code until after both `bison` and `flex` run successfully.

> BTW: this would also be useful simply for people who don't have the right versions, maybe?

That is the job of `bfok.sh`: to determine if and where there is a `bison` and `flex` whose version is >= the minimum required version.  For systems that lack a proper `bison` and `flex`, `bfok.sh` will cause the Makefile to use the reference C code.

**Comment by xexyl** [comment]
> > First of all can we come up with a hook that encourages developers to use prior to committing? If so what should the script do?
> 
> There may be a place for [GitHub actions](https://docs.github.com/en/actions), although probably not a high priority in this repo at this time. The result of `make prep` run as a background check on a variety of internal GitHub platforms might be useful.

Sounds good.

> 
> > BTW: Where such hooks and actions are more needed is in the repo from which the [www.ioccc.org](http://www.ioccc.org) web site is built and maintained. That repo will have a wider set of mods and pull requests made to it over time.

Sounds good here too.
> 
> We see this repo is now converging towards a stable release. The JSON parser it likely to be the of the final major missing code chuck still to be added.

Apologies about the delays! I do hope tomorrow I can do more than just the basic types of things I did today (even if that means just reading) but often I need a few days to recover after being awake early (and/or awake late) for some days. I will keep this in mind although I kind of already thought this was the case anyway.

> 
> After the JSON parser, the most likely need for changes will be:
> 
> * Additional test cases

Including more test files for the JSON parser!

> * Bug fixing test code and test cases 🙂

Of course.

>   NOTE: Our experience is that test code and cases tend to be
>   a bit more buggy than the code they are testing 🤓

This is funny but I believe it well!

> * Man page and doc improvements

I'm happy to continue what I've done with this. I've kind of been focusing on other things so I've not made man pages for all the tools and probably all can be updated. I think `txzchk.1` is in a really good state though.

> * Improvements to text printed by mkiocccentry

In what way do you mean?

> * A few more bug fixes 😁
> * Changes needed for the 1st formal release
>   NOTE: See [Enhancement: Prepare for a formal release #87](https://github.com/ioccc-src/mkiocccentry/issues/87)

Yes which of course also means trying to find other systems to test it everything on as many systems as possible.

> * Improvements due to lessons learned from IOCCCMOCK 😱
> 

Of course.

> So yes, running `make prep` as a GitHub background action on a variety of GitHub servers might be something to do as the code base converges.

Looking forward to all of it!

> 
> # **On the larger IOCCC plan**:
> Outside of this repo: We are mindful that the code for the submit server has not been touched since an Swiss engineer made an initial release. And that we need:
> 
> * notifications of a submission compressed tarball upload
> * Ability to update submit server to inform contestants in issue with their entry
> * A process for submit users to change their Password
> * Code for judges to download and inspect submitted compressed tarballs
> 
> There is also the prep for refactoring of the [www.ioccc.org](http://www.ioccc.org) web site:
> 
> * Finish the process of rebuilding ALL Makefiles for all previous winning entries
> * Move files to consistent places on the web site
> * Eliminate duplication of remarks about a winning entry
> 
> We need to focus on the above before we can have outside people when with the web site. That is why we hope to refocus, once the `struct string` stuff is done, we can focus mostly on the set of points immediately above.

Thanks for these details.

> 
> Once at work is done and we can again process pull requests, the BIG thing will be to:
> 
> * Fix broken web page links
> * Improve / fix Makefiles for winning entries
> * Fix typos
> 
> We believe that your ability to fix compile issues and spot typos, @xexyl, will be **extremely valuable** in helpline with that previous item set above.
> 

Funny you should say this because today I looked at an entry of old and I saw some typos... I like to not modify other people's entries of course as there might even be some intended reason behind it (even if usually that's not the case when it comes to typos) but I can point them out if nothing else.

The others I can see myself helping with as well yes. Perhaps not so much with broken leg page links but I suppose that could actually be automated somehow.


> While typos and Makefiles are being addressed with pull requests, we plan to employ a web designer to improve the web page to help with the web page style.
> 

Sounds good.

> Then hold the IOCCCMOCK, learn from it and then hold IOCCC28.

Looking forward to that perhaps more than anything else - in some ways at least.

**Comment by xexyl** [comment]
Okay I'll be online for a bit but I'm done for the day here. If you reply to anything I might reply also but otherwise probably more from me tomorrow.

Good day!

**Comment by xexyl** [comment]
> We believe that your ability to fix compile issues and spot typos, @xexyl, will be **extremely valuable** in helpline with that previous item set above.

As for this I wanted to say thank you for the wonderful compliment and request. I was trying to get back to something at the time I was replying but now I have a bit of time before I go to sleep. 

I absolutely will help you here. Unless of course the Vogons turn out to be real or something happens to me. But I am pretty sure we’re safe from the Vogons and I don’t expect anything to happen to me so this should be possible. 

Anyway thank you very much!

I hope you have a great sleep. I will be sleeping soon probably as I am really exhausted. I hope that tomorrow I can sleep in a bit but if nothing else it will be the first day since Friday that I didn’t have something specific that I had to deal with. 

Good night!

**Comment by lcn2** [comment]
>> After the JSON parser, the most likely need for changes will be:
>> ..
>> Additional test cases
>> ..
> Including more test files for the JSON parser!

Exactly!

**Comment by lcn2** [comment]
>> Improvements to text printed by mkiocccentry
>>
> In what way do you mean?

When we make the first "_formal_" release of this `mkiocccenrtry` repo: when #87 is done, the hacker community / people interested in IOCCC from a C coder's perspective will be invited to try the `mkiocccenrtry` command and will be encouraged to provide feedback via GitHub issues, questions and even pull requests.  This will happen well before the submit server is ready / well before **IOCCCMOCK**.

There may be suggested changes to the text that `mkiocccenrtry` during its run as a result of this feedback.  That is likely to be a primary source of _Improvements to text printed by mkiocccentry_ .. if that happens at all.

Of course, someone providing feedback doesn't mean we do what they say.  Such feedback won't have the larger context of the new IOCCC process, and so any feedback needs to be politely evaluated and responded to, including a olive "sorry (tm Canada :))" but firm **NO** to feedback that isn't going to be accepted.

**Comment by xexyl** [comment]
> > > After the JSON parser, the most likely need for changes will be:
> > > ..
> > > Additional test cases
> > > ..
> > > Including more test files for the JSON parser!
> 
> Exactly!

Which reminds me of two things. First of all do you want me to explain how to test `txzchk`? I added a feature so I could test different formats without having to have an actual tarball. This was very useful to test linux versus macOS but it could be used to make test tarballs as well with all sorts of crazy inputs that maybe wouldn't normally be possible with tar. If you like I could show you how to do this either in a new issue or some where else. What are your thoughts here?

The second one has to do with the parser tree struct/union but I'll worry about that in the other thread maybe after you've finished struct string. As for me today I'm hoping I can do some things but right now I have to wake up properly. I did sleep in till 4:30 which is great but for some reason I'm having a harder time waking up today.

**Comment by xexyl** [comment]
> > > Improvements to text printed by mkiocccentry
> > 
> > 
> > In what way do you mean?
> 
> When we make the first "_formal_" release of this `mkiocccenrtry` repo: when #87 is done, the hacker community / people interested in IOCCC from a C coder's perspective will be invited to try the `mkiocccenrtry` command and will be encouraged to provide feedback via GitHub issues, questions and even pull requests. This will happen well before the submit server is ready / well before **IOCCCMOCK**.
> 
> There may be suggested changes to the text that `mkiocccenrtry` during its run as a result of this feedback. That is likely to be a primary source of _Improvements to text printed by mkiocccentry_ .. if that happens at all.

That makes sense and I think it's a great idea too!

> 
> Of course, someone providing feedback doesn't mean we do what they say. Such feedback won't have the larger context of the new IOCCC process, and so any feedback needs to be politely evaluated and responded to, including a olive "sorry (tm Canada :))" but firm **NO** to feedback that isn't going to be accepted.

Of course. This does indeed happen some of the time.

Hope you're having a nice sleep my friend!

**Pull request merged**
