### PR TITLE
Make it easier to update existing entries

### PR DESCRIPTION
**Pull request by xexyl**
Add -o <output> option that writes the answers to the specified file (if
it does not already exist; it is not overwritten). Then one can do e.g.
`cat answers.txt | ./mkiocccentry ...' so that you don't have to
repeatedly type the same information like id, name, abstract etc.

There is probably room for clean-up here maybe particularly the calls to
warn/fpara/para and possibly modularising the writing to the output file
but this was done quickly for the idea (I make a lot of updates during
the contest so having this feature would be highly useful).

### CODE REVIEW

**Comment by ilyakurdyukov** [comment]
There is a tool named `tee` that will do the same for you: 

`$ tee answers.txt | ./mkiocccentry <args to mkiocccentry>`

Your input for mkioccccentry will be written to the "answers.txt" file.

**Comment by xexyl** [comment]
> There is a tool named `tee` that will do the same for you:
> 
> `$ tee answers.txt | ./mkiocccentry <args to mkiocccentry>`
> 
> Your input for mkioccccentry will be written to the "answers.txt" file.

Yes I have used the tool before but I tend to forget about it. I used to use it a lot! This would be a better way to go about it maybe - except that having it built-in would possibly simplify some (not all) workflows (like mine).

**Comment by xexyl** [comment]
Good thing is it gave me something to do. It's the first time I've written any code in quite a long time. I'm done for the day and probably quite a few days. If nothing else it was a good for that reason that I forgot about tee(1).

**Comment by lcn2** [comment]
Looks useful @xexyl Thanks.

**Comment by xexyl** [comment]
> Looks useful @xexyl Thanks.

Thank you for accepting it! I appreciate it.

**Comment by lcn2** [comment]
I think we will use [-a answers] instead because we might implement plans for a -o flag in the future.

It is a small exit, so expect a push to the top of the master branch soon for your consideration.

Thanks again, @xexyl for the idea.

**Comment by lcn2** [comment]
We will also make a change to use warnp() for warnings where errno may be useful.

I know we have not born consistent on our use @xexyl , so we will take the opportunity
you created for also address some of that.

**Comment by xexyl** [comment]
> I think we will use [-a answers] instead because we might implement plans for a -o flag in the future.
> 

That's fine by me. I'll be curious to find out what -o might mean!

> It is a small exit, so expect a push to the top of the master branch soon for your consideration.
> 
> Thanks again, @xexyl for the idea.

Thank you for the appreciation and accepting it.

**Comment by xexyl** [comment]
> We will also make a change to use warnp() for warnings where errno may be useful.
> 
I like that idea. It was quickly implemented and I knew there could be some better ways to go about some of it including printing/errors/warnings.

> I know we have not born consistent on our use @xexyl , so we will take the opportunity you created for also address some of that.

Not sure I follow that but I'm sure you'll work it out fine; I have complete faith in it!

Stay safe,
Cody

**Comment by lcn2** [comment]
See 0d8b7bd6e77e6794a5e1f27b60f4aaf371ebe0ce @xexyl 

Thanks for the good idea.  When it passes other people testing, we will form a new version number and make the alpha test release "official".

**Comment by xexyl** [comment]
Thanks! I tested both more than one author and single author as well as omitting some of the answers some of the time and not others.

I'm more than happy if you or someone else has ideas to make it even better; I had another thought for this but this seemed like the better way to go about making it easier to update entries of the ideas I had.

**Comment by xexyl** [comment]
Oh I see that you have added me in comments with my handle (which I really appreciate). Would you mind changing the real name to 'Cody Boone Ferguson' please? Nothing urgent but I thought doing git config user.name would do that but it didn't seem to work (before this the only other git stuff I did was on private git servers so I'm inexperienced on GitHub).

Thank you.

**Pull request merged**
