### PR TITLE
Attempt to restrict CodeQL paths - #917

### PR DESCRIPTION
**Pull request by xexyl**
This is based on discussion started by @SirWumpus. Since he thinks this might be all we need this is a test on the process. If there is a problem, syntax error or something else, it can then be revised.

### CODE REVIEW

**Comment by xexyl** [comment]
Let's see if this works okay .. if not I'll see about updating it though maybe will require discussion. I do have to go afk soon however.

**Comment by xexyl** [comment]
All good! Thanks @SirWumpus! I'll copy over to the jparse repo even though it's a placeholder at this point.

**Comment by xexyl** [comment]
Checking in jparse now ..

**Comment by SirWumpus** [comment]
BTW the scan results will appear under the `Security` > `Code Scanning` section (not under `Actions` doh).

**Comment by xexyl** [comment]
> BTW the scan results will appear under the `Security` > `Code Scanning` section (not under `Actions` doh).

Thanks. Oddly even though the file is there I only see the test.yml running. Any idea why that might be? Well I'll check that section too as maybe the test.yml is where I looked and the CodeQL is in the section you mention?

**Comment by xexyl** [comment]
Over there CodeQL is only run on a schedule. Any idea what needs to change so it's on commit ?

**Comment by xexyl** [comment]
Oh! It's because the files were not modified maybe?

**Comment by xexyl** [comment]
Trying that now .. updated Makefile.

**Comment by xexyl** [comment]
I don't see anything .. hmm.

**Comment by xexyl** [comment]
Ah! I see it under Actions. It's running now. So that's good.

**Comment by xexyl** [comment]
It worked! Thanks again!

**Comment by SirWumpus** [comment]
You should be able to manually start a workflow (if you have write access) after fixing any restriction problems.  You should see both runs in Actions (All Workflows); Security results talk a couple of minutes to do and appear later.

**Comment by xexyl** [comment]
> You should be able to manually start a workflow (if you have write access) after fixing any restriction problems. You should see both runs in Actions (All Workflows); Security results talk a couple of minutes to do and appear later.

I do indeed have access but I had to look at Actions to find it. All good it seems. It's not as detailed as here but that's because there's no code except a single C file with a simple `main()` and the test (and similar) Makefile rules don't do anything yet.

**Comment by xexyl** [comment]
Will likely be afk soon. When back I'll probably look at the other repo.

**Review by lcn2 — APPROVED** [review]
Thanks @SirWumpus and @xexyl, lets check this in and see what happens

**Comment by xexyl** [comment]
> Thanks @SirWumpus and @xexyl, lets check this in and see what happens

Well it seemed to pass so that's encouraging at least. Hopefully it's not a mistake that will end up with problems another time down the road due to some unforeseen reason. Anyway you're welcome on my behalf as well.

**Pull request merged**
