### PR TITLE
txzchk updates + new chkentry test functions

### PR DESCRIPTION
**Pull request by xexyl**
In other words a line like:

    -rw-r--r--  0 501    20          0 Jul 28 08:25 test-0/file bogus data

will report (for this line specifically):

    Warning: txzchk: test_txzchk/entry.test-0.1658587455.txt: bogus field found after filename: bogus
    Warning: txzchk: test_txzchk/entry.test-0.1658587455.txt: bogus field found after filename: data

Previously it would have only detected 'bogus'.

A question that was brought up is whether or not the line should count
as a filename of 'file bogus data' or if considering 'bogus' and 'data'
as bogus fields is enough. On the one hand the most likely case is it
would be a filename with spaces (unless of course the tarball was
created by mkiocccentry); but on the other hand it might also be someone
messing with the tarball and since strtok_r() is used (with " \t") it
would require more code to detect and display the full filename and
since it's also bogus this works (for now if not indefinitely).

### CODE REVIEW

**Comment by xexyl** [comment]
I will be going afk a bit ... depending on how I feel I might do add some more tests today.

**Comment by xexyl** [comment]
I am on the fence of whether I want to work on adding more test functions. I think I could help with the booleans for the `.info.json` checks but right now I have other things on my mind as well so I'm going to take another break. Commit https://github.com/ioccc-src/mkiocccentry/pull/289/commits/4af9a9a72a3c62f16f2d50211d13673929d50969 might very possibly be the final commit of the day but I do feel good at what I got done.

I'm sure I can do more tomorrow as well. Good day either way!

**Comment by xexyl** [comment]
> I am on the fence of whether I want to work on adding more test functions. I think I could help with the booleans for the `.info.json` checks but right now I have other things on my mind as well so I'm going to take another break. Commit [4af9a9a](https://github.com/ioccc-src/mkiocccentry/commit/4af9a9a72a3c62f16f2d50211d13673929d50969) might very possibly be the final commit of the day but I do feel good at what I got done.
> 
> I'm sure I can do more tomorrow as well. Good day either way!

I could also help with the `.author.json` tests though I think there are fewer that I can do (at least with the current knowledge of what you have in mind).

I will later on today or if not then hopefully tomorrow look at more of the tests I added in the old chkinfo tool. I can think of (off the top of my head) several additional checks that can be done right away - unless by chance those have already been added and I missed them. Actually some of them might be for both `.info.json` and `.author.json` (I seem to think that though there are still some in the individual files of course).

But for now I'm doing something else.

**Comment by xexyl** [comment]
I believe that commit https://github.com/ioccc-src/mkiocccentry/pull/289/commits/2558c5af165b1a3cd4d90104cd97ef6ac5541647 will be incredibly helpful. I was going to make do the other half (based on the function chk_Makefile_override() which is also just a boolean) but I am starting to feel I need to stop as I'm having a hard time focusing. Going to take it easy now.

I can work on more test functions later on - if not today then hopefully tomorrow. Looking at the clock and how early I go to bed and what else I have on my mind I suspect it won't be until tomorrow at the earliest. But I think that this pull request will be very helpful.

Good day!

**Comment by xexyl** [comment]
Oh I should point something out. The bool test functions that were added - these were for `.info.json`. I haven't done anything for the `.author.json` file today (maybe not at all - not sure but I need to go do something else).

**Comment by xexyl** [comment]
Oh one more thing and then I really am going. I moved the functions in the order of the bools in the struct (at least in the source file .. now I think on it I'm not sure if I fixed this for the header file).

There was another change in txzchk I neglected to mention in a git log but it wasn't really anything to mention. I would mention it anyway but it escapes my mind atm (as it is I'm not even sure if it was txzchk or another thing) - that's why it's only one more thing to mention even if technically I mentioned two.

**Comment by lcn2** [comment]
Sorry @xexyl there are too many conflicts.  See the recent comments such as commit b078729fdd0df5b651c0b352cdd8563c9d965fcd for changes to json_dbg() calls in entry_util.c.

**Comment by xexyl** [comment]
> Sorry @xexyl there are too many conflicts. See some of the recent commits such as commit [b078729](https://github.com/ioccc-src/mkiocccentry/commit/b078729fdd0df5b651c0b352cdd8563c9d965fcd) for changes to json_dbg() calls in entry_util.c.

Okay that's really strange. Did you make commits that I did not get? Looks like maybe you did.

I'll see if I can resolve them.

**Comment by xexyl** [comment]
Hmm yes the calls are indeed a problem. Is it possible for you to merge the txzchk related ones at least?

**Comment by xexyl** [comment]
If you can merge the txzchk related commits that would be good. Looking at the clock I will have to deal with the other stuff tomorrow. I'm hoping using `vimdiff` will help sort this out. I have it set up for this but I'm not sure how doable it will be. Unfortunate timing with commits but it is what it is.

**Comment by xexyl** [comment]
Closing this in favour of a new pull request. It occurred to me it should be easy to fix. There might be a few things missing but besides some typos the only things I changed in the conflicting files involved adding new test bool functions (which don't even have a test). The typos and other things can be dealt with later.

This way the txzchk changes are added and the new test functions are added too. See https://github.com/ioccc-src/mkiocccentry/pull/290.

**Pull request closed without merging**
