### PR TITLE
Bug fix warn_on_err + typo fixes

### PR DESCRIPTION
**Pull request by xexyl**
That's all I'll be doing for the day. Off to do something else.

### CODE REVIEW

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl

Sure. 

I have had some thoughts on the dbg documentation that I think I will work on next. Not sure if I will be able to do it today but:

I think it would be really helpful to have hyperlinks and a table of contents as there’s a lot of text to go through. 

I will also try and figure out if I can shorten the text as well. I have some thoughts but I have to be looking at it in order to really be sure. 

I am very tired today (more than usual) so I really have no idea if I will be able to get anything done. I have a few changes that fix some sentences but so far that’s it. 

I have given more thought to it than actually working on it. I could have put this there in that thread but I was typing my reply here and since it is relevant I decided to not bother opening the other page (typing this on my phone). 

Well we shall see.

**Comment by lcn2** [comment]
> > Thank you @xexyl
> 
> Sure.
> 
> I have had some thoughts on the dbg documentation that I think I will work on next. Not sure if I will be able to do it today but:
> 
> I think it would be really helpful to have hyperlinks and a table of contents as there’s a lot of text to go through.
> 
> I will also try and figure out if I can shorten the text as well. I have some thoughts but I have to be looking at it in order to really be sure.
> 
> I am very tired today (more than usual) so I really have no idea if I will be able to get anything done. I have a few changes that fix some sentences but so far that’s it.
> 
> I have given more thought to it than actually working on it. I could have put this there in that thread but I was typing my reply here and since it is relevant I decided to not bother opening the other page (typing this on my phone).
> 
> Well we shall see.

Excellent ideas.

**Comment by xexyl** [comment]
> > > Thank you @xexyl
> > 
> > 
> > Sure.
> > I have had some thoughts on the dbg documentation that I think I will work on next. Not sure if I will be able to do it today but:
> > I think it would be really helpful to have hyperlinks and a table of contents as there’s a lot of text to go through.
> > I will also try and figure out if I can shorten the text as well. I have some thoughts but I have to be looking at it in order to really be sure.
> > I am very tired today (more than usual) so I really have no idea if I will be able to get anything done. I have a few changes that fix some sentences but so far that’s it.
> > I have given more thought to it than actually working on it. I could have put this there in that thread but I was typing my reply here and since it is relevant I decided to not bother opening the other page (typing this on my phone).
> > Well we shall see.
> 
> Excellent ideas.

On that note what is your preference on back-links? So for example if someone clicks on a link that takes them to the debug functions they could then click on the title and it would take them back to the table of contents. I know some people don't like them and some people think they're not really used (actually Simon told me that) but I like them and do use them. If you want it one way or the other though I'll take care of it.

**Comment by lcn2** [comment]
> On that note what is your preference on back-links? So

Back links may not be so important if the table of contents is at the very top and easy to find / scroll up to find.

**Comment by xexyl** [comment]
> > On that note what is your preference on back-links? So
> 
> Back links may not be so important if the table of contents is at the very top and easy to find / scroll up to find.

Okay. Well we'll see I guess. Good day!

**Pull request merged**
