### PR TITLE
Fixes to and an additional entry to FAQ

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
The new entry is about Makefiles .. but needs to be finished when the other repo can have a named anchor to the FAQ entry about what to put in the Makefile (that should also be updated I guess .. haven't read it but I presume it's not been updated for the mkiocccentry repo). As such there's an XXX comments in the entry.

I also changed 'entry' to 'submission' in the FAQ. Haven't checked for other things. Going afk now and doubt very much I'll do anything else here today.

**Comment by xexyl** [comment]
> I also changed 'entry' to 'submission' in the FAQ. Haven't checked for other things. Going afk now and doubt very much I'll do anything else here today.

Particularly because I'm holding off pending your changes in both repos but also other things.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

You are most welcome. Off to do other things .. will see what tomorrow brings. Kind of depends on the other repo markdown files being edited and various other things too. In my free time today though I'll be reading.

**Pull request merged**
