### PR TITLE
Fix warning on some systems in foo.c

### PR DESCRIPTION
**Pull request by xexyl**
Without explaining the purpose of the original check I cannot explain
the fix so use your imagination and don't panic! :)

### CODE REVIEW

**Comment by lcn2** [comment]
🙂 @xexyl

**Comment by xexyl** [comment]
> 🙂 @xexyl

It works on my end but want to make sure: it works on the system you reported the problem, right?

And again have a good day and a great and SAFE holiday! BCNU! :)

**Comment by lcn2** [comment]
> > 🙂 @xexyl
> 
> It works on my end but want to make sure: it works on the system you reported the problem, right?
> 
> And again have a good day and a great and SAFE holiday! BCNU! :)

Yes it works and thanks.

**Comment by xexyl** [comment]
> > > 🙂 @xexyl
> > 
> > 
> > It works on my end but want to make sure: it works on the system you reported the problem, right?
> > And again have a good day and a great and SAFE holiday! BCNU! :)
> 
> Yes it works and thanks.

Thank you for confirming!

**Pull request merged**
