### PR TITLE
Various updates and fixes

### PR DESCRIPTION
**Pull request by xexyl**
I do have other commits to do but I'm not sure I'll be doing them today as I'm not feeling well. I'm not even sure at this point if I'll get to the comments in the other thread (the documentation one). Doing something else again.

Good day!

### CODE REVIEW

**Comment by xexyl** [comment]
Did a few more things but now I really think I'll be doing something else. Hopefully I can look at those other comments (documentation issue) later on but I don't know if that'll be today or not. The above commits were spontaneously done.

**Comment by xexyl** [comment]
Today I don't really feel that great either so I probably won't be doing much here. I hope that tomorrow I can feel a bit better and do more. Hope you're having a nice sleep my friend!

Going to try resting a bit soon again.

**Comment by xexyl** [comment]
I'm doing something else now. I do not plan on doing anything else today and I rather plan on not doing anything else today. 

More from me tomorrow I am sure. Good day!

**Comment by lcn2** [comment]
Fun update, @xexyl 

```
"Because sometimes people add feathers to tar." :-(
```

LOL.

TODO today: make good progress on the _JSON semantics code_ (... that has been brewing in our head and is ready for a code trial 🤓).

**Comment by xexyl** [comment]
> Fun update, @xexyl
> 
> ```
> "Because sometimes people add feathers to tar." :-(
> ```
> 
> LOL.
> 

I'm glad you got a laugh out of it too. It makes me laugh very much and yes out loud as well!

> TODO today: make good progress on the _JSON semantics code_ (... that has been brewing in our head and is ready for a code trial 🤓).

Good luck!

**Comment by lcn2** [comment]
> > Fun update, @xexyl
> 
> > 
> 
> > ```
> 
> > "Because sometimes people add feathers to tar." :-(
> 
> > ```
> 
> > 
> 
> > LOL.
> 
> 
> 
> Question for you Landon. In continuation of this fun with feathers do you object to this diff in `txzchk.c`:
> 
> 
> 
> ```diff
> 
> diff --git i/txzchk.c w/txzchk.c
> 
> index f564ded..7cf88d3 100644
> 
> --- i/txzchk.c
> 
> +++ w/txzchk.c
> 
> @@ -157,11 +157,11 @@ main(int argc, char **argv)
> 
>      if (!quiet) {
> 
>         para("", "Performing checks on tarball ...", NULL);
> 
>      }
> 
>      txz_info.total_issues = check_tarball(tar, fnamchk);
> 
>      if (!quiet && !txz_info.total_issues) {
> 
> -       para("All checks passed.", "", NULL);
> 
> +       para("No feathers found in tarball.", "", NULL);
> 
>      }
> 
> ```
> 
> 
> 
> I'm not sure if that's the best wording. Maybe it should also say something about all checks passing. I don't know. But this might be a fun way to play on the comment I added yesterday. What do you think? Will it cause any problems with the contest somehow? Is it going too far? 

That would be a fun mod 👍 @xexyl.

**Comment by xexyl** [comment]
> > > Fun update, @xexyl
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > "Because sometimes people add feathers to tar." :-(
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > LOL.
> > 
> > 
> > Question for you Landon. In continuation of this fun with feathers do you object to this diff in `txzchk.c`:
> > ```diff
> > diff --git i/txzchk.c w/txzchk.c
> > 
> > index f564ded..7cf88d3 100644
> > 
> > --- i/txzchk.c
> > 
> > +++ w/txzchk.c
> > 
> > @@ -157,11 +157,11 @@ main(int argc, char **argv)
> > 
> >      if (!quiet) {
> > 
> >         para("", "Performing checks on tarball ...", NULL);
> > 
> >      }
> > 
> >      txz_info.total_issues = check_tarball(tar, fnamchk);
> > 
> >      if (!quiet && !txz_info.total_issues) {
> > 
> > -       para("All checks passed.", "", NULL);
> > 
> > +       para("No feathers found in tarball.", "", NULL);
> > 
> >      }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm not sure if that's the best wording. Maybe it should also say something about all checks passing. I don't know. But this might be a fun way to play on the comment I added yesterday. What do you think? Will it cause any problems with the contest somehow? Is it going too far?
> 
> That would be a fun mod 👍 @xexyl.

Thank you. I will do that later on - possibly today. In the middle of something and I have a zoom meeting at the hour. It's possible I have to finish the current thing after that but once I'm done with that I'll do this.

Hope you have a great day!

**Pull request merged**
