### PR TITLE
Various fixes and enhancements

### PR DESCRIPTION
**Pull request by xexyl**
Please see the git log of the commits.

I don't expect to do anything else here today but I'm also not sure what else needs to be done aside from some man page issues that I should bring up.

### CODE REVIEW

**Comment by xexyl** [comment]
> Please see the git log of the commits.
> 
> I don't expect to do anything else here today but I'm also not sure what else needs to be done aside from some man page issues that I should bring up.

I just checked: one of the man page issues was resolved at some point recently. So only one remains that I'm aware of. I'll maybe open an issue or make a comment in the issue that was closed without that part being done.

**Comment by xexyl** [comment]
Commit dc13a18fdc5980385eccd17a38d6c00319f66965 is interesting. I can improve in the way I suggested but not now and probably not today. I really am doing something else now but at least there's the problem fixed.

**Comment by xexyl** [comment]
Leaving for the day .. can hopefully do more tomorrow.

**Comment by lcn2** [comment]
We are confused about https://github.com/ioccc-src/mkiocccentry/pull/470/commits/da067c0b7a8d6af269d0087a1cf5fa4296f21cfd

We will perform this pull request, however we wonder if that above mentioned commit is a mistake?

**Comment by xexyl** [comment]
> We are confused about [da067c0](https://github.com/ioccc-src/mkiocccentry/commit/da067c0b7a8d6af269d0087a1cf5fa4296f21cfd)
> 
> We will perform this pull request, however we wonder if that above mentioned commit is a mistake?

Don’t we want to exclude html files though?

if not then yes it is in error and I will be happy to rectify it tomorrow. Please let me know. 

I am getting ready to sleep now though. 

I hope you have a great night!

**Comment by lcn2** [comment]
> Don’t we want to exclude html files though?

We recommend against excluding html files, just in case one is created or is hanging around. :-)

FYI: This is a useful command:

```sh
git status --ignored
```

Anyway, with commit b3f517f589e4dbd747a74968bd48c6be4e840acd we have perform a cleanup and sort of the `.gitignore` file and resolved the question in [comment 1374989433](https://github.com/ioccc-src/mkiocccentry/pull/470#issuecomment-1374989433).

**Comment by xexyl** [comment]
> > Don’t we want to exclude html files though?
> 
> We recommend against excluding html files, just in case one is created or is hanging around. :-)
> 

That's fair enough.

> FYI: This is a useful command:
> 
> ```shell
> git status --ignored
> ```
> 


Indeed the `--ignored` option sounds useful. I just tried it and it seems very useful. Thanks for the tip!


> to show what files are being ignored because of `.gitignore`.
> 

Plus those in `.git/info/exclude` :-) 


> To list file files under the current directory that are already committed files being tracked by your git repo:
> 
> ```shell
> git ls-tree -r --name-only HEAD
> ```
> 

I knew of `ls-files` which is very useful too. Thanks for this. I just made it an alias: git tracking-cwd. Seems like a good name though if you have a better idea (maybe from an earlier RCS) I'm open to it.

Before I started using git I used mostly CVS. I briefly used svn. I do miss one thing about CVS though: I could pull (though as I recall it was just `checkout` or `co` which git has but different meaning) changes to specific files which sometimes was very useful.

> And the same already committed files being tracked by your git repo for the entire repo:
> 
> ```shell
> git ls-tree --full-tree -r --name-only HEAD
> ```
> 
Thanks! I made an alias for this too `git tracking`.

I also have two other aliases from you and I made a third one from one of those:

```gitconfig
        cdiff-nameonly = diff @~ @ --name-only
        cdiff = diff @~ @
        check = diff --name-only
```

though I don't remember the exact details of the cdiff and check ones - just that they were in an older RCS.

Here's something funny: the cdiff ones do not work under git in CentOS. I bet you didn't see that one :-)

> Anyway, with commit [b3f517f](https://github.com/ioccc-src/mkiocccentry/commit/b3f517f589e4dbd747a74968bd48c6be4e840acd) we have perform a cleanup and sort of the `.gitignore` file and resolved the question in [comment 1374989433](https://github.com/ioccc-src/mkiocccentry/pull/470#issuecomment-1374989433).

Thanks. I was going to do it with some clean up of that special file under soup/ but I'll do that with another commit instead.

**Comment by lcn2** [comment]
FYI, we added the following aliases to our `~/.gitconfig` file:

```
[alias]
...
        # git branch alias
        br = branch

        # git checkout alias
        co = checkout

        # git log with graph decorations on the side
        glog = log --graph --color --decorate

        # list files modified
        check = diff --name-only

        # diff involving most recent commit
        cdiff = diff @~ @

        # information on a commit
        cinfo = cat-file -p

        # list already committed files being tracked by your git repo
        ls = ls-tree -r --name-only HEAD
...
```

especially as `git ls` seems like an apt git alias.

**Comment by xexyl** [comment]
> FYI, we added the following aliases to our `~/.gitconfig` file:
> 
> ```
> [alias]
> ...
>         # git branch alias
>         br = branch
> 
>         # git checkout alias
>         co = checkout
> 
>         # git log with graph decorations on the side
>         glog = log --graph --color --decorate
> 
>         # list files modified
>         check = diff --name-only
> 
>         # diff involving most recent commit
>         cdiff = diff @~ @
> 
>         # information on a commit
>         cinfo = cat-file -p
> 
>         # list already committed files being tracked by your git repo
>         ls = ls-tree -r --name-only HEAD
> ...
> ```
> 
> especially as `git ls` seems like an apt git alias.

Good ones! The `co` makes me think of `CVS` - well and some others too I guess.

I'll play with the rest as well. Thanks.

**Comment by lcn2** [comment]
> Good ones! The co makes me think of CVS - well and some others too I guess.

Yes, that is why.  :-)

FYI:

```
        # list files modified
        check = diff --name-only
```

is from the SCCS and RCS days.  :-)

**Comment by xexyl** [comment]
> > Good ones! The co makes me think of CVS - well and some others too I guess.
> 
> Yes, that is why. :-)
> 

I figured.

> FYI:
> 
> ```
>         # list files modified
>         check = diff --name-only
> ```
> 
> is from the SCCS and RCS days. :-)

Yes you told me about that one.

Thank you.

**Comment by xexyl** [comment]
BTW some aliases I've added based on some you've told me. One I just noticed is one you suggested! Your `ls` one I had as `tracking-cwd` as it actually only shows those in the current file (though that makes sense since `ls` would also do that). If you want the full tree look at my `tracking` alias. Though maybe it could be `ls-r` or something like that too. I didn't use `br` as I have bash completion and funnily enough I just type `git br<tab>`. Anyway my full alias list including the ones you've given me:

```gitconfig
[alias]
    check = diff --name-only
    # diff involving most recent commit
    cdiff = diff @~ @
    # diff involving most recent commit but name only
    cdiff-nameonly = diff @~ @ --name-only
    # list already committed files tracked from the current directory
    tracking-cwd = ls-tree -r --name-only HEAD
    # list full tree of already committed files tracked
    tracking = ls-tree --full-tree -r --name-only HEAD
    # git branch alias
    # br = branch
    # git checkout alias
    co = checkout
    # git log with graph decorations on the side
    glog = log --graph --color --decorate
    # list files modified
    check = diff --name-only
    # information on a commit
    cinfo = cat-file -p
    # list already committed files being tracked by your git repo
    ls = ls-tree -r --name-only HEAD
```

Something else not related to git.

You've asked me at times for suggestions with vim. Would you find it of interest if you could see my `.vimrc`? Maybe I could clean it up and make it a repo here even .. maybe. But if nothing else I could clean it ups nd post it as a file in some thread (maybe the OT one). 

As for now: I'm hoping to work on the repo. I hope you're having a nice sleep my friend!

**Comment by lcn2** [comment]
> Would you find it of interest if you could see my .vimrc?

Yes, please.

**Comment by xexyl** [comment]
> > Would you find it of interest if you could see my .vimrc?
> 
> Yes, please.

Okay I'll set a reminder to do that at the beginning of February. Hopefully by that time we'll have made enough progress on this repo that I can spend some time on this. I have another thing I want to start doing on the first of February but that won't be an all day thing so I will set it for 1 February 2023. Of course if I feel up to this and not the repo I could do that too.

It might prove it doesn't need much cleaning up anyway. Thus I'll also set a reminder for sometime next week.

**Pull request merged**
