### PR TITLE
New version of txzchk - address much of #334 + typo fixes + man page updates (formatting + new file)

### PR DESCRIPTION
**Pull request by xexyl**
Happy Hobbit Day! In honour of both Bilbo Baggins and Frodo Baggins and their birthdays (which also happened to be a Thursday in the Third Age 3001 or T.A. 3001 or in the Shire Reckoning S.R. 1401 - where Bilbo turned 111 and Frodo turned 33 which was his coming of age and his inheritance) I have made some fixes and enhancements to txzchk (okay - it's not done in honour of the Bagginses but it's fun to think about and they should be honoured), addressing a number of points in #334.

The new version addresses comments
https://github.com/ioccc-src/mkiocccentry/issues/334#issuecomment-1242821987 and
https://github.com/ioccc-src/mkiocccentry/issues/334#issuecomment-1242823960 as well as later discussion. To be more more specific:

- rounded file size is no longer used.
- there is a limit on the number of files allowed in the tarball (currently 42 or MAX_FILE_COUNT).
- there is a limit on the size of all files summed (currently 27651*1024 or MAX_SUM_FILELEN).
- only regular files count against files and file sizes (so directories, sockets and anything else not a regular file will not count against file count or total size of all files).
- and possibly some other things I have forgotten.

As well I made the following changes:

- More debug information (show the size of required files for example).
- Increased the verbosity level of some debug messages (this is because of debug information added to util.c in sum_and_count() - the information in txzchk is not useful to have at medium debug level).
- Fixed the case where it would say 'files' even when it was a single file.
- A new 'static char const *tok_sep = " \t";' used instead of having " \t" strewn about the code (instead 'tok_sep' can be strewn about the code! :-) ).
- Each file in the files list has a size member (this was originally going to be used for something but it was not needed and I only see it now with git diff so not removing it: it might be removed in the future should it prove useless).
- Probably some other changes in txzchk.c as well.

I'm aware of the issue of part of sum_and_count() might better off use off_t but for now it uses intmax_t.

Fix string_to_intmax2() to check for non-digits after digits as per comment
https://github.com/ioccc-src/mkiocccentry/issues/334#issuecomment-1242821987 which shows the invalid line:

    -rw-r--r--  0 501    20        4.0 Jun  4 04:52 12345678-1234-4321-abcd-1234567890ab-2/extra2

which previously was valid because strtoimax() will not report an error there. Whether the other string_to_ functions need to be updated for this (including string_to_intmax()) I am uncertain but I wanted to get these changes in.

Temporarily comment out the test in sum_and_count() that has a calculation error with a 'FIXME' note on it. This is so the changes to txzchk could be tested successfully (as I noted yesterday I'm not sure the purpose of that specific check so I can't fix it without risking losing an important test that is necessary in the judging process).

Added three files to test_txzchk/bad and one to test_txzchk/good (all pass).

Updated test_JSON tree so that all cases of the previous txzchk version was changed to the new version.

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Happy to help. Today is shot I'm afraid but maybe I can do something earlier on - hard to say ... depends on how much I wake up and how I feel before I have to leave (still morning). After that I won't likely be able to do much of anything.

Hope you're having a nice sleep.

**Comment by xexyl** [comment]
> > Thanks @xexyl
> 
> Happy to help. Today is shot I'm afraid but maybe I can do something earlier on - hard to say ... depends on how much I wake up and how I feel before I have to leave (still morning). After that I won't likely be able to do much of anything.

With that said though I want to bring up the issue of:

```c
    /*
     * FIXME - this is buggy and so it's disabled for now so that the code which
     * needs this function will be able to work - FIXME
     */
    #if 0
    if (-sum != prev_sum-(~inv_value)) {
        dbg(DBG_HIGH, "sum: %jd", sum);
        dbg(DBG_HIGH, "prev_sum: %jd", prev_sum);
        dbg(DBG_HIGH, "inv_value: %jd", inv_value);
        dbg(DBG_HIGH, "prev_sum-(~inv_value): %jd", prev_sum-(~inv_value));
        warn(__func__, "third check on sum failed: -sum %jd != prev_sum-(~inv_value) %jd", -sum, prev_sum-(~inv_value));
        return false;
    }
    #endif
```

**Comment by xexyl** [comment]
> > > Thanks @xexyl
> > 
> > 
> > Happy to help. Today is shot I'm afraid but maybe I can do something earlier on - hard to say ... depends on how much I wake up and how I feel before I have to leave (still morning). After that I won't likely be able to do much of anything.
> 
> With that said though I want to bring up the issue of:
> 
> ```c
>     /*
>      * FIXME - this is buggy and so it's disabled for now so that the code which
>      * needs this function will be able to work - FIXME
>      */
>     #if 0
>     if (-sum != prev_sum-(~inv_value)) {
>         dbg(DBG_HIGH, "sum: %jd", sum);
>         dbg(DBG_HIGH, "prev_sum: %jd", prev_sum);
>         dbg(DBG_HIGH, "inv_value: %jd", inv_value);
>         dbg(DBG_HIGH, "prev_sum-(~inv_value): %jd", prev_sum-(~inv_value));
>         warn(__func__, "third check on sum failed: -sum %jd != prev_sum-(~inv_value) %jd", -sum, prev_sum-(~inv_value));
>         return false;
>     }
>     #endif
> ```

Also I'm not sure of what to do with mkiocccentry using the `sum_and_count()` - for now at least. Some of it maybe but not entirely - though I haven't looked at it yet either.

**Comment by lcn2** [comment]
Removed improper test in `sum_and_count()`, to fix it would have created a redundant test and so it was removed in commit 174d904a639f42d2d7fa106c5b7b273b2e3ce087

**Comment by xexyl** [comment]
> Removed improper test in `sum_and_count()`, to fix it would have created a redundant test and so it was removed in commit [174d904](https://github.com/ioccc-src/mkiocccentry/commit/174d904a639f42d2d7fa106c5b7b273b2e3ce087)

Thank you for confirming that. What was the purpose of that specific check anyway ? (Answer only if you have extra time and feel up to it.)

**Comment by lcn2** [comment]
> > Removed improper test in `sum_and_count()`, to fix it would have created a redundant test and so it was removed in commit [174d904](https://github.com/ioccc-src/mkiocccentry/commit/174d904a639f42d2d7fa106c5b7b273b2e3ce087)
> 
> Thank you for confirming that. What was the purpose of that specific check anyway ? (Answer only if you have extra time and feel up to it.)

It was an attempt to code hardware failure tests by looking at other code and refactoring it for C.
The attempt for the remover code was incorrect.

**Comment by xexyl** [comment]
> > > Removed improper test in `sum_and_count()`, to fix it would have created a redundant test and so it was removed in commit [174d904](https://github.com/ioccc-src/mkiocccentry/commit/174d904a639f42d2d7fa106c5b7b273b2e3ce087)
> > 
> > 
> > Thank you for confirming that. What was the purpose of that specific check anyway ? (Answer only if you have extra time and feel up to it.)
> 
> It was an attempt to code hardware failure tests by looking at other code and refactoring it for C. The attempt for the remover code was incorrect.

I guess this code came from your work with working on primes ? I think it’s great how much you have done for prime numbers! And I also really love how the guidelines refer to ‘Curios!’  Yes I know of that website and it magical and wonderful! 

Normally I would not bring something like that up lest you might identify me but I don’t see any entries of mine doing anything that special with primes and it would - I think - be hard to win since you have done so much for primes. It is better to simply share my appreciation of the website. I hadn’t heard of it until I looked it up after reading it in the guidelines though but I am glad I did. 

Actually I have a really interesting maths book you might like. I also am aware of another one but I would have to search for the title of that one as I don’t have it. The one I do have is interestingly named as it uses British English but has only ‘math’. Anyway it’s called ‘30 Second Math’ (I think that is it). It has some really wondrous things in it including the Fibonacci sequence in different parts of nature. One example is its on pineapples. I believe it’s also in bee generations as well (loose idea). I have taken pictures of plants with it in it as well. Or at least I am pretty sure they have it. 

Anyway I got the book at a bookshop several years back and it was really interesting and fun. 

Going back to the topic:

And what is remover code? Maybe I should not ask until I am looking at the diff again. If that’s the case I will find out tomorrow when I do a pull but if you have another moment I would be curious. 

With that said I will be putting the phone down very soon. Hope you sleep well when you do and good night! More from me tomorrow I am sure.

**Comment by xexyl** [comment]
If you’re curious about the book please let me know and I will see if I can find my copy and get the author and such. I am not sure how easy that will be because I have (currently) some things in front of my bookcase and (even more unfortunately) I have so many books that I have to rearrange them so that many are hard to access. But I can see about trying to get the author if you’re interested. 

Not today though. I will be putting the phone down in a few minutes. Good night my friend!

**Comment by lcn2** [comment]
### OT

> > > > Removed improper test in `sum_and_count()`, to fix it would have created a redundant test and so it was removed in commit [174d904](https://github.com/ioccc-src/mkiocccentry/commit/174d904a639f42d2d7fa106c5b7b273b2e3ce087)
> > > 
> > > 
> > > Thank you for confirming that. What was the purpose of that specific check anyway ? (Answer only if you have extra time and feel up to it.)
> > 
> > 
> > It was an attempt to code hardware failure tests by looking at other code and refactoring it for C. The attempt for the remover code was incorrect.
> 
> I guess this code came from your work with working on primes ? I think it’s great how much you have done for prime numbers! And I also really love how the guidelines refer to ‘Curios!’ Yes I know of that website and it magical and wonderful!

Yes, and other huge computational tasks where the result must be correct and the length of time to perform the work exceeds the mean time to error.

The ‘Curios!’ is a fun site.  We have to be careful to not get sucked into spending too much time there .. generating bursts of curious facts can be a super time sync.  :-)

We try to confine ourselves to focusing on integers <= 100, providing prime facts on someone's birthday based on their age (even if that age is not prime).

> Normally I would not bring something like that up lest you might identify me but I don’t see any entries of mine doing anything that special with primes and it would - I think - be hard to win since you have done so much for primes. It is better to simply share my appreciation of the website. I hadn’t heard of it until I looked it up after reading it in the guidelines though but I am glad I did.

We have to feel satisfied to help promote the progress for large prime number hunting by performing basic research and offering tutorials such as:

[A Grand Coding Challenge!
Finding a new Largest Known Prime](http://www.isthe.com/chongo/tech/math/prime/prime-tutorial.pdf)

There have been times when we have been tempted to go out and snag a prime number record .. tempting as that would be .. better to help others and promote the general field than to collect yet another world record.

> Actually I have a really interesting maths book you might like. I also am aware of another one but I would have to search for the title of that one as I don’t have it. The one I do have is interestingly named as it uses British English but has only ‘math’. Anyway it’s called ‘30 Second Math’ (I think that is it). It has some really wondrous things in it including the Fibonacci sequence in different parts of nature. One example is its on pineapples. I believe it’s also in bee generations as well (loose idea). I have taken pictures of plants with it in it as well. Or at least I am pretty sure they have it.

The use of **maths** is amusing.  For some people, treating a _collective_ as a singular object by referring to the collective via a _collective noun_, does not come easy for them.

> _data is_ vs. _data are_

for example.  Those who have a rigid view of grammar might be the type to declare _data is_ improper, perhaps because they like to correct others rather than to understand linguistic variety.  So they ignore the case where _data_ is used as a _collective noun_ and this _data_ is a singular object (a set of datum) and thus _data is_ is proper.  Thus both _data is_ and _data are_ have cases where they are correct and proper.

So **math** is a _collective noun_ of various mathematical topics can be proper, just as **maths** without the collective can be proper.

We are aware that there are idioms for which **maths** becomes habit forming.  :-)

I was taught _by ABCs_ by a Kiwi 🇳🇿, and thus my "proms" were burned with saying **zed** when referring to the last letter of the alphabet.  I have to remember when speaking in an area that says **zee** to do so and override by automatic prom recall.  :-)

BTW: A a young child is wholly and firmly rejected calling 0 **naught** because it sounded like the mathematical negation term **not** and so force myself to use **zero** instead.  :-)

For the **zed** case, the result is understandable to a **zee** person.

But for something such as:

```
!0
```

**not** **naught** is unacceptable, thus we prefer **zero**.  :-)

The **maths** vs. **math** does not suffer from such contextual problems, and given the _collective noun_ exception case, we can go either way.

On the other hand, we prefer singular over plurals, so we would use **math** by default.

> This is why we call prog such as `dbg_test` by the singlar instead of `dbg_tests`: less typing plus singular preference.

**Comment by lcn2** [comment]
> And what is remover code? Maybe I should not ask until I am looking at the diff again. If that’s the case I will find out tomorrow when I do a pull but if you have another moment I would be curious.

We do not understand the context for **remover code**, perhaps the was a typo on our part.

**Comment by xexyl** [comment]
> > And what is remover code? Maybe I should not ask until I am looking at the diff again. If that’s the case I will find out tomorrow when I do a pull but if you have another moment I would be curious.
> 
> We do not understand the context for **remover code**, perhaps the was a typo on our part.

I referred to:


> 
> It was an attempt to code hardware failure tests by looking at other code and refactoring it for C. **The attempt for the remover code was incorrect.**

**Comment by xexyl** [comment]
> ### OT
> > > > > Removed improper test in `sum_and_count()`, to fix it would have created a redundant test and so it was removed in commit [174d904](https://github.com/ioccc-src/mkiocccentry/commit/174d904a639f42d2d7fa106c5b7b273b2e3ce087)
> > > > 
> > > > 
> > > > Thank you for confirming that. What was the purpose of that specific check anyway ? (Answer only if you have extra time and feel up to it.)
> > > 
> > > 
> > > It was an attempt to code hardware failure tests by looking at other code and refactoring it for C. The attempt for the remover code was incorrect.
> > 
> > 
> > I guess this code came from your work with working on primes ? I think it’s great how much you have done for prime numbers! And I also really love how the guidelines refer to ‘Curios!’ Yes I know of that website and it magical and wonderful!
> 
> Yes, and other huge computational tasks where the result must be correct and the length of time to perform the work exceeds the mean time to error.
> 
> The ‘Curios!’ is a fun site. We have to be careful to not get sucked into spending too much time there .. generating bursts of curious facts can be a super time sync. :-)
> 
> We try to confine ourselves to focusing on integers <= 100, providing prime facts on someone's birthday based on their age (even if that age is not prime).
> 
> > Normally I would not bring something like that up lest you might identify me but I don’t see any entries of mine doing anything that special with primes and it would - I think - be hard to win since you have done so much for primes. It is better to simply share my appreciation of the website. I hadn’t heard of it until I looked it up after reading it in the guidelines though but I am glad I did.
> 
> We have to feel satisfied to help promote the progress for large prime number hunting by performing basic research and offering tutorials such as:
> 
> [A Grand Coding Challenge! Finding a new Largest Known Prime](http://www.isthe.com/chongo/tech/math/prime/prime-tutorial.pdf)
> 
> There have been times when we have been tempted to go out and snag a prime number record .. tempting as that would be .. better to help others and promote the general field than to collect yet another world record.
> 
> > Actually I have a really interesting maths book you might like. I also am aware of another one but I would have to search for the title of that one as I don’t have it. The one I do have is interestingly named as it uses British English but has only ‘math’. Anyway it’s called ‘30 Second Math’ (I think that is it). It has some really wondrous things in it including the Fibonacci sequence in different parts of nature. One example is its on pineapples. I believe it’s also in bee generations as well (loose idea). I have taken pictures of plants with it in it as well. Or at least I am pretty sure they have it.
> 
> The use of **maths** is amusing. For some people, treating a _collective_ as a singular object by referring to the collective via a _collective noun_, does not come easy for them.
> 

Yes. Well the way I describe it: you don't say you're doing/studying/dreaming mathematic .. you say you're doing/studying/dreaming mathematicS. So it should be mathS.

> > _data is_ vs. _data are_
> 
> for example. Those who have a rigid view of grammar might be the type to declare _data is_ improper, perhaps because they like to correct others rather than to understand linguistic variety. So they ignore the case where _data_ is used as a _collective noun_ and this _data_ is a singular object (a set of datum) and thus _data is_ is proper. Thus both _data is_ and _data are_ have cases where they are correct and proper.

Well to be technical it's more complicated than that. For instance usage in OED:

```
USAGE
In Latin, data is the plural of datum and, historically and in specialized scientific fields, it is also treated as a plural in English, taking a plural verb, as in the data were collected and classified. In modern non-scientific use, however, it is generally not treated as a plural. Instead, it is treated as a mass noun, similar to a word like information, which takes a singular verb. Sentences such as data was collected over a number of years are now widely accepted in standard English.
```

So it depends on the field and use but also how far back in time you live! :) So in general both are actually correct as you say but historically it's not so easy to say. Fun fact: historically and historic - how do you pronounce them? Historically the H was silent so you'd have people say 'an historic' rather than 'a historic'. Now people still say it and some people still have the silent H. I view this as correct just as I view the silent H incorrect in 'homage' and 'herb' but I'll not go down that garden path! :) Still the fact it was once correct makes it somewhat understandable.


However the term `maths` is treated as a singular (which makes sense if you think about it) but is actually a plural noun (which might sound strange without even thinking about it :-) ).

> 
> So **math** is a _collective noun_ of various mathematical topics can be proper, just as **maths** without the collective can be proper.
> 

Well I explained above why it should be maths but I know that for many it's difficult and also in American English they do say 'math'. Well that's okay but they also say a lot of other things that are dubious. :-) But it's the spelling changes that drive me crazy (or maybe: crazier ? :-) ).

> We are aware that there are idioms for which **maths** becomes habit forming. :-)
> 

Do you have an example idiom ? Funny thing: idiot and idiom are very close lexicographically :-) 


> I was taught _by ABCs_ by a Kiwi 🇳🇿, and thus my "proms" were burned with saying **zed** when referring to the last letter of the alphabet. I have to remember when speaking in an area that says **zee** to do so and override by automatic prom recall. :-)

Well you're kinder than me because I don't care who I talk to - I say **zed**. Did you also know that there are two pronunciations for H? One is how I say it HAITCh but the other I guess you say. Or do you say HAITCH?

Another fun one: pronunciation for controversy - two different ways of saying it. I guess you probably say it the way that's more common in American English (or even just traditionally) but in British English it's more common to put stress on the **-trov-** But here's a more amusing one: 


> USAGE
> There are two possible pronunciations for **decade**: one puts the stress on the dec- while the other puts the stress on the -cade (sounds like **decayed**). The second pronunciation is disapproved of by some traditionalists but is now regarded as a standard, acceptable alternative.

> 
> BTW: A a young child is wholly and firmly rejected calling 0 **naught** because it sounded like the mathematical negation term **not** and so force myself to use **zero** instead. :-)
> 

I've always viewed **naught** for 'nothing' and not 'zero' or 0. ... ah but I see now. Apparently in North American English 'naught' can also mean 0. I did not know that. (I had to check!)


> For the **zed** case, the result is understandable to a **zee** person.
> 

Though I wonder on that. Funny thing: I once was on the phone with an American post office and I said 'post' to him and he said 'here we say 'mail'. I immediately asked him: 'why don't you call it the mail office then?' He didn't have an answer for that. Well I knew he wouldn't but I had to make my point! :-)



> But for something such as:
> 
> ```
> !0
> ```
> 
> **not** **naught** is unacceptable, thus we prefer **zero**. :-)
> 

That's true of course. Funny thing though: first I read that as in C as in it would evaluate to 1 but then reading the comment more and seeing the context I know you refer to subfactorial (well I thought factorial but I had to check - there's an incredible amount of symbols for maths and I hate how some programming books use those symbols instead.)

> The **maths** vs. **math** does not suffer from such contextual problems, and given the _collective noun_ exception case, we can go either way.
> 

I've noticed you've gone both ways yes.

> On the other hand, we prefer singular over plurals, so we would use **math** by default.
> 
So you prefer to be incorrect by default! :-)

> > This is why we call prog such as `dbg_test` by the singlar instead of `dbg_tests`: less typing plus singular preference.

Interesting trivia there. Or I might say: titbit which you'd say 'tidbit'. 

... yes I'm a logophile and also something of a philologist (just not to the same degree) so there's a lot more than you probably expected but there it is anyway! :-)

The next thing I'll get to is another comment of importance though I'm not sure if I'll do that now or if I'm going to take a break. I think I might be forced to take a break. This was fun though so I thank you for it! :)

**Comment by xexyl** [comment]
... seems I missed replying to some of it so I have to do that first. Then I will take a break. After that I hope to address the script threads.

**Comment by xexyl** [comment]
> ### OT
> > > > > Removed improper test in `sum_and_count()`, to fix it would have created a redundant test and so it was removed in commit [174d904](https://github.com/ioccc-src/mkiocccentry/commit/174d904a639f42d2d7fa106c5b7b273b2e3ce087)
> > > > 
> > > > 
> > > > Thank you for confirming that. What was the purpose of that specific check anyway ? (Answer only if you have extra time and feel up to it.)
> > > 
> > > 
> > > It was an attempt to code hardware failure tests by looking at other code and refactoring it for C. The attempt for the remover code was incorrect.
> > 
> > 
> > I guess this code came from your work with working on primes ? I think it’s great how much you have done for prime numbers! And I also really love how the guidelines refer to ‘Curios!’ Yes I know of that website and it magical and wonderful!
> 
> Yes, and other huge computational tasks where the result must be correct and the length of time to perform the work exceeds the mean time to error.
> 

For instance? Not high priority of course but even just a word or a sentence is enough if you have the time and it's possible to say simply.

> The ‘Curios!’ is a fun site. We have to be careful to not get sucked into spending too much time there .. generating bursts of curious facts can be a super time sync. :-)
> 
I know how that goes - especially with the dictionary! I have spent hours and hours in the dictionary. But I've also been - as you say - sucked into spending a lot of time on that website too.

> We try to confine ourselves to focusing on integers <= 100, providing prime facts on someone's birthday based on their age (even if that age is not prime).

Speaking of such I guess you know of the birthday problem / paradox ? I heard a funny story: a statistics teacher made a bet with new students that he shared a birthday with at least one of the pupils. They would invariably make the bet and he'd have a lot of money :-) ... but he then gave it back and explained it to them. I love it. I enjoy telling people about it. They're usually flabbergasted.


> 
> > Normally I would not bring something like that up lest you might identify me but I don’t see any entries of mine doing anything that special with primes and it would - I think - be hard to win since you have done so much for primes. It is better to simply share my appreciation of the website. I hadn’t heard of it until I looked it up after reading it in the guidelines though but I am glad I did.
> 
> We have to feel satisfied to help promote the progress for large prime number hunting by performing basic research and offering tutorials such as:
> 
> [A Grand Coding Challenge! Finding a new Largest Known Prime](http://www.isthe.com/chongo/tech/math/prime/prime-tutorial.pdf)
> 

I think you've actually shared this one with me - it's very interesting! Well pretty much everything from you is fascinating but to different degrees. We have a lot of similarities but one thing you have far more experience in is maths (speaking of the devil word :-) ). But it's cool that you enjoy it so much.


> There have been times when we have been tempted to go out and snag a prime number record .. tempting as that would be .. better to help others and promote the general field than to collect yet another world record.

I understand that. My favourite one you've done is that palindromic one you shared on twitter. I think that was a prime, right? I did take a screenshot of it but I'm trying to hurry along so I can have my break and then get back to more important things (though this feels just as worth spending time on I must admit!).


And now I'll go take my break and then I'll try getting to the other things. I'm not sure how long my break will be though. 

BTW when do you get home from Canada or are you already there ?  Ah I see you are. How? The git log timestamp. Hope you had a great time! Well I guess you could be in another part of Canada but anyway I guess you're home?

**Comment by lcn2** [comment]
> BTW when do you get home from Canada or are you already there ? Ah I see you are. How? The git log timestamp. Hope you had a great time! Well I guess you could be in another part of Canada but anyway I guess you're home?

Home now.

**Comment by xexyl** [comment]
> > BTW when do you get home from Canada or are you already there ? Ah I see you are. How? The git log timestamp. Hope you had a great time! Well I guess you could be in another part of Canada but anyway I guess you're home?
> 
> Home now.

Glad you made it home safely! Hope you had a great time as well.

**Pull request merged**
