### PR TITLE
Change entry/entries to submission/submissions

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Please address the issue in iocccsize when you can if you feel you need to.

**Comment by lcn2** [comment]
> Please address the issue in iocccsize when you can if you feel you need to.

We don't see an issue with `iocccsize(1)`.  Did we miss something?

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
> > Please address the issue in iocccsize when you can if you feel you need to.
> 
> We don't see an issue with `iocccsize(1)`. Did we miss something?

The term entry/entries I believe is what I was getting at. Do you not want to change it to submission/submissions?

**Comment by xexyl** [comment]
> Thank you @xexyl

You are very welcome.

**Comment by lcn2** [comment]
Odd things, @xexyl  ... `make prep` passes but `make release` fails:

```sh
$ make release
make_action 10 clobber OK
make_action 11 all OK
make_action 12 depend OK
make_action 13 clean_mkchk_sem OK
make_action 14 all_sem_ref OK
make_action 15 mkchk_sem OK
make_action 16 all OK
make_action 17 parser-o ERROR exit code 2

make release: ERROR: ./test_ioccc/prep.sh exit code: 17

make release: see build.log for details
make: *** [release] Error 17
zsh: exit 2     make release
```

The `./bug_report.sh` reports "All tests PASSED":

[bug-report.20240308.110538.txt](https://github.com/ioccc-src/mkiocccentry/files/14542240/bug-report.20240308.110538.txt)

Here is the `build.log` from the `make release`

[build.log](https://github.com/ioccc-src/mkiocccentry/files/14542252/build.log)

**Comment by xexyl** [comment]
Trying now .. though not sure if I can take care of it today.

**Comment by xexyl** [comment]
Oh I know why. Did you update our macOS (the most recent one) and not update xcode related things? I see that in the log ....

**Comment by xexyl** [comment]
Looks like you don't have bison and/or flex?

**Comment by xexyl** [comment]
Yes all good on my end. That's a relief.

**Comment by lcn2** [comment]
We will have to work on this when we are back in town .. after train ride return

**Comment by lcn2** [comment]
We had to:

```sh
brew reinstall m4
sudo ln -s -f -v /opt/homebrew/opt/m4/bin/m4 /usr/local/bin/m4
```

before `make release` worked after macOS 14.4 upgrade.

Now `make release` works.  *sigh*

**Pull request merged**
