### PR TITLE
Minor fixes and enhancements to jfmt/jval/jnamval

### PR DESCRIPTION
**Pull request by xexyl**
New versions of jfmt, jval and jnamval with some minor bug fixes and enhancements: 0.0.6 2023-07-28, 0.0.7 2023-07-28 and 0.0.6 2023-07-28.

Fixed bug where redirecting stdout to /dev/null resulted in an error:

    Warning: vfpr: called from jfmt: vfprintf returned: 56 <= 0: errno[25]: Inappropriate ioctl for device

For jval and jnamval the functions parse_jval_args() and parse_jnamval_args() have been updated to take the proper struct, a pointer to argc from main() and a pointer to argv from main(). That is a int * and a char ***. The functions increment argc/argv past the file name so that main() can check if there are any args without having to worry about argv[0]. The function (not main() - the parsing ones) now show debug information about the args shown. Currently the debug level is 0 so that it's always printed but this will change later on. As there is no implementation yet (but see below) there is no list or array or searching of any kind with the args.

Since the ability to check if any args is now easy and since -i flag with no args specified means that there are no matches and that indicates exiting 8 jval and jnamval now have this check. That is the extent of any implementation details until we have discussed output, how jfmt should format code, search routines are added and numerous other things. This was just an aside, one might say.

Update jval(1) man page - add exit code 8 to list of exit codes.

### CODE REVIEW

**Comment by xexyl** [comment]
I forgot to mention I did a couple typos and such in the readme file.

**Comment by lcn2** [comment]
We will need await better processing of matters address in [comment 1655617615](https://github.com/lcn2/calc/issues/83#issuecomment-1655617615) before address this and future pull requests.

**Comment by xexyl** [comment]
> We will need await better processing of matters address in [comment 1655617615](https://github.com/lcn2/calc/issues/83#issuecomment-1655617615) before address this and future pull requests.

What about the readme file ?

I'd think the code change might be considered a workaround and then we can address the issue. It could then be changed back if desired. It might be a new issue should be opened as a bug report?

**Comment by xexyl** [comment]
> > We will need await better processing of matters address in [comment 1655617615](https://github.com/lcn2/calc/issues/83#issuecomment-1655617615) before address this and future pull requests.
> 
> What about the readme file ?
> 
> I'd think the code change might be considered a workaround and then we can address the issue. It could then be changed back if desired. It might be a new issue should be opened as a bug report?

The man pages was updated too btw.

**Comment by xexyl** [comment]
I added some comments with some useful information including the fact it's a macOS issue with the function particularly if `stdout` is being redirected to `/dev/null`.

I'll do more tomorrow if this has been resolved. Off to do other things. Hope you had a good sleep.

**Comment by lcn2** [comment]
Pull request processed after resolving conflicts with `CHANGES.md`.

**Pull request merged**
