### PR TITLE
Fix make picky in jprint.c

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
Good pick @xexyl

**Comment by xexyl** [comment]
> Good pick @xexyl 

Not as good as a pick of fresh strawberries 🍓but I do agree otherwise!

**Comment by xexyl** [comment]
> > Good pick @xexyl
> 
> Not as good as a pick of fresh strawberries 🍓but I do agree otherwise!

Speaking of strawberries do you have any plans for the upcoming Strawberry Moon ?

**Comment by lcn2** [comment]
> > > Good pick @xexyl
> 
> > 
> 
> > Not as good as a pick of fresh strawberries 🍓but I do agree otherwise!
> 
> 
> 
> Speaking of strawberries do you have any plans for the upcoming Strawberry Moon ?
> 
> 

Already picking out first strawberries 🍓 of the season.

**Comment by xexyl** [comment]
> > > > Good pick @xexyl
> > 
> > 
> > > 
> > 
> > 
> > > Not as good as a pick of fresh strawberries 🍓but I do agree otherwise!
> > 
> > 
> > Speaking of strawberries do you have any plans for the upcoming Strawberry Moon ?
> 
> Already picking out first strawberries 🍓 of the season.

We get ours from the same woman fresh from farms. They're wonderful strawberries!

But I hope that you enjoy the Moon! I doubt I'll see it but I do want to look into the time etc.

**Comment by xexyl** [comment]
> > > > > Good pick @xexyl
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Not as good as a pick of fresh strawberries 🍓but I do agree otherwise!
> > > 
> > > 
> > > Speaking of strawberries do you have any plans for the upcoming Strawberry Moon ?
> > 
> > 
> > Already picking out first strawberries 🍓 of the season.
> 
> We get ours from the same woman fresh from farms. They're wonderful strawberries!
> 
> But I hope that you enjoy the Moon! I doubt I'll see it but I do want to look into the time etc.

It seems I was off by one week .. I should have known too: I was sent a picture of the Moon the other day. Ah well, I hope you enjoyed it!

**Pull request merged**
