### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by xexyl**
This comes from 'make depend' and was not previously ignored.

### CODE REVIEW

**Comment by SirWumpus** [comment]
You probably want to add more general `*.orig` and `*.rej` (?) patch reject files.

**Comment by xexyl** [comment]
> You probably want to add more general `*.orig` and `*.rej` (?) patch reject files.

The first one is an interesting idea for sure ... the other maybe too. We do use patch in one place. I'll do that. Thanks!

**Comment by xexyl** [comment]
Done .. thanks!

**Review by lcn2 — APPROVED** [review]
👍

**Pull request merged**
