### PR TITLE
Minor fixes, txzchk.1 update and add jparse.1 #188

### PR DESCRIPTION
**Pull request by xexyl**
Sorry for the confusion of the earlier pull requests. Wanted to clean it up. I'm off to do other things now as I'm having a difficult day. Going to take it easy but I can discuss things with you still.

Good day!

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks @xexyl .. we may need to process the dbg changes as it is used in other tools as well

**Comment by xexyl** [comment]
> Thanks @xexyl .. we may need to process the dbg changes as it is used in other tools as well

Welcome. I'm not sure what might have to change though as I only made it so the version is available to all the other utils - and `limit_ioccc.sh`. Well I guess I'll find out.

**Comment by lcn2** [comment]
The dbg system is self contained so we will need to do something slightly different for version.h.

See commit 0766073a329b02a1acf5b0fd19fa94de4d77aede

    Release dbg v1.10 2022-05-01

    Changed dbg version string to DBG_VERSION.

    Moved DBG_VERSION back into dbg.h so that using the
    dbg facility only requires one include file (dbg.h)
    and compiling dbg.c to form dbg.o.

**Comment by xexyl** [comment]
> The dbg system is self contained so we will need to do something slightly different for version.h.
> 
> See commit [0766073](https://github.com/ioccc-src/mkiocccentry/commit/0766073a329b02a1acf5b0fd19fa94de4d77aede)
> 
> ```
> Release dbg v1.10 2022-05-01
> 
> Changed dbg version string to DBG_VERSION.
> 
> Moved DBG_VERSION back into dbg.h so that using the
> dbg facility only requires one include file (dbg.h)
> and compiling dbg.c to form dbg.o.
> ```

That makes sense yes. Just to remind in case you forgot: you ran `make depend` after doing this, right?

**Pull request merged**
