### PR TITLE
JSON warning and error updates + clean up

### PR DESCRIPTION
**Pull request by xexyl**
See git log for details. I don't plan on doing anything more today with this repo.

### CODE REVIEW

**Comment by lcn2** [comment]
Making good progress @xexyl

**Comment by lcn2** [comment]
On the train .. going thru show country .. have a bit of satellite signal so about to push out some `vermod.sh` code and `test_JSON` test file changes.

**Comment by xexyl** [comment]
> On the train .. going thru show country .. have a bit of satellite signal so about to push out some `vermod.sh` code and `test_JSON` test file changes.

Thanks for the note.

I'll check it out later. I'm done for the day with programming and soon I'll be running the macOS update. Or possibly: I might do that when I get food later. Not sure yet but it's still preparing the update.

**Comment by lcn2** [comment]
To update something:

1. make clobber all test
    To make sure everything is OK
2. edit ONE version string in version.h
3. make clobber all
4. ./vermod.sh -n -L "1.8 2022-02-13" "1.9 2022-03-15"
     As an example: see what is NOT being changed
5. ./vermod.sh -n -l "1.8 2022-02-13" "1.9 2022-03-15" 
     As an example: see what is being changed
6. hand edit any exceptions to the list that come up
7. ./vermod.sh "1.8 2022-02-13" "1.9 2022-03-15"
8. git add ...
9. git commit
10. git push

Now if you are just editing the author.json sub-tree, you can do:

```sh
./vermod.sh -d ./test_JSON/author.json -n -L "1.11 2022-02-23" "1.12 2022-03-15"
./vermod.sh -d ./test_JSON/author.json "1.11 2022-02-23" "1.12 2022-03-15"
```

See also:

```sh
./vermod -h
```

We hops this helps.

p.s. We just added JSON fields to things.  We hope things went well and that we did the `json.c` and `json.h` mods in good standing.  Sorry (tm Canada) if we messed something up.

**Comment by xexyl** [comment]
> p.s. And for something that its everywhere, the `-d foo` is not needed as it defaults to `./test_JSON`.

Yep. I knew that but thanks for the reminder.

**Comment by xexyl** [comment]
As for the other stuff I'll look at it next time I feel the need to update a version; saved it in a text file and I see now that you also added it to the git log.

And whether or not the versions have been updated properly I don't know as I haven't used the json test script in some time due to the fact I've not worked on the parsing any recently. I'll worry about that later on. Thanks.

I'll be shutting down for the day. Enjoy the rest of your day!

**Comment by xexyl** [comment]
> As for the other stuff I'll look at it next time I feel the need to update a version; saved it in a text file and I see now that you also added it to the git log.
> 
> And whether or not the versions have been updated properly I don't know as I haven't used the json test script in some time due to the fact I've not worked on the parsing any recently. I'll worry about that later on. Thanks.
> 
> I'll be shutting down for the day. Enjoy the rest of your day!

I am going to sleep now but I wanted to say that something else that I think might have to be addressed is the fact that `make test` actually passes: the fields should be required to be there, right? In that case the fact that it’s not handled should trigger an issue. I will look into this tomorrow as well. 

Good night and enjoy the rest of your journey home and stay safe!

**Comment by xexyl** [comment]
What's really interesting is when removing one of the version fields I get:

```
Warning: check_found_info_json_fields: found unhandled info field in file test_work/test-0/.info.json: 'fnamchk_version'
Warning: check_found_info_json_fields: found unhandled info field in file test_work/test-0/.info.json: 'jinfochk_version'
Warning: check_found_info_json_fields: required field not found in found_info_json_fields list in file test_work/test-0/.info.json: 'txzchk_version'
```

which is expected. But the unhandled lines should always be there until they're actually handled. I'll have to look into that when I'm more awake. Unfortunately I'm still tired but unable to sleep but hopefully I'll be more awake soon. I'm not sure when I'll start but in a bit I hope. I see you added more json test files which is good although right now of course I'm not even bothering running those tests since the json parser will have to change which will require some reading on my part about flex and bison but I'm not sure when that'll be: won't be until after I get warning and error messages cleaned up (or at least all the warn and error calls to be the json equivalents).

Hope you're having a nice sleep.

**Comment by xexyl** [comment]
I was going to add `txzchk_version` and `fnamchk_version` to the common fields with the rationale of the fnamchk is used on both files and tarball field is in both files as well.

But then it occurred to me: can version mod script add fields that aren't actually there? I'll add these fields to the common fields table and add handling of them but maybe you can tell me about this question and if this is not a good idea (this = having the fnamchk and txzchk in both files) - though it seems like it is a good idea for the reasons I cited - then I can move the fields back to the info fields table and move the handling of the checks to the info fields checks function.

**Comment by xexyl** [comment]
Okay I decided that only `fnamchk_version` should be added to common fields because although yes the tarball field is in both files the check on the txzchk is more of a `jinfochk` thing. Please let me know if any of this should change. I'll possibly make a commit of this in a while: still not sure of this so I'm going to do something else for a bit and think on it.

**Comment by xexyl** [comment]
> > Okay I decided that only `fnamchk_version` should be added to common fields because although yes the tarball field is in both files the check on the txzchk is more of a `jinfochk` thing. Please let me know if any of this should change. I'll possibly make a commit of this in a while: still not sure of this so I'm going to do something else for a bit and think on it.
> 
> The `vermod.sh` tool was designed to modify strings (usually due to a version change) in the `test_JSON` tree. It does not have the ability to add new strings, nor was it ever intended to do so as adding strings should be a rare occurrence (by now).

Right. I understand that.

> 
> There are tools that can help add strings in mass:
> 
> * vim with macros

That's one thing of vim I haven't really ever got used to using even though they're useful.

> * rpl with the `-e` flag
> * perl with `-p -i -e`
> * Etc.

Although I've used perl it was a long time ago and not very much. The other I've not used before though I have it installed of course.

**Comment by lcn2** [comment]
What tag and what value to you want to add to JSON test values?  And to both types of JSON values or just info or auth types?

**Comment by xexyl** [comment]
> What tag and what value to you want to add to JSON test values? And to both types of JSON values or just info or auth types?

I made it so `fnamchk_version` is common to both because both `jinfochk` and `jauthchk` use the tool but it's only in `.info.json` so it would need to be in `.author.json`. I did do this in `mkiocccentry` but the `test_JSON` files should be updated though right now it doesn't matter since that's not verified since it's far from incomplete.

**Comment by lcn2** [comment]
WIth commit 5b19a135b7cf09e18462c5e1def67195740315d3 , @xexyl. the author based JSON files now have the `fnamchk_version` field and they better reflect the test_work/test-0/.author.json that is build via make test.

**Comment by xexyl** [comment]
> WIth commit [5b19a13](https://github.com/ioccc-src/mkiocccentry/commit/5b19a135b7cf09e18462c5e1def67195740315d3) , @xexyl. the author based JSON files now have the `fnamchk_version` field and they better reflect the test_work/test-0/.author.json that is build via make test.

Thank you. 

Would you please elaborate on the last part though? If it’s a code change I will see it tomorrow so if that’s the case no worries. But if it’s something else and/or you have a moment what do you mean? Is it that they have the fields in the same order as `mkiocccentry` writes them? That’s the only thing I can think of. 

Going to sleep soon. Hope you have a great night! Thank you for the help adding the field.

**Comment by lcn2** [comment]
> > WIth commit [5b19a13](https://github.com/ioccc-src/mkiocccentry/commit/5b19a135b7cf09e18462c5e1def67195740315d3) , @xexyl. the author based JSON files now have the `fnamchk_version` field and they better reflect the test_work/test-0/.author.json that is build via make test.
> 
> Thank you.
> 
> Would you please elaborate on the last part though? If it’s a code change I will see it tomorrow so if that’s the case no worries. But if it’s something else and/or you have a moment what do you mean? Is it that they have the fields in the same order as `mkiocccentry` writes them? That’s the only thing I can think of.

A canonical JSON file set is what `mkiocccentry-test.sh` produces.  So the `test_work/test-0/.author.json` was used to generate a new `test_JSON/author.json/good/author.default.json` file.  From there, bad variants under `mkiocccentry/test_JSON` were generated.

For example, all of the `author-missing-line.*.json` files were copies of `test_work/test-0/.author.json` with a single line removed.  etc.

So yes, the `test_JSON/author.json/good/author.default.json` was generated by `mkiocccentry`, (as generated by the `mkiocccentry-test.sh` produces) so that the _good_ value looks kind of / sort of like a typical entry might look.  True, there are other types of JSON test files that are generated and need to be generated: but if you are going to start with a quasi-canonical file, using the JSON files produced by `mkiocccentry-test.sh` is a good and convenient starting point.

BTW: We plan to re-factor the `test_JSON/info.json/* files sometime.

**Comment by xexyl** [comment]
> > > WIth commit [5b19a13](https://github.com/ioccc-src/mkiocccentry/commit/5b19a135b7cf09e18462c5e1def67195740315d3) , @xexyl. the author based JSON files now have the `fnamchk_version` field and they better reflect the test_work/test-0/.author.json that is build via make test.
> > 
> > 
> > Thank you.
> > Would you please elaborate on the last part though? If it’s a code change I will see it tomorrow so if that’s the case no worries. But if it’s something else and/or you have a moment what do you mean? Is it that they have the fields in the same order as `mkiocccentry` writes them? That’s the only thing I can think of.
> 
> A canonical JSON file set is what `mkiocccentry-test.sh` produces. So the `test_work/test-0/.author.json` was used to generate a new `test_JSON/author.json/good/author.default.json` file. From there, bad variants under `mkiocccentry/test_JSON` were generated.
> 
> For example, all of the `author-missing-line.*.json` files were copies of `test_work/test-0/.author.json` with a single line removed. etc.
> 
> So yes, the `test_JSON/author.json/good/author.default.json` was generated by `mkiocccentry`, (as generated by the `mkiocccentry-test.sh` produces) so that the _good_ value looks kind of / sort of like a typical entry might look. True, there are other types of JSON test files that are generated and need to be generated: but if you are going to start with a quasi-canonical file, using the JSON files produced by `mkiocccentry-test.sh` is a good and convenient starting point.
> 

That sounds like a good idea yes.

> BTW: We plan to re-factor the `test_JSON/info.json/* files sometime. Changs should be cosmetic only.

Thanks.

**Pull request merged**
