### PR TITLE
Nightmare warning added to programmer's apology

### PR DESCRIPTION
**Pull request by xexyl**
Trying to work on the generated code is impossible and it will also give
you nightmares about spaghetti code and the comment is now an apology
AND a warning:

    /*
     * A programmer's apology and warning
     *
     * Sorry (tm Canada :-)) for the appalling condition of the code below.
     *
     * The people who worked on this repo did NOT write his code.  Well,
     * OK, we did write this comment. But we refer to code beyond this comment. :-)
     * The code below was generated by the bison or flex code generator.
     *
     * WARNING: We do NOT recommend that you modify this code even though it's
     * incredibly offensive and ugly if only because it's impossible to maintain and
     * it'll also give you nightmares about spaghetti code with monstrous tentacles
     * grabbing at you to try and swallow you whole after putting you in its hideous
     * mouth.
     *
     * Instead work on the bison *.y and flex *.l source files. See the Makefile for
     * more info on how the code below was generated.
     *
     * Thanks in advance for your understanding, and sorry (tm Canada :-)).
     *
     * P.S. In 2022 April 04, when this comment was created, none of the people
     *	working on this repo were Canadian.  But some of them have several
     *	good friends who live in, or are from Canada. Those friends say sorry
     *	in a fun and friendly way, so we honour those friends in this comment.
     */

### CODE REVIEW

**Comment by xexyl** [comment]
There. I think it's better now and we could all use some extra humour so why not? :)

**Comment by xexyl** [comment]
FYI: I'll be off for the day very soon. I might be able to reply to some quick things at some points but it won't be until tomorrow that I can do more proper replies.


Good day!

**Comment by xexyl** [comment]
Off now. Have a good day my friend!

**Comment by lcn2** [comment]
Fun pull request @xexyl 🙏

**Comment by lcn2** [comment]
... and amplified via commit 4ab55593a40c1d176b08e2ae00c8341ee39f9485

We suggest, @xexyl, that we reward ourselves when the JSON parser passes unit tests by considering adding additional paragraphs to `sorry.tm.ca.h` to help encourage us to bring the parser to a conclusion.  :-)

**Comment by xexyl** [comment]
> ... and amplified via commit [4ab5559](https://github.com/ioccc-src/mkiocccentry/commit/4ab55593a40c1d176b08e2ae00c8341ee39f9485)
> 
> We suggest, @xexyl, that we reward ourselves when the JSON parser passes unit tests by considering adding additional paragraphs to `sorry.tm.ca.h` to help encourage us to bring the parser to a conclusion. :-)

Great idea! Look forward to seeing your commit. Good day my friend!

**Comment by xexyl** [comment]
> Fun pull request @xexyl 🙏

I think it is too. I'm looking at your modifications now. Unfortunately there's a merge conflict on my end as I had not realised you had already merged the previous pull request (I had gone afk a bit) and so pushed it only to have to make a new commit: then I noticed that I could just do a new pull request form the branch. So I have to work this out and then will do a merge commit I guess.

**Comment by xexyl** [comment]
> ... and amplified via commit [4ab5559](https://github.com/ioccc-src/mkiocccentry/commit/4ab55593a40c1d176b08e2ae00c8341ee39f9485)
> 

Okay I love that commit so much .... especially `gleet` which macOS spellcheck does not even know and repeatedly tried to change to fleet (of course vim under macOS and I bet it's not in most OS dictionary files also do not have it.

Now it's funny you'd also bring up the Flying Spaghetti Monster because I actually thought of it but I'm glad I did not put it in because your edit is even better than I would have come up with: I'm sure of it!

Just did a pull request. Hope you're having a nice sleep my friend!

**Pull request merged**
