### PR TITLE
Minor shell script fixes + major update to bug_report.sh

### PR DESCRIPTION
**Pull request by xexyl**
I would have left this pull request for later but there's a fix to a script that's important (in some ways not minor at all). Yesterday I inadvertently committed `hostchk.sh` with the execute bit disabled which means `make` will fail (or issue a warning) and any script that calls `hostchk.sh` will also fail. Sorry about that!

The other change is that for the scripts that had a specific list of `signal_spec` for `trap` I changed it to `EXIT` as discussed yesterday.

I do expect to do more commits today.

### CODE REVIEW

**Comment by xexyl** [comment]
Okay I think that at least for now I'm done for the day. I think I made great progress though. I wonder what you think about what I did for exit code in the bug_report.sh script. I think it's a clever or at least convenient way to do it. However I am not sure about one thing.

Would it be more portable to use `let` than to do `((EXIT_CODE++))` ? I'm not sure but I guess that might be better. I almost did do that and I can do it if that seems like a better idea but I am happy I got a lot done today. Still much more to do for that script and also a fair bit with `hostchk.sh` but much has been done today.

I however need to do something else. It's possible I will return to this later today but I'm not sure of it. I'm guessing I won't do much more today. Very tired and today has been kind of strange as well.

**Comment by lcn2** [comment]
> Would it be more portable to use let than to do ((EXIT_CODE++)) ? I'm not sure but I guess that might be better. I almost did do that and I can do it if that seems like a better idea but I am happy I got a lot done today. Still much more to do for that script and also a fair bit with hostchk.sh but much has been done today.

This '((EXIT_CODE++))' makes it **MUCH** worse.  When an shell script exits with a value of 7, where did it exit?  You might not know as it would depend on the order of execution within the script.  Even if there is a single explicit path thru the code such that the order of '((EXIT_CODE++))' execution is deterministic, you have to now count thru the code just to find a particular exit value.

MUCH netter to use explicit values.

**Comment by xexyl** [comment]
> > Would it be more portable to use let than to do ((EXIT_CODE++)) ? I'm not sure but I guess that might be better. I almost did do that and I can do it if that seems like a better idea but I am happy I got a lot done today. Still much more to do for that script and also a fair bit with hostchk.sh but much has been done today.
> 
> This '((EXIT_CODE++))' makes it **MUCH** worse. When an shell script exits with a value of 7, where did it exit? You might not know as it would depend on the order of execution within the script. Even if there is a single explicit path thru the code such that the order of '((EXIT_CODE++))' execution is deterministic, you have to now count thru the code just to find a particular exit value.
> 
> MUCH netter to use explicit values.

So what can we do to make sure it's easy to add tests ? I did wonder about this but the message was why I went ahead and did it. What do you think?

**Comment by lcn2** [comment]
Based on [comment 1279790494](https://github.com/ioccc-src/mkiocccentry/issues/357#issuecomment-1279790494) we have to reject this commit, sorry @xexyl.

**Comment by xexyl** [comment]
I just fixed the trap thing from the update in the question I had. I'll look at the exit code stuff too though I think it's unfortunate because it will make editing the script more complicated.

**Comment by xexyl** [comment]
> Based on [comment 1279790494](https://github.com/ioccc-src/mkiocccentry/issues/357#issuecomment-1279790494) we have to reject this commit, sorry @xexyl.

But I already fixed it.

**Comment by xexyl** [comment]
> > Based on [comment 1279790494](https://github.com/ioccc-src/mkiocccentry/issues/357#issuecomment-1279790494) we have to reject this commit, sorry @xexyl.
> 
> But I already fixed it.

So I will have to recommit everything I guess unless there's a way to reopen it. I'll do that but it probably won't be today. I need a break from working on this stuff. Been awake too long and very tired.

**Comment by lcn2** [comment]
> I just fixed the trap thing from the update in the question I had. I'll look at the exit code stuff too though I think it's unfortunate because it will make editing the script more complicated.

We reopened the pull request so that you can fix the trap issues.

**Comment by xexyl** [comment]
> > I just fixed the trap thing from the update in the question I had. I'll look at the exit code stuff too though I think it's unfortunate because it will make editing the script more complicated.
> 
> We reopened the pull request so that you can fix the trap issues.

It's already fixed. Or did it not go through?

**Comment by xexyl** [comment]
... ah I see. It did indeed not go through. I'm not sure how to recommit this. I'll have to think on it and then at the same time I'll have to fix the exit codes.

**Comment by lcn2** [comment]
> > > Based on [comment 1279790494](https://github.com/ioccc-src/mkiocccentry/issues/357#issuecomment-1279790494) we have to reject this commit, sorry @xexyl.
> 
> > 
> 
> > But I already fixed it.
> 
> 
> 
> So I will have to recommit everything I guess unless there's a way to reopen it. I'll do that but it probably won't be today. I need a break from working on this stuff. Been awake too long and very tired.

Sorry, we didn't realize that the exit stuff was mixed into a set of other edits.  We reopened it for your convenience.

**Comment by xexyl** [comment]
> > > > Based on [comment 1279790494](https://github.com/ioccc-src/mkiocccentry/issues/357#issuecomment-1279790494) we have to reject this commit, sorry @xexyl.
> > 
> > 
> > > 
> > 
> > 
> > > But I already fixed it.
> > 
> > 
> > So I will have to recommit everything I guess unless there's a way to reopen it. I'll do that but it probably won't be today. I need a break from working on this stuff. Been awake too long and very tired.
> 
> Sorry, we didn't realize that the exit stuff was mixed into a set of other edits. We reopened it for your convenience.

It's okay. Thank you. I'm not sure how to recommit this issue though. I might have to make some other changes simply so I can recommit and at the same time I'll manually sequence exit codes in the bug report script.

**Comment by lcn2** [comment]
> 
> > Would it be more portable to use let than to do ((EXIT_CODE++)) ? I'm not sure but I guess that might be better. I almost did do that and I can do it if that seems like a better idea but I am happy I got a lot done today. Still much more to do for that script and also a fair bit with hostchk.sh but much has been done today.
> 
> This '((EXIT_CODE++))' makes it **MUCH** worse.  When an shell script exits with a value of 7, where did it exit?  You might not know as it would depend on the order of execution within the script.  Even if there is a single explicit path thru the code such that the order of '((EXIT_CODE++))' execution is deterministic, you have to now count thru the code just to find a particular exit value.
> 
> We believe it is MUCH better to use explicit values.

We recommend that you amend the changes to set EXIT_CODE to explicit values as per comment 1279790494.

**Comment by xexyl** [comment]
> > > Would it be more portable to use let than to do ((EXIT_CODE++)) ? I'm not sure but I guess that might be better. I almost did do that and I can do it if that seems like a better idea but I am happy I got a lot done today. Still much more to do for that script and also a fair bit with hostchk.sh but much has been done today.
> > 
> > 
> > This '((EXIT_CODE++))' makes it **MUCH** worse.  When an shell script exits with a value of 7, where did it exit?  You might not know as it would depend on the order of execution within the script.  Even if there is a single explicit path thru the code such that the order of '((EXIT_CODE++))' execution is deterministic, you have to now count thru the code just to find a particular exit value.
> > We believe it is MUCH better to use explicit values.
> 
> We recommend that you amend the changes to set EXIT_CODE to explicit values as per comment 1279790494.

I will. But first I have to fix the other thing.

**Comment by lcn2** [comment]
We found a case where `trap ... 0 0 1 2 3 15` was used.  The double 0 trap use might be OK, but it probably needs to be fixed just in case there are unwanted side effects.

**Comment by xexyl** [comment]
> We found a case where `trap ... 0 0 1 2 3 15` was used. The double 0 trap use might be OK, but it probably needs to be fixed just in case there are unwanted side effects.

That's already fixed actually. Haven't pushed it yet.

**Comment by xexyl** [comment]
As for the exit code there was another reason to have it the way I do have it and I'm not sure what to do now. Can the exit code for finding a non-executable file be the same as any other non-executable tool (of the repo)? Because that greatly simplifies things - have a simple loop that checks everything.

That was another reason to have it that way.

**Comment by xexyl** [comment]
I will go ahead and do that in the hopes that it's okay. If necessary I will amend the loop another time. For now it'll have to do. Let me quickly make this commit and then I'll push the two.

**Comment by lcn2** [comment]
> > > Would it be more portable to use let than to do ((EXIT_CODE++)) ? I'm not sure but I guess that might be better. I almost did do that and I can do it if that seems like a better idea but I am happy I got a lot done today. Still much more to do for that script and also a fair bit with hostchk.sh but much has been done today.
> 
> > 
> 
> > This '((EXIT_CODE++))' makes it **MUCH** worse. When an shell script exits with a value of 7, where did it exit? You might not know as it would depend on the order of execution within the script. Even if there is a single explicit path thru the code such that the order of '((EXIT_CODE++))' execution is deterministic, you have to now count thru the code just to find a particular exit value.
> 
> > 
> 
> > MUCH netter to use explicit values.
> 
> 
> 
> So what can we do to make sure it's easy to add tests ? I did wonder about this but the message was why I went ahead and did it. What do you think?

Add then at the end of the existing set to make it easier to increase the EXIT codes and minimize the need to renumber.  


Also if you have a few ending or special case EXIT codes, move then numerically up to, say 100 or more so that additional tests at the end are unlikely to force you to renumber those other special exit codes.

**Comment by xexyl** [comment]
> > > > Would it be more portable to use let than to do ((EXIT_CODE++)) ? I'm not sure but I guess that might be better. I almost did do that and I can do it if that seems like a better idea but I am happy I got a lot done today. Still much more to do for that script and also a fair bit with hostchk.sh but much has been done today.
> > 
> > 
> > > 
> > 
> > 
> > > This '((EXIT_CODE++))' makes it **MUCH** worse. When an shell script exits with a value of 7, where did it exit? You might not know as it would depend on the order of execution within the script. Even if there is a single explicit path thru the code such that the order of '((EXIT_CODE++))' execution is deterministic, you have to now count thru the code just to find a particular exit value.
> > 
> > 
> > > 
> > 
> > 
> > > MUCH netter to use explicit values.
> > 
> > 
> > So what can we do to make sure it's easy to add tests ? I did wonder about this but the message was why I went ahead and did it. What do you think?
> 
> Add then at the end of the existing set to make it easier to increase the EXIT codes and minimize the need to renumber. 

There is that. However for some things it might be better to have a newly thought of test before an already existing test.

> 
> Also if you have a few ending or special case EXIT codes, move then numerically up to, say 100 or more so that additional tests at the end are unlikely to force you to renumber those other special exit codes.

That's something to consider too I guess though for now I have it sorted - except for the loop of all the tools. If that has to change it will have to be another day. I do think though with the message of what's not executable then it should be okay if we just say 'this exit code means that one or more of our tools cannot be executed'.

**Comment by xexyl** [comment]
I just pushed the two commits with the fixes.

As for the exit code for each tool I thought of a way to calculate the exit code so that we can still have the loop if this is necessary. However I hope that this can be done tomorrow if you feel that is necessary.

**Comment by xexyl** [comment]
And with that I'm taking a much needed break. I should likely be able to continue tomorrow. If necessary I'll improve the loop for checking the tools being executable at that point. Since it's a work in progress I hope that's okay. I also hope you enjoy the rest of your day.

I'll be online for a few more hours probably but doing mindless things.

**Review by lcn2 — CHANGES_REQUESTED** [review]
We recommend that the change to jstr_test.sh be removed from this pull request.  We also recommend, for a similar reason, that the change to old.chkcode.sh be removed from this pull request.

BTW: In general changes to old.* are not recommended.  They exist for reference purposes and will removed once the semantic test code is complete and fully tested.

**Comment by xexyl** [comment]
> We recommend that the change to jstr_test.sh be removed from this pull request. We also recommend, for a similar reason, that the change to old.chkcode.sh be removed from this pull request.
> 
> BTW: In general changes to old.* are not recommended. They exist for reference purposes and will removed once the semantic test code is complete and fully tested.

Which change in particular please? The update of trap or the inclusion of it in the bug report script?

**Comment by xexyl** [comment]
..I see the old one is of course not in the bug report script so I guess you mean trap? I'm not sure.

**Comment by lcn2** [comment]
> And with that I'm taking a much needed break. I should likely be able to continue tomorrow. If necessary I'll improve the loop for checking the tools being executable at that point. Since it's a work in progress I hope that's okay. I also hope you enjoy the rest of your day.
> 
> 
> 
> I'll be online for a few more hours probably but doing mindless things. 

See [comment 1143216141](https://github.com/ioccc-src/mkiocccentry/pull/365#pullrequestreview-1143216141).

We did that at a "GitHub pull request review" and are not sure how or if pull request authors are notified of such reviews, @xexyl.

**Comment by xexyl** [comment]
> > And with that I'm taking a much needed break. I should likely be able to continue tomorrow. If necessary I'll improve the loop for checking the tools being executable at that point. Since it's a work in progress I hope that's okay. I also hope you enjoy the rest of your day.
> > I'll be online for a few more hours probably but doing mindless things.
> 
> See [comment 1143216141](https://github.com/ioccc-src/mkiocccentry/pull/365#pullrequestreview-1143216141).
> 
> We did that at a "GitHub pull request review" and are not sure how or if pull request authors are notified of such reviews, @xexyl.

I was indeed notified. But I'm not sure what needs to change. I only updated the trap to be the way it was. Isn't that what you wanted? Though see my discovery in the other thread on the trap command for some interesting bits of information!

**Comment by xexyl** [comment]
If I undo the commit it'll go back to what it started out with before today, right? If I undo the commit from a short bit ago it'll go back to having just `EXIT`. I also only updated those scripts as you suggested I should do. We learnt that it was a mistake (and I tested to find out even more interesting things) so I undid it. But now you want something else changed, seemingly, but I'm not sure what?

**Comment by lcn2** [comment]
> > > And with that I'm taking a much needed break. I should likely be able to continue tomorrow. If necessary I'll improve the loop for checking the tools being executable at that point. Since it's a work in progress I hope that's okay. I also hope you enjoy the rest of your day.
> 
> > > I'll be online for a few more hours probably but doing mindless things.
> 
> > 
> 
> > See [comment 1143216141](https://github.com/ioccc-src/mkiocccentry/pull/365#pullrequestreview-1143216141).
> 
> > 
> 
> > We did that at a "GitHub pull request review" and are not sure how or if pull request authors are notified of such reviews, @xexyl.
> 
> 
> 
> I was indeed notified. But I'm not sure what needs to change. I only updated the trap to be the way it was. Isn't that what you wanted? Though see my discovery in the other thread on the trap command for some interesting bits of information!

Those changes simply introduce an extra space in to a trap line that isn't needed.  And in one case an old.* file is being changed for the same reason.

**Comment by xexyl** [comment]
> > > > And with that I'm taking a much needed break. I should likely be able to continue tomorrow. If necessary I'll improve the loop for checking the tools being executable at that point. Since it's a work in progress I hope that's okay. I also hope you enjoy the rest of your day.
> > 
> > 
> > > > I'll be online for a few more hours probably but doing mindless things.
> > 
> > 
> > > 
> > 
> > 
> > > See [comment 1143216141](https://github.com/ioccc-src/mkiocccentry/pull/365#pullrequestreview-1143216141).
> > 
> > 
> > > 
> > 
> > 
> > > We did that at a "GitHub pull request review" and are not sure how or if pull request authors are notified of such reviews, @xexyl.
> > 
> > 
> > I was indeed notified. But I'm not sure what needs to change. I only updated the trap to be the way it was. Isn't that what you wanted? Though see my discovery in the other thread on the trap command for some interesting bits of information!
> 
> Those changes simply introduce an extra space in to a trap line that isn't needed. And in one case an old.* file is being changed for the same reason.

Oh that! Thank you for clarifying. I did that so I could actually make a commit. Because the commit was already locally made but also pushed to the branch. Yes. Let me fix that.

**Comment by xexyl** [comment]
Does that help?

**Comment by lcn2** [comment]
Thanks @xexyl, and sorry (tm Canada 🇨🇦) for all of the complications related to this pull request.

**Comment by xexyl** [comment]
> Thanks @xexyl, and sorry (tm Canada 🇨🇦) for all of the complications related to this pull request.

It's okay but thank you. Doing something else now. Enjoy the rest of your day. Hopefully I can do more tomorrow. Very possibly will be an early night tonight. Good day!

**Comment by xexyl** [comment]
I have a bad feeling that the next time I make a pull request it's going to want to do some of the same commits again. I think this because I see the same commit twice which I have had happen before. This was when the pull request was closed temporarily right as I was fixing the trap code. If so I'll have to delete my fork and re-fork again. Well it can't be helped either way.

I'll worry about it tomorrow. Hope you have a good day and night.

**Pull request merged**
