### PR TITLE
Bug fixes in jparse

### PR DESCRIPTION
**Pull request by xexyl**
Sync the jparse/ directory from jparse repo
(https://github.com/xexyl/jparse/). This includes some important bug fixes, including a segfault when JSON debug level was specified and a string was encountered (the problem was that when has_nul was removed it the format specifier, a '%s', was not removed).

A more significant change (that only requires minor changes in mkiocccentry code) is that the tools jstrencode(1) and jstrdecode(1) were swapped as according to other sources, converting a code point to another character (accented character, emoji etc.) is encoding, not decoding. This means that functions and comments were also changed. Only minor changes in this repo had to be made, as noted, however and specifically function name changes.

With this merged the temp-test-ioccc repo will have to have the scripts updated to use the right tool (not jstrdecode but jstrencode) and the correct version (2.0.0).

### CODE REVIEW

**Comment by xexyl** [comment]
I decided to go ahead and make the pull request due to the bug uncovered and since the function names were changed to let this work okay. `make release` worked fine on my end and as long as it works in the test workflow it should be fine. The other repo does need updates to the scripts, of course, but that can't be helped.

**Comment by xexyl** [comment]
And I see some problems. I guess to do with the format changes .... or else one I had to do in another file. Let's see... will fix.

**Comment by xexyl** [comment]
Hopefully what I just pushed will catch them all.

**Review by lcn2 — APPROVED** [review]
‼️

**Comment by xexyl** [comment]
> ‼️

Thanks. Tomorrow I'll run the test for the other repo. It'll take some time esp if I do the `make install` from jparse itself and then do it again with `make install` from `jparse/` under here but I can do that anyway and I agree it should be done.

**Comment by lcn2** [comment]
Found some signal on the train passing thru stations 🚉 where we did a strategic update at the right times. 😉

**Comment by xexyl** [comment]
> Found some signal on the train passing thru stations 🚉 where we did a strategic update at the right times. 😉

Thanks. This will help test things. I know it was a major change too but better to have the terms right. The good thing is the test suite works here and also in jparse. Now we just have to make sure that the website scripts will be fine too.

Leaving in a few minutes .. back tomorrow. Good day!

**Comment by lcn2** [comment]
BTW: @xexyl, the involvement of Leo at this stage is a **very good sign** that he has confidence on the several years of efforts people have put into "this repo" and the "other repo". 

And while Leo has write and PR acceptance to these repos, being an official IOCCC judge, do remember that Leo is not familiar with the tools, not the JSON files and friend.  So he may need some guidance from you in that regard.  

Helping and encouraging Leo to participate by fine tuning existing entire .. especially with his vast knowledge of the contest and his collection of files .. even though we are in a _"soft freeze"_ .. is a good thing.  The benefits of his direct involvement during this time that we are away outweighs the issue of mods. And we trust that you, @xexyl, will be able guide such post-a _"soft freeze"_ / pre-**Great Fork Merge** while we are away. 

Normally, and once the **Great Fork Merge** is completed, some of the finer points (like updating the inventory of an existing entry, mods to the thanks file, mods to the FAQ, fixing bugs / mods to bugs) we did **NOT** cover, so looking out for and helping Leo with that sort of stuff would be most appreciated. 

Also keep in mind that the compressed tarballs are **NOT** up to date.  We don't want to do an `make update` nor `make tar` at this time. That will happen I the later stages of the **Great Fork Merge** as described in the TODO list. 

We would also encourage you to encourage Leo to compile and test the "other repo" (I.e., mkiocccentry and friends) on his systems.  You may find that, like what happened with BSD, the "other repo" would benefit from such a portability test. 

Leo is an **extraordinarily skilled** developer with a **genius-level** ability to look at twisted code and understand it in part, if not in whole. It is an unusual occurrence when a submission completely stumps him. That being said, his looking over code would be beneficial.

**Comment by xexyl** [comment]
> BTW: @xexyl, the involvement of Leo at this stage is a **very good sign** that he has confidence on the several years of efforts people have put into "this repo" and the "other repo".
> 

That's good to hear.

> And while Leo has write and PR acceptance to these repos, being an official IOCCC judge, do remember that Leo is not familiar with the tools, not the JSON files and friend. So he may need some guidance from you in that regard.
> 

Of course. I'm always happy to help. It's something I'm passionate about and I enjoy helping other people too.

> Helping and encouraging Leo to participate by fine tuning existing entire .. especially with his vast knowledge of the contest and his collection of files .. even though we are in a _"soft freeze"_ .. is a good thing. The benefits of his direct involvement during this time that we are away outweighs the issue of mods. And we trust that you, @xexyl, will be able guide such post-a _"soft freeze"_ / pre-**Great Fork Merge** while we are away.

I sure can. I appreciate you have that confidence in me too. Thank you!

> 
> Normally, and once the **Great Fork Merge** is completed, some of the finer points (like updating the inventory of an existing entry, mods to the thanks file, mods to the FAQ, fixing bugs / mods to bugs) we did **NOT** cover, so looking out for and helping Leo with that sort of stuff would be most appreciated.

Sure. I am not sure if I follow what you're saying though. I can interpret it more than one way:

0. He'll have to get used to it so if he has any questions I can answer while you're away (or something like that).
1. Or maybe if he adds something but forgets to run a command I can take care of it and tell him what was done.
2. Something else?


> 
> Also keep in mind that the compressed tarballs are **NOT** up to date. We don't want to do an `make update` nor `make tar` at this time. That will happen I the later stages of the **Great Fork Merge** as described in the TODO list.

Yes and I know you also have in mind to kind of rewrite history in that regard, a gift that historians seem to possess more than anyone else. I've not touched the tarballs because doing so would slow things way down and you have plans for it them anyway, as you told me.


> 
> We would also encourage you to encourage Leo to compile and test the "other repo" (I.e., mkiocccentry and friends) on his systems. You may find that, like what happened with BSD, the "other repo" would benefit from such a portability test.
> 

I just posted a comment about this so hopefully he can get to it sometime soon.

> Leo is an **extraordinarily skilled** developer with a **genius-level** ability to look at twisted code and understand it in part, if not in whole. It is an unusual occurrence when a submission completely stumps him. That being said, his looking over code would be beneficial.

I remember you telling me this fact, that he's amazing at parsing obfuscated code, and I agree that it would be great if he were to check things out.

I have a bit more time before I have to shut down. It seems like I might not get the first `make www` done after all but if not I'll do it tomorrow and should be able to do the other one too.

**Pull request merged**
