### PR TITLE
Forbid certain filenames in submissions

### PR DESCRIPTION
**Pull request by xexyl**
The following files are no longer allowed:

- README.md
- prog.orig
- prog
- index.html
- inventory.html
- prog.orig.c

The mkiocccentry program will detect this early on and tell users this rather than making them input details about their entry only to have to start over simply because of an invalid filename.

The function test_extra_file() for chkentry has also been updated.

New version of mkiocccentry 1.0.2 2023-11-06. Updated json files for new version of mkiocccentry.

No extra test files were added but this might be a good idea to test the chkentry checks as well.

### CODE REVIEW

**Comment by xexyl** [comment]
Hmm ... see a possible problem. Checking. I did run `make prep` and no problem but pulling now I see one. Will fix if necessary.

**Comment by lcn2** [comment]
That was fast 💨 @xexyl thanks 🙏 

Too bad it has to be done. However we just know that someone might have submitted their source code as `README.md` and made it difficult for us to do a writeup of their win. 🥇 😉

**Comment by xexyl** [comment]
Ah .. I forgot to run `make all` before the test it seems.

**Comment by xexyl** [comment]
> That was fast 💨 @xexyl thanks 🙏
> 
Welcome.

> Too bad it has to be done. However we just know that someone might have submitted their source code as `README.md` and made it difficult for us to do a writeup of their win. 🥇 😉

Yes indeed though that would be kind of funny. Would require the `-x c` option too.

I'm working on the txzchk fix but I'm tired enough where I might have to delay that until tomorrow :(

**Comment by lcn2** [comment]
> Ah .. I forgot to run `make all` before the test it seems. 

Feel free to revise with another pull request.  As this code has not been used, the version number can be the same, @xexyl

**Comment by xexyl** [comment]
> > Ah .. I forgot to run `make all` before the test it seems.
> 
> Feel free to revise with another pull request. As this code has not been used, the version number can be the same, @xexyl

I ended up changing the version anyway. That would have been useful to not have to though. It was just forgetting to run `make all` that caused the problem though. Thanks.

**Comment by lcn2** [comment]
> Yes indeed though that would be kind of funny. Would require the -x c option too.

C code as markdown could be fun for someone, just not as `README.md` 🤓

**Comment by xexyl** [comment]
> > Yes indeed though that would be kind of funny. Would require the -x c option too.
> 
> C code as markdown could be fun for someone, just not as `README.md` 🤓

It could indeed! Or as html. Or as I know has been done graphics.

**Pull request merged**
