### PR TITLE
Typo fix in jprint usage string

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks for the progress @xexyl

We are planning to again review the command line in more detail soon.

In the mean time we have had a request from two IOCCC winners (outside of the GitHub process) about how to
best thank those who have important contributions to the IOCCC presentation of past IOCCC winners.
We are working to centralize the recognition, and especially your numerous important contributions @xexyl,
via a single markdown file instead of scattering individual recognition throughout the many README.md files.
We agree with these IOCCC winners and think/hope you will prefer this improved way of recognizing
contributions to how the past IOCCC winners are presented.

Please continue to make progress in `jprint` while we work on implementing the centralized thank you in
the temp-test-src repo.

**Comment by xexyl** [comment]
> Thanks for the progress @xexyl
> 
> We are planning to again review the command line in more detail soon.
> 
> In the mean time we have had a request from two IOCCC winners (outside of the GitHub process) about how to best thank those who have important contributions to the IOCCC presentation of past IOCCC winners. We are working to centralize the recognition, and especially your numerous important contributions @xexyl, via a single markdown file instead of scattering individual recognition throughout the many README.md files. We agree with these IOCCC winners and think/hope you will prefer this improved way of recognizing contributions to how the past IOCCC winners are presented.
> 
I do - depending on how it's done of course and as long as Yusuke Endoh is also credited for the numerous fixes he made. I want to point out a couple others though in case you are unaware and/or forgot about them, see below.

I think it would be nicer to have the README.md files cleaner though certainly. I think it's nice to have the reasons or what was wrong but it could be simplified too (as in shortened). 

Maybe a file that's like `bugs.md` but for the fixed entries? I like that idea most I think but I'm sure you'll work it out. 

I think it would help to have the thank yous in another file too in another way: it means that the entry will remain 'clean' in the README.md file too. For instance for my winning entries I get them on a shirt but that has the code on the back and the judges' remarks on the front (with the to build, to run and try commands as well) so what would happen if that also had the other text? It'd make it much harder to have!

As far as the other fixes two files I'm aware of, one with Westley (though it's simply what you wrote in the remarks but they included it as a file so you thanked them which is nice) and another is a bug fix in the judges' remarks which I presume was done by Simon Cooper due to initials [sc]. Those are:

- 2000/briddlebane - sc, I guess Simon Cooper
- 1988/westley, Misha Dynin

I hope that's helpful and I also hope that a file like `bugs.md` in the sense of what was fixed and maybe how (where it was noted) is something you like but on the other hand the way you've done things in the past is also very nice so I'm sure it'll be fine! In the meantime I've archived my fixes 'just in case' as it's nice for myself to see what I did!

Thanks for the note and for all the appreciation! That's not why I do it but it's a nice thing for sure! I think there are other ways it'll be nice to have it all in a single file: it kind of keeps it focused and so that everyone can see it more easily - not that it's for that reason but let's be honest, it is an honour to have done these things esp some of the harder to fix entries!

Incidentally there _are_ some entries I still wonder if the fixes should be made into alt targets. I also wonder about some of the `gets()` -> `fgets()` changes. Some but not all ... there is the option also of having a script which runs each command (or tries to depending on user invocation) that simply redirects stderr to /dev/null. This of course doesn't fix the problem of linker warnings in linux. Well I will review those in time anyway.

> Please continue to make progress in `jprint` while we work on implementing the centralized thank you in the temp-test-src repo.

Will do .. hope to look at it more when a bit more awake.

**Comment by xexyl** [comment]
Unrelated here's a funny issue with GitHub:

Screenshot 2023-06-06 at 02 31 53

My guess is once I reload the page it'll figure it out. It was a tab that was open from yesterday and I've noticed the last couple days (whether that includes today or not I'm not sure now - I hardly remember the last few days :( ) that GitHub is not refreshing pages when updates are there like new comments where I'm pretty sure it had before.

**Comment by xexyl** [comment]
Oh btw in case you don't know or forgot or didn't think of it to find the fixes except the ones I already mentioned you could try:


```sh
git grep Yusuke_Endoh '*README.md'
git grep Cody_Boone_Ferguson '*README.md'
```

That will show the README.md files of the fixes documented or where something was noted by either of us. Anyway I am sure you'll work it out!

**Comment by xexyl** [comment]
Please see commit https://github.com/ioccc-src/temp-test-ioccc/pull/830/commits/a981cacbeeaeb52338dc04efbe865ccb51121b42 for a POSSIBLE start. If nothing else it includes a list of entries that were fixed or modified in some way. Some are alternate code which should I guess stay in the README.md files but I believe these are the entries that were actually changed or updated. In 2018 I was referred to by Dave Burton, in 2019 another author referred to me (I only recently discovered it) and in 2020 Ilya also thanked me so these are not in the list!

But of course I _**FULLY EXPECT**_ that there will be many changes and if you wish to reject it entirely that's okay but at least you'll have the list of entries! I also imagine (and would actually like but I had to put something in) you might change the wording. 

I do think having the problems listed is a good thing to do for instructional / educational value but if you disagree with that that's also perfectly okay! In short take it as you will but I hope that the list is at least useful. I hope also that you will write your own thank you notes but like I said I had to put something in as otherwise the file might be too vague.

I hope to work on `jprint` a little bit a bit later on but we'll see ... hope you're sleeping well! I'm going to try and rest now myself. Good day!

**Comment by lcn2** [comment]
> Please see commit https://github.com/ioccc-src/temp-test-ioccc/pull/830/commits/a981cacbeeaeb52338dc04efbe865ccb51121b42 for a POSSIBLE start. If nothing else it includes a list of entries that were fixed or modified in some way. Some are alternate code which should I guess stay in the README.md files but I believe these are the entries that were actually changed or updated. In 2018 I was referred to by Dave Burton, in 2019 another author referred to me (I only recently discovered it) and in 2020 Ilya also thanked me so these are not in the list!
> 
> 
> 
> But of course I _**FULLY EXPECT**_ that there will be many changes and if you wish to reject it entirely that's okay but at least you'll have the list of entries! I also imagine (and would actually like but I had to put something in) you might change the wording. 
> 
> 
> 
> I do think having the problems listed is a good thing to do for instructional / educational value but if you disagree with that that's also perfectly okay! In short take it as you will but I hope that the list is at least useful. I hope also that you will write your own thank you notes but like I said I had to put something in as otherwise the file might be too vague.
> 
> 
> 
> I hope to work on `jprint` a little bit a bit later on but we'll see ... hope you're sleeping well! I'm going to try and rest now myself. Good day!
> 
> 
> 
> Oh BTW: since I mostly yanked pasted there are redundant 'thank you' notes in the entries themselves. Those were supposed to be removed but I need to stop for now for not only this repo but first a break. Also I felt like the links in each entry (to the respective people fixing) should be removed but for the yank paste issue this was also not updated. Anyway the list if nothing else should be of a big help and I hope you change the top of the file so that only the information about each entry stays the same .. assuming you like that idea!
> 
> 
> 
> Now for a break - hopefully a rest included.

Please consider focusing on `jprint` and let us draft a solution to this issue  instead.

**Comment by xexyl** [comment]
> > Please see commit [ioccc-src/temp-test-ioccc@a981cac](https://github.com/ioccc-src/temp-test-ioccc/commit/a981cacbeeaeb52338dc04efbe865ccb51121b42) for a POSSIBLE start. If nothing else it includes a list of entries that were fixed or modified in some way. Some are alternate code which should I guess stay in the README.md files but I believe these are the entries that were actually changed or updated. In 2018 I was referred to by Dave Burton, in 2019 another author referred to me (I only recently discovered it) and in 2020 Ilya also thanked me so these are not in the list!
> > But of course I _**FULLY EXPECT**_ that there will be many changes and if you wish to reject it entirely that's okay but at least you'll have the list of entries! I also imagine (and would actually like but I had to put something in) you might change the wording.
> > I do think having the problems listed is a good thing to do for instructional / educational value but if you disagree with that that's also perfectly okay! In short take it as you will but I hope that the list is at least useful. I hope also that you will write your own thank you notes but like I said I had to put something in as otherwise the file might be too vague.
> > I hope to work on `jprint` a little bit a bit later on but we'll see ... hope you're sleeping well! I'm going to try and rest now myself. Good day!
> > Oh BTW: since I mostly yanked pasted there are redundant 'thank you' notes in the entries themselves. Those were supposed to be removed but I need to stop for now for not only this repo but first a break. Also I felt like the links in each entry (to the respective people fixing) should be removed but for the yank paste issue this was also not updated. Anyway the list if nothing else should be of a big help and I hope you change the top of the file so that only the information about each entry stays the same .. assuming you like that idea!
> > Now for a break - hopefully a rest included.
> 
> Please consider focusing on `jprint` and let us draft a solution to this issue instead.

No worries .. already done with it but I wanted to get the list for you.

Unfortunately though I don't think I'll manage anything else today. Just too tired. But we'll see.

**Comment by xexyl** [comment]
> > > Please see commit [ioccc-src/temp-test-ioccc@a981cac](https://github.com/ioccc-src/temp-test-ioccc/commit/a981cacbeeaeb52338dc04efbe865ccb51121b42) for a POSSIBLE start. If nothing else it includes a list of entries that were fixed or modified in some way. Some are alternate code which should I guess stay in the README.md files but I believe these are the entries that were actually changed or updated. In 2018 I was referred to by Dave Burton, in 2019 another author referred to me (I only recently discovered it) and in 2020 Ilya also thanked me so these are not in the list!
> > > But of course I _**FULLY EXPECT**_ that there will be many changes and if you wish to reject it entirely that's okay but at least you'll have the list of entries! I also imagine (and would actually like but I had to put something in) you might change the wording.
> > > I do think having the problems listed is a good thing to do for instructional / educational value but if you disagree with that that's also perfectly okay! In short take it as you will but I hope that the list is at least useful. I hope also that you will write your own thank you notes but like I said I had to put something in as otherwise the file might be too vague.
> > > I hope to work on `jprint` a little bit a bit later on but we'll see ... hope you're sleeping well! I'm going to try and rest now myself. Good day!
> > > Oh BTW: since I mostly yanked pasted there are redundant 'thank you' notes in the entries themselves. Those were supposed to be removed but I need to stop for now for not only this repo but first a break. Also I felt like the links in each entry (to the respective people fixing) should be removed but for the yank paste issue this was also not updated. Anyway the list if nothing else should be of a big help and I hope you change the top of the file so that only the information about each entry stays the same .. assuming you like that idea!
> > > Now for a break - hopefully a rest included.
> > 
> > 
> > Please consider focusing on `jprint` and let us draft a solution to this issue instead.
> 
> No worries .. already done with it but I wanted to get the list for you.
> 
> Unfortunately though I don't think I'll manage anything else today. Just too tired. But we'll see.

Actually I want you to work on this one. I think it'll be great! But having worked on the README.md files I know which ones were modified in this way.

Anyway I'll be focusing on jprint more than the other repo but if I do focus on the other repo it'll be other things like README.md formatting etc. Depends on what I have energy and time for whether it's one or the other. But I hope to work bit on jprint every day anyway. I expect I won't in the other repo.

**Pull request merged**
