### PR TITLE
Move IOCCC tools' paths to soup.h

### PR DESCRIPTION
**Pull request by xexyl**
These paths do not belong in jparse at all now that it is its own repo.
The soup.h seems to be the most appropriate place.

### CODE REVIEW

**Comment by xexyl** [comment]
Fixing then have to go ...

**Comment by xexyl** [comment]
... first have to find out the problem which means running `make release` locally.

**Comment by xexyl** [comment]
First have to find out the problem .... running `make release`.

**Comment by xexyl** [comment]
I guess what the problem is but I'm not sure .. strange thing is `make test` worked here.

**Comment by xexyl** [comment]
And it still worked. Bizarre. I have an idea what might solve it but have to see what happens here.

**Comment by xexyl** [comment]
Seems like it might have been something I wondered about. If so then it's fixed and I can go do the other things. It's taking longer so I guess it is okay.

**Review by lcn2 — APPROVED** [review]
👍

**Comment by xexyl** [comment]
> 👍

👎👈👉

... but how do I do diagonally? Let's see...

╱╲⟍⟋𒑴⋱⋰╳𒑲𒑳

**Pull request merged**
