### PR TITLE
Add extension override to fnamchk + jparse.l update

### PR DESCRIPTION
**Pull request by xexyl**
See the git log for details as for why the override will be useful. The jparse.l update is very minor.

Unfortunately it's later than I thought and I have to get going soon. I was hoping to get more done today but that seems unlikely now. Sorry!

EDIT: I forgot to say in the git log how to actually test text files in `txzchk`. It's quite simple and I built it in so I could test linux tarball listing format under macOS (though I had thought of the option prior to the discovery of different formats):

```shell
./txzchk -T ...
```

forces txzchk to use `fopen(3)` on the file instead of opening a pipe to `tar(1)`.

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks for also updating the man pages, @xexyl

**Comment by xexyl** [comment]
> Thanks for also updating the man pages, @xexyl

I do try my best to remember to update man pages when something like options change but in this case there was room for improvement elsewhere as well. 

But what’s good about that commit is we can now devise a test suite for `txzchk`. I can explain the details more if you like though I guess for now it’s probably good. Let me know.

**Comment by lcn2** [comment]
> > Thanks for also updating the man pages, @xexyl
> 
> 
> 
> I do try my best to remember to update man pages when something like options change but in this case there was room for improvement elsewhere as well. 
> 
> 
> 
> But what’s good about that commit is we can now devise a test suite for `txzchk`. I can explain the details more if you like though I guess for now it’s probably good. Let me know. 

Adding a test suite for `txzchk` is a very good idea.

While most people will just need to use `mkiocccentry`, encouraging people to run a variant of `make test`, one that does not stop on the first problem, during the `IOCCCMOCK` would be a good thing.  So adding such a test is a good thing.

The `make test` should continue as it does now: stop on 1st failure.  Running the entire test suite, sending output to a log file, reporting any problems at the end: this is best done via a shell script.  The test suite would also write useful information about versions and the environment to the log file.  On detection of a problem and/or test failure, the user would encouraged to send in a "bug report".

The question is, what make rule should added to run such a test suite script?  How about:

```sh
make chk
```

We want the rule to be something short and quick to type.

Of course, the ultimate test to add to the suite will be the test for `jparse` :-)

**Comment by xexyl** [comment]
> > > Thanks for also updating the man pages, @xexyl
> > 
> > 
> > I do try my best to remember to update man pages when something like options change but in this case there was room for improvement elsewhere as well.
> > But what’s good about that commit is we can now devise a test suite for `txzchk`. I can explain the details more if you like though I guess for now it’s probably good. Let me know.
> 
> Adding a test suite for `txzchk` is a very good idea.
> 
> While most people will just need to use `mkiocccentry`, encouraging people to run a variant of `make test`, one that does not stop on the first problem, during the `IOCCCMOCK` would be a good thing. So adding such a test is a good thing.

Here's what I'm thinking and how it could work.

First of all we might have a directory for `txzchk` like for the JSON with good and bad subdirectories (i.e. `test_JSON`).

Then a script similar to `json-test.sh` but maybe `txx-test.sh` (or whatever you see as fit) that can test the good or bad or both files. Now here's where the magic happens.

With each file in the subdirectories it can end in `.txt`: this way the files can be edited with a text editor and we don't have any destructive tarballs (and if nothing else no binary files added). Here's an example text file:

[entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt](https://github.com/ioccc-src/mkiocccentry/files/8463363/entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt)

Now I forgot to add an option to `txzchk` to make it specify the extension for `fnamchk` as well but I've just added it (not yet committed: will do this soon). Once it's merged for that file we can do:

```shell
$ ./txzchk -T -E txt entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt 
Welcome to txzchk version: 0.10 2022-03-15

Performing sanity checks on your environment ...
... environment looks OK

Performing checks on tarball ...
12345678-1234-4321-abcd-1234567890ab-2
txzchk: entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt size of 946 bytes OK
drwxr-xr-x  0 501    20          0 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/
-rw-r--r--  0 501    20       1854 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/Makefile
-rw-r--r--  0 501    20          4 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/extra2
-rw-r--r--  0 501    20       2815 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/foo
-rw-r--r--  0 501    20         61 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/prog.c
-rw-r--r--  0 501    20       2806 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/.author.json
-rw-r--r--  0 501    20       2869 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/remarks.md
-rw-r--r--  0 501    20       5235 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/bar
-rw-r--r--  0 501    20       1498 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/.info.json
-rw-r--r--  0 501    20          4 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/extra1
txzchk: entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt total size of files 17146 rounded up to 1024 multiple: 17408 OK
All checks passed.
```

That's all there is to it: exit value != 0 if there are issues. Specifying verbosity level can add some additional info (see the function: `show_txz_info()` for details.


> 
> The `make test` should continue as it does now: stop on 1st failure. Running the entire test suite, sending output to a log file, reporting any problems at the end: this is best done via a shell script. The test suite would also write useful information about versions and the environment to the log file. On detection of a problem and/or test failure, the user would encouraged to send in a "bug report".
> 

Great idea! And maybe the script that does this would run the scripts specific to each tool ?

> The question is, what make rule should added to run such a test suite script? How about:
> 
> ```shell
> make chk
> ```
> 
> We want the rule to be something short and quick to type.

That sounds reasonable yes. 

> 
> Of course, the ultimate test to add to the suite will be the test for `jparse` :-)

Indeed true and of course the `jinfochk` and `jauthchk` that `jparse` is for.

Expect a commit and pull request soon... I'm not sure what else I'll do today but this will be good. I'm hoping to be more awake to work on the parser soon so I can focus on the details you've provided in that thread. In the meantime I might do the pull request and then look at the vim spell information: first making sure to tar up my `~/.vim` entirely. Hopefully by the time I'm done with that I will be able to look at the parser. We shall see.

Hope you're having a nice sleep! Going to do a commit and pull request now...

**Comment by xexyl** [comment]
...forgot to update the man page so the pull request will be a few more minutes away. I will add an example in addition to the option.

**Comment by xexyl** [comment]
Just did a pull request with the above information on how to write a test suite for `txzchk` along with additional information (that's why it took longer to do).

I'll take a look at your vim data soon and see if I can figure out why you're having that strange problem - even if I think some of how you have it might not be necessary.

**Comment by lcn2** [comment]
> Here's what I'm thinking and how it could work.
> 
> First of all we might have a directory for txzchk like for the JSON with good and bad subdirectories (i.e. test_JSON).
> ...

Sounds good!

**Comment by xexyl** [comment]
> > Here's what I'm thinking and how it could work.
> > First of all we might have a directory for txzchk like for the JSON with good and bad subdirectories (i.e. test_JSON).
> > ...
> 
> Sounds good!

Great! I look forward to seeing what you come up with!

**Comment by xexyl** [comment]
> The question is, what make rule should added to run such a test suite script? How about:
> 
> ```shell
> make chk
> ```
> 
> We want the rule to be something short and quick to type.
> 

I do propose that we make it `chk check` so that one can type either. I'm probably more likely to use check personally but it might be that other people would prefer to use `chk`. As you say it should be easy to do. We could also add other names as well of course so that more people might end up running the checks. Of course during the IOCCCMOCK you could encourage people in the guidelines (and maybe the main website and twitter too?) to run it. And prior to the IOCCCMOCK after everything is in good order (for initial testing) you could have it on the website and twitter as well.

Just some thoughts that will matter more when things are in order to start testing.

**Comment by lcn2** [comment]
> > The question is, what make rule should added to run such a test suite script? How about:
> > ```shell
> > make chk
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We want the rule to be something short and quick to type.
> 
> I do propose that we make it `chk check` so that one can type either. I'm probably more likely to use check personally but it might be that other people would prefer to use `chk`. As you say it should be easy to do. We could also add other names as well of course so that more people might end up running the checks. Of course during the IOCCCMOCK you could encourage people in the guidelines (and maybe the main website and twitter too?) to run it. And prior to the IOCCCMOCK after everything is in good order (for initial testing) you could have it on the website and twitter as well.
> 
> Just some thoughts that will matter more when things are in order to start testing.

Added a TODO item to #87 to deal with this issue.

**Comment by xexyl** [comment]
> > > The question is, what make rule should added to run such a test suite script? How about:
> > > ```shell
> > > make chk
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > We want the rule to be something short and quick to type.
> > 
> > 
> > I do propose that we make it `chk check` so that one can type either. I'm probably more likely to use check personally but it might be that other people would prefer to use `chk`. As you say it should be easy to do. We could also add other names as well of course so that more people might end up running the checks. Of course during the IOCCCMOCK you could encourage people in the guidelines (and maybe the main website and twitter too?) to run it. And prior to the IOCCCMOCK after everything is in good order (for initial testing) you could have it on the website and twitter as well.
> > Just some thoughts that will matter more when things are in order to start testing.
> 
> Added a TODO item to #87 to deal with this issue.

Sounds good. Thanks for letting me know. I'm going to be afk for a little bit at least and then I hope to reply to the comments from yesterday. I am also hoping I can do a bit today as well. We shall see! I hope you're either having a nice sleep or you're having a good morning and had a great sleep!

**Comment by lcn2** [comment]
We plan to review [this comment above](https://github.com/ioccc-src/mkiocccentry/pull/149#issuecomment-1094901804).

**Comment by xexyl** [comment]
> We plan to review [this comment above](https://github.com/ioccc-src/mkiocccentry/pull/149#issuecomment-1094901804).

Looking forward to seeing what you come up with! If you have any additional requests for this in `txzchk` please let me know. 

I will probably be going to sleep pretty soon btw.

**Comment by lcn2** [comment]
> > > > Thanks for also updating the man pages, @xexyl
> > > 
> > > 
> > > I do try my best to remember to update man pages when something like options change but in this case there was room for improvement elsewhere as well.
> > > But what’s good about that commit is we can now devise a test suite for `txzchk`. I can explain the details more if you like though I guess for now it’s probably good. Let me know.
> > 
> > 
> > Adding a test suite for `txzchk` is a very good idea.
> > While most people will just need to use `mkiocccentry`, encouraging people to run a variant of `make test`, one that does not stop on the first problem, during the `IOCCCMOCK` would be a good thing. So adding such a test is a good thing.
> 
> Here's what I'm thinking and how it could work.
> 
> First of all we might have a directory for `txzchk` like for the JSON with good and bad subdirectories (i.e. `test_JSON`).
> 
> Then a script similar to `json-test.sh` but maybe `txz-test.sh` (or whatever you see as fit) that can test the good or bad or both files. Now here's where the magic happens.
> 
> With each file in the subdirectories it can end in `.txt`: this way the files can be edited with a text editor and we don't have any destructive tarballs (and if nothing else no binary files added). Here's an example text file:
> 
> [entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt](https://github.com/ioccc-src/mkiocccentry/files/8463363/entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt)
> 
> Now I forgot to add an option to `txzchk` to make it specify the extension for `fnamchk` as well but I've just added it (not yet committed: will do this soon). Once it's merged for that file we can do:
> 
> ```shell
> $ ./txzchk -T -E txt entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt 
> Welcome to txzchk version: 0.10 2022-03-15
> 
> Performing sanity checks on your environment ...
> ... environment looks OK
> 
> Performing checks on tarball ...
> 12345678-1234-4321-abcd-1234567890ab-2
> txzchk: entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt size of 946 bytes OK
> drwxr-xr-x  0 501    20          0 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/
> -rw-r--r--  0 501    20       1854 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/Makefile
> -rw-r--r--  0 501    20          4 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/extra2
> -rw-r--r--  0 501    20       2815 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/foo
> -rw-r--r--  0 501    20         61 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/prog.c
> -rw-r--r--  0 501    20       2806 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/.author.json
> -rw-r--r--  0 501    20       2869 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/remarks.md
> -rw-r--r--  0 501    20       5235 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/bar
> -rw-r--r--  0 501    20       1498 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/.info.json
> -rw-r--r--  0 501    20          4 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/extra1
> txzchk: entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt total size of files 17146 rounded up to 1024 multiple: 17408 OK
> All checks passed.
> ```
> 
> That's all there is to it: exit value != 0 if there are issues. Specifying verbosity level can add some additional info (see the function: `show_txz_info()` for details.

This is a very good idea.  Essentially instead of having to build malformed tarballs, use files that are effectively the output of `tar -t...` as '*.txt' files and some mode of `txzchk` that bypasses the actual `tar` command and instead works a `*.txt` file as it were the output of some `tar -t...` command.

Correct?

**Comment by xexyl** [comment]
> > > > > Thanks for also updating the man pages, @xexyl
> > > > 
> > > > 
> > > > I do try my best to remember to update man pages when something like options change but in this case there was room for improvement elsewhere as well.
> > > > But what’s good about that commit is we can now devise a test suite for `txzchk`. I can explain the details more if you like though I guess for now it’s probably good. Let me know.
> > > 
> > > 
> > > Adding a test suite for `txzchk` is a very good idea.
> > > While most people will just need to use `mkiocccentry`, encouraging people to run a variant of `make test`, one that does not stop on the first problem, during the `IOCCCMOCK` would be a good thing. So adding such a test is a good thing.
> > 
> > 
> > Here's what I'm thinking and how it could work.
> > First of all we might have a directory for `txzchk` like for the JSON with good and bad subdirectories (i.e. `test_JSON`).
> > Then a script similar to `json-test.sh` but maybe `txz-test.sh` (or whatever you see as fit) that can test the good or bad or both files. Now here's where the magic happens.
> > With each file in the subdirectories it can end in `.txt`: this way the files can be edited with a text editor and we don't have any destructive tarballs (and if nothing else no binary files added). Here's an example text file:
> > [entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt](https://github.com/ioccc-src/mkiocccentry/files/8463363/entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt)
> > Now I forgot to add an option to `txzchk` to make it specify the extension for `fnamchk` as well but I've just added it (not yet committed: will do this soon). Once it's merged for that file we can do:
> > ```shell
> > $ ./txzchk -T -E txt entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt 
> > Welcome to txzchk version: 0.10 2022-03-15
> > 
> > Performing sanity checks on your environment ...
> > ... environment looks OK
> > 
> > Performing checks on tarball ...
> > 12345678-1234-4321-abcd-1234567890ab-2
> > txzchk: entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt size of 946 bytes OK
> > drwxr-xr-x  0 501    20          0 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/
> > -rw-r--r--  0 501    20       1854 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/Makefile
> > -rw-r--r--  0 501    20          4 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/extra2
> > -rw-r--r--  0 501    20       2815 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/foo
> > -rw-r--r--  0 501    20         61 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/prog.c
> > -rw-r--r--  0 501    20       2806 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/.author.json
> > -rw-r--r--  0 501    20       2869 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/remarks.md
> > -rw-r--r--  0 501    20       5235 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/bar
> > -rw-r--r--  0 501    20       1498 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/.info.json
> > -rw-r--r--  0 501    20          4 Apr 11 10:38 12345678-1234-4321-abcd-1234567890ab-2/extra1
> > txzchk: entry.12345678-1234-4321-abcd-1234567890ab-2.1649673512.txt total size of files 17146 rounded up to 1024 multiple: 17408 OK
> > All checks passed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's all there is to it: exit value != 0 if there are issues. Specifying verbosity level can add some additional info (see the function: `show_txz_info()` for details.
> 
> This is a very good idea. Essentially instead of having to build malformed tarballs, use files that are effectively the output of `tar -t...` as '*.txt' files and some mode of `txzchk` that bypasses the actual `tar` command and instead works a `*.txt` file as it were the output of some `tar -t...` command.
> 
> Correct?
> 
> UPDATE: Assuming this is correct, we added this to the TODO list.

This is exactly correct. That was entirely the purpose of the option in the first place - to make it easy to test (and it turns out became really useful when it was discovered linux and BSD/macOS have different tar listing formats).

Instead of using a pipe to read from the output of `tar` it uses `fopen()` and `fgets()`. Then with the extension changed (defaulting to `txz`) it can pass the `fnamchk` which I added to that tool as well.

**Pull request merged**
