### PR TITLE
JSON parser updates, other fixes and man page addition

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I am aware of a bug in the code too I think.

Check this:

```shell
$ ./utf8_test 'Cody Boone Ferguson'
cody_boone_ferguson
```

Okay but what happens if you just have `_`?

```shell
$ ./utf8_test '_'
FATAL[26]: default_handle: default author handle contains unsafe chars: <_>
```

why does it convert the spaces above to `_` and then complain that `_` is unsafe when that's all that's provided? I didn't look at the code mind you and I've not given it any thought.

I'm going to do something else now and I don't expect to return to this later on today. More tomorrow I'm sure. Good day!

**Comment by xexyl** [comment]
Commit 2700242 is the last one for now and probably the day. Should have read in comments and messages but that's okay. Off to do something else. Good day!

**Comment by xexyl** [comment]
I know you’re busy with the website but wanted to say I hope everything is okay. I will probably do some more commits in a bit. Hope you’re having a nice sleep!

**Comment by xexyl** [comment]
I suspect that commit cc3173e will be the last one of the day but I think it's a good start for the parser (though as noted it's very incomplete).

**Comment by xexyl** [comment]
https://github.com/ioccc-src/mkiocccentry/pull/194/commits/b0b426c084e13597503f8145f6fbac8cafb96c97 is the last one for the day but I think you'll like it. I'll mention it in the other thread.

**Comment by lcn2** [comment]
Looks like good progress, @xexyl Thanks!

**Pull request merged**
