### PR TITLE
Fix typos (in 7c428821) causing compilation errors + other typos and foo

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I hope this makes your day Landon:

```diff
-       fwarnp(stderr, "ABCDEFG...", "\npossible insomnia detected\n");
+       fwarnp(stderr, __func__, "possible insomnia detected ... whee! :-)");
```

**Comment by xexyl** [comment]
Perhaps you remember the contents of commit https://github.com/ioccc-src/mkiocccentry/pull/299/commits/e8623a479d35e59ce50e245e3b28824fd22a2846 from 1999 ? I have shared it with some friends over the years and they always love it ... Not sure why I remembered it now.

**Comment by xexyl** [comment]
I have some other things to add to foo but I'm not sure I'll be doing those today. I have some of them prepared but I want to do it in one commit and I need stop for now. Might return to it later but this is more than likely not going to happen until tomorrow.

**Comment by xexyl** [comment]
Commit https://github.com/ioccc-src/mkiocccentry/pull/299/commits/cfb364f3990c1d00ade77735a681c855614932ec is because I just remembered it and it felt appropriate. The other things will have to be another time. Probably tomorrow.

**Comment by lcn2** [comment]
Good changes, @xexyl thanks

**Comment by xexyl** [comment]
> Good changes, @xexyl thanks

Thank you. I am happy to help! Expect more from me tomorrow. Mostly foo but maybe some other non foo stuff too. 

Getting ready to sleep in a few minutes now. Good night!

**Pull request merged**
