### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by xexyl**
The commit https://github.com/ioccc-src/mkiocccentry/commit/0ec8f81843b9c7b317950b2656497f6b59317e7f should be obvious but the other one I'll include the log here even though it's easy enough to see:

    Don't use ../dyn_array/dyn_array.h in dyn_test.h
    
    This is because when it's a separate repo there's no guarantee that the
    directory name will be dyn_array/ so it might actually fail to include
    the right file.
    
    Make depend.

As for the other things I was hoping to tackle today or start anyway - the man pages related issue. I was going to start but suddenly felt not up to it. I also have other things I need to do very soon so I probably won't get to that today. Maybe I can tomorrow. We shall see.

### CODE REVIEW

**Comment by xexyl** [comment]
Commits https://github.com/ioccc-src/mkiocccentry/pull/443/commits/19eda5091eecf5d596f795f1d4e06c205860b433 and https://github.com/ioccc-src/mkiocccentry/pull/443/commits/44021e5b8928dd1c264dd488a8191045ad054d06 will be all I'm doing for the day. Doing something else now.

**Comment by lcn2** [comment]
> Commits https://github.com/ioccc-src/mkiocccentry/pull/443/commits/19eda5091eecf5d596f795f1d4e06c205860b433 and https://github.com/ioccc-src/mkiocccentry/pull/443/commits/44021e5b8928dd1c264dd488a8191045ad054d06 will be all I'm doing for the day. Doing something else now.

Thank you @xexyl

**Comment by xexyl** [comment]
> > Commits [19eda50](https://github.com/ioccc-src/mkiocccentry/commit/19eda5091eecf5d596f795f1d4e06c205860b433) and [44021e5](https://github.com/ioccc-src/mkiocccentry/commit/44021e5b8928dd1c264dd488a8191045ad054d06) will be all I'm doing for the day. Doing something else now.
> 
> Thank you @xexyl

I'm happy to help.

I'm also happy to report that I thought of a way to simplify the man page changes for the APIs. Am thinking I'll be working on those soon but I'm not sure how much I'll get done today.

**Comment by xexyl** [comment]
> > > Commits [19eda50](https://github.com/ioccc-src/mkiocccentry/commit/19eda5091eecf5d596f795f1d4e06c205860b433) and [44021e5](https://github.com/ioccc-src/mkiocccentry/commit/44021e5b8928dd1c264dd488a8191045ad054d06) will be all I'm doing for the day. Doing something else now.
> > 
> > 
> > Thank you @xexyl
> 
> I'm happy to help.
> 
> I'm also happy to report that I thought of a way to simplify the man page changes for the APIs. Am thinking I'll be working on those soon but I'm not sure how much I'll get done today.

See https://github.com/ioccc-src/mkiocccentry/issues/275#issuecomment-1364555641 and commit (here) https://github.com/ioccc-src/mkiocccentry/pull/444/commits/7254e014f78feeafa4b0e1847b65fb89382e50d9 and the same at the dbg repo https://github.com/lcn2/dbg/pull/16/commits/fb8ba14dd42f567a8c906665d517b9f69d1873d2

**Pull request merged**
