### PR TITLE
Various updates and fixes

### PR DESCRIPTION
**Pull request by xexyl**
I am going to do something else now and I don't expect to return to this today. I'm not even sure I can get to the other comments today. We'll see but sorry if I cannot. Was a difficult night and I have a lot of other things on my mind.

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Happy to help. Going to get some food and then just take it easy a bit before I get ready for sleep.

Hope you have a great night! Hopefully tomorrow I can work on some of those comments.

Btw on Monday I have the pre-op Covid test. This unfortunately clashes with another Monday appointment which has just been rescheduled to Tuesday. This shouldn't matter but figured you might want to know. Surgery again is next Thursday at 1430. That day I almost certainly won't do anything. The next day is hard to say. It depends on a lot of factors. But most likely I will still be able to do things even if I'm a bit slower.

Anyway hopefully more from me tomorrow. I think I will try (as far as code goes) work on the `chkentry` tool next: what I mentioned some place or another earlier today (at least I think I did). 

Good day my friend!

**Comment by lcn2** [comment]
Best wishes on your test .. hope you receive a passing grade :-)

**Comment by xexyl** [comment]
> Best wishes on your test .. hope you receive a passing grade :-)

Very funny way to put it - and a much needed laugh (though I had plenty with the film I just finished .. one I've loved ever since I saw it back in the 1980s - Romancing the Stone).

I should be fine. I'm seldom out anyway and I'm very careful when I am. Got my second booster dose in April as well. 

I have some thoughts to sort through and after that I'm going to turn the laptop off and try and get some sleep.

**Pull request merged**
