### PR TITLE
Various updates, fixes and enhancements

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
It is probably not a good idea for any `make test` to trigger the building of something, let alone depending on the _all_ rule. 

The `make test` needs to that what IS now, instead of trying to change it to something else while testing. 

In general when one wants to test the code base from the source, `make clobber all test` (or of you will `make clobber all` and then `make test`) should be done.  When one wants to test the current code as it is now (perhaps in light of compilation or Makefile issues), just `make test` should be done. 

The dependency in `jparse/Makefile` of _test_ on _all_ should be regarded as a bug 🐛 not a feature 🤓. 

As such, we will accept this pull request, but that will need to change soon.

**Comment by xexyl** [comment]
> It is probably not a good idea for any `make test` to trigger the building of something, let alone depending on the _all_ rule.
> 

In that case make test is broken. Or the script that it calls is broken.

> The `make test` needs to that what IS now, instead of trying to change it to something else while testing.

> 
> In general when one wants to test the code base from the source, `make clobber all test` (or of you will `make clobber all` and then `make test`) should be done. When one wants to test the current code as it is now (perhaps in light of compilation or Makefile issues), then just `make test` should be done.
> 
That's true. One could do that. I however was testing a problem that was encountered by change in path.

> The dependency in `jparse/Makefile` of _test_ on _all_ should be regarded as a bug 🐛 not a feature 🤓.
> 

Well that's not one I changed.

> As such, we will accept this pull request, but that will need to change soon.

What would you like me to change ? I can do it but not today most likely. Tomorrow I should be able to.

**Comment by xexyl** [comment]
> > It is probably not a good idea for any `make test` to trigger the building of something, let alone depending on the _all_ rule.
> 
> In that case make test is broken. Or the script that it calls is broken.
> 


By broken I mean that the script can easily fail and cause a confusing problem. I can elaborate later or else just change what you think might be fixed including the one in jparse.

**Comment by xexyl** [comment]
.. and sorry if some of that is not clear. I'm incredibly tired. I'm just making the picky repo - well fixing the README a bit - and then will be doing things that do not take much thinking.

I'll be happy to show you what I encountered later if you like.

**Comment by lcn2** [comment]
>> The dependency in jparse/Makefile of test on all should be regarded as a bug 🐛 not a feature 🤓.
> 
> Well that's not one I changed.

Our mistake. The change was made to the top level `Makefile`, not `jparse/Makefile`. 

>> As such, we will accept this pull request, but that will need to change soon.
> 
> What would you like me to change ? I can do it but not today most likely. Tomorrow I should be able to.

After you get some **well needed rest** (best wishes on that), please remove all dependencies from test rules (including `all` and Makefiles) from all Makefiles.

**Comment by xexyl** [comment]
> > > The dependency in jparse/Makefile of test on all should be regarded as a bug 🐛 not a feature 🤓.
> > 
> > 
> > Well that's not one I changed.
> 
> Our mistake. The change was made to the top level `Makefile`, not `jparse/Makefile`.
> 

Right.

> > > As such, we will accept this pull request, but that will need to change soon.
> > 
> > 
> > What would you like me to change ? I can do it but not today most likely. Tomorrow I should be able to.
> 
> After you get some **well needed rest** (best wishes on that), please remove all dependencies from _test_ rules (including `all`, `soup/limit_ioccc.sh`, `check_man` and Makefiles) from all Makefiles.

Thank you.

But as far as removing _all_ (by which I do not mean `all` itself) dependencies from all test rules: what if this will cause an error? That was the purpose of the change in the first place. Well that's why I added `all`. I didn't add the others: I figured they were there for a reason though. Is there a reason for the change? Well it doesn't matter why I guess unless there's a change in function you're after?

> 
> Please remove remove all dependencies from _check_man_ rules in all Makefiles. All explicit calls to make check_man in test rule actions in sub-directories such as:
> 
> ```makefile
> Xxx we are editing this on our iPhone hang on ...
> ```

Will do. Probably not until tomorrow.

**Comment by xexyl** [comment]
> > > The dependency in jparse/Makefile of test on all should be regarded as a bug 🐛 not a feature 🤓.
> > 
> > 
> > Well that's not one I changed.
> 
> Our mistake. The change was made to the top level `Makefile`, not `jparse/Makefile`.
> 
> > > As such, we will accept this pull request, but that will need to change soon.
> > 
> > 
> > What would you like me to change ? I can do it but not today most likely. Tomorrow I should be able to.
> 
> After you get some **well needed rest** (best wishes on that), ... _text removed_ ...
> 
> ### UPDATE 0
> It appears you were responding to mid-level iPhone edits. Please, after you rest, review the above.
> 
> ### UPDATE 1
> Please disregard, @xexyl, the above and rest as best as you can.
> 
> See commit [bd8ddbd](https://github.com/ioccc-src/mkiocccentry/commit/bd8ddbdda8d8ea88f0d7035faadbddfbc7b25f6d) for the `make test` fix.

Thank you. I'm resting as well now but I really appreciate the concern! I was just going through some photos of my pets. I'm going to watch a film now. Thank you for taking care of the issue too.

Hope you have a great day! I'll see about opening new issues for the man pages tomorrow or the next day. I'll also look at the Makefile issue that you were wondering if I had any thoughts on tomorrow or the next day.

**Comment by xexyl** [comment]
> > > > > The dependency in jparse/Makefile of test on all should be regarded as a bug 🐛 not a feature 🤓.
> > > > 
> > > > 
> > > > Well that's not one I changed.
> > > 
> > > 
> > > Our mistake. The change was made to the top level `Makefile`, not `jparse/Makefile`.
> > 
> > 
> > Right.
> > > > > As such, we will accept this pull request, but that will need to change soon.
> > > > 
> > > > 
> > > > What would you like me to change ? I can do it but not today most likely. Tomorrow I should be able to.
> > > 
> > > 
> > > After you get some **well needed rest** (best wishes on that), please remove all dependencies from _test_ rules (including `all`, `soup/limit_ioccc.sh`, `check_man` and Makefiles) from all Makefiles.
> > 
> > 
> > Thank you.
> > But as far as removing _all_ (by which I do not mean `all` itself) dependencies from all test rules: what if this will cause an error? That was the purpose of the change in the first place. Well that's why I added `all`. I didn't add the others: I figured they were there for a reason though. Is there a reason for the change? Well it doesn't matter why I guess unless there's a change in function you're after?
> > > Please remove remove all dependencies from _check_man_ rules in all Makefiles. All explicit calls to make check_man in test rule actions in sub-directories such as:
> > > ```makefile
> > > Xxx we are editing this on our iPhone hang on ...
> > > ```
> > 
> > 
> > Will do. Probably not until tomorrow.
> 
> Please get some rest, as best as you can.
> 
Thank you kindly! I am doing so. Hope you have a great day!

**Comment by lcn2** [comment]
A deep concept that we learned back in the early days of Unix:

```
Test without impacting the code, wherever possible: for sailing out into the waters of "tests modifying test conditions" lies an ocean of confusion with many shipwrecks.
```

This concept led to the development of writing code with test frameworks built in, preferably from the very beginning, that could be triggered if needed.  It led to the development of debugging APIs and frameworks.  It let to the development of debuggers.

There is few things worse than trying to change down a "_pointer smash_" by adding printfs only to find the bug changes or goes away.

We call seeing once:

```c
    fprintf(stderr, ""); /* do not remove this line or the program will dump core! */
```

Such things are best left to the IOCCC (pun intended).  🤓

So try to test by building in the test cases into the code from the very beginning of code development.  Add more tests after you **FIND AND THEN FIX** problems to help prevent regression.  Make it easy to test.  Make it even easier to perform a full test.

This is why your work on making `make prep` and `make release` easy to view was very important!

We should have done that in the first place .. adding it in was more complicated because we did not do that from the beginning.  That was our mistake.

We should have used Makefile debuting variables in the first place .. adding them in was ore complicated because we did not do that from the beginning.  That was our mistake too.

We did a fair amount of this by using the _dbg repo_, we just didn't go far enough to make testing easier.

As they say: sorry (tm Canada 🇨🇦).

**Comment by xexyl** [comment]
> A deep concept that we learned back in the early days of Unix:
> 
> ```
> Test without impacting the code, wherever possible: for sailing out into the waters of "tests modifying test conditions" lies an ocean of confusion with many shipwrecks.
> ```
> 
> This concept led to the development of writing code with test frameworks built in, preferably from the very beginning, that could be triggered if needed. It led to the development of debugging APIs and frameworks. It let to the development of debuggers.

Of course.

> 
> There is few things worse than trying to change down a "_pointer smash_" by adding printfs only to find the bug changes or goes away.
> 
True. Which could happen if the address space changes (I'm thinking of how unless you go WAY out of bounds you will likely only corrupt part of the address space -not go out of it - so won't segfault right away which is when you'd want it to happen).


> We call seeing once:
> 
> ```c
>     fprintf(stderr, ""); /* do not remove this line or the program will dump core! */
> ```
> 
I have too but I don't know where now. It might be I saw it in a comment about funny / strange things in code. Do you know the original source of this ? It's always made me laugh and I'd love to know the source!

> Such things are best left to the IOCCC (pun intended). 🤓
> 
Of course.

> So try to test by building in the test cases into the code from the very beginning of code development. Add more tests after you **FIND AND THEN FIX** problems to help prevent regression. Make it easy to test. Make it even easier to perform a full test.
> 

Right. Which I've done I'm sure numerous times working on this repo but I know I have recently.

> This is why your work on making `make prep` and `make release` easy to view was very important!
> 
Thank you!

> We should have done that in the first place .. adding it in was more complicated because we did not do that from the beginning. That was our mistake.
> 

Well as I told you before: nobody is perfect, I am nobody, therefore I'm perfect and you're not! :-)

But seriously we're all human and we all make mistakes at times. My late grandpa liked to joke:

> There are hardly any more of us perfect people left in the world...

He was a very very funny person. My grandparents - all of them - were. Great grandmother too. I didn't know my great grandfather as much as I did my great grandmother as he died younger and they lived further away at the time. But my grandparents on my father's side - hilarious.


> We should have used Makefile debuting variables in the first place .. adding them in was ore complicated because we did not do that from the beginning. That was our mistake too.
> 
How it goes sometimes.

> We did a fair amount of this by using the _dbg repo_, we just didn't go far enough to make testing easier.

As above.

> 
> As they say: sorry (tm Canada 🇨🇦).

Or as you say: :)

**Comment by lcn2** [comment]
> I have too but I don't know where now. It might be I saw it in a comment about funny / strange things in code. Do you know the original source of this ? It's always made me laugh and I'd love to know the source!

It was _roff(1)_ in v6 Unix.

**Comment by xexyl** [comment]
> > I have too but I don't know where now. It might be I saw it in a comment about funny / strange things in code. Do you know the original source of this ? It's always made me laugh and I'd love to know the source!
> 
> It was _roff(1)_ in v6 Unix.
> 
> ### UPDATE 0
> Or maybe v5 Unix. Very early code.
> 
> ### UPDATE 1
> See [Roff Software](https://en.wikipedia.org/wiki/Roff_(software)).

Thanks!

**Comment by xexyl** [comment]
> > I have too but I don't know where now. It might be I saw it in a comment about funny / strange things in code. Do you know the original source of this ? It's always made me laugh and I'd love to know the source!
> 
> It was _roff(1)_ in v6 Unix.
> 
> ### UPDATE 0
> Or maybe v5 Unix. Very early code.
> 
> ### UPDATE 1
> See [Roff Software](https://en.wikipedia.org/wiki/Roff_(software)).

Actually this reminds me of a meme I made not too long ago .. I almost shared it on mastodon but I did not. I'll just share it here and then I'm going back to the film.

**Comment by xexyl** [comment]
you-are-a-unix-hacker-if-you-still-do-this

**Pull request merged**
