### PR TITLE
Typo fix in json_util.c

### PR DESCRIPTION
**Pull request by xexyl**
Leaving now. If this conflicts with what you're working on don't worry about it. I can always do it again or you can do it yourself - it's just one place.

Good day!

### CODE REVIEW

**Comment by xexyl** [comment]
I'm logging off now. The typo fix in the test script is important but the other one is not - it can be done later if necessary.

Good night my friend! Hope you get some sleep in the actual night today.

**Comment by lcn2** [comment]
Good catch @xexyl !

**Comment by xexyl** [comment]
Yes. It did look funny!

I'm not sure if I can get to the other comments today. I had a very difficult night last night. Woke up at least seven times and possibly more. I'm finding it very difficult to focus on anything much at all. I will reply to all the comments as soon as I can though. Sorry for delays!

**Comment by lcn2** [comment]
> Yes. It did look funny!
> 
> 
> 
> I'm not sure if I can get to the other comments today. I had a very difficult night last night. Woke up at least seven times and possibly more. I'm finding it very difficult to focus on anything much at all. I will reply to all the comments as soon as I can though. Sorry for delays!

Hope you get some better, less interrupted sleep, soon,

**Comment by xexyl** [comment]
> > Yes. It did look funny!
> > I'm not sure if I can get to the other comments today. I had a very difficult night last night. Woke up at least seven times and possibly more. I'm finding it very difficult to focus on anything much at all. I will reply to all the comments as soon as I can though. Sorry for delays!
> 
> Hope you get some better, less interrupted sleep, soon,

Thank you! 

Today was very very interesting in various ways but I hope tomorrow I can do more. 

I meant to say in my reply to your comment about surgery - thank you for sharing it with me. I really hope all is well!

I also meant to ask: is that one of the reasons the IOCCC was not run that year?

Going to get some food and then some rest a while later.

**Comment by lcn2** [comment]
> I also meant to ask: is that one of the reasons the IOCCC was not run that year?

yes

**Comment by xexyl** [comment]
> > I also meant to ask: is that one of the reasons the IOCCC was not run that year?
> 
> yes

Well I am sorry it had to happen but I am glad that you didn’t overdo it! I know how hard it can be to not do something even if you’re mentally and cognitively capable and even want to do whatever it is when your body is not able to deal with it. 

It takes a lot of will to manage that!

**Comment by lcn2** [comment]
> > > I also meant to ask: is that one of the reasons the IOCCC was not run that year?
> > 
> > 
> > yes
> 
> Well I am sorry it had to happen but I am glad that you didn’t overdo it! I know how hard it can be to not do something even if you’re mentally and cognitively capable and even want to do whatever it is when your body is not able to deal with it.
> 
> It takes a lot of will to manage that!

Thank you for your find words, @xexyl

**Comment by xexyl** [comment]
> > > > I also meant to ask: is that one of the reasons the IOCCC was not run that year?
> > > 
> > > 
> > > yes
> > 
> > 
> > Well I am sorry it had to happen but I am glad that you didn’t overdo it! I know how hard it can be to not do something even if you’re mentally and cognitively capable and even want to do whatever it is when your body is not able to deal with it.
> > It takes a lot of will to manage that!
> 
> Thank you for your find words, @xexyl

Of course my friend! I care a lot about you and I assure you that it’s not just because you’re a judge for the IOCCC (not that I think you had any doubts there but I wanted to reiterate that as I think it’s significant). 

I hope you don’t have to ever go through something like that again! 

I will let you know about surgery after I know more tomorrow. 

I hope you have a good sleep tonight. I will give my thoughts about the todo list in the commit you mentioned in the other thread a few minutes ago after I have had a sleep. Hopefully tonight will be better than last night and I can focus more. 

Something else did come up but that doesn’t make much a difference in why I didn’t feel up to doing much today. I just had a really awful night last night. Worse than usual and by quite a lot. 

Anyway good night my friend! Sleep tight when you do!

**Pull request merged**
