### PR TITLE
Add a boolean to person array in h2g2.json

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I'll be away again .. I hope I can do more tomorrow than I was able to do today as I doubt I'll be able to do anything more here today.

**Comment by lcn2** [comment]
No warnings seen during the latest GitHub CodeQL scan.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> No warnings seen during the latest GitHub CodeQL scan.

That's good!

**Comment by xexyl** [comment]
> Thanks @xexyl

You're most welcome.

**Pull request merged**
