### PR TITLE
More foo + bug fix txzchk file size conversion

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by lcn2** [comment]
Looks like in commit aaeebd0 you didn't like the colon joke, @xexyl, and so you replaced it.  Oh well.

**Comment by lcn2** [comment]
Thanks @xexyl.. just passing thru

**Comment by xexyl** [comment]
> Looks like in commit [aaeebd0](https://github.com/ioccc-src/mkiocccentry/commit/aaeebd09979b5dd1c474fd958d6a91ffd64457bb) you didn't like the colon joke, @xexyl, and so you replaced it. Oh well.

Oh no. That's not true at all! I loved it I just thought it would be fun to have it flipped as then it would be more confusing. Maybe I missed part of the joke? Anyway I had to do a merge conflict fix on my end so I reversed it again.

FWIW I laughed out loud when I first saw it. I'll do a pull request later on. I'm unable to sleep now but I hope I can in a bit.

**Comment by xexyl** [comment]
> Thanks @xexyl.. just passing thru

Hope you're having a good time abroad ?

**Comment by xexyl** [comment]
> > > Thanks @xexyl.. just passing thru
> > 
> > 
> > Hope you're having a good time abroad ?
> 
> Fun and at times, interesting, yes.

Great! Well I fixed the joke comment and now I'm going to try sleeping. Good day!

**Pull request merged**
