### PR TITLE
Add missing 'sudo' to GitHub workflow test.yml

### PR DESCRIPTION
**Pull request by xexyl**
A yank paste oversight caused this. Added sudo to the rest of the install commands that did not use sudo.

### CODE REVIEW

**Comment by xexyl** [comment]
One of the files seems to have a problem but hopefully the sudo added here will solve the error this is meant to fix.

**Review by lcn2 — APPROVED** [review]
sudo make thank you @xexyl

**Comment by xexyl** [comment]
But at least part of it failed. I wonder if installing checknr might be a mistake?

**Review by lcn2 — COMMENTED** [review]
sudo make thanks @xexyl

**Pull request merged**
