### PR TITLE
JSON debug output updates and parser fixes

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Commit 2ecc5be is probably the last one of the day - unless I find the energy later on.


Good day!

**Comment by xexyl** [comment]
About 15 minutes ago I replaced the UPS battery so the fedora box can now stay up. The commit https://github.com/ioccc-src/mkiocccentry/pull/203/commits/0384efec919931a6328b5a7f7a3bab291881adef I just pushed fixes a compilation error under fedora 36.

**Comment by xexyl** [comment]
Going afk now .. back in a bit and can reply to comments but done with programming most likely. Will watch a film I think.

Enjoy your day!

**Comment by xexyl** [comment]
Oh one more thing. Unfortunately fedora 36 has the most recent versions of both flex and bison so in order to test earlier versions after the parser is complete I will have to download the source and compile. Whether this means I will have to update the Makefile for the paths yet I'm not sure. Shouldn't be a big problem but I was hoping that I wouldn't have to do that.

**Comment by lcn2** [comment]
Thanks for this pull request and for adjusting / fixing / improving the JSON parse debugging level code, @xexyl.

**Comment by xexyl** [comment]
> Thanks for this pull request and for adjusting / fixing / improving the JSON parse debugging level code, @xexyl.

Happy to help! Going for the day now. Enjoy your evening!

**Pull request merged**
