### PR TITLE
Move oebxergfB to oebxergfB and expand oebxergfB

### PR DESCRIPTION
**Pull request by xexyl**
This required changing foo and foo plus the Makefile (make depend).

### CODE REVIEW

**Comment by xexyl** [comment]
I did in fact change the keys so I'll have to send you an updated version which as I said elsewhere is also a bug fixed version. Should I wait until you're home?

And I'm afraid that's all I'll be doing for the rest of the day here. Going to take it easy. Enjoy the rest of your day!

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Thank you as well.

Please let me know when you want me to send the updated tool and I'll do that.

**Comment by xexyl** [comment]
Oh another thing. I excluded the new header file from picky. Reason being is that there are diacritics in some of the strings.

Is there a way past this or is this okay to not have it pass picky?

**Comment by xexyl** [comment]
Ah ... must be the option `-8` which means I can put it in the less picky files list. Right?

**Comment by lcn2** [comment]
> Ah ... must be the option `-8` which means I can put it in the less picky files list. Right?

Yes

**Comment by xexyl** [comment]
> > Ah ... must be the option `-8` which means I can put it in the less picky files list. Right?
> 
> Yes

I ended up doing it as I looked at the help. ...which I see you just noticed. Thanks.

**Pull request merged**
