### PR TITLE
Add test suite for txzchk - issue #235 + bug fix jparse_test.sh and typo fixes

### PR DESCRIPTION
**Pull request by xexyl**
usage: ./txzchk_test.sh [-h] [-v level] [-D dbg_level] [-t txzchk] [-T tar]
			 [-F fnamchk] [-d txzchk_tree]

	-h				print help and exit 2
	-v level			set verbosity level for this script: (def level: 0)
	-D dbg_level			set verbosity level for tests (def: level: 0)
	-t /path/to/txzchk		path to txzchk executable (def: ./txzchk)
	-T /path/to/tar			path to tar that accepts -J option
	-F /path/to/fnamchk		path to fnamchk (def: ./fnamchk)

	-d txzchk_tree			tree where txzchk test files are to be found (def: ./test_txzchk)
					These subdirectories are expected:
					    txzchk_tree/bad
					    txzchk_tree/good

    exit codes:
	0 - all is well
	1 - at least one test failed
	2 - help mode exit
	3 - invalid command line
	>= 4 - internal error

This is very much like json_test.sh except only one tool is checked and
there's no need for a code checker either. In general text files need to
be added. However as discussed there are a couple tarballs in each of
test_txzchk/good and test_txzchk/bad.  No more tarballs need to be added
here (though a few might be); many more text files should be added. This
will help find faults in the tool.

See test_txzchk/README.md for details on the format of these files. More
could be said there; I can elaborate later if necessary.

As for the script itself there are two functions that matter:
run_txz_test which runs txzchk on tarballs and run_txt_test which runs
txzchk on text files. The key difference is that for the text file the
following has to be appended to the command line prior to the --:

     -T -E txt

This cannot be changed! The -T says to not use tar but rather read it as
a text file (you can also read it as it's test mode as it's primarily
for testing new formats and validity of tar output without having to
construct tarballs: that's what I originally implemented it for from
almost the very beginning). However the -E is needed because it modifies
the behaviour of fnamchk: otherwise fnamchk would break and it would
mean that txzchk would fail. Note that files ending in .txz.txt are not
allowed either! The default extension is txz so there's no need to
specify -E txz in the run_txz_test.

An important note on adding test files and .gitignore is that it has the
following glob:

    entry.*.tx[zt]

Which would mean -f is required to `git add'. This is important but
under test_txzchk this is negated so one should not need to add -f to
`git add` when adding to test_txzchk.

One more thing is that just like json_test.sh there is a problem in that
for some reason even if a test fails the script reports that everything
passed. I've not tried to figure out why it is in the other script and
so it's also in this script.

With the exception of this above mentioned problem and adding more test
files this resolves issue #235.

### CODE REVIEW

**Comment by xexyl** [comment]
I don't know if I'll do any of the `dbg` things today but I feel good about this one! II might be able to do a bit about `dbg` later on but right now I have some other things I have to take care of. It depends on how I feel after those things. 

Many more test files should be added. Feel free to do so! There is a bug I mentioned that is also in `json_test.sh` (which is why it's in `txzchk_test.sh` as well):

```
One more thing is that just like json_test.sh there is a problem in that
for some reason even if a test fails the script reports that everything
passed. I've not tried to figure out why it is in the other script and
so it's also in this script.
```

Hope you're feeling better today!

**Comment by xexyl** [comment]
Likely that's all I'll do today I'm afraid but it's good to get this in. Now `ioccc_test.sh` needs to call it (I guess) and more test files added.

Tomorrow I can work on `dbg` documentation and hopefully I can get a lot done. I'll start out with trying to shorten it and then add hyperlinks as I mentioned yesterday. 

Good day my friend! 

(It is possible that I do do some dbg stuff today but unlikely at this point).

**Comment by lcn2** [comment]
Interesting pull request and nice `xzchk_test.sh` test, @xexyl.

We will look at issue #238 

The `.gitignore` issue was that we had been maintaining some private malformed tarballs that we did not want to be included in the repo.  We did not want to _teach_ people about creating **toxic** tarballs by distributing them. Your use of `foo.txt` files is a much better approach.

We had some binary edited **toxic** tarballs just to see what would happen.  The modern `tar(1)` utility (the code that was a result of the _POSIX tar wars_ is MUCH more robust than the classic _tar_ and the naive _System V tar and cpio_).  We do not want to maintain our own `tar(1)` code in this repo and the modern `tar(1)` handles the job, especially when we look at the `tar -t ...` output.  

If there had been an issue with modern `tar(1)` utility, we would have filed a bug report with the appropriate teams and/or raised a CERT advisory so that vendors with `tar(1)` utility could fix it.  We were unable to compromise the integrity of the `tar(1)` utility with binary edited tarballs, so the need carrying around malformed tarballs is gone.

We can safely assume that the modern `tar(1)` utility will function correctly, and the team who is maintaining the modern `tar(1)` utility will address any issues should any arise.  Give the above, we can safely remove `entry.*.tx[zt]` from the top level `.gitignore` and eliminate the need for `test_txzchk/.gitignore` as well.   In short, testing the modern `tar(1)` utility should be beyond the scope if this repo.

In regards to `test_txzchk/*/*.txz`: We would like to keep the number of tarballs in the repo to a minimum.  Binary blobs are not fun to grep over.   One has to start treating those binary blobs in a special while doing things such as search and replace edits arcs the tree.  It is bad enough to have `.git` carry blobs, and most tools such as `rpl(1)` know enough to avoid going into the `.git` directory.  But `test_txzchk/*/*.txz is a different matter.  In short, binary blobs such as binary tarballs are an annoyance.

There is also an issue, perhaps minor, that some people scan over a repo and become concerted when they see binary blobs.  The reasons for such concerns will vary, but some people do have them.

The `test_txzchk/bad/*.txz` tarballs should be avoided.   We would prefer to use the _tar listing_ style `foo.txt` instead of carrying bad tarball binaries.  Again, we don't need to test the modern `tar(1)` utility.  Such such we recommend replacing the `test_txzchk/bad/entry.12345678-1234-4321-abcd-1234567890ab-2.1654267291.txz` binary tarball with a tar listing file such as `test_txzchk/bad/entry.12345678-1234-4321-abcd-1234567890ab-2.1654267291.txt`.  We also recomment replacing the `test_txzchk/bad/entry.test-1.1654343546.txz` binary tarball with a tar listing file such as `test_txzchk/bad/entry.test-1.1654343546.txt`.

This brings us to the question of the `test_txzchk/good/*.txz` binary tarballs.  There was the idea of having a single good binary tarball as a special test for `txzchk_test.sh`.  There is an argument, along the lines of completeness, that we might want at least 1 binary tarball.  In fact, in a moment of _not thinking about the implications_, we even suggested single good binary tarball be added: that was probably a mistake.

But the positive value of such a binary tarball test is offset by annoyance of carrying binary blobs.  We certainly don't need two `test_txzchk/good/*.txz` binary tarballs.  Can we get away with none?  Probably yes.

Overall the this pull is worthy of considering.  But perhaps with the following changes:

1. Remove `entry.*.tx[zt]` from the top level `.gitignore`
2. Delete `test_txzchk/.gitignore` 
3. Replace all `test_txzchk/bad/*.txz` tarballs with `test_txzchk/bad/*.txt` tar listing files
4. Replace all `test_txzchk/good/*.txz` tarballs with `test_txzchk/good/*.txt` tar listing files
5. Modify `txzchk_test.sh` to only work with `*.txt` tar listing files

Comments, concerns, and suggestions welcome.  In the mean time we will keep this pull request open.

**Comment by xexyl** [comment]
> Interesting pull request and nice `xzchk_test.sh` test, @xexyl.
> 
> We will look at issue #238
> 
> The `.gitignore` issue was that we had been maintaining some private malformed tarballs that we did not want to be included in the repo. We did not want to _teach_ people about creating **toxic** tarballs by distributing them. Your use of `foo.txt` files is a much better approach.
> 
> We had some binary edited **toxic** tarballs just to see what would happen. The modern `tar(1)` utility (the code that was a result of the _POSIX tar wars_ is MUCH more robust than the classic _tar_ and the naive _System V tar and cpio_). We do not want to maintain our own `tar(1)` code in this repo and the modern `tar(1)` handles the job, especially when we look at the `tar -t ...` output.
> 
> If there had been an issue with modern `tar(1)` utility, we would have filed a bug report with the appropriate teams and/or raised a CERT advisory so that vendors with `tar(1)` utility could fix it. We were unable to compromise the integrity of the `tar(1)` utility with binary edited tarballs, so the need carrying around malformed tarballs is gone.
> 
> We can safely assume that the modern `tar(1)` utility will function correctly, and the team who is maintaining the modern `tar(1)` utility will address any issues should any arise. Give the above, we can safely remove `entry.*.tx[zt]` from the top level `.gitignore` and eliminate the need for `test_txzchk/.gitignore` as well. In short, testing the modern `tar(1)` utility should be beyond the scope if this repo.
> 
> In regards to `test_txzchk/*/*.txz`: We would like to keep the number of tarballs in the repo to a minimum. Binary blobs are not fun to grep over. One has to start treating those binary blobs in a special while doing things such as search and replace edits arcs the tree. It is bad enough to have `.git` carry blobs, and most tools such as `rpl(1)` know enough to avoid going into the `.git` directory. But `test_txzchk/_/_.txz is a different matter. In short, binary blobs such as binary tarballs are an annoyance.
> 
> There is also an issue, perhaps minor, that some people scan over a repo and become concerted when they see binary blobs. The reasons for such concerns will vary, but some people do have them.
> 
> The `test_txzchk/bad/*.txz` tarballs should be avoided. We would prefer to use the _tar listing_ style `foo.txt` instead of carrying bad tarball binaries. Again, we don't need to test the modern `tar(1)` utility. Such such we recommend replacing the `test_txzchk/bad/entry.12345678-1234-4321-abcd-1234567890ab-2.1654267291.txz` binary tarball with a tar listing file such as `test_txzchk/bad/entry.12345678-1234-4321-abcd-1234567890ab-2.1654267291.txt`. We also recomment replacing the `test_txzchk/bad/entry.test-1.1654343546.txz` binary tarball with a tar listing file such as `test_txzchk/bad/entry.test-1.1654343546.txt`.
> 
> This brings us to the question of the `test_txzchk/good/*.txz` binary tarballs. There was the idea of having a single good binary tarball as a special test for `txzchk_test.sh`. There is an argument, along the lines of completeness, that we might want at least 1 binary tarball. In fact, in a moment of _not thinking about the implications_, we even suggested single good binary tarball be added: that was probably a mistake.
> 
> But the positive value of such a binary tarball test is offset by annoyance of carrying binary blobs. We certainly don't need two `test_txzchk/good/*.txz` binary tarballs. Can we get away with none? Probably yes.
> 
> Overall the this pull is worthy of considering. But perhaps with the following changes:
> 
> 1. Remove `entry.*.tx[zt]` from the top level `.gitignore`
> 2. Delete `test_txzchk/.gitignore`
> 3. Replace all `test_txzchk/bad/*.txz` tarballs with `test_txzchk/bad/*.txt` tar listing files
> 4. Replace all `test_txzchk/good/*.txz` tarballs with `test_txzchk/good/*.txt` tar listing files
> 5. Modify `txzchk_test.sh` to only work with `*.txt` tar listing files
> 
> Comments, concerns, and suggestions welcome. In the mean time we will keep this pull request open.


I only did the `txz` as you had suggested that it would be good. I can certainly update it though I was about to leave for the day.  However I will quickly do this and then commit. After that I'll be leaving for the day.

**Comment by lcn2** [comment]
p.s. to [comment 1146679103](https://github.com/ioccc-src/mkiocccentry/pull/237#issuecomment-1146679103):

We know that there are binary blobs under `test_JSON`.  We haver a plan to convert them to text using `uuencode(1)` and then have the `json_test.sh` use `uudecode(1)` before processing those test files.

That is a TBD.

**Comment by xexyl** [comment]
> p.s. to [comment 1146679103](https://github.com/ioccc-src/mkiocccentry/pull/237#issuecomment-1146679103):
> 
> We know that there are binary blobs under `test_JSON`. We haver a plan to convert them to text using `uuencode(1)` and then have the `json_test.sh` use `uudecode(1)` before processing those test files.
> 
> That is a TBD.

Good idea.

**Comment by lcn2** [comment]
> I only did the txz as you had suggested that it would be good. I can certainly update it though I was about to leave for the day. However I will quickly do this and then commit. After that I'll be leaving for the day.

Sorry (tm Canada 🇨🇦), for the extra work, we made a mistake!

We will now focus on fixing #238 and then applying our fix for #214.

**Comment by xexyl** [comment]
It's okay. I'm about to do a commit. I hope I got everything in order as I'll be leaving. If not maybe you could do it - or else I'll do it tomorrow. Though I might boot the laptop up again later today - that's not certain.

**Comment by xexyl** [comment]
There you go. I'll reply to the more detailed comments later on. Heading off now. If I missed something please let me know.

**Comment by lcn2** [comment]
Thanks @xexyl 

Looking at the odd bug #238 ... humm ...

**Comment by xexyl** [comment]
Thank you!

Good day my friend! Hope you're feeling better. Time for me to go get some food and then a bit later on sleep.

**Comment by xexyl** [comment]
> Thanks @xexyl
> 
> Looking at the odd bug #238 ... humm ...

It is indeed very odd!

**Comment by xexyl** [comment]
Maybe you could update the txzchk one too? It's the same problem.

**Comment by lcn2** [comment]
We suspect the `trap` statement may be at fault.

BTW: Should #235 be closed, or is there more to do on that issue?

**Comment by xexyl** [comment]
Anyway heading off now. Will look at replying to the longer comment later on. Feel free to add more test cases for the new script as well. I have some somewhere but I'm not sure where - I have to find them. I think I have them in a hidden directory and I didn't look much earlier on.

**Comment by xexyl** [comment]
> We suspect the `trap` statement may be at fault.
> 
> BTW: Should #235 be closed, or is there more to do on that issue?

More test files should be added I guess.

**Comment by lcn2** [comment]
> Maybe you could update the txzchk one too? It's the same problem.

You mean `txzchk` has the same bug as #235?

**Comment by xexyl** [comment]
> > Maybe you could update the txzchk one too? It's the same problem.
> 
> You mean `txzchk` has the same bug as #235?

No. I mean the `txzchk_test.sh` has the same exit code issue as the `json_test.sh` script.

**Comment by xexyl** [comment]
(Because I based it on that script.).

**Comment by xexyl** [comment]
Also those scripts don't use `trap`. Otherwise I'd think that's a great thought. But maybe we're talking two different issues.

Really going off in a moment though!

**Comment by xexyl** [comment]
> Interesting pull request and nice `xzchk_test.sh` test, @xexyl.
> 
> We will look at issue #238
> 

Thank you. 

> The `.gitignore` issue was that we had been maintaining some private malformed tarballs that we did not want to be included in the repo. We did not want to _teach_ people about creating **toxic** tarballs by distributing them. Your use of `foo.txt` files is a much better approach.

The funny thing is I thought I had added that glob and for the exact same reason! I do recall having your created malformed tarballs though and I think I still do. Would be good to convert to text as files to add under bad. Will look st that tomorrow morning hopefully. 

And yes I agree on my idea. It also makes it much easier to add files. Thing is that if you try editing a file ending with a tarball extension in vim it opens it as a tarball which makes it difficult to add text. 

There is a way theoretically:

`:set filetype=text` 

but that becomes annoying and tedious. 

> 

I do have some comments on the rest of this interesting comment but I am getting quite tired so I will keep this open in Safari on my phone to address in the morning.

**Comment by xexyl** [comment]
> We had some binary edited **toxic** tarballs just to see what would happen. The modern `tar(1)` utility (the code that was a result of the _POSIX tar wars_ is MUCH more robust than the classic _tar_ and the naive _System V tar and cpio_). We do not want to maintain our own `tar(1)` code in this repo and the modern `tar(1)` handles the job, especially when we look at the `tar -t ...` output.

The latter part makes sense. But would you mind elaborating on the rest please if you get a chance? Thank you!

**Comment by xexyl** [comment]
> If there had been an issue with modern `tar(1)` utility, we would have filed a bug report with the appropriate teams and/or raised a CERT advisory so that vendors with `tar(1)` utility could fix it. We were unable to compromise the integrity of the `tar(1)` utility with binary edited tarballs, so the need carrying around malformed tarballs is gone.
> 

About that: how did you manage to construct those bogus tarballs anyway? You used a hex editor? If so which one?

> We can safely assume that the modern `tar(1)` utility will function correctly, and the team who is maintaining the modern `tar(1)` utility will address any issues should any arise. Give the above, we can safely remove `entry.*.tx[zt]` from the top level `.gitignore` and eliminate the need for `test_txzchk/.gitignore` as well. In short, testing the modern `tar(1)` utility should be beyond the scope if this repo.

Makes sense. Though there’s the argument that having the glob in the ignore file might still be a good idea (well not the txt part) just so one isn’t accidentally committed.

**Comment by xexyl** [comment]
> In regards to `test_txzchk/*/*.txz`: We would like to keep the number of tarballs in the repo to a minimum. Binary blobs are not fun to grep over. 

Definitely true. 

> One has to start treating those binary blobs in a special while doing things such as search and replace edits arcs the tree. 

Do you mind elaborating on the ‘search and replace **edits arcs** …’ please? If you have the time. I just find your history and experiences fascinating!

It is bad enough to have `.git` carry blobs, and most tools such as `rpl(1)` know enough to avoid going into the `.git` directory. But `test_txzchk/_/_.txz is a different matter. In short, binary blobs such as binary tarballs are an annoyance.
> 

Agreed. 
> There is also an issue, perhaps minor, that some people scan over a repo and become concerted when they see binary blobs. The reasons for such concerns will vary, but some people do have them.
> 

I understand that definitely. And it might go more so for something like the IOCCC!

> The `test_txzchk/bad/*.txz` tarballs should be avoided. We would prefer to use the _tar listing_ style `foo.txt` instead of carrying bad tarball binaries. Again, we don't need to test the modern `tar(1)` utility. Such such we recommend replacing the `test_txzchk/bad/entry.12345678-1234-4321-abcd-1234567890ab-2.1654267291.txz` binary tarball with a tar listing file such as `test_txzchk/bad/entry.12345678-1234-4321-abcd-1234567890ab-2.1654267291.txt`. We also recomment replacing the `test_txzchk/bad/entry.test-1.1654343546.txz` binary tarball with a tar listing file such as `test_txzchk/bad/entry.test-1.1654343546.txt`.
> 

Well as you know I took care of this so that’s good. 

> This brings us to the question of the `test_txzchk/good/*.txz` binary tarballs. There was the idea of having a single good binary tarball as a special test for `txzchk_test.sh`. There is an argument, along the lines of completeness, that we might want at least 1 binary tarball. In fact, in a moment of _not thinking about the implications_, we even suggested single good binary tarball be added: that was probably a mistake.
> 

Makes sense. And no worries about having to modify it slightly. 


> But the positive value of such a binary tarball test is offset by annoyance of carrying binary blobs. We certainly don't need two `test_txzchk/good/*.txz` binary tarballs. Can we get away with none? Probably yes.
> 
> Overall the this pull is worthy of considering. But perhaps with the following changes:
> 
> 1. Remove `entry.*.tx[zt]` from the top level `.gitignore`
> 2. Delete `test_txzchk/.gitignore`
> 3. Replace all `test_txzchk/bad/*.txz` tarballs with `test_txzchk/bad/*.txt` tar listing files
> 4. Replace all `test_txzchk/good/*.txz` tarballs with `test_txzchk/good/*.txt` tar listing files
> 5. Modify `txzchk_test.sh` to only work with `*.txt` tar listing files
> 
> Comments, concerns, and suggestions welcome. In the mean time we will keep this pull request open.

Other than my questions above this sounds good and of course I did it almost immediately.

**Comment by lcn2** [comment]
> About that: how did you manage to construct those bogus tarballs anyway? You used a hex editor? If so which one?

In some cases `dd(1)` and `sed(1)` and `tr(1)`, in some cases a C program, in one case I resorted to `emacs(1)`.

**Comment by xexyl** [comment]
> > About that: how did you manage to construct those bogus tarballs anyway? You used a hex editor? If so which one?
> 
> In some cases `dd(1)` and `sed(1)` and `tr(1)`, in some cases a C program, in one case I resorted to `emacs(1)`.

Your expertise amazes me all the time! I have no idea how you could have possibly constructed a tarball with any of those tools except for the C program. Maybe sed allowed you to edit the binary (if say you know the tar format which I guess you might) but no idea with `dd(1)` or `tr(1)`. What is this C program? Did you write it? If so is it available? I'm just curious what it entails!

**Comment by xexyl** [comment]
As for `emacs(1)` I know very little about it except some jokes of mine like...

>  If vi is the editor of the beast then emacs must be the editor of an obese woolly mammoth.

though an obese blue whale would have been a better choice since they're bigger than any dinosaur ever known!

and:

>     If EMACS is superior to VI then why does EMACS need VI emulation ?

and another one that's hard to display here - I would have to attach a screenshot and I'd rather get to the other comments if I can (very fatigued today!).

**Comment by lcn2** [comment]
> As for `emacs(1)` I know very little about it except some jokes of mine like...
> 
> > If vi is the editor of the beast then emacs must be the editor of an obese woolly mammoth.
> 
> though an obese blue whale would have been a better choice since they're bigger than any dinosaur ever known!
> 
> and:
> 
> > ```
> > If EMACS is superior to VI then why does EMACS need VI emulation ?
> > ```
> 
> and another one that's hard to display here - I would have to attach a screenshot and I'd rather get to the other comments if I can (very fatigued today!).

`emacs` is no longer our primary editor.

**Comment by xexyl** [comment]
> > As for `emacs(1)` I know very little about it except some jokes of mine like...
> > > If vi is the editor of the beast then emacs must be the editor of an obese woolly mammoth.
> > 
> > 
> > though an obese blue whale would have been a better choice since they're bigger than any dinosaur ever known!
> > and:
> > > ```
> > > If EMACS is superior to VI then why does EMACS need VI emulation ?
> > > ```
> > 
> > 
> > and another one that's hard to display here - I would have to attach a screenshot and I'd rather get to the other comments if I can (very fatigued today!).
> 
> `emacs` is no longer our primary editor.

That's good!

**Comment by lcn2** [comment]
> > > As for `emacs(1)` I know very little about it except some jokes of mine like...
> > > > If vi is the editor of the beast then emacs must be the editor of an obese woolly mammoth.
> > > 
> > > 
> > > though an obese blue whale would have been a better choice since they're bigger than any dinosaur ever known!
> > > and:
> > > > ```
> > > > If EMACS is superior to VI then why does EMACS need VI emulation ?
> > > > ```
> > > 
> > > 
> > > and another one that's hard to display here - I would have to attach a screenshot and I'd rather get to the other comments if I can (very fatigued today!).
> > 
> > 
> > `emacs` is no longer our primary editor.
> 
> That's good!

OT: We sometimes found ourselves spending more time coding in to `emacs` editor, instead of editing the thing we needed to work on.

**Comment by xexyl** [comment]
> > > > As for `emacs(1)` I know very little about it except some jokes of mine like...
> > > > > If vi is the editor of the beast then emacs must be the editor of an obese woolly mammoth.
> > > > 
> > > > 
> > > > though an obese blue whale would have been a better choice since they're bigger than any dinosaur ever known!
> > > > and:
> > > > > ```
> > > > > If EMACS is superior to VI then why does EMACS need VI emulation ?
> > > > > ```
> > > > 
> > > > 
> > > > and another one that's hard to display here - I would have to attach a screenshot and I'd rather get to the other comments if I can (very fatigued today!).
> > > 
> > > 
> > > `emacs` is no longer our primary editor.
> > 
> > 
> > That's good!
> 
> OT: We sometimes found ourselves spending more time coding in to `emacs` editor, instead of editing the thing we needed to work on.

Well you know what they say... it's a really good OS lacking only a decent text editor.

Text editor wars are fun at least when it's only humour and not actually attacking.

A fun one for vi(m):

A great way to get a pseudo-random sequence of characters is to put an inexperienced user in insert mode and have them try and exit it.

It's true though!

**Pull request merged**
