### PR TITLE
GH-893 Fix root Makefile to pass`-m${MAKE}` to `prep.sh`; fix

### PR DESCRIPTION
**Pull request by SirWumpus**
`prep.sh` to reference `$MAKE` in place of `make`.

### CODE REVIEW

**Comment by xexyl** [comment]
FWIW: I tested this and it works ... but is it necessary to do `export` on the `MAKE` variable in the parsing of options? It doesn't matter really but it is kind of inconsistent with the rest of the script (and `MAKE` is already exported).

What did it solve on your end btw? (Since we haven't had the problem.) I guess it's so you can use gmake on your system ?

**Comment by xexyl** [comment]
Ah .. I see that is the case, for NetBSD or other systems which have to rely on `gmake`.

**Comment by xexyl** [comment]
Anyway works well (as expected but thought it might be nice to have confirmation in macOS also .. sure it's fine in linux also).

**Comment by xexyl** [comment]
I just did another couple tests, fwiw:

```sh
make MAKE=/opt/local/libexec/gnubin/make prep
```

and also:

```sh
./test_ioccc/prep.sh -m /opt/local/libexec/gnubin/make 
```

though obviously the former is the preferred way as it's cleaner: no flooding the screen of compilation etc. and you get a nice summary (that was something I was asked to do and I'm glad I was: it's MUCH nicer and much more helpful!).

I would add a space after the `-m` of course to be consistent with the rest of the command but that is less important (though I might do it anyway :-) ).

#894

**Comment by xexyl** [comment]
.. oddly adding `-m ${MAKE}` to the bug_report rules does not however work ... even though I added the option `-m` recently. But since I made the script (thanks to @SirWumpus) have the search for `gmake` first that should not be a problem .. I think.

**Review by lcn2 — COMMENTED** [review]
Thank you @SirWumpus for this pull request.

We recommend that we try this and see how it goes.

We can experiment with forcing a "deliberate failure" and see how it goes,
before reverting the that change and restoring to working order.

On a slightly related matter,
see [comment-2206988540](https://github.com/ioccc-src/temp-test-ioccc/issues/2537#issuecomment-2206988540),
and see [comment-2206996221](https://github.com/ioccc-src/temp-test-ioccc/issues/2537#issuecomment-2206996221).

We suggest we try this one in this repo and given the results think about issue #2537 for the other repo.

**Comment by xexyl** [comment]
> Thank you @SirWumpus for this pull request.
> 
> We recommend that we try this and see how it goes.
> 
> We can experiment with forcing a "deliberate failure" and see how it goes, before reverting the that change and restoring to working order.
> 
> On a slightly related matter, see [comment-2206988540](https://github.com/ioccc-src/temp-test-ioccc/issues/2537#issuecomment-2206988540), and see [comment-2206996221](https://github.com/ioccc-src/temp-test-ioccc/issues/2537#issuecomment-2206996221).
> 
> We suggest we try this one in this repo and given the results think about issue #2537 for the other repo.

I was going to suggest just making a quick formatting change (extra line or something) for testing it but I'm glad you thought of the other way, a failure. That does seem like a good idea just to make sure it doesn't cause a problem.

Thanks @SirWumpus for the work!

**Pull request merged**
