### PR TITLE
Move open_json_dir_file to open_dir_file (util.c)

### PR DESCRIPTION
**Pull request by xexyl**
As this function is useful for more than just chkentry.c and more than just JSON (though this is all it's used for currently) it has been renamed and moved to jparse/util.c.

This commit is, although useful, not critical at this time. No versions have changed because it is not clear yet what version strings should be changed and because this might not (yet) warrant a new release.

### CODE REVIEW

**Review by lcn2 — CHANGES_REQUESTED** [review]
Please update to change `MKIOCCCENTRY_REPO_VERSION` in `soup/version.h` and we will be happy to process this PR.

**Comment by xexyl** [comment]
Sure. Give me a few.

**Comment by xexyl** [comment]
Done. I'm not sure if you want it in CHANGES.md though? If so please let me know. I can do that but maybe you want to do that when you decide to make a new release out of it?

**Comment by lcn2** [comment]
> Done. I'm not sure if you want it in CHANGES.md though? If so please let me know. I can do that but maybe you want to do that when you decide to make a new release out of it?

We can go ether way: feel free to do so.

**Comment by xexyl** [comment]
Done.

**Review by lcn2 — APPROVED** [review]
Thanks @xexyl for your patience in this matter.

We will process this PR but not issue a new repo release as the changes in this PR are not critical.

**Comment by xexyl** [comment]
> Thanks @xexyl for your patience in this matter.

No problem. I think (not sure) I'm almost done with the other things but I'm not sure if I'll continue in the other repo today other than what I already did (that you processed).

> 
> We will process this PR but not issue a new repo release as the changes in this PR are not critical.

That's perfectly reasonable to me too.

**Comment by lcn2** [comment]
We were happy to do this as the change requested was not a change in behavior, unlike issue #940 where that **WILL** result in an eventual new release of the repo (and probably best for after the **Great Fork Merge**).

Nevertheless, should an emergency or critical fix become needed, the code will change.  You need to be prepared in your development branch in your repo to have to merge potential changes back into the development code.  **We don't want to make undo work for you**, so we will try to keep changes to a minimum.  Nevertheless, merging changes into a development branch is just life in development.  Please take whatever steps and/or snapshots as needed to be able to handle changes to the master branch.

**Comment by xexyl** [comment]
> We were happy to do this as the change requested was not a change in behavior, unlike issue #940 where that **WILL** result in an eventual new release of the repo (and probably best for after the **Great Fork Merge**).
> 
> Nevertheless, should an emergency or critical fix become needed, the code will change. You need to be prepared in your development branch in your repo to have to merge potential changes back into the development code. **We don't want to make undo work for you**, so we will try to keep changes to a minimum. Nevertheless, merging changes into a development branch is just life in development. Please take whatever steps and/or snapshots as needed to be able to handle changes to the master branch.

No worries and I certainly am. I'm aware it might happen. I **hope** it does not but I know full well it might in which case I'll have to merge them whether there are conflicts or not. Indeed that is part of development as you say. But I will say it's part of life in general. Things sometimes happen in ways that cause problems in other things. Of course you know this but I'm also very well aware of it, having to deal with this in many different ways over the years. Thank you for the note though! I have multiple copies (including on backup) and I also have git stash at my disposal.

I agree that that issue is better after the merge too and after the next contest too, likely.

**Comment by lcn2** [comment]
p.s. Please do not issue PRs to add new functionality against this repo based on issue #940 until that code is ready for prime time.

House cleanup such as what PR #946 did, where no real functionality was changed, is fine for future PRs until issue #940 is ready for development.  So should you see something like what this PR #946 did, feel free to submit a PR with similar changes to version numbers.  And until or unless something critical comes along to force a new repo update.

**Pull request merged**
