### PR TITLE
Add test_jparse/test_json/good/42.json test file

### PR DESCRIPTION
**Pull request by xexyl**
This file is currently in discussion and it will also be an important file to test functionality of the jprint tool.

### CODE REVIEW

**Comment by xexyl** [comment]
Hmm ... I made a mistake in doing `git commit -va`. This commit also has a comment update to the `json_search.c` file. But I forgot to do it in the header file so I'll dot hat now and make a new pull request.

**Comment by lcn2** [comment]
Thru is a perfectly cromulent word.

**Comment by xexyl** [comment]
> Thru is a perfectly cromulent word.

It's non-standard nonetheless and it was done for consistency.

**Comment by lcn2** [comment]
> > Thru is a perfectly cromulent word.
> 
> 
> 
> It's non-standard nonetheless and it was done for consistency.

[thru](https://www.thefreedictionary.com/thru) :)

**Comment by xexyl** [comment]
> > > Thru is a perfectly cromulent word.
> > 
> > 
> > 
> > It's non-standard nonetheless and it was done for consistency.
> 
> [thru](https://www.thefreedictionary.com/thru) :)

Yeah. I guess it can go without saying that often non standard English is in American English. Nite is another one. I didn't know it was even accepted in some cases until I came across it in a word game and thought it was bogus. 

Regional differences don't really matter of course. 

But I think it's good to have standard English in the repo. Probably doesn't hurt that much for most people but I am a logophile so it kind of does hurt!

(I am also a purist but I of course accept American English spelling as long as it's not my doing [0] even if it's wrong 😀)

[0] Nevertheless there are places where I also use American English particularly if it makes more sense. It happens. But except for when someone tries telling me that I spelt humour wrong by putting a U in it (which is correct) or something like that I just ignore it even when it's a word that makes me cringe. I can't explain why some do. They just do. But I won't tell people that they spelt humour wrong without the U either except jokingly. 

I wish that there weren't so many changes but at the same time it is I guess similar to culture and I think culture is very important. 

Anyway I think it's good to have through and not thru even if everyone knows what is meant. 

Well now that my novel is done I will be leaving again. I know it's not on par with LR but I tried! 😀

Good night!

**Pull request merged**
