### PR TITLE
Add pre-commit.sample hook to help with commits + add code for fast mode in hostchk.sh + initial bug_report.sh code

### PR DESCRIPTION
**Pull request by xexyl**
I want to stress this point:

```
For most people it's probably not even useful but I'm committing it for discussion and/or improvements. This might or might not be worth even having in the repo but time will tell on that.
```

If you believe this is not useful to even have a sample file this is more than okay. Just let me know and I'll close this pull request. But if you feel it's worth having in the repo we can then make adjustments / improvements etc. Just let me know. No worries on my behalf. I'll probably not make any script changes (well I have some but probably won't make commits) until you've had time to look at this so no worries on not wanting this. I'm not sure if you can only merge some commits and if so that would work too. Anyway this is the log as I wrote it:

## log below

This is completely optional! It is only useful if you'll be making major changes. There are some caveats. For example if a test fails because of a platform specific problem but you have other changes to make (but cannot fix the problem) then this script will pose a problem. In this case you can temporarily rename or delete the file under the hooks directory to disable it. For most people it's probably not even useful but I'm committing it for discussion and/or improvements. This might or might not be worth even having in the repo but time will tell on that.

Again it is not required but for those making major changes it can be useful. To install it copy 'pre-commit.sample' to
'.git/hooks/pre-commit'. That's all there is to it.

It looks like:

    #!/bin/sh
    #
    # Sample hook for pre-commit that checks if make test will pass before
    # committing. This is not required for making pull requests but it will prevent
    # having to fix any changes that are merged prior to being committed.
    #
    # To install copy this script as pre-commit to the .git/hooks subdirectory in
    # your clone of your fork.
    #
    # Again this is completely optional but recommended if you'll be making
    # significant changes. In the case that one or more tool changes because of a
    # platform specific problem or a change you did not make then this might pose a
    # problem and that is one of the reasons it is completely optional. Nevertheless
    # it can help you discover a problem with changes you made prior to committing.

    if ! make test; then

	    cat <<\EOF
    Error: Attempt to commit when make test fails.
    EOF
	    exit 1
    fi

### CODE REVIEW

**Comment by xexyl** [comment]
Bugger me. I thought of this as a possible problem but I forgot to address it. The problem with the piping the output to the log file is that I believe it's that that has the exit code so if say `make test` fails that test will not be reported as a problem if `tee` succeeds. I'm going to raise this in the other thread as well with a discussion as I think there's more than one way to address this. But for now I'm too tired to actually fix it.

**Comment by lcn2** [comment]
We do not wish to include the  pre-commit.sample file.  While we do understand that the use of this file is optional, we do not intend to use it.  In particular we do not intend to move this file into place, but rather perform a `make release` action and proceed if all is well instead.

**Comment by lcn2** [comment]
We have removed both the pre-commit.sample file and the changes to README.md documentation related to pre-commit.sample.

**Comment by xexyl** [comment]
> We do not wish to include the pre-commit.sample file. While we do understand that the use of this file is optional, we do not intend to use it. In particular we do not intend to move this file into place, but rather perform a `make release` action and proceed if all is well instead.

That's fine. That's why I specifically stressed that part that it might not be good to include. It was in case so we could at least have it. But I think I agree even.

**Comment by xexyl** [comment]
That being said I hope you didn't delete README.md entirely by mistake? Anyway I am happy to recommit all of these.

**Comment by lcn2** [comment]
> That being said I hope you didn't delete README.md entirely by mistake? Anyway I am happy to recommit all of these.

We did that by mistake .. thinking that the GitHub process was going to delete the change instead of the file.

**Comment by xexyl** [comment]
> > That being said I hope you didn't delete README.md entirely by mistake? Anyway I am happy to recommit all of these.
> 
> We did that by mistake .. thinking that the GitHub process was going to delete the change instead of the file.

Want me to close this and then recreate?

**Comment by xexyl** [comment]
Let me close this and then recreate. Give me a little bit of time.

**Comment by lcn2** [comment]
> > > That being said I hope you didn't delete README.md entirely by mistake? Anyway I am happy to recommit all of these.
> > 
> > 
> > We did that by mistake .. thinking that the GitHub process was going to delete the change instead of the file.
> 
> Want me to close this and then recreate?

yes please

**Comment by xexyl** [comment]
> > > > That being said I hope you didn't delete README.md entirely by mistake? Anyway I am happy to recommit all of these.
> > > 
> > > 
> > > We did that by mistake .. thinking that the GitHub process was going to delete the change instead of the file.
> > 
> > 
> > Want me to close this and then recreate?
> 
> yes please

Beat you to it. Give me a little bit of time.

**Comment by xexyl** [comment]
See comment https://github.com/ioccc-src/mkiocccentry/pull/363#issuecomment-1278050748.

Sorry about that again! I was trying to get to the other stuff and it was on my mind so I committed it knowing that this could be closed anyway. It's why I didn't make all the commits I have ready as well. I certainly did not expect the issue with the README! I can also see your confusion there - it seems strange that GitHub would have it that way.

Anyway leaving for now. Enjoy the rest of your day!

**Pull request closed without merging**
