### PR TITLE
New txzchk test cases and  fix log output in {json,txzchk}_test.sh

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I'll try replying to the other thread in a bit but I probably won't do any more changes today I'm afraid. Hopefully the discussion will allow me to update the `dbg` documentation though and get that done.

For now I'm taking a break.

**Comment by xexyl** [comment]
I was hoping to work on the man page of `dbg` before I left but unfortunately something came up so I'll have to look at it tomorrow. Whether it's something to include or not I don't know but it should if nothing else give an idea of what the tl;dr section might look like.

Good day! Hopefully I can really start doing more on the documentation tomorrow. I feel like the `txzchk` testing suite is for this time all done though if you want to add more files I'd welcome them.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Happy to help. 

Apparently I did not do what I normally do after pulling so I'm having a problem creating a pull request. Might have to recommit what I've done. Will figure it out and then will reply to the comments and then be done for the day probably.

**Pull request merged**
