### PR TITLE
Add check for has_nul in json_decode()

### PR DESCRIPTION
**Pull request by xexyl**
This commit is on a different branch because it's somewhat hackish and I
    might be missing something. More specifically I'm not quite sure it's
    correct. Although the has_nul is set to true if it's encoded there very
    possibly is a better way. Not only that but I might have missed some
    cases.
    
    Nevertheless with a file like:
    
        $ cat nul.json
        "test\u0000test"
    
        one will see:
    
        $ ./jparse -J 5 nul.json
        in parse_json_stream(): JSON debug[5]: calling parse_json on data block with length 17:
        in yyparse(): JSON debug[5]: under json_string: returning $json_string type: JTYPE_STRING
        JSON tree[5]:       lvl: 0  type: JTYPE_STRING      len{q0a}: 9     value:  "test\0test"
        in yyparse(): JSON debug[5]: under json_value: returning $json_value type: JTYPE_STRING
        JSON tree[5]:       lvl: 0  type: JTYPE_STRING      len{q0a}: 9     value:  "test\0test"
        in yyparse(): JSON debug[5]: under json_element: returning $json_element type: JTYPE_STRING
        JSON tree[5]:       lvl: 0  type: JTYPE_STRING      len{q0a}: 9     value:  "test\0test"
        in yyparse(): JSON debug[5]: under json: starting: json: json_element
        in yyparse(): JSON debug[5]: under json: $json_element type: JTYPE_STRING
        in yyparse(): JSON debug[5]: under json: about to perform: $json = $json_element;
        in yyparse(): JSON debug[5]: under json: returning $json_element type: JTYPE_STRING
        JSON tree[3]:       lvl: 0  type: JTYPE_STRING      len{q0a}: 9     value:  "test\0test"
        in yyparse(): JSON debug[5]: under json: about to also perform: *tree = $json;
        in yyparse(): JSON debug[5]: under json: ending: json: json_element
        in parse_json(): JSON debug[1]: valid JSON
        valid JSON
    
    This output is correct but whether anything else is missing I do not
    know. But that's why it's a separate pull request.
    
    Note that the only time has_nul != NULL is in the function
    json_conv_string().
    
    There were also some typo fixes.

### CODE REVIEW

**Comment by xexyl** [comment]
I'm not sure how this works with multiple pull requests but as I said in the other thread I'm also not sure if I'm missing something here. It does at least work but if it's entirely correct I cannot say. If I missed something please let me know and I will be happy to adjust it or if after seeing this you think of another way I will close this.

With that being said I'm shutting the laptop down and going to do something else. I hope to rest though I seriously doubt I'll be able to rest long if at all.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Oh it's good then? That's great! Want me to close the json parser issue then ?

**Comment by lcn2** [comment]
> > Thanks @xexyl
> 
> Oh it's good then? That's great! Want me to close the json parser issue then ?

Sure!

We are not sure of the questions in see #156 still need addressing given the closing of the json parser issue, however.

**Comment by xexyl** [comment]
> > > Thanks @xexyl
> > 
> > 
> > Oh it's good then? That's great! Want me to close the json parser issue then ?
> 
> Sure!
> 
> We are not sure of the questions in see #156 still need addressing given the closing of the json parser issue, however.

Well I'll close it but we can still discuss it. I think the only issue is the strange error message of `"` when it's something else that's an invalid token, right?

If that's the case we can discuss this when we have more ideas of what should happen maybe after the mock contest and before (or when) I create a separate repo.

If not you can reopen the issue (I think you can do that) or we could open a new issue for improving the parser. Just let me know. I'll close the issue now and then will be leaving for a bit.

Sleep well when you do or if you did already have a great day!

**Comment by lcn2** [comment]
> Well I'll close it but we can still discuss it. I think the only issue is the strange error message of " when it's something else that's an invalid token, right?

Correct.  Feel free to open a new issue if needed.

**Comment by xexyl** [comment]
> > Well I'll close it but we can still discuss it. I think the only issue is the strange error message of " when it's something else that's an invalid token, right?
> 
> Correct. Feel free to open a new issue if needed.

Sure. Well closing this now. Well done and congratulations again on the JSON parser! We did GREAT!

**Pull request merged**
