### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by xexyl**
The most important commit is probably https://github.com/ioccc-src/mkiocccentry/commit/235eca81e5edb5a7d900d8113177f35001de0c45 for consistency in comments (wrt json) but you might appreciate the diff for commit https://github.com/ioccc-src/mkiocccentry/commit/c38eb0efceac4582fcbc984358f677556bd50582:

```diff
7556bd50582
diff --git a/fnamchk.c b/fnamchk.c
index cd68fdf..f333557 100644
--- a/fnamchk.c
+++ b/fnamchk.c
@@ -23,10 +23,12 @@
  * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
  * PERFORMANCE OF THIS SOFTWARE.
  *
  * chongo (Landon Curt Noll, http://www.isthe.com/chongo/index.html) /\oo/\
  *
+ * "Because everyone hates when someone gets their name wrong." :-)
+ *
  * Share and enjoy! :-)
  */
```

This is probably all I'll be doing today but we'll see. Going afk now or very soon anyway. Good day and HAPPY BIRTHDAY!

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)

**Comment by xexyl** [comment]
> Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)

Very funny way of putting it!

What volcano show please? I love volcanoes as I told you once before. And have a great rest of your birthday!

**Comment by lcn2** [comment]
> > Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)
> 
> Very funny way of putting it!
> 
> What volcano show please? I love volcanoes as I told you once before. And have a great rest of your birthday!

The show has just been scheduled (by the organizer) until 2022 Nov 11 13:00 (1PM) Pacific .. sorry (tm Canada 🇨🇦).

**Comment by xexyl** [comment]
> > > Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)
> > 
> > 
> > Very funny way of putting it!
> > What volcano show please? I love volcanoes as I told you once before. And have a great rest of your birthday!
> 
> The show has just been scheduled (by the organizer) until 2022 Nov 11 13:00 (1PM) Pacific .. sorry (tm Canada 🇨🇦).

More information please?

And of course no need to explain the 24 hour clock. I wish everyone used it! Then of course they could only say all clocks are right once a day. I like to point out that not all clocks are right at least twice a day. If it's a 24 hour clock it's only once.

**Comment by xexyl** [comment]
BTW on the subject of volcanoes.. have you ever read Journey to the Centre of the Earth?

If you do though make sure you get a proper translation. Oxford publishing is a good one. I have two copies of that book because the first one is a bad translation. Has the same character named two different names in different parts of the book! When I read it I felt like I was there .. that's how it is for books with me in general but loving volcanoes made it better.

Anyway since I am pretty sure you also like science fiction if you've not read it you might enjoy it. Vernes was a great author and wrote about (iirc) things before they happened like electricity and submarines.

Well anyway happy birthday!

**Comment by lcn2** [comment]
> > > > Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)
> > > 
> > > 
> > > Very funny way of putting it!
> > > What volcano show please? I love volcanoes as I told you once before. And have a great rest of your birthday!
> > 
> > 
> > The show has just been scheduled (by the organizer) until 2022 Nov 11 13:00 (1PM) Pacific .. sorry (tm Canada 🇨🇦).
> 
> More information please?
> 
> And of course no need to explain the 24 hour clock. I wish everyone used it! Then of course they could only say all clocks are right once a day. I like to point out that not all clocks are right at least twice a day. If it's a 24 hour clock it's only once.

A "about once a month YouTube" show on the on-going eruption of the Kilauea volcano in Hawaii, plus a comment on some other volcano in the world.

**Comment by lcn2** [comment]
> BTW on the subject of volcanoes.. have you ever read Journey to the Centre of the Earth?
> 
> If you do though make sure you get a proper translation. Oxford publishing is a good one. I have two copies of that book because the first one is a bad translation. Has the same character named two different names in different parts of the book! When I read it I felt like I was there .. that's how it is for books with me in general but loving volcanoes made it better.
> 
> Anyway since I am pretty sure you also like science fiction if you've not read it you might enjoy it. Vernes was a great author and wrote about (iirc) things before they happened like electricity and submarines.
> 
> Well anyway happy birthday!

Thank you kindly.

**Comment by xexyl** [comment]
> > BTW on the subject of volcanoes.. have you ever read Journey to the Centre of the Earth?
> > If you do though make sure you get a proper translation. Oxford publishing is a good one. I have two copies of that book because the first one is a bad translation. Has the same character named two different names in different parts of the book! When I read it I felt like I was there .. that's how it is for books with me in general but loving volcanoes made it better.
> > Anyway since I am pretty sure you also like science fiction if you've not read it you might enjoy it. Vernes was a great author and wrote about (iirc) things before they happened like electricity and submarines.
> > Well anyway happy birthday!
> 
> Thank you kindly.

Of course! I think birthdays are so important and everyone should have a great great birthday! 

I hope it was a wonderful day! I will reply to the above and then shutting down. I was getting more ports updated after upgrading to Ventura but more will have to be done tomorrow.

**Comment by xexyl** [comment]
> > > > > Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)
> > > > 
> > > > 
> > > > Very funny way of putting it!
> > > > What volcano show please? I love volcanoes as I told you once before. And have a great rest of your birthday!
> > > 
> > > 
> > > The show has just been scheduled (by the organizer) until 2022 Nov 11 13:00 (1PM) Pacific .. sorry (tm Canada 🇨🇦).
> > 
> > 
> > More information please?
> > And of course no need to explain the 24 hour clock. I wish everyone used it! Then of course they could only say all clocks are right once a day. I like to point out that not all clocks are right at least twice a day. If it's a 24 hour clock it's only once.
> 
> A "about once a month YouTube" show on the on-going eruption of the Kilauea volcano in Hawaii, plus a comment on some other volcano in the world.

Link please? 

And … enjoy the rest of your birthday and sleep well when you do! Good night my friend!

**Comment by lcn2** [comment]
> > > > > > Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)
> > > > > 
> > > > > 
> > > > > Very funny way of putting it!
> > > > > What volcano show please? I love volcanoes as I told you once before. And have a great rest of your birthday!
> > > > 
> > > > 
> > > > The show has just been scheduled (by the organizer) until 2022 Nov 11 13:00 (1PM) Pacific .. sorry (tm Canada 🇨🇦).
> > > 
> > > 
> > > More information please?
> > > And of course no need to explain the 24 hour clock. I wish everyone used it! Then of course they could only say all clocks are right once a day. I like to point out that not all clocks are right at least twice a day. If it's a 24 hour clock it's only once.
> > 
> > 
> > A "about once a month YouTube" show on the on-going eruption of the Kilauea volcano in Hawaii, plus a comment on some other volcano in the world.
> 
> Link please?
> 
> And … enjoy the rest of your birthday and sleep well when you do! Good night my friend!

There will be a link created as the show managers get closer to the event.

**Comment by xexyl** [comment]
> > > > > > > Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)
> > > > > > 
> > > > > > 
> > > > > > Very funny way of putting it!
> > > > > > What volcano show please? I love volcanoes as I told you once before. And have a great rest of your birthday!
> > > > > 
> > > > > 
> > > > > The show has just been scheduled (by the organizer) until 2022 Nov 11 13:00 (1PM) Pacific .. sorry (tm Canada 🇨🇦).
> > > > 
> > > > 
> > > > More information please?
> > > > And of course no need to explain the 24 hour clock. I wish everyone used it! Then of course they could only say all clocks are right once a day. I like to point out that not all clocks are right at least twice a day. If it's a 24 hour clock it's only once.
> > > 
> > > 
> > > A "about once a month YouTube" show on the on-going eruption of the Kilauea volcano in Hawaii, plus a comment on some other volcano in the world.
> > 
> > 
> > Link please?
> > And … enjoy the rest of your birthday and sleep well when you do! Good night my friend!
> 
> There will be a link created as the show managers get closer to the event.

Thank you very much! If you remember please let me know about it!

Did you have a great birthday yesterday ? I really hope so and I am glad that I could contribute to it in part (the German cartoons and the birthday curses wish if not anything else!)!

Hope you are sleeping well. Been awake since before midnight :( there’s very very little chance of sleeping again but I hope to look at the repo in a bit. I don’t know what actually needs to be done right now but maybe I will figure out something to do! 

Anyway again I hope you’ had a great great birthday! 🎂🍩🥧🥮🧁

**Comment by lcn2** [comment]
> > > > > > > > Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)
> > > > > > > 
> > > > > > > 
> > > > > > > Very funny way of putting it!
> > > > > > > What volcano show please? I love volcanoes as I told you once before. And have a great rest of your birthday!
> > > > > > 
> > > > > > 
> > > > > > The show has just been scheduled (by the organizer) until 2022 Nov 11 13:00 (1PM) Pacific .. sorry (tm Canada 🇨🇦).
> > > > > 
> > > > > 
> > > > > More information please?
> > > > > And of course no need to explain the 24 hour clock. I wish everyone used it! Then of course they could only say all clocks are right once a day. I like to point out that not all clocks are right at least twice a day. If it's a 24 hour clock it's only once.
> > > > 
> > > > 
> > > > A "about once a month YouTube" show on the on-going eruption of the Kilauea volcano in Hawaii, plus a comment on some other volcano in the world.
> > > 
> > > 
> > > Link please?
> > > And … enjoy the rest of your birthday and sleep well when you do! Good night my friend!
> > 
> > 
> > There will be a link created as the show managers get closer to the event.
> 
> Thank you very much! If you remember please let me know about it!
> 
> Did you have a great birthday yesterday ? I really hope so and I am glad that I could contribute to it in part (the German cartoons and the birthday curses wish if not anything else!)!
> 
> Hope you are sleeping well. Been awake since before midnight :( there’s very very little chance of sleeping again but I hope to look at the repo in a bit. I don’t know what actually needs to be done right now but maybe I will figure out something to do!
> 
> Anyway again I hope you’ had a great great birthday! 🎂🍩🥧🥮🧁

Thanks .. Landon's personal firmware upgrade to v6.2 is going well.  :-)

**Comment by xexyl** [comment]
> > > > > > > > > Thanks @xexyl .. focusing on the Volcano show now, and then celebrations for Landon's v.6.2 firmware update :-)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Very funny way of putting it!
> > > > > > > > What volcano show please? I love volcanoes as I told you once before. And have a great rest of your birthday!
> > > > > > > 
> > > > > > > 
> > > > > > > The show has just been scheduled (by the organizer) until 2022 Nov 11 13:00 (1PM) Pacific .. sorry (tm Canada 🇨🇦).
> > > > > > 
> > > > > > 
> > > > > > More information please?
> > > > > > And of course no need to explain the 24 hour clock. I wish everyone used it! Then of course they could only say all clocks are right once a day. I like to point out that not all clocks are right at least twice a day. If it's a 24 hour clock it's only once.
> > > > > 
> > > > > 
> > > > > A "about once a month YouTube" show on the on-going eruption of the Kilauea volcano in Hawaii, plus a comment on some other volcano in the world.
> > > > 
> > > > 
> > > > Link please?
> > > > And … enjoy the rest of your birthday and sleep well when you do! Good night my friend!
> > > 
> > > 
> > > There will be a link created as the show managers get closer to the event.
> > 
> > 
> > Thank you very much! If you remember please let me know about it!
> > Did you have a great birthday yesterday ? I really hope so and I am glad that I could contribute to it in part (the German cartoons and the birthday curses wish if not anything else!)!
> > Hope you are sleeping well. Been awake since before midnight :( there’s very very little chance of sleeping again but I hope to look at the repo in a bit. I don’t know what actually needs to be done right now but maybe I will figure out something to do!
> > Anyway again I hope you’ had a great great birthday! 🎂🍩🥧🥮🧁
> 
> Thanks .. Landon's personal firmware upgrade to v6.2 is going well. :-)

Great to hear my good friend! I think it’s quite funny how you put it! I also think it’s excellent that you’re celebrating more than just the 24 hours! 

In my past I have also done that and in fact I often do. Also since I was a child I have had half birthdays - something my parents came up with (no idea of anyone else has them but I love having them!). 

I’m quite a bit younger than you but as I said the other day I will be 41 on 14 February. My mum is almost 10 years older than you and my dad is a bit older than that. 

Anyway I am happy it is going great! Best wishes that the upgrade doesn’t end up corrupting due to a power outage or something like that! :) though I suspect you’re like me and have several UPSes (and as for the laptop you have a different kind of battery). 

Well anyway I hope you’re sleeping well! I can’t sleep now. I will possibly shower soon and then I hope to have the laptop out after that but it might be a bit of time yet.

**Comment by xexyl** [comment]
Oh totally OT questions (that I believe are short but if they’re against time for the contest I can ask another time). 

- I noticed that you have a number named after you (I think I read that right on Twitter). I would guess it’s a prime. Mind telling me which one it is? Or did I misinterpret it?
- You’re for an independent Scotland. Just out of curiosity: are you of Scots descent? I know you know that I also am - my name kind of gives it away! :-) 

That is all for now!

**Comment by lcn2** [comment]
> I noticed that you have a number named after you?

Not aware of a "Landon's number" ... perhaps there is one that some else named?

There is the work with Conway on generating English names for numbers of any size:

- [The English name of a number](http://www.isthe.com/cgi-bin/chongo/number.cgi)
- [How high can you count?](http://www.isthe.com/chongo/tech/math/number/howhigh.html)
- [Known Mersenne Primes ](http://www.isthe.com/chongo/tech/math/prime/mersenne.html)
- [English names of the first 10000 powers of 10](http://lcn2.github.io/mersenne-english-name/tenpower/tenpower.html)

Plus some fun decimal palindrome primes:

- [proff of the Cheshire prime conjecture](https://twitter.com/landonnoll/status/1534274465919422464?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
- [smallest decimal palindrome prime with at least 10000 digits](https://twitter.com/landonnoll/status/1464360670233694208?s=20&t=DAF5PrznFa26_DmLaIPQ6g)

etc.

**Comment by lcn2** [comment]
> You’re for an independent Scotland. Just out of curiosity: are you of Scots descent? I know you know that I also am - my name kind of gives it away! :-)

Yes.  And while some remained behind in the Edinburgh region, most of the Americans came over in the 1660's from that region.  etc.

**Comment by xexyl** [comment]
> > I noticed that you have a number named after you?
> 
> Not aware of a "Landon's number" ... perhaps there is one that some else named?
> 
> There is the work with Conway on generating English names for numbers of any size:
> 
> * [The English name of a number](http://www.isthe.com/cgi-bin/chongo/number.cgi)
> * [How high can you count?](http://www.isthe.com/chongo/tech/math/number/howhigh.html)
> * [Known Mersenne Primes ](http://www.isthe.com/chongo/tech/math/prime/mersenne.html)
> * [English names of the first 10000 powers of 10](http://lcn2.github.io/mersenne-english-name/tenpower/tenpower.html)
> 
> Plus some fun decimal palindrome primes:
> 
> * [proff of the Cheshire prime conjecture](https://twitter.com/landonnoll/status/1534274465919422464?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> * [smallest decimal palindrome prime with at least 10000 digits](https://twitter.com/landonnoll/status/1464360670233694208?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> 
> etc.

Thanks for the links! I was referring to your twitter profile.

**Comment by xexyl** [comment]
> > You’re for an independent Scotland. Just out of curiosity: are you of Scots descent? I know you know that I also am - my name kind of gives it away! :-)
> 
> Yes. And while some remained behind in the Edinburgh region, most of the Americans came over in the 1660's from that region. etc.

Ah. I have roots in Perthshire.

**Comment by xexyl** [comment]
... as for the palindrome prime I love that one! I actually took a screenshot of it and imported it into my photos! I think I might have even stated that there.

**Comment by xexyl** [comment]
And as for the English name of a number: that's a fun one. I have pointed out to people that million can be two different numbers depending on where you are. They didn't like me saying it. But then they probably also didn't appreciate that I told them they didn't know the basics of percentages right either.

It's amazing how many people don't understand that it's based on another number (the word 'per' somehow escapes them ... and in British English of course per cent is two words). I've had people try telling me that 200% is not possible but that's of course nonsense because yes it is possible.

**Comment by lcn2** [comment]
> > > I noticed that you have a number named after you?
> > 
> > 
> > Not aware of a "Landon's number" ... perhaps there is one that some else named?
> > There is the work with Conway on generating English names for numbers of any size:
> > 
> > * [The English name of a number](http://www.isthe.com/cgi-bin/chongo/number.cgi)
> > * [How high can you count?](http://www.isthe.com/chongo/tech/math/number/howhigh.html)
> > * [Known Mersenne Primes ](http://www.isthe.com/chongo/tech/math/prime/mersenne.html)
> > * [English names of the first 10000 powers of 10](http://lcn2.github.io/mersenne-english-name/tenpower/tenpower.html)
> > 
> > Plus some fun decimal palindrome primes:
> > 
> > * [proff of the Cheshire prime conjecture](https://twitter.com/landonnoll/status/1534274465919422464?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> > * [smallest decimal palindrome prime with at least 10000 digits](https://twitter.com/landonnoll/status/1464360670233694208?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> > 
> > etc.
> 
> Thanks for the links! I was referring to your twitter profile.

The text _English name of a number_ refers to the above mentioned tool.

Nevertheless if someone does name _Landon's number_ we hope it is a fun prime.

**Comment by xexyl** [comment]
> > > > I noticed that you have a number named after you?
> > > 
> > > 
> > > Not aware of a "Landon's number" ... perhaps there is one that some else named?
> > > There is the work with Conway on generating English names for numbers of any size:
> > > 
> > > * [The English name of a number](http://www.isthe.com/cgi-bin/chongo/number.cgi)
> > > * [How high can you count?](http://www.isthe.com/chongo/tech/math/number/howhigh.html)
> > > * [Known Mersenne Primes ](http://www.isthe.com/chongo/tech/math/prime/mersenne.html)
> > > * [English names of the first 10000 powers of 10](http://lcn2.github.io/mersenne-english-name/tenpower/tenpower.html)
> > > 
> > > Plus some fun decimal palindrome primes:
> > > 
> > > * [proff of the Cheshire prime conjecture](https://twitter.com/landonnoll/status/1534274465919422464?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> > > * [smallest decimal palindrome prime with at least 10000 digits](https://twitter.com/landonnoll/status/1464360670233694208?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> > > 
> > > etc.
> > 
> > 
> > Thanks for the links! I was referring to your twitter profile.
> 
> The text _English name of a number_ refers to the above mentioned tool.

Ahh right. Well that makes sense too. I have seen those documents before! They're fun.

> 
> Nevertheless if someone does name _Landon's number_ we hope it is a fun prime.

Of course! I would hope so too. Or pi. I mean who doesn't want more pi(e) ? :-)

**Comment by lcn2** [comment]
> > > > > I noticed that you have a number named after you?
> > > > 
> > > > 
> > > > Not aware of a "Landon's number" ... perhaps there is one that some else named?
> > > > There is the work with Conway on generating English names for numbers of any size:
> > > > 
> > > > * [The English name of a number](http://www.isthe.com/cgi-bin/chongo/number.cgi)
> > > > * [How high can you count?](http://www.isthe.com/chongo/tech/math/number/howhigh.html)
> > > > * [Known Mersenne Primes ](http://www.isthe.com/chongo/tech/math/prime/mersenne.html)
> > > > * [English names of the first 10000 powers of 10](http://lcn2.github.io/mersenne-english-name/tenpower/tenpower.html)
> > > > 
> > > > Plus some fun decimal palindrome primes:
> > > > 
> > > > * [proff of the Cheshire prime conjecture](https://twitter.com/landonnoll/status/1534274465919422464?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> > > > * [smallest decimal palindrome prime with at least 10000 digits](https://twitter.com/landonnoll/status/1464360670233694208?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> > > > 
> > > > etc.
> > > 
> > > 
> > > Thanks for the links! I was referring to your twitter profile.
> > 
> > 
> > The text _English name of a number_ refers to the above mentioned tool.
> 
> Ahh right. Well that makes sense too. I have seen those documents before! They're fun.
> 
> > Nevertheless if someone does name _Landon's number_ we hope it is a fun prime.
> 
> Of course! I would hope so too. Or pi. I mean who doesn't want more pi(e) ? :-)

... more of an integer person actually :)

**Comment by xexyl** [comment]
> > > > > > I noticed that you have a number named after you?
> > > > > 
> > > > > 
> > > > > Not aware of a "Landon's number" ... perhaps there is one that some else named?
> > > > > There is the work with Conway on generating English names for numbers of any size:
> > > > > 
> > > > > * [The English name of a number](http://www.isthe.com/cgi-bin/chongo/number.cgi)
> > > > > * [How high can you count?](http://www.isthe.com/chongo/tech/math/number/howhigh.html)
> > > > > * [Known Mersenne Primes ](http://www.isthe.com/chongo/tech/math/prime/mersenne.html)
> > > > > * [English names of the first 10000 powers of 10](http://lcn2.github.io/mersenne-english-name/tenpower/tenpower.html)
> > > > > 
> > > > > Plus some fun decimal palindrome primes:
> > > > > 
> > > > > * [proff of the Cheshire prime conjecture](https://twitter.com/landonnoll/status/1534274465919422464?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> > > > > * [smallest decimal palindrome prime with at least 10000 digits](https://twitter.com/landonnoll/status/1464360670233694208?s=20&t=DAF5PrznFa26_DmLaIPQ6g)
> > > > > 
> > > > > etc.
> > > > 
> > > > 
> > > > Thanks for the links! I was referring to your twitter profile.
> > > 
> > > 
> > > The text _English name of a number_ refers to the above mentioned tool.
> > 
> > 
> > Ahh right. Well that makes sense too. I have seen those documents before! They're fun.
> > > Nevertheless if someone does name _Landon's number_ we hope it is a fun prime.
> > 
> > 
> > Of course! I would hope so too. Or pi. I mean who doesn't want more pi(e) ? :-)
> 
> ... more of an integer person actually :)

Well I think the number pi is not as pretty as an integer as well but can you eat an integer ? :-)

I suppose you could and let's go further by calling it a chocolate int! :-)

```c

void eat(int chocolate)
{
    while (chocolate > 0) --chocolate;

    /* The rule is 'don't panic' but how can we not panic with no chocolate left ? :-) */
}

```

Or something like that :-) did not actually write it in an editor or anything so maybe I made a typo or mistake that I missed. If I did my excuse is I'm dead tired.

**Comment by xexyl** [comment]
> > > Ahh right. Well that makes sense too. I have seen those documents before! They're fun.
> > > > Nevertheless if someone does name _Landon's number_ we hope it is a fun prime.
> > > 
> > > 
> > > Of course! I would hope so too. Or pi. I mean who doesn't want more pi(e) ? :-)
> > 
> > 
> > ... more of an integer person actually :)
> 
> Well I think the number pi is not as pretty as an integer as well but can you eat an integer ? :-)
> 
> I suppose you could and let's go further by calling it a chocolate int! :-)
> 
> ```c
> void eat(int chocolate)
> {
>     while (chocolate > 0) --chocolate;
> 
>     /* The rule is 'don't panic' but how can we not panic with no chocolate left ? :-) */
> }
> ```
> 
> Or something like that :-) did not actually write it in an editor or anything so maybe I made a typo or mistake that I missed. If I did my excuse is I'm dead tired.

This idea popped into my head yesterday as a new quote that I'll eventually add to my own fortune file:

> I love pie but I also love whole numbers and whole pies a lot more than pi - partially eaten pies (with the possible exception being if I'm the one who ate it). So what can we do about this fattening but oh so delicious problem? We multiply it by 100 and then it becomes 314.00, the whole pi(e).

When I thought of it I thought of this thread too but I wasn't at a place where I could say anything and I had to find it too.

I'll be shutting the laptop down soon and I hope to rest. I know my body will not let me rest just yet but I'm hoping I'll be able to soon. Anyway I did a nice pull request earlier. Until next time!

**Pull request merged**
