### PR TITLE
Sync jparse/ from jparse repo

### PR DESCRIPTION
**Pull request by xexyl**
This adds a new utility function that will be used in required updates for chkentry(1) post IOCCC28 and updates the util test code (which tests the new function).

A minor change in the jstrencode.1 man page was also done though wording might be needing in fixing (that can come another time however as other changes might be required).

### CODE REVIEW

**Comment by xexyl** [comment]
Ah .. missed an arg. Let me fix real quick. Hope I have time. Otherwise in a while.

**Comment by lcn2** [comment]
Waiting for you to fix the "too few args" issue.

**Comment by xexyl** [comment]
Hmm .. conflicting files how? And how do you enable that test btw? I tried to see but didn't seem to find it or be able to enable it.

**Comment by xexyl** [comment]
Okay will have to fix in a bit. Sorry!

**Comment by lcn2** [comment]
> Hmm .. conflicting files how? And how do you enable that test btw? I tried to see but didn't seem to find it or be able to enable it.

It is one of the security workflows.  See `.github/workflows/codeql.yml`

**Comment by lcn2** [comment]
We will wait until you resolve the merge conflict.  It is probably better if you do that on your end.

**Comment by lcn2** [comment]
We have to shower and pack up the hotel room for a checkout.  Will come back in about an hour or so.

**Comment by xexyl** [comment]
> > Hmm .. conflicting files how? And how do you enable that test btw? I tried to see but didn't seem to find it or be able to enable it.
> 
> It is one of the security workflows. See `.github/workflows/codeql.yml`

Could have sworn I had it .. will check in a while.

**Comment by xexyl** [comment]
> We will wait until you resolve the merge conflict. It is probably better if you do that on your end.

I will. Strange problem though .. I just copied the new file over and committed it yet it has the merge conflict ? I have to go afk now ..

Safe travels!

**Comment by xexyl** [comment]
Hopefully this solves it now ...

**Review by lcn2 — APPROVED** [review]
✅

**Comment by xexyl** [comment]
All good!

**Pull request merged**
