### PR TITLE
Add -e switch to mkiocccentry for txzchk

### PR DESCRIPTION
**Pull request by xexyl**
The mkiocccentry_test.sh script always uses this option to simplify
things and because the ones who run it most often (or make prep or make
release, the latter of which was run) appreciate the option as well (and
it's quicker to do which allows getting to other more important things).

MKIOCCCENTRY_VERSION changed to "1.0.7 2024-07-12".

Man page mkiocccentry.1 updated.

### CODE REVIEW

**Review by lcn2 — APPROVED** [review]
Thank you  @xexyl

**Comment by lcn2** [comment]
# QUESTION 

Why do we have to approve the 2 actions in order their them to run?

As you see below, we had to click ((Approve and run)) to get them to start:

image

Also when you submit a pull request are there any actions that automatically run or actions you must explicitly execute?

**Comment by xexyl** [comment]
> # QUESTION
> Why do we have to approve the 2 actions in order their them to run?
> 
> As you see below, we had to click ((Approve and run)) to get them to start:
> 
> image
> 
> Also when you submit a pull request are there any actions that automatically run or actions you must explicitly execute?

The strange thing is the other repo does do that automatically but this one does not. In the other issue, the one that talks about adding these workflows, I linked to a document that might help. 

What is also strange is the first time this was set up here I could have sworn when I did a pull request it started automatically on my fork but yesterday I did not see it and I don't think I did today either. 

It's good that adding the changes in the Makefile solved this though. Hopefully this was a good idea, to have GitHub ensure that the backup files were updated. But I wonder if there might be a way to only have it done if they are not updated. I wonder .. probably some dependency. But doesn't `make release` always rebuild the parser files? Been a long time since I looked into the `prep.sh` script. If it was some dependency though would it perhaps prevent the rest from running? Maybe but I don't know.

**Comment by xexyl** [comment]
that being said it doesn't appear like this pull request was merged? Or is it GitHub lag ?

**Comment by lcn2** [comment]
> that being said it doesn't appear like this pull request was merged? Or is it GitHub lag ?

We were waiting for the checks to complete. 

In general we have been trying to go thru the "GitHub review" procedure that one is presented by GitHub.  Next there are the checks that annoyingly have to be manually approved.  Then we can do the merge. 

The "GitHub review" procedure generates a review comment that you can see. The lag is because we then gave to click ((Approve and run)) and then wait for the feedback before doing the merge.

**Comment by xexyl** [comment]
> > that being said it doesn't appear like this pull request was merged? Or is it GitHub lag ?
> 
> We were waiting for the checks to complete.
> 
> In general we have been trying to go thru the "GitHub review" procedure that one is presented by GitHub. Next there are the checks that annoyingly have to be manually approved. Then we can do the merge.
> 
> The "GitHub review" procedure generates a review comment that you can see. The lag is because we then gave to click ((Approve and run)) and then wait for the feedback before doing the merge.

No worries .. just wanted to be sure. Strange that this repo does not do it automatically but the other does. But see the comment I linked to. I must leave for a bit now but I think I can do a bit more when back. It might be that I'm not gone for very long at all even though in about an hour to an hour and a half I will be gone for a bit to get some food.

**Pull request merged**
