### PR TITLE
Various updates, fixes and clean up

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
I couldn't stop myself. I had to fix the typo in the commit. I'm done for the day now though. More from me tomorrow!

**Comment by lcn2** [comment]
Thank you for helping us rid this repo of typos (many which we ourselves put in, sadly), @xexyl

**Comment by lcn2** [comment]
> > Thank you for helping us rid this repo of typos (many which we ourselves put in, sadly), @xexyl
> 
> No worries. It's true my eyes do zoom in on typos usually but vim can help as well. I have configured in `.vimrc`:
> 
> ```viml
> lang en_GB                      " One Language to Rule them All.
> set spell spelllang=en_gb ai nosmartindent formatoptions=crj
> ```
> 
> But of course you could change the language and format options (I do in fact have different format options based on the file type but that's the starting point). Then to add a word to the dictionary `zg` and then to jump to the next typo `]s` and the previous one `[s`. But then with a language set up it highlights words that are not spelt correctly as well as regional words etc.:
> 
> ```viml
> hi! spellbad term=bold ctermfg=red cterm=bold ctermbg=0
> hi! spellcap term=bold cterm=bold ctermfg=lightblue ctermbg=0
> hi! spellrare ctermbg=0 cterm=bold ctermfg=green
> hi! spelllocal ctermbg=0  cterm=bold ctermfg=green
> ```
> 
> But obviously you can have different colours etc.

Thanks!  Will try:

```vimdc
" set languge
lang en_US
" set spelling options
"
" Add a word to the dictionary: zg
" Remove a dictionary word: zug
" Jump to the next typo: ]s
" Jump to the prev typo: [s
:set spell spelllang=en_us
highlight spellbad term=bold ctermfg=red cterm=bold ctermbg=0
highlight spellcap term=bold cterm=bold ctermfg=lightblue ctermbg=0
highlight spellrare ctermbg=0 cterm=bold ctermfg=green
highlight spelllocal ctermbg=0  cterm=bold ctermfg=green
```

We used the above to discover a few typos in mkiocccentry.c that were fixed in commit 2b8b7e568348725c6576e334a906b15189a14e6b

Obviously it takes a bit of up front work to train the dictionary to not object to C.

Any other `vimrc(1)` spelling advice would be welcome.

**Comment by xexyl** [comment]
> > > Thank you for helping us rid this repo of typos (many which we ourselves put in, sadly), @xexyl
> > 
> > 
> > No worries. It's true my eyes do zoom in on typos usually but vim can help as well. I have configured in `.vimrc`:
> > ```viml
> > lang en_GB                      " One Language to Rule them All.
> > set spell spelllang=en_gb ai nosmartindent formatoptions=crj
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But of course you could change the language and format options (I do in fact have different format options based on the file type but that's the starting point). Then to add a word to the dictionary `zg` and then to jump to the next typo `]s` and the previous one `[s`. But then with a language set up it highlights words that are not spelt correctly as well as regional words etc.:
> > ```viml
> > hi! spellbad term=bold ctermfg=red cterm=bold ctermbg=0
> > hi! spellcap term=bold cterm=bold ctermfg=lightblue ctermbg=0
> > hi! spellrare ctermbg=0 cterm=bold ctermfg=green
> > hi! spelllocal ctermbg=0  cterm=bold ctermfg=green
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But obviously you can have different colours etc.
> 
> Thanks! Will try:
> 
> ```
> " set languge
> lang en_US
> " set spelling options
> "
> " Add a word to the dictionary: zg
> " Remove a dictionary word: zug
> " Jump to the next typo: ]s
> " Jump to the prev typo: [s
> :set spell spelllang=en_us
> highlight spellbad term=bold ctermfg=red cterm=bold ctermbg=0
> highlight spellcap term=bold cterm=bold ctermfg=lightblue ctermbg=0
> highlight spellrare ctermbg=0 cterm=bold ctermfg=green
> highlight spelllocal ctermbg=0  cterm=bold ctermfg=green
> ```
> 
> We used the above to discover a few typos in mkiocccentry.c that were fixed in commit [2b8b7e5](https://github.com/ioccc-src/mkiocccentry/commit/2b8b7e568348725c6576e334a906b15189a14e6b)
> 
> Obviously it takes a bit of up front work to train the dictionary to not object to C.

Yes it does indeed. I've done that ages ago though so for me it's not really an issue. I'd offer my file but it would have all sorts of other things as well that aren't related to C (some are German since I never could get German and English to work well in vim though I didn't try very hard either; others are things in Tolkien's Legendarium and others are things you wouldn't know about at all).

> Any other `vimrc(1)` spelling advice would be welcome.

Nothing comes to mind except do:

```
:help mkspell
```

You could more easily, perhaps, import a bunch of names and C keywords into your language file. For example you could take a list of the C keywords/etc. (one per line) and then use the command to update the file.

If I were to do that I would update the file:

`~/.vim/spell/en.utf-8.add`

and then use `:mkspell!` on the file `en.utf-8.add.spl` and then I would (I'm not sure if this is necessary though) close vim and then the next time open it it should be good. You could always test it by opening the file again and verifying that no misspelt words are there (the one without the `.spl` at the end).

```
                                                        *:mksp* *:mkspell*
:mksp[ell][!] [-ascii] {outname} {inname} ...
                        Generate a Vim spell file from word lists.  Example: >
                :mkspell /tmp/nl nl_NL.words
<                                                               *E751*
                        When {outname} ends in ".spl" it is used as the output
                        file name.  Otherwise it should be a language name,
                        such as "en", without the region name.  The file
                        written will be "{outname}.{encoding}.spl", where
                        {encoding} is the value of the 'encoding' option.

                        When the output file already exists [!] must be used
                        to overwrite it.

                        When the [-ascii] argument is present, words with 
                        non-ascii characters are skipped.  The resulting file
                        ends in "ascii.spl".

[...]
```

That's all I can think of atm. I'll reply to the other comment you just made and then that's probably all I'll do for the day.

**Comment by xexyl** [comment]
Oh as for the spell file having utf8 it might be because I also have in the `.vimrc`:

```vim
set encoding=utf8
```

So you might want to set that too if you don't already have it set.

**Comment by xexyl** [comment]
BTW: I know you use American English so I've kept American English spelling as you (and any others) have it but when I'm writing something I use British English so we'll both see highlights from `spelllocal` option.

**Comment by lcn2** [comment]
The following is our common `~/.vimrc` file that we use across many systems that have vim.
It contains a number of comments to try and help us understand / remember some things it does.

Comments, corrections, and suggestions are welcome @xexyl:

```vim
" Set language for messages - required for Debian
:language messages en_US.UTF-8
" set UTF-8 encoding
:set encoding=utf8
" Enable autoindent
:set ai
" Set shift width to 4
:set sw=4
" Declare the tags file as tags
"
" CTRL-]		  Jump to definition of the keyword under cursor
" :[count]ta[g] {name}	  Jump to the count definition of {name}
" :[count]ta[g]! {regexp} Jump to the count definition of {regexp} pattern
:set tags=tags
" Enable vim dark mode
:set bg=dark
" Ignore case in searches
"
" NOTE: Can be overruled by using "\c" or "\C" in the pattern
:set ic
" Set smart case
:set scs
" format current paragraph
map  }!{fmt
" spell check current line
map  !!ispell -a
" trim trailing whitespace
map  :%s/\s\+$//e
" look for spaces before a tab
map  /  *
" fix use from update area lines in ~/NOTES/installed.txt
map  $F:Wmm$T/d`m:s/\s\+$//e
" turn on syntax coloring and detection
syntax on
" handy to scroll between open windows
map <F6> w
" No key pressing -- focus-follows-mouse for gvim
:set mousefocus
" Enable search highlighting
"
" NOTE: Disable search highlighting by using :nohlsearch
:set hlsearch
" Enable incremental searches
:set incsearch
" Set windows title to filename
:set titlestring=%t
" Display the title
:set title
" Display cursor position
:set ruler
" Highlight trailing spaces
:let c_space_errors = 1
" set spelling options
"
" Add a word to the dictionary: zg
" Remove a dictionary word: zug
" Jump to the next typo: ]s
" Jump to the prev typo: [s
:set spell spelllang=en_us
highlight spellbad term=bold ctermfg=red cterm=bold ctermbg=0
highlight spellcap term=bold cterm=bold ctermfg=lightblue ctermbg=0
highlight spellrare ctermbg=0 cterm=bold ctermfg=green
highlight spelllocal ctermbg=0  cterm=bold ctermfg=green
" special spell check setting for git commit Filetype
"
" These settings only apply when editing a gitcommit Filetype
" such as .git/COMMIT_EDITMSG
autocmd! Filetype gitcommit setlocal textwidth=72 formatoptions=jt spell spelllang=en_us noai nosmartindent
" Enable search magic
"
"	\a	any alphabetic character
"	\m	pattern after it be interpreted as if 'magic' is set
"	\M	pattern after it be interpreted as if 'nomagic' (magic unset)
"	\v	ASCII characters except [0-9a-zA-Z_] have special meaning: "very magic"
"	\V	only backslash & terminating char (usually / or ?) have special meaning
"
" Examples:
"
" after:    \v       \m       \M       \V         matches ~
"                 'magic' 'nomagic'
"           a        a        a        a          literal 'a'
"           \a       \a       \a       \a         any alphabetic character
"           .        .        \.       \.         any character
"           \.       \.       .        .          literal dot
"           $        $        $        \$         end-of-line
"           *        *        \*       \*         any number of the previous atom
"           ~        ~        \~       \~         latest substitute string
"           ()       \(\)     \(\)     \(\)       group as an atom
"           |        \|       \|       \|         nothing: separates alternatives
"           \\       \\       \\       \\         literal backslash
"           \{       {        {        {          literal curly brace
:set magic
"
" Misc search notes
"
" :set smartcase   or   :set scs	turn off:	:set noscs
" :set ignorecase  or	:set ic		turn off:	:st noic
" pattern  :set ignorecase  :set smartcase	matches
"
" /foo		off		off		foo
" /Foo		off		off		    Foo
" /FOO		off		off		        FOO
"
" /foo		on		off		foo Foo FOO
" /Foo		on		off		foo Foo FOO
" /FOO		on		off		foo Foo FOO
"
" /foo		off		on		foo
" /Foo		off		on		    Foo
" /FOO		off		on		        FOO
"
" /foo		on		on		foo Foo FOO
" /Foo		on		on		    Foo
" /FOO		on		on		        FOO
"
" /\cfoo	-		-		foo Foo FOO
" /\cFoo	-		-		foo Foo FOO
" /\cFOO	-		-		foo Foo FOO
"
" /\Cfoo	-		-		foo
" /\CFoo	-		-		    Foo
" /\CFOO	-		-		        FOO
"
```

**Comment by xexyl** [comment]
Besides the one I suggested today - gitcommit - here are a few others that I have in my file. It's a lot longer than this though. I've actually had the thought of making my `.vimrc` public but it's kind of long and has some things that aren't what you expect for most users (like mud syntax highlighting). If I were to do that I'd probably comment it more too.

Anyway here are some things of interest, maybe, some more useful than others:

If you ever want line numbers you can do `:set number`. I find this helpful at times but usually not because if I ever want to copy the text by mouse (so not yank but for some other purpose) It has the line numbers. Thus I have in my `.vimrc` `:set nonumber`.

My titlestring is more involved as it includes the FQDN of the system as I often use vim over ssh. This is one I rely on a lot:

```vim
"always show file name etc. at bottom of screen (next two lines):
set ruler
set laststatus=2
```

I have this one disabled as I don't end up using it but maybe it'll be useful to you:

```vim
"set digraph                    " allow typing e.g. û by typing 'u + <BS> >' instead of having to use 'ctrl+k, u + >'
```

This is a useful one for C functions as it allows you to jump to the beginning of the function:

```vim
" map [f to jump to beginning of function
map [f [m[{
```

I have some templates as well so that if I open an empty file e.g. TODO it initialises the contents (as long as I save it) as whatever the template has.

There are many other things though as I said. Hope the gitcommit one is of help to you!

Going back to watching a film. Have a good rest of your day!

**Comment by xexyl** [comment]
Some others I just noticed (and then I really am going back to the film):


`]m`: jump to the next `{` below current cursor position.
`[m`: jump to the previous `{` above the current cursor position.

**Comment by lcn2** [comment]
Regarding [a comment above](https://github.com/ioccc-src/mkiocccentry/pull/118#issuecomment-1071691690):

> You could more easily, perhaps, import a bunch of names and C keywords into your language file. For example you could take a list of the C keywords/etc. (one per line) and then use the command to update the file.
> 
> If I were to do that I would update the file:
>
> ~/.vim/spell/en.utf-8.add

What counts as a word in `en.utf-8.add`?

Take for example these strings (we will list them one per line):

```
stdio.h
#define
_Bool
```

Or does one just need:

```
stdio
define
Bool
```

What about case?  Does one need:

```
trigraph
TRIGRAPH
```

or just:

```
trigraph
```

?

**Comment by xexyl** [comment]
> Regarding [a comment above](https://github.com/ioccc-src/mkiocccentry/pull/118#issuecomment-1071691690):
> 
> > You could more easily, perhaps, import a bunch of names and C keywords into your language file. For example you could take a list of the C keywords/etc. (one per line) and then use the command to update the file.
> > If I were to do that I would update the file:
> > ~/.vim/spell/en.utf-8.add
> 
> What counts as a word in `en.utf-8.add`?
> 
> Take for example these strings (we will list them one per line):
> 
> ```
> stdio.h

If you put the cursor under `stdio` that's added to the spell file. If you use visual mode and highlight all of `stdio.h` it will include all of that. I'm not sure what all the word breaks are but space is one (of course) and I believe dots are as well. I think `-` might be also but I'm not sure of that.

> #define
> _Bool
> ```
> 
> Or does one just need:
> 
> ```
> stdio
> define
> Bool
> ```
> 

That's correct. Just like you don't need all of:

```c
/*ooo*/
```

You can get away with just `ooo`. If you don't you might see a warning that certain characters are ignored (see it when you modify the spell file e.g. by `zg`).


> What about case? Does one need:
> 
> ```
> trigraph
> TRIGRAPH
> ```
> 
> or just:
> 
> ```
> trigraph
> ```
> 
> ?


Okay this is an interesting one as it depends. If you have it in lower case then it will recognise it in any case (well not sure of mixed case like tEsT but test will recognise TEST or test). If however you were to add to the spell file say Gondolin and you were to type out 'gondolin' it would indicate there's a problem.

So if it has upper case letters then it expects it to have upper case letters; if not it can be upper case or lower case. I'm not certain however when it comes to diacritics. For example if you add `öö` I'm not if it would accept also `ÖÖ`.

As for punctuation here's a good example where you might want it: the ridiculously named syscall `creat()`.  Obviously `creat` is not a real word so you might not want it in the spell file. But you could do a visual selection of `creat(` or `creat()` and then you would see that `creat` is not a valid word but if you add the `(` (or `()`) it is. That way in a comment you wouldn't trigger `creat()` but if you just did `creat` you would.

I hope that helps! I might have more knowledge on the spellcheck mechanisms of vim but I'd probably have to think about it - or be prompted by a question.

**Comment by lcn2** [comment]
> UPDATE: Just tested it. Mixed case does not register as a correctly spelt word. So when I added Skynet recently (as I watched all the Terminator films recently) I cannot do SkYnet - it would say it's not a word. If I were to do SKYNET though everything is fine.

So if one had:

```
github
```

then both **github** and **GITHUB** would os considered OK, while **GitHub** would not be OK?

**Comment by xexyl** [comment]
> > UPDATE: Just tested it. Mixed case does not register as a correctly spelt word. So when I added Skynet recently (as I watched all the Terminator films recently) I cannot do SkYnet - it would say it's not a word. If I were to do SKYNET though everything is fine.
> 
> So if one had:
> 
> ```
> github
> ```
> 
> then both **github** and **GITHUB** would be considered OK, while **GitHub** would not be OK?

I believe so but I'm not sure in this case because I just looked at my spell file and I only have `github.com` and not without the `.com`. I can't think why that might be. However typing **GitHuB** causes a problem. I'm not sure why this one is but it appears that having `github.com` should suffice for all cases.

> 
> **UPDATE** 0: If one just had:
> 
> ```
> FIZZBIN
> ```
> 
> then **FIZZBIN** be considered OK, but **fizzbin** would not be OK?
> 

Right.

> **UPDATE** 1: If one just had:
> 
> ```
> Makefile
> ```
> 
> then **Makefile**be considered OK, but **makefile** would not be OK?

Correct. Unless of course it's already in the system vim spell files which it might very well be: not sure.

**Comment by lcn2** [comment]
> If I were to do that I would update the file:
>
> ~/.vim/spell/en.utf-8.add
>
> and then use :mkspell! on the file en.utf-8.add.spl and then I would (I'm not sure if this is necessary though) close vim and then the next time open it it should be good. You could always test it by opening the file again and verifying that no misspelt words are there (the one without the .spl at the end).

We have this file (we added lots of C keywords from the handy `rule_count.c` file) in our local directory:

```
en.utf-8.add
```

In order to "_enable_" those works in vim, we did the following:

```vim
:misspell en.utf-8.add
```

this produced the following output:

```
eading word file en.utf-8.add...
Compressing word tree...
Compressed case-folded: 938 of 2274 nodes; 1336 (58%) remaining
Compressed keep-case: 4 of 28 nodes; 24 (85%) remaining
Writing spell file en.utf-8.add.spl...
Done!
Estimated runtime memory use: 6820 bytes
```

That produced the following file in our local directory:

```
en.utf-8.add.spl
```

So in order for this to become permanent, we need to:

```sh
cp en.utf-8.add ~/.vim/spell/en.utf-8.add
cp en.utf-8.add.spl ~/.vim/spell/en.utf-8.add.spl
```

We could have also in done:

```sh
cp en.utf-8.add ~/.vim/spell/en.utf-8.add
```

and then in vim:

```vim
:mkspell! ~/.vim/spell/en.utf-8.add
```

BTW: The ! in the above example is needed to avoid "E13: File exists (add ! to override)"

This produces the following output:

```
Reading word file /Users/chongo/.vim/spell/en.utf-8.add...
Compressing word tree...
Compressed case-folded: 938 of 2274 nodes; 1336 (58%) remaining
Compressed keep-case: 4 of 28 nodes; 24 (85%) remaining
Writing spell file /Users/chongo/.vim/spell/en.utf-8.add.spl...
Done!
Estimated runtime memory use: 6820 bytes
```

correct?

**Comment by xexyl** [comment]
> > If I were to do that I would update the file:
> > ~/.vim/spell/en.utf-8.add
> > and then use :mkspell! on the file en.utf-8.add.spl and then I would (I'm not sure if this is necessary though) close vim and then the next time open it it should be good. You could always test it by opening the file again and verifying that no misspelt words are there (the one without the .spl at the end).
> 
> We have this file (we added lots of C keywords from the handy `rule_count.c` file) in our local directory:
> 
> ```
> en.utf-8.add
> ```
> 
> In order to "_enable_" those works in vim, we did the following:
> 
> ```viml
> :misspell en.utf-8.add
> ```
> 

`mkspell` yes. I used to manually edit the spell file by deleting a line if it shouldn't be there or else by merging more than one spell file and then use this command to make it.

> this produced the following output:
> 
> ```
> eading word file en.utf-8.add...
> Compressing word tree...
> Compressed case-folded: 938 of 2274 nodes; 1336 (58%) remaining
> Compressed keep-case: 4 of 28 nodes; 24 (85%) remaining
> Writing spell file en.utf-8.add.spl...
> Done!
> Estimated runtime memory use: 6820 bytes
> ```
> 
> That produced the following file in our local directory:
> 
> ```
> en.utf-8.add.spl
> ```
> 
> So in order for this to become permanent, we need to:
> 
> ```shell
> cp en.utf-8.add ~/.vim/spell/en.utf-8.add
> cp en.utf-8.add.spl ~/.vim/spell/en.utf-8.add.spl
> ```
> 

That's one way of doing it yes.

> We could have also in done:
> 
> ```shell
> cp en.utf-8.add ~/.vim/spell/en.utf-8.add
> ```
> 
> and then in vim:
> 
> ```viml
> :mkspell! ~/.vim/spell/en.utf-8.add
> ```
> 
Right.
> BTW: The ! in the above example is needed to avoid "E13: File exists (add ! to override)"
> 

Correct. Just like with `:w`, `:x` etc.

> This produces the following output:
> 
> ```
> Reading word file /Users/chongo/.vim/spell/en.utf-8.add...
> Compressing word tree...
> Compressed case-folded: 938 of 2274 nodes; 1336 (58%) remaining
> Compressed keep-case: 4 of 28 nodes; 24 (85%) remaining
> Writing spell file /Users/chongo/.vim/spell/en.utf-8.add.spl...
> Done!
> Estimated runtime memory use: 6820 bytes
> ```
> 
> correct?

Looks good to me.

**Comment by xexyl** [comment]
As for `!` you can use it in other commands too to overwrite previous settings. For example I use it with highlight command (not the only command though).

**Comment by lcn2** [comment]
Interesting .. when e restart vim and look at our local C word in `./en.utf-8.add` we see two colo[u]red words,
and using your vim spelling color scheme, we see:

```
alignas
```

in light blue.

Now in our spelling table we have both:

```
alignas
_Alignas
```

We also have in red:

```
and
```

Now in our spelling table we have both:

```
and
and_eq
```

When we take out the `and_eq` the`and` is no longer red.

However we have both:

```
xor
xor_eq
```

and `xor` was never red.

Why?

**Comment by lcn2** [comment]
Do we need:

```
_Alignof
_Atomic
_Bool
...
```

or just:

```
Alignof
Atomic
Bool
```

Humm ...

**Comment by xexyl** [comment]
Alternatively you can just have:

```
alignof
atomic
bool
```

And I would think that should solve the problem. As for `and_eq` I have this strange memory of an issue with `_` but I'm not sure if I'm making that up. As for xor it might be in the system default spell file: not sure.

**Comment by xexyl** [comment]
> Do we need:
> 
> ```
> _Alignof
> _Atomic
> _Bool
> ...
> ```
> 
> or just:
> 
> ```
> Alignof
> Atomic
> Bool
> ...
> ```
> 
> UPDATE: The issue are these c11 keywords:
> 
> ```
> _Alignof
> _Atomic
> _Bool
> _Complex
> _Generic
> _Imaginary
> _Noreturn
> _Pragma
> _Static_assert
> _Thread_local
> ```
> 
> How should those we put into the `en.utf-8.add` file for `mkspell` to process?

One way to make sure it's right is to go into visual mode, selecting the word (including the `_`) and then use `zg`. This should add it to the text file as well as make the spell file. Then you could copy both to the other systems `.vim/spell/` directory.

**Comment by lcn2** [comment]
> Alternatively you can just have:
> 
> ```
> alignof
> atomic
> bool
> ```
> 
> And I would think that should solve the problem. As for `and_eq` I have this strange memory of an issue with `_` but I'm not sure if I'm making that up. As for xor it might be in the system default spell file: not sure.

Wouldn't you want:

```
Alignas
Alignof
Atomic
Bool
Complex
Generic
Imaginary
Noreturn
Pragma
Static_assert
Thread_local
```

given the c11 keyword case?

**Comment by xexyl** [comment]
> > Alternatively you can just have:
> > ```
> > alignof
> > atomic
> > bool
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And I would think that should solve the problem. As for `and_eq` I have this strange memory of an issue with `_` but I'm not sure if I'm making that up. As for xor it might be in the system default spell file: not sure.
> 
> Wouldn't you want:
> 
> ```
> Alignas
> Alignof
> Atomic
> Bool
> Complex
> Generic
> Imaginary
> Noreturn
> Pragma
> Static_assert
> Thread_local
> ```
> 
> given the c11 keyword case?

Quite possibly true yes. I was thinking more generally and maybe trying to not worry about the `_`. For example both `thread` and `local` are words so you shouldn't even have to have that in the file. Same with some of the others.

But see the other suggestion in the comment I just made as that should solve the problem easily enough.

**Comment by lcn2** [comment]
> One way to make sure it's right is to go into visual mode, selecting the word (including the _) and then use zg. This should add it to the text file as well as make the spell file.

In regards to red and:

In _en.utf-8.add_ we had:

```
and
```

When we typed:

```
and_eq
```

The `eq` turned red.  So we put the cursor on the `a` of `and_eq` and typed `zg`:

The `and` turned red and  `eq` remained red from the `and_eq` .

Odd.

**Comment by xexyl** [comment]
> > One way to make sure it's right is to go into visual mode, selecting the word (including the _) and then use zg. This should add it to the text file as well as make the spell file.
> 
> In regards to red and:
> 
> In _en.utf-8.add_ we had:
> 
> ```
> and
> ```
> 
> When we typed:
> 
> ```
> and_eq
> ```
> 
> The `eq` turned red. So we put the cursor on the `a` of `and_eq` and typed `zg`:
> 
> The `and` turned red and `eq` remained red from the `and_eq` .
> 
> Odd.

What about opening the file and using visual mode select all of `and_eq` and then type `zg` .. and then type it in a text file and see if it's recognised as a word? That should solve the problem.

Maybe `eq` by itself would be enough there but I'm not sure. I'm not sure how `_` works in the spell file or if it has any effect or not.

**Comment by xexyl** [comment]
Tomorrow if I think of it and I have the time/energy I'll maybe play with this a bit more as it is interesting and it would be good to know why it's happening. Maybe not necessary with the solution I gave but might be useful to know anyway.

**Comment by xexyl** [comment]
Typing on the phone so if I miss anything or it’s not clear please let me know. I have reread this comment more clearly when not in the midst of something else. 

> Interesting .. when e restart vim and look at our local C word in `./en.utf-8.add` we see two colo[u]red words, and using your vim spelling color scheme, we see:
> 
> ```
> alignas
> ```
> 
> in light blue.
> 

Iirc I have that colour for words that should be capitalised but are not. So if it’s at the beginning of a sentence that makes sense to me. 
> Now in our spelling table we have both:
> 
> ```
> alignas
> _Alignas
> ```
> 

See above why this is. The problem is vim spellcheck is also acting as a minimal grammar checker (and even the best ones have problems). Here’s an experiment for you to try. Type in a text file the words:

> the the

and you will see an indication that there’s something wrong. Thus I believe this is not a bug but a feature. 

> We also have in red:
> 
> ```
> and
> ```
> 
> Now in our spelling table we have both:
> 
> ```
> and
> and_eq
> ```
> 
> When we take out the `and_eq` the`and` is no longer red.

Now this is more interesting. I don’t have an explanation for this. I don’t know but perhaps the one file is causing problems with the other (or one entry with the other)? 

If you upload the ascii file (and if possible the actual spell file) maybe I can figure it out when I have the time and not the energy for more important things. I absolutely love puzzles!


> 
> However we have both:
> 
> ```
> xor
> xor_eq
> ```
> 
> and `xor` was never red.
> 
> Why?

It’s indeed very strange but I believe that if you remove the words that aren’t needed e.g. `and` it might not be a problem at all. In order words just have `eq` in the file. 

To help debug this I wonder though: if you put automate it via `zg` does it have this problem? Maybe there’s something strange going on when invoking `mkspell` directly for some reason?

**Comment by xexyl** [comment]
> > Alternatively you can just have:
> > ```
> > alignof
> > atomic
> > bool
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And I would think that should solve the problem. As for `and_eq` I have this strange memory of an issue with `_` but I'm not sure if I'm making that up. As for xor it might be in the system default spell file: not sure.
> 
> Wouldn't you want:
> 
> ```
> Alignas
> Alignof
> Atomic
> Bool
> Complex
> Generic
> Imaginary
> Noreturn
> Pragma
> Static_assert
> Thread_local
> ```
> 
> given the c11 keyword case?

As for this list I think you could get away with just having the words that aren’t English words in the case of the keyword in question and I don’t believe you should need the underscores. You can test this though by seeing if vim actually adds it when you use `zg`.

**Comment by xexyl** [comment]
> > One way to make sure it's right is to go into visual mode, selecting the word (including the _) and then use zg. This should add it to the text file as well as make the spell file.
> 
> In regards to red and:
> 
> In _en.utf-8.add_ we had:
> 
> ```
> and
> ```
> 
> When we typed:
> 
> ```
> and_eq
> ```
> 
> The `eq` turned red. So we put the cursor on the `a` of `and_eq` and typed `zg`:
> 
> The `and` turned red and `eq` remained red from the `and_eq` .
> 
> Odd.

Now that is very bizarre. I am very tempted to see if I can duplicate this. What system was this on btw?

You might (as I suggested above in another comment) get away with just having `eq` in the file and not worry about the words that should already be okay. 

Perhaps by opening an empty file and typing:

> eq

and moving the cursor under the e and then using `zg`. After that maybe look (or if it’s a long file like mine then use search) for words that are valid words in the default spell file e.g. English words. 

Let me know if these comments help and if you want to upload those files I would be very curious to see if I can figure out what is happening.

**Comment by lcn2** [comment]
> > > One way to make sure it's right is to go into visual mode, selecting the word (including the _) and then use zg. This should add it to the text file as well as make the spell file.
> 
> > 
> 
> > In regards to red and:
> 
> > 
> 
> > In _en.utf-8.add_ we had:
> 
> > 
> 
> > ```
> 
> > and
> 
> > ```
> 
> > 
> 
> > When we typed:
> 
> > 
> 
> > ```
> 
> > and_eq
> 
> > ```
> 
> > 
> 
> > The `eq` turned red. So we put the cursor on the `a` of `and_eq` and typed `zg`:
> 
> > 
> 
> > The `and` turned red and `eq` remained red from the `and_eq` .
> 
> > 
> 
> > Odd.
> 
> 
> 
> Now that is very bizarre. I am very tempted to see if I can duplicate this. What system was this on btw?
> 
> 
> 
> You might (as I suggested above in another comment) get away with just having `eq` in the file and not worry about the words that should already be okay. 
> 
> 
> 
> Perhaps by opening an empty file and typing:
> 
> 
> 
> > eq
> 
> 
> 
> and moving the cursor under the e and then using `zg`. After that maybe look (or if it’s a long file like mine then use search) for words that are valid words in the default spell file e.g. English words. 
> 
> 
> 
> Let me know if these comments help and if you want to upload those files I would be very curious to see if I can figure out what is happening. 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

We try to upload the spell file, if we can, when have access to the Apple MacBook Pro (with Apple Silicon) running the current version of macOS (12.3.1 if we recall correctly).

**Comment by lcn2** [comment]
Here is a zip file with both `en.utf-8.add` and `en.utf-8.add.spl`:

[en.utf-8.zip](https://github.com/ioccc-src/mkiocccentry/files/8461194/en.utf-8.zip)

Here is our `.vimrc` as a zip file:

[vimrc.zip](https://github.com/ioccc-src/mkiocccentry/files/8461206/vimrc.zip)

We had to form zip files because GitHub does not support any j-random file type.

When we vi the `en.utf-8.add` file, the only colored word is `and` (in red).

Comments, corrections and suggestions welcome @xexyl.

**Comment by xexyl** [comment]
> vimrc.zip

Now this is incredibly strange that in the actual spell file (text - not the spell file that's generated from `mkspell`) there's the word `and` but it's marked as red! I wonder if there was an error with making the spell file itself. 

But it's even stranger because typing 'and' in a text file in the same vim session and it does not indicate a problem! What's more is that `and_eq` is in the spell file but having `and_eq` in the text file the `_eq` part is in red!

I've got `eq` to not be marked as red by typing `eq` in a text file and using `zg` on it. I'll attach the new spell files. But what's really strange is in the spell file and itself is still marked red: that should not happen as that's the actual spell file suggesting it's okay: nothing in that file should be marked red!

However I think the problem was a bad invocation of `mkspell` because after removing and from the text file and then running `mkspell!` it works. What's more is adding the word `and` with `zg` and then reopening vim it does not show an error in `and_eq` or `and` (I had added `eq` to the spell file too). I'm attaching the files as a zip file (for the reason you cited).

I don't have any thoughts on the `.vimrc` file but I didn't really look at it either. 

Here's what the `vimspell.zip` file has:

- The previous version of your spell files (in the zip file you provided).
- My updates to both the input and output.

All are in the directory spell. I've gone ahead and removed some words that you shouldn't need in there e.g. `Imaginary` as it's of course in the default list so no need to specify case. Instead of `and_eq` for example I have added just `eq`. Then I ran `mkspell` on the file, reopened vim and it seems good. There were some words that probably weren't needed either that I did not remove but a number of them I have.

Hope this helps? Let me know if you have any problems either way. 

[vimspell.zip](https://github.com/ioccc-src/mkiocccentry/files/8463762/vimspell.zip)

As for how this happened I can only conclude that somewhere the file got corrupt and recreating the file was the only solution. Maybe there's another explanation that could be devised but I don't know what it is.

Hope you're having a nice sleep my friend! I'm not sure I'll get anything done with the repo today other than what I did in the pull request but at least now a test suite for `txzchk` can be made.

**Comment by xexyl** [comment]
Something occurred to me a bit ago: which system did you run the `mkspell` on? I wonder if it's an incompatibility between linux and macOS. Just a thought... I haven't actually tested the generated file under linux or linux file under macOS: just the text file.

**Comment by lcn2** [comment]
> Something occurred to me a bit ago: which system did you run the `mkspell` on? I wonder if it's an incompatibility between linux and macOS. Just a thought... I haven't actually tested the generated file under linux or linux file under macOS: just the text file.
> 
> EDIT: I see the comment where you answered this. Did you also try it under linux? Is the problem on one or the other? If it's under macOS which is where you generated the file I can come only to the conclusion earlier - that somehow the file got corrupted and only a regeneration of it would fix it which I did.

Under Linux, yes we think we did.

**Comment by xexyl** [comment]
> > Something occurred to me a bit ago: which system did you run the `mkspell` on? I wonder if it's an incompatibility between linux and macOS. Just a thought... I haven't actually tested the generated file under linux or linux file under macOS: just the text file.
> > EDIT: I see the comment where you answered this. Did you also try it under linux? Is the problem on one or the other? If it's under macOS which is where you generated the file I can come only to the conclusion earlier - that somehow the file got corrupted and only a regeneration of it would fix it which I did.
> 
> Under Linux, yes we think we did.

Perhaps that's why? What if you take the one I uploaded and try it under linux? Does it show some problems? Either way might be better to always run the command on the same platform.

**Pull request merged**
