### PR TITLE
Minor updates and fixes

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Unfortunately might be all I can do today .. just so tired and can't think well :(

It's possible a while later I might be able to. I hope so.

**Comment by xexyl** [comment]
Well I can at least do some simple things, maybe, like I did in commit https://github.com/ioccc-src/mkiocccentry/pull/370/commits/8fa4e494ebb88760b7b1232684a355c456d7334a.

There's that at least.

**Comment by lcn2** [comment]
> I am wondering if you see it?

No, we we're focusing on there details, sorry (tm Canada 🇨🇦).

**Comment by lcn2** [comment]
Nice update on the tool, @xexyl

**Comment by xexyl** [comment]
> Nice update on the tool, @xexyl

Thank you.

**Comment by xexyl** [comment]
> > > I am wondering if you see it?
> > 
> > 
> > No, we we're focusing on there details, sorry (tm Canada 🇨🇦).
> 
> Well I'll point it out anyway as it's fun.
> 
> In the case that a tool is not executable it ironically says:
> 
> ```shell
>         echo "### ISSUE DETECTED: $f is safe from execution" | tee -a -- "$LOG_FILE"
> ```
> 
> but of course that's actually a problem (which normally would not be of course).

... just some fun that might or might not be good to have in the end but for now it works. I think though that if we have to go through such a long file it is good to have some laughs.

**Comment by lcn2** [comment]
> > > > I am wondering if you see it?
> > > 
> > > 
> > > No, we we're focusing on there details, sorry (tm Canada 🇨🇦).
> > 
> > 
> > Well I'll point it out anyway as it's fun.
> > In the case that a tool is not executable it ironically says:
> > ```shell
> >         echo "### ISSUE DETECTED: $f is safe from execution" | tee -a -- "$LOG_FILE"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but of course that's actually a problem (which normally would not be of course).
> 
> ... just some fun that might or might not be good to have in the end but for now it works. I think though that if we have to go through such a long file it is good to have some laughs.

While I appreciate the humor, how about:

```sh
echo "### ISSUE DETECTED: $f process execution was botched: not even a zombie process was produced" | tee -a -- "$LOG_FILE"
```

in order to make it clear there was a failure.  Remember that other people will read and want to understand the log file.

BTW: Let us not descend to deep into easter eggs for this program.

**Comment by xexyl** [comment]
> > > > > I am wondering if you see it?
> > > > 
> > > > 
> > > > No, we we're focusing on there details, sorry (tm Canada 🇨🇦).
> > > 
> > > 
> > > Well I'll point it out anyway as it's fun.
> > > In the case that a tool is not executable it ironically says:
> > > ```shell
> > >         echo "### ISSUE DETECTED: $f is safe from execution" | tee -a -- "$LOG_FILE"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > but of course that's actually a problem (which normally would not be of course).
> > 
> > 
> > ... just some fun that might or might not be good to have in the end but for now it works. I think though that if we have to go through such a long file it is good to have some laughs.
> 
> While I appreciate the humor, how about:
> 

I knew you would.

> ```shell
> echo "### ISSUE DETECTED: $f process execution was botched: not even a zombie process was produced" | tee -a -- "$LOG_FILE"
> ```
> 

That's funny too!

> in order to make it clear there was a failure. Remember that other people will read and want to understand the log file.
> 

Yes that's true that some might. I think most people who participate in the IOCCC would get it however.

> BTW: Let us not descend to deep into easter eggs for this program.

Well as I said - it might not be good to keep it there. I like your idea too though. Can go for that. If I don't address this please remind me.

**Comment by xexyl** [comment]
... just made a change in it so I can commit it next time.

**Pull request merged**
