### PR TITLE
Test all done!! Test all Done!!

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Hmm ... see something .. will put it in other issue.

**Comment by xexyl** [comment]
The failure appears to be because of a missing `sudo` in the test.yml (which I added). But the other one, the dependabot.yml, which I know nothing about, that seems to have a problem.

**Review by lcn2 — COMMENTED** [review]
All Done!!! :-)

**Comment by xexyl** [comment]
> All Done!!! :-)

I don't know why but the quote amuses me. Do you remember the context ?

**Comment by lcn2** [comment]
> > All Done!!! :-)
> 
> I don't know why but the quote amuses me. Do you remember the context ?

Ny niece, when she was 2, back in 1985, wanted down from her chair and exit the room because she was done with dinner.  She wasn't getting her way fast enough and started yelling "All Done!!!".  👶 😁

**Comment by xexyl** [comment]
> > > All Done!!! :-)
> 
> > 
> 
> > I don't know why but the quote amuses me. Do you remember the context ?
> 
> 
> 
> Ny niece, when she was 2, back in 1985, wanted down from her chair and exit the room because she was done with dinner.  She wasn't getting her way fast enough and started yelling "All Done!!!".  👶 😁

Ah I can see that happening. I always figured it was your daughter: not sure why. Thanks. Makes it more amusing.

**Comment by xexyl** [comment]
Did I ever tell you the story when I was three years old and I was complaining how it was hot (in the car with of course no ac those days)? I was in the back with my younger brother and I kept saying 'it's hot'. My parents kept replying with 'we know it's hot; we're hot too'. I kept it up so long that my father finally said: 'if you say it's hot one more time I will whip you' to which I replied: 'I wish it were colder'. 

They obviously burst into laughter and a three year old outwitted his parents. I have always been quick witted and have a comment for almost everything. I am one of those people who can make people turn their head round and ask 'did you REALLY just say that?!' and I quite enjoy it. It can be a lot of fun to deliberately misinterpret people too: in good fun of course.

**Pull request merged**
