### PR TITLE
Resolve issue #1039

### PR DESCRIPTION
**Pull request by xexyl**
This syncs jparse from jparse repo with a variety of bug fixes and improvements, including a lot of documentation updates.

With this commit I believe only one more top priority prior to the contest opening needs to be resolved and that should be possible later today or if not then tomorrow, unless those Vogons build that hyperspace bypass of course :-)

### CODE REVIEW

**Comment by xexyl** [comment]
Lots of file changed, I know, but lots of good work done including fixes and improvements, some mentioned yesterday. Running `make www` with these versions on the website results in no problems!

**Comment by xexyl** [comment]
I must go afk now but when back I'll continue working on the website and hopefully get close to being ready for the great fork merge when you do it tomorrow. Then after that I can focus on the linking to the submit server FAQ.

**Review by lcn2 — APPROVED** [review]
OK 👍, @xexyl.  Let's see how this update / jparse link functions.  Thanks

**Comment by xexyl** [comment]
> OK 👍, @xexyl. Let's see how this update / jparse link functions. Thanks
> 

Sure.

> ## UPDATE 0
> Due to the pending, **Great Fork Merge**, we won't test this until afterwards.

Sure. Though I did test `make www` and all is good. I have made some progress on the website too. Working on it now.

**Pull request merged**
