### PR TITLE
hostchk.sh updates and bug_report.sh addition (very incomplete)

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
There you go. I have other commits to do but not today. Going to do something else now and will in fact be done for the day shortly. Hope you have a good day!

**Comment by xexyl** [comment]
...in fact shutting down in just a few minutes. Will have the laptop up again later for a bit but not to do anything here. Sorry for the problem with the hook stuff. I almost didn't commit it but that's why I added the notes I did. It's an interesting idea but I too thought it might be problematic. Still I felt it worth sharing just in case. This is why I usually ask such things first but I wanted to get it done so I could focus on the other things. 

Hopefully I can do more tomorrow with the bug report script. It does seem lately though that some days I don't feel up to doing anything and given how this week has been there's a good chance that I won't get anything done. We'll see. Enjoy the rest of your day. I'm off to get some food and just take it easy.

Cheers.

**Comment by lcn2** [comment]
Thank you, @xexyl.  Sorry (tm Canada 🇨🇦) for the mixup in the incorrect README.md file relation.

**Comment by xexyl** [comment]
> Thank you, @xexyl. Sorry (tm Canada 🇨🇦) for the mixup in the incorrect README.md file relation.

That's quite all right. I'm sorry for the mess in the first place! But I understand your thinking on it all as I said (including on whether it was a good thing to have in the first place). I'm surprised that GitHub would have that design as well as far as the README goes. Well maybe I'm not surprised but it seems strange anyway.

Anyway no worries on recreating it. I think it's better that I did it that way anyway - unless of course you can just merge only some of the commits. I did not know and that's why I said something about it.

Anyway I'm going to head off for the day. Enjoy the rest of your day!

**Pull request merged**
