### PR TITLE
Change twitter to mastodon - resolve #431

### LINKED ISSUE #431: Turn off twitter, turn on Mastodon
Based on [comment 1331452956](https://github.com/ioccc-src/mkiocccentry/issues/171#issuecomment-1331452956), we need to disable use of Twitter handles and migrate to using Mastodon handles.

We need change asking for optional twitter handles and instead ask for optional Mastodon usernames.

NOTE: Full Mastodon usernames are of the form:

@username@server.foo

For example, the full IOCCC Mastodon usernames is:

**@ioccc@fosstodon.org**

### PR DESCRIPTION
**Pull request by xexyl**
Due to Elon Musk taking over twitter the IOCCC is abandoning active use of their twitter account and instead are moving to mastodon at @ioccc@fosstodon.org.

This also means that all the code and data files that refer to twitter had to be updated to deal with mastodon handles. A great deal of files have been changed for this commit.

It's possible I have missed all sanity checks on mastodon handles. Right now it checks for the following:

- more than one @ that's adjacent to each other (@@).
- string does not start with @ or ends with @
- string does not have exactly two '@'s (see count_char() in util.c).
- string matches "@" (nothing after the @).

There might be a better way to go about some of these.

The test_ioccc/test_JSON files have all been updated to match the mastodon handle format. I've run make prep and make test multiple times and I also ran mkiocccentry manually to make sure that it works okay, trying to find any mistakes. Although it's certainly possible that I missed something I think I have got everything covered.

Trivia question: what is the difference between Twitter and the SpaceX Starship rockets SN3, SN4, SN7, SN8, SN9, SN10, SN11 and probably others? Musk hasn't successfully blown Twitter up yet.

### CODE REVIEW

**Comment by xexyl** [comment]
Something I forgot to mention in the commit log is the maximum length. I chose the maximum length of domains and then the previous max length of twitter handles (19 I think it was). Probably not ever going to reach that many characters and we can certainly change it but it felt like a good default.

Check the trivia question there too! 

And now I really am going to rest. I feel good about getting this done. It's probably all I'll do today here.

**Comment by lcn2** [comment]
> Something I forgot to mention in the commit log is the maximum length. I chose the maximum length of domains and then the previous max length of twitter handles (19 I think it was). Probably not ever going to reach that many characters and we can certainly change it but it felt like a good default.

While the limit may be technically correct, we may wish to impose a smaller limit such as 64 or 48.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Happy to help. 

Does this mean you have your Internet service restored?

Also you forgot to close the issue. Or is there a reason to have it open still?

**Comment by xexyl** [comment]
> > Something I forgot to mention in the commit log is the maximum length. I chose the maximum length of domains and then the previous max length of twitter handles (19 I think it was). Probably not ever going to reach that many characters and we can certainly change it but it felt like a good default.
> 
> While the limit may be technically correct, we may wish to impose a smaller limit such as 64 or 48.

Perhaps so. I thought it might be a bit high. My suggestion: either 64 or `42*2` (I of course can do that in my head but I wanted to say it that way due to 42). 

I am going to try resting again. Hopefully I can get some things done today but it was a difficult night and I woke up too early. I hope I can get more rest. 

Hope you’re having a nice sleep my friend!

**Pull request merged**
