### PR TITLE
Minor bug fixes in json scanner

### PR DESCRIPTION
**Pull request by xexyl**
There were some other changes as well but that's the most of it.

### CODE REVIEW

**Comment by xexyl** [comment]
Landon see the commit log for a possible problem:

```git
    Updated Makefile to use seqcexit on the flex and bison files and
    sequenced exit codes. I'm aware of an issue though: although it appears
    that the same exit code stays in jparse.l as jparse.c there happens to
    be a call to err() in mkiocccentry.c with the same error code.

```

The error code in question is 35 btw if that helps.

**Comment by xexyl** [comment]
> Landon see the commit log for a possible problem:
> 
> ```
>     Updated Makefile to use seqcexit on the flex and bison files and
>     sequenced exit codes. I'm aware of an issue though: although it appears
>     that the same exit code stays in jparse.l as jparse.c there happens to
>     be a call to err() in mkiocccentry.c with the same error code.
> ```
> 
> The error code in question is 35 btw if that helps.

This is what I mean after running `make seqcexit`:
```
$ grep 'err(35' *.c
jinfochk.c:	err(35, __func__, "strdup() error on filename %s", filename);
jparse.c:	err(35, __func__, "passed NULL arg(s)");
mkiocccentry.c:	err(35, __func__, "work_dir is not a directory: %s", work_dir);
```

But I don't know why this is.

**Comment by xexyl** [comment]
Okay I think that's all I'll do today. Will hopefully get back to it more tomorrow.

**Comment by lcn2** [comment]
> > Landon see the commit log for a possible problem:
> 
> > 
> 
> > ```
> 
> >     Updated Makefile to use seqcexit on the flex and bison files and
> 
> >     sequenced exit codes. I'm aware of an issue though: although it appears
> 
> >     that the same exit code stays in jparse.l as jparse.c there happens to
> 
> >     be a call to err() in mkiocccentry.c with the same error code.
> 
> > ```
> 
> > 
> 
> > The error code in question is 35 btw if that helps.
> 
> 
> 
> This is what I mean after running `make seqcexit`:
> 
> ```
> 
> $ grep 'err(35' *.[lyc]
> 
> jinfochk.c:	err(35, __func__, "strdup() error on filename %s", filename);
> 
> jparse.c:	err(35, __func__, "passed NULL arg(s)");
> 
> jparse.l:	err(35, __func__, "passed NULL arg(s)");
> 
> mkiocccentry.c:	err(35, __func__, "work_dir is not a directory: %s", work_dir);
> 
> ```
> 
> 
> 
> But I don't know why this is. It's good that the one in jparse.c and jparse.l match but why are the others not being updated?

By default, `seqcexit` resets the sequencing for each file.  Given the number of exit points and the limited number of exit codes, this is expected.  We cannot have unique exit codes repo.

You do raise a good point about `jparse.y` and `jparse.l`.  Together they produce a single set of code that is distributed into 3 files.  It is probably the case that these two files should be treated as a single exit sequence.  For cases such as this, `seqcexit` has the `-c` flag.  Probably this is best:

```sh
seqcexit -c jparse.y jparse.l
```

On the other hand, the 3 files produced by `bison` and `flex` should NOT be processed by `seqcexit`.  It is very important to keep the input files `jparse.y` and `jparse.l` in sync with the C code they produce.

**Comment by xexyl** [comment]
> > > Landon see the commit log for a possible problem:
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > Updated Makefile to use seqcexit on the flex and bison files and
> > > ```
> > 
> > 
> > > ```
> > > sequenced exit codes. I'm aware of an issue though: although it appears
> > > ```
> > 
> > 
> > > ```
> > > that the same exit code stays in jparse.l as jparse.c there happens to
> > > ```
> > 
> > 
> > > ```
> > > be a call to err() in mkiocccentry.c with the same error code.
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > The error code in question is 35 btw if that helps.
> > 
> > 
> > This is what I mean after running `make seqcexit`:
> > ```
> > 
> > $ grep 'err(35' *.[lyc]
> > 
> > jinfochk.c:	err(35, __func__, "strdup() error on filename %s", filename);
> > 
> > jparse.c:	err(35, __func__, "passed NULL arg(s)");
> > 
> > jparse.l:	err(35, __func__, "passed NULL arg(s)");
> > 
> > mkiocccentry.c:	err(35, __func__, "work_dir is not a directory: %s", work_dir);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I don't know why this is. It's good that the one in jparse.c and jparse.l match but why are the others not being updated?
> 
> By default, `seqcexit` resets the sequencing for each file. Given the number of exit points and the limited number of exit codes, this is expected. We cannot have unique exit codes repo.

What should be done then?

> 
> You do raise a good point about `jparse.y` and `jparse.l`. Together they produce a single set of code that is distributed into 3 files. It is probably the case that these two files should be treated as a single exit sequence. For cases such as this, `seqcexit` has the `-c` flag. Probably this is best:
> 

Right.

> ```shell
> seqcexit -c jparse.y jparse.l
> ```
> 

So should the Makefile have two invocations of the command ? If so do you mind updating it when doing the other changes? If not I can do it but not today - too tired I'm afraid

> On the other hand, the 3 files produced by `bison` and `flex` should NOT be processed by `seqcexit`. It is very important to keep the input files `jparse.y` and `jparse.l` in sync with the C code they produce.
> 

I agree they should be kept in sync. But this means some things have to change in the Makefile even besides what you referred to above.


> UPDATE: The Makefile rule for `make seqcexit` needs to be fixed accordingly.

Okay the OBJFILES variable in the Makefile might be problematic then. If you look at it:

```makefile
OBJFILES = dbg.o util.o mkiocccentry.o iocccsize.o fnamchk.o txzchk.o jauthchk.o jinfochk.o \
        json.o jstrencode.o jstrdecode.o rule_count.o location.o utf8_posix_map.o sanity.o jparse.o \
        jparse.tab.o
```

...you can see that the `jparse.tab.o` is there and so is `jparse.o`. These are important there (I think). But the problem is that we also have (both for make depend):

```makefile
SRCFILES = $(patsubst %.o,%.c,$(OBJFILES))
```

And make depend relies on SRCFILES. Now the make depend could use two different variables if necessary (or more than two) but which ones I am not sure. Also if OBJFILES needs those files then this could be a real problem for seqcexit. I don't know what to do about that. I might have some ideas when more alert but that's beyond me today.

If you have any ideas maybe you could do it when you're doing the other Makefile update(s)?

**Comment by lcn2** [comment]
> > > > Landon see the commit log for a possible problem:
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > ```
> > > > Updated Makefile to use seqcexit on the flex and bison files and
> > > > ```
> > > 
> > > 
> > > > ```
> > > > sequenced exit codes. I'm aware of an issue though: although it appears
> > > > ```
> > > 
> > > 
> > > > ```
> > > > that the same exit code stays in jparse.l as jparse.c there happens to
> > > > ```
> > > 
> > > 
> > > > ```
> > > > be a call to err() in mkiocccentry.c with the same error code.
> > > > ```
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > The error code in question is 35 btw if that helps.
> > > 
> > > 
> > > This is what I mean after running `make seqcexit`:
> > > ```
> > > 
> > > $ grep 'err(35' *.[lyc]
> > > 
> > > jinfochk.c:	err(35, __func__, "strdup() error on filename %s", filename);
> > > 
> > > jparse.c:	err(35, __func__, "passed NULL arg(s)");
> > > 
> > > jparse.l:	err(35, __func__, "passed NULL arg(s)");
> > > 
> > > mkiocccentry.c:	err(35, __func__, "work_dir is not a directory: %s", work_dir);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > But I don't know why this is. It's good that the one in jparse.c and jparse.l match but why are the others not being updated?
> > 
> > 
> > By default, `seqcexit` resets the sequencing for each file. Given the number of exit points and the limited number of exit codes, this is expected. We cannot have unique exit codes repo.
> 
> What should be done then?
> 
> > You do raise a good point about `jparse.y` and `jparse.l`. Together they produce a single set of code that is distributed into 3 files. It is probably the case that these two files should be treated as a single exit sequence. For cases such as this, `seqcexit` has the `-c` flag. Probably this is best:
> 
> Right.
> 
> > ```shell
> > seqcexit -c jparse.y jparse.l
> > ```
> 
> So should the Makefile have two invocations of the command ? If so do you mind updating it when doing the other changes? If not I can do it but not today - too tired I'm afraid
> 
> > On the other hand, the 3 files produced by `bison` and `flex` should NOT be processed by `seqcexit`. It is very important to keep the input files `jparse.y` and `jparse.l` in sync with the C code they produce.
> 
> I agree they should be kept in sync. But this means some things have to change in the Makefile even besides what you referred to above.
> 
> > UPDATE: The Makefile rule for `make seqcexit` needs to be fixed accordingly.
> 
> Okay the OBJFILES variable in the Makefile might be problematic then. If you look at it:
> 
> ```makefile
> OBJFILES = dbg.o util.o mkiocccentry.o iocccsize.o fnamchk.o txzchk.o jauthchk.o jinfochk.o \
>         json.o jstrencode.o jstrdecode.o rule_count.o location.o utf8_posix_map.o sanity.o jparse.o \
>         jparse.tab.o
> ```
> 
> ...you can see that the `jparse.tab.o` is there and so is `jparse.o`. These are important there (I think). But the problem is that we also have (both for make depend):
> 
> ```makefile
> SRCFILES = $(patsubst %.o,%.c,$(OBJFILES))
> ```
> 
> And make depend relies on SRCFILES. Now the make depend could use two different variables if necessary (or more than two) but which ones I am not sure. Also if OBJFILES needs those files then this could be a real problem for seqcexit. I don't know what to do about that. I might have some ideas when more alert but that's beyond me today.
> 
> If you have any ideas maybe you could do it when you're doing the other Makefile update(s)?

Fixed in commit 66bea9f6d5ee3f805fab9c36ae3ae32923b92908.

**Comment by xexyl** [comment]
> Fixed in commit [66bea9f](https://github.com/ioccc-src/mkiocccentry/commit/66bea9f6d5ee3f805fab9c36ae3ae32923b92908).

Thank you.

**Pull request merged**
