### PR TITLE
JSON parser error message improvements

### PR DESCRIPTION
**Pull request by xexyl**
We now address what was discussed in the json parser thread but I also in commit de1561a3965a14520815025c7a8953e4e843a09e print the filenames. Although I'll paste the log in the other thread you might want to check the log because I do bring up a possible issue that might want to be addressed prior to merging. It should be a very simple fix but I must leave for a while now. I meant to include some examples in the log but I forgot to do that. Will show it in the other thread instead before I leave. Might or might not be able to do any other changes today but I do hope to at least address the comment I deferred to later earlier on.

### CODE REVIEW

**Comment by xexyl** [comment]
... really going now .. might do more later.

**Comment by xexyl** [comment]
Converting to a draft .. have a couple fixes to make.

**Comment by xexyl** [comment]
This is incredibly amusing.

Running (as I do after editing `jparse.{l,y}`) `make parser all` works fine. But try running `run_flex.sh` and `run_bison.sh` and then `make all` fails:

```sh
$ ./run_bison.sh 
/opt/local/bin/bison  jparse.y
# prepending comment and line number reset to jparse.tab.c
cat sorry.tm.ca.h > .sorry.run_bison.sh.XXXXXXXXXX.c
cat jparse.tab.c >> .sorry.run_bison.sh.XXXXXXXXXX.c
mv -v -f .sorry.run_bison.sh.XXXXXXXXXX.c jparse.tab.c
.sorry.run_bison.sh.XXXXXXXXXX.c -> jparse.tab.c
# completed update of jparse.tab.c
# prepending comment and line number reset to jparse.tab.h
cat sorry.tm.ca.h > .sorry.run_bison.sh.XXXXXXXXXX.c
cat jparse.tab.h >> .sorry.run_bison.sh.XXXXXXXXXX.c
mv -v -f .sorry.run_bison.sh.XXXXXXXXXX.c jparse.tab.h
.sorry.run_bison.sh.XXXXXXXXXX.c -> jparse.tab.h
# completed update of jparse.tab.h
$ ./run_flex.sh 
/opt/local/bin/flex  jparse.l
# prepending comment and line number reset to jparse.c
cat sorry.tm.ca.h > .sorry.run_flex.sh.XXXXXXXXXX.c
cat jparse.c >> .sorry.run_flex.sh.XXXXXXXXXX.c
mv -v -f .sorry.run_flex.sh.XXXXXXXXXX.c jparse.c
.sorry.run_flex.sh.XXXXXXXXXX.c -> jparse.c
# completed update of jparse.c
$ make all
cc -std=gnu11 -O0 -g -pedantic  -Wall -Wextra -Werror -ferror-limit=0  jsemtblgen.c -c
cc -std=gnu11 -O0 -g -pedantic  -Wall -Wextra -Werror -ferror-limit=0  -Wno-unused-but-set-variable -Wno-unused-function -Wno-unneeded-internal-declaration jparse.c -c
cc -std=gnu11 -O0 -g -pedantic  -Wall -Wextra -Werror -ferror-limit=0  -Wno-unused-function -Wno-unneeded-internal-declaration jparse.tab.c -c
jparse.y:73:7: error: typedef redefinition with different types ('struct YYLTYPE' vs 'struct YYLTYPE')
    } YYLTYPE;
      ^
jparse.y:73:7: note: previous definition is here
    } YYLTYPE;
      ^
1 error generated.
make: *** [jparse.tab.o] Error 1

```

So unless I'm badly mistaken the problem is I'm replacing a struct with the same struct at the same location. But I can't be because I copy pasted each one into a separate file:

```sh
$ cat s
struct YYLTYPE
jparse.y:73:7
    } YYLTYPE;
$ cat s2
struct YYLTYPE
jparse.y:73:7
    } YYLTYPE;
$ diff s s2
$
```

so there's no difference at all. Funny and I'm not sure why yet.

**Comment by xexyl** [comment]
Fixed it. Also fixed the shadow declaration. Will commit and then I hope to look at the other thread. I don't think I'll be able to go back to sleep.

**Comment by lcn2** [comment]
Thank you @xexyl

**Comment by xexyl** [comment]
> Thank you @xexyl

Happy to help! Leaving now. I hope I can do more tomorrow. Good day!

**Pull request merged**
