### PR TITLE
Bug fix prep.sh, use is_available.sh in Makefiles

### PR DESCRIPTION
**Pull request by xexyl**
The prep.sh script printed incorrect messages for skipped checks.

The URL of each tool (in the skipped check messages) are now indented.

Make use of soup/is_available.sh in the Makefiles.

Synced jparse from jparse repo (https://github.com/xexyl/jparse/) with the above changes (to do with the jparse repo).

Ran make release to test these changes in macOS.

### CODE REVIEW

**Comment by xexyl** [comment]
That other file had some important fixes made but should now be on the ice block (not iceblock .. which macOS does not think is a word :-) ).

**Review by lcn2 — APPROVED** [review]
thanks @xexyl

**Comment by xexyl** [comment]
> thanks @xexyl 

Welcome. A little bit ago I made another commit to jparse but I can't sync that right now. It's not important but you're certainly welcome to do it if you want. 

Otherwise I will do it tomorrow morning.

**Comment by lcn2** [comment]
> > thanks @xexyl
> 
> Welcome. A little bit ago I made another commit to jparse but I can't sync that right now. It's not important but you're certainly welcome to do it if you want.
> 
> Otherwise I will do it tomorrow morning.

See commit 72fda28df0a2dd2db363c85a11ef4a37ea44f10a

**Pull request merged**
