### PR TITLE
Fix issue #1037 - submit server is ready

### PR DESCRIPTION
**Pull request by xexyl**
mkiocccentry updated to show that the registration URL and submit server URL
are available and to show what file and what slot to upload, how to register
etc. The macros that checked for the readiness of these servers are no more as
they are always ready now even if one can only register if in pending and open
and only submit if status is open.

Updated mkiocccentry version to "1.1.2 2024-12-31" and soup version to
"1.1.3 2024-12-31". The reason the soup version was updated is because of
macro changes, including new ones for the URLs.

### CODE REVIEW

**Comment by xexyl** [comment]
Does this solve the issue and the other issue #1038 as I think it does ?

It looks btw like:

```
To submit to the IOCCC, you must be a registered contestant
and have received an IOCCC contest ID (a UUID) and initial
password (via email). To do so, please visit:

    https://www.freelists.org/list/ioccc28-reg

Please also see the FAQ on how to enter the IOCCC:

    https://www.ioccc.org/faq.html#enter

...and the register, password change and submit help pages:

    https://www.ioccc.org/next/register.html
    https://www.ioccc.org/next/pw-change.html
    https://www.ioccc.org/next/submit.html

Please note that you may ONLY register when the contest is in
a PENDING or OPEN status! For the contest status see:

    https://www.ioccc.org/status.html

When the contest is open (see https://www.ioccc.org/status.html),
after you have registered, you must upload:

    test_ioccc/test_work/submit.12345678-1234-4321-abcd-1234567890ab-2.1735658259.txz into slot 2

to the IOCCC submit server:

    https://submit.ioccc.org

For more information, see the FAQ on how to enter at:

    https://www.ioccc.org/faq.html#enter
```

but perhaps you wish for some slight changes?

Afk now .. when back I'll see if I can look at the winner repo! If not though at least these things should be done today which are probably the highest priority (I guess anyway).

**Review by lcn2 — APPROVED** [review]
Happy New 2025 (soon) 🥳 ‼️

Wow, lots of good and careful mods here, @xexyl.  Thanks for the notes about no change in functionality too.

**Comment by lcn2** [comment]
> but perhaps you wish for some slight changes?

These are very good mods.

On that foundation:

```
When the contest is open (see https://www.ioccc.org/status.html),
after you have registered, you must upload:

    test_ioccc/test_work/submit.12345678-1234-4321-abcd-1234567890ab-2.1735658259.txz into slot 2
```

The " into slot 2" at the end of the line will be hard to notice on some devices because of the necessarily long file path.

We suggest in a subsequent PR, something along these lines:

```
When the contest is open (see https://www.ioccc.org/status.html),
after you have registered, you must upload into slot 2:

    test_ioccc/test_work/submit.12345678-1234-4321-abcd-1234567890ab-2.1735658259.txz
```

**Comment by xexyl** [comment]
> Happy New 2025 (soon) 🥳 ‼️
> 
To you and all yours too!

> Wow, lots of good and careful mods here, @xexyl. Thanks for the notes about no change in functionality too.

Of course. I know it would be helpful there as we do need stability. But the error message is now slightly less confusing. Although we're the only ones (most likely) here who will install jparse it's still better. I've thought of this issue a number of times in other places in the code too, both jparse and here.

**Comment by xexyl** [comment]
> > but perhaps you wish for some slight changes?
> 
> These are very good mod, @xexyl
> 
> On that foundation:
> 
> ```
> When the contest is open (see https://www.ioccc.org/status.html),
> after you have registered, you must upload:
> 
>     test_ioccc/test_work/submit.12345678-1234-4321-abcd-1234567890ab-2.1735658259.txz into slot 2
> ```
> 
> The " into slot 2" at the end of the line will be hard to notice on some devices because of the necessarily long file path.
> 
> We suggest in a subsequent PR, something along these lines:
> 
> ```
> When the contest is open (see https://www.ioccc.org/status.html),
> after you have registered, you must upload into slot 2:
> 
>     test_ioccc/test_work/submit.12345678-1234-4321-abcd-1234567890ab-2.1735658259.txz
> ```

Sure. Let me take a look now ... hopefully have time to do it.

**Comment by xexyl** [comment]
Seeing if the change is good ...

**Pull request merged**
