### PR TITLE
Add -F fmt to jfmt, jval, jnamval man pages

### PR DESCRIPTION
**Pull request by xexyl**
There is - how to say? - let's say a colourful update to the man pages 
as well to do with one of the -F styles.

### CODE REVIEW

**Comment by lcn2** [comment]
We didn't see the addition of `1line` and `nows` styles: 2 varieties of the "JSON as a single line" printing process. 

See [comment 1659014228](https://github.com/ioccc-src/mkiocccentry/issues/523#issuecomment-1659014228) for more information. 

The `1line` style will be useful when printing JSON values that are compound JSON items in `jval` and `jnamval`.

**Comment by xexyl** [comment]
> We didn't see the addition of `1line` and `nows` styles: 2 varieties of the "JSON as a single line" printing process.
> 
> See [comment 1659014228](https://github.com/ioccc-src/mkiocccentry/issues/523#issuecomment-1659014228) for more information.
> 
> The `1line` style will be useful when printing JSON values that are compound JSON items in `jval` and `jnamval`.

That was a mistake .. see pull request https://github.com/ioccc-src/mkiocccentry/pull/817.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl 

Happy to help.

**Pull request merged**
