### PR TITLE
Improve JSON error messages (add token) + jparse.1 updates

### PR DESCRIPTION
**Pull request by xexyl**
Specifically json_{parse,util}.{h,c}.

A question remains of whether or not the reference files should be added
to the man page (and the files generated by flex and bison in general).
There is an argument for and against: on the one hand it is part of the
tool; but on the other hand they shouldn't be touched. Even so it might
be better as that's what is actually compiled to make the tool. But this
can be decided upon and if necessary done another time.

### CODE REVIEW

**Comment by xexyl** [comment]
As for maybe even better error messages this is an interesting idea. From a very quick glance with a tired head it sounds like it's recreating the error messages via a post-processing (or post generation) of the files. It's probably not worth it even but since I saw it I figured I'd bring it up:


https://research.swtch.com/yyerror

**Comment by xexyl** [comment]
Leaving for the day. Good luck with the Internet and good day!

**Comment by lcn2** [comment]
This looks like good progress, @xexyl.

**Comment by xexyl** [comment]
> This looks like good progress, @xexyl.

Thank you! I think so as well. Hope you're having a nice sleep my friend! How's the Internet access issue btw ?

**Comment by lcn2** [comment]
> > This looks like good progress, @xexyl.
> 
> 
> 
> Thank you! I think so as well. Hope you're having a nice sleep my friend! How's the Internet access issue btw ?

- Ongoing but getting better. We will be able to travel outside the area for some coffee shop ☕️ Wi-Fi access for some limited work.

**Comment by xexyl** [comment]
> > > This looks like good progress, @xexyl.
> > 
> > 
> > Thank you! I think so as well. Hope you're having a nice sleep my friend! How's the Internet access issue btw ?
> 
> * Ongoing but getting better. We will be able to travel outside the area for some coffee shop ☕️ Wi-Fi access for some limited work.

Sounds good. Well I'm done for the day so maybe tomorrow I'll see something nice that's been added. Been a very slow day here. I want to watch a film or documentary or do something but I'm so tired I can barely keep my eyes open. Well we all have our problems I suppose. 

Good day! Good luck with the Internet being restored.

**Pull request merged**
