### PR TITLE
Minor improvements and fixes to location.1

### PR DESCRIPTION
**Pull request by xexyl**
This is not complete checked yet. I will look at it more thoroughly later hopefully today. Hopefully nothing else needs to be done and if that's the case the only commit might be a comment update.

The fixes were typos and formatting / styling.

--

Fix rest of location.1

I believe that at this time everything is good. There might be a few
things off / wrong but there were additional typo fixes and a minor
change in an example.

I am actually aware that the EXAMPLES section could probably be improved
formatting wise but since it looks fine it's probably okay and it might
be that I am remembering wrong: certainly it's the format I once had but
I believe I ended up changing it a bit later on. This is unneeded 
however.

### CODE REVIEW

**Comment by xexyl** [comment]
Now for a rest .. I hope.

**Comment by xexyl** [comment]
After https://github.com/ioccc-src/mkiocccentry/pull/534/commits/8a4b1fcfc779685e975080a33e528985a1318e7b I really do plan on trying to rest now!

I'm not sure if I will get anything else done here today .. been an absolutely crazy morning! Good day and hope you're sleeping well for a while!

**Comment by xexyl** [comment]
[Merry Christmas](https://github.com/ioccc-src/mkiocccentry/pull/534/commits/ceb4e5c823d86db3e52cb40ccb6bc6dc8ee5c112)! :-)

.. really going to turn the lights off now .. hope to do more later but this is far from certain.

**Comment by lcn2** [comment]
Thanks for the `location(1)` man page corrections / improvements @xexyl

**Comment by xexyl** [comment]
> Thanks for the `location(1)` man page corrections / improvements @xexyl

Happy to help!

**Pull request merged**
