### PR TITLE
Update txzchk version

### PR DESCRIPTION
**Pull request by xexyl**
The CHANGES.md file notes the version change. The changes prompting the version update are already there.

### CODE REVIEW

**Comment by xexyl** [comment]
Leaving for the day .. will do more tomorrow.

**Comment by lcn2** [comment]
thanks @xexyl

**Comment by xexyl** [comment]
You're most welcome!

**Comment by xexyl** [comment]
Here's a funny thing. It won't here let me delete the branch.

Screenshot 2023-06-17 at 02 33 13

I'll have to go about that a different way but first going to try and rest again .. hopefully can get a bit more sleep.

**Comment by xexyl** [comment]
> Here's a funny thing. It won't here let me delete the branch.
> 
> Screenshot 2023-06-17 at 02 33 13
> 
> I'll have to go about that a different way but first going to try and rest again .. hopefully can get a bit more sleep.

## UPDATE 0

Reloading allowed it. Trying to rest now .. will update the json parser bugs in man page later on if nothing else: but I hope to do more. I do have to ask you some things about jprint: some things I am not clear about but that's for another time.

**Pull request merged**
