### PR TITLE
Fix at least part of issue #393 + typo fixes

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
Not sure if the changing of the mktemp template will solve the other problem. Not sure how it would be related but I can't duplicate the other issues on my end.

**Comment by lcn2** [comment]
Thanks, @xexyl 

We used the GitHub process to resolve the pull request conflict on hostchk.sh.  Hopefully that went OK.

**Comment by lcn2** [comment]
Well the GitHub process to resolve conflicts did this:

```
 mode change 100755 => 100644 hostchk.sh
```

commit f494ea6a5fa95f070daea981036a8f0dcf0496aa fixed this.

**Comment by xexyl** [comment]
> Well the GitHub process to resolve conflicts did this:
> 
> ```
>  mode change 100755 => 100644 hostchk.sh
> ```
> 
> commit [f494ea6](https://github.com/ioccc-src/mkiocccentry/commit/f494ea6a5fa95f070daea981036a8f0dcf0496aa) puts the executable bits back. :-)

I saw that and I wasn't sure what happened there. Thanks for doing it this way! Ironically I might have to re-fork again .. not sure. I'll find out when I do the next pull request. Not because of this mind you but because I accidentally did a commit on my master branch and then made the same commit on the updates branch.

Hope you had a nice sleep.

**Comment by lcn2** [comment]
We had a nice storm last night, so sleep was entertaining if not less than usual. Hope you sleep better.

**Comment by lcn2** [comment]
We had a nice storm last night, so sleep was more entertaining than long. We hope your sleep is more efficient.

**Comment by xexyl** [comment]
> We had a nice storm last night, so sleep was more entertaining than long. We hope your sleep is more efficient.

Thank you. Unlikely any time soon I'm afraid. I love storms depending on the kind. If it's rain I love listening to it and so it's disappointing when it's in the night. Though ironically the other morning (early) since I was awake I got to listen to the rain .. for a few minutes. It doesn't rain here much at all. Supposed to rain Monday and Tuesday but I'll believe it when it happens.

I used to love lightning and thunder but it scares my dogs so I don't really enjoy it now. Still the sound is incredible and looking at pictures of it - it can be stunning. It's amazing how powerful and beautiful it is. And there it is. Some of the most destructive things in nature can be so beautiful. Volcanoes and fires are two examples but there are others too. What I really like is because volcanic eruptions can have their own weather system you'll sometimes have lightning in them. I have pictures of some instances of these.

Anyway hope you have a better sleep tonight as well!

**Pull request merged**
