### PR TITLE
Fix 'web site' to 'website'

### PR DESCRIPTION
**Pull request by xexyl**
Only one file needed modification, it seemed: jparse/json_README.md.

### CODE REVIEW

**Comment by xexyl** [comment]
> Just to be different, you could have gone from `web site` to `web sight`, just to be different.
> 

Or maybe better yet: `web cite` ? :-)

> Too much?

Probably too much for both, yes.

**Comment by xexyl** [comment]
It was discussed btw and fwiw, in the other repo, mostly to be consistent. I got a laugh out of your comment though and that's **very much appreciated** so thank you! Best wishes to you!

**Comment by lcn2** [comment]
> Just to be different, you could have gone from `web site` to `web sight`, just to be different.  
> 
> 
> 
> Too much?

How about 🕸️👀 @SirWumpus ❓🤓

**Comment by xexyl** [comment]
> > Just to be different, you could have gone from `web site` to `web sight`, just to be different.  
> > 
> > 
> > 
> > Too much?
> 
> How about 🕸️👀 @SirWumpus ❓🤓

That's funny enough that I would do it if it was more obvious. But alas even an FAQ would not be enough. Still thank you for the great laugh! It's brilliant.

**Pull request merged**
