### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
There. I'll worry about the bug report script another day. Going to do something else now. Hopefully tomorrow I will feel a bit better. Hope you have a good rest of your weekend.

**Comment by lcn2** [comment]
this has some good updates and consistency improvements.  Thanks @xexyl

**Comment by xexyl** [comment]
> this has some good updates and consistency improvements. Thanks @xexyl

Thank you as well.

I want to bring up the situation that I brought up in the other thread - in the pull request that I closed - though as I'm not sure what to do about it. Namely that there are two scripts that I cannot update to have a `-V` flag for version. I could add a version string of course for help/usage mode but it would be nice to have a `-V` option too.

The two scripts:

- iocccsize_test.sh: this just has `-V` call `./iocccsize -V` which is not the same thing though maybe it'll work? I don't know.
- jsemcgen.sh: this one is more problematic because it has another use of `-V` entirely. But unfortunately the help string suggests that it shows the version. As I noted before I'm still not entirely sure (and I've not tried to figure it out either I admit) what the purpose of the json semantics tables are for so I can't even update the description of the option. Perhaps you haven't even fully decided what they should look like.

So with those thoughts in mind perhaps you'd like to update these scripts to account for this?

Thank you and have a great evening!

**Comment by xexyl** [comment]
Oh btw I have made a number of updates to the private tool. Mostly it's just string updates but there have been some code updates as well. I'd still love if you (maybe as a reward later on) were to add strings as well.

I do have some changes in mind for it and I recently fixed some typos but I won't copy the file over here until later on.

Anyway will look at this repo tomorrow hopefully but certainly sometime in the week.

**Comment by xexyl** [comment]
BTW: I have more consistency updates for the man pages. I also have some typo fixes. I'll probably commit these tomorrow.

I'm shutting down now and getting ready for sleep after that.

Good night. Please see comment https://github.com/ioccc-src/mkiocccentry/pull/367#issuecomment-1280063315. The changes I have in mind in this comment would not cause a conflict. Anyway until another day - probably tomorrow even if only a little bit.

Sleep well when you do! Good night my friend!

**Comment by lcn2** [comment]
> > this has some good updates and consistency improvements. Thanks @xexyl
> 
> Thank you as well.
> 
> I want to bring up the situation that I brought up in the other thread - in the pull request that I closed - though as I'm not sure what to do about it. Namely that there are two scripts that I cannot update to have a `-V` flag for version. I could add a version string of course for help/usage mode but it would be nice to have a `-V` option too.
> 
> The two scripts:
> 
> * iocccsize_test.sh: this just has `-V` call `./iocccsize -V` which is not the same thing though maybe it'll work? I don't know.

See commit 827ded902077ff2e98d890c84a2953fd7565af08

We added a version string, among lots of other things, to `iocccsize_test.sh`.

Why?  Because the iocccsize_test.sh, as given to the IOCCC, was less than pleasing. :-)

**Comment by lcn2** [comment]
> BTW: I have more consistency updates for the man pages. I also have some typo fixes. I'll probably commit these tomorrow.
> 
> I'm shutting down now and getting ready for sleep after that.
> 
> Good night. Please see comment [#367 (comment)](https://github.com/ioccc-src/mkiocccentry/pull/367#issuecomment-1280063315). The changes I have in mind in this comment would not cause a conflict. Anyway until another day - probably tomorrow even if only a little bit.
> 
> Sleep well when you do! Good night my friend!

See commit 58f9f5b845871f695fbd59f3c8580f7bf916efdf for changes to `iocccsize(1)`.

**Comment by xexyl** [comment]
> > > this has some good updates and consistency improvements. Thanks @xexyl
> > 
> > 
> > Thank you as well.
> > I want to bring up the situation that I brought up in the other thread - in the pull request that I closed - though as I'm not sure what to do about it. Namely that there are two scripts that I cannot update to have a `-V` flag for version. I could add a version string of course for help/usage mode but it would be nice to have a `-V` option too.
> > The two scripts:
> > 
> > * iocccsize_test.sh: this just has `-V` call `./iocccsize -V` which is not the same thing though maybe it'll work? I don't know.
> 
> See commit [827ded9](https://github.com/ioccc-src/mkiocccentry/commit/827ded902077ff2e98d890c84a2953fd7565af08)
> 
> We added a version string, among lots of other things, to `iocccsize_test.sh`.
> 
> Why? Because the iocccsize_test.sh, as given to the IOCCC, was less than pleasing. :-)

Thank you! I see it and it looks great. Hope you're having a nice sleep.

**Comment by xexyl** [comment]
> > BTW: I have more consistency updates for the man pages. I also have some typo fixes. I'll probably commit these tomorrow.
> > I'm shutting down now and getting ready for sleep after that.
> > Good night. Please see comment [#367 (comment)](https://github.com/ioccc-src/mkiocccentry/pull/367#issuecomment-1280063315). The changes I have in mind in this comment would not cause a conflict. Anyway until another day - probably tomorrow even if only a little bit.
> > Sleep well when you do! Good night my friend!
> 
> See commit [58f9f5b](https://github.com/ioccc-src/mkiocccentry/commit/58f9f5b845871f695fbd59f3c8580f7bf916efdf) for changes to `iocccsize(1)`.

I did. Looks good though I have a slight improvement - will commit in a bit I hope. Just a formatting thing with the options (underline specific).

**Comment by lcn2** [comment]
> * jsemcgen.sh: this one is more problematic because it has another use of `-V` entirely. But unfortunately the help string suggests that it shows the version. As I noted before I'm still not entirely sure (and I've not tried to figure it out either I admit) what the purpose of the json semantics tables are for so I can't even update the description of the option. Perhaps you haven't even fully decided what they should look like.

Fixed in commit e3935798def8a0fcddf77cf40689fa63d40f7dcb

**Comment by xexyl** [comment]
> > * jsemcgen.sh: this one is more problematic because it has another use of `-V` entirely. But unfortunately the help string suggests that it shows the version. As I noted before I'm still not entirely sure (and I've not tried to figure it out either I admit) what the purpose of the json semantics tables are for so I can't even update the description of the option. Perhaps you haven't even fully decided what they should look like.
> 
> Fixed in commit [e393579](https://github.com/ioccc-src/mkiocccentry/commit/e3935798def8a0fcddf77cf40689fa63d40f7dcb)

In case I did not already say anything about it - thanks. I think I did say something but just in case.

I'll be shutting the laptop down soon and after that anything will have to wait until tomorrow.

**Pull request merged**
