### PR TITLE
Restructure dbg facility, test suite and soup 

### PR DESCRIPTION
**Pull request by xexyl**
This is a major update which probably can be and if so should be improved (as part of it feels hackish) but it's an important first step to issue #87 Pre-release 1.0 actions.

The dbg facility was moved over to dbg/ subdirectory. This was done via some rules that were recently added to the Makefile. Now when the dbg repo is updated we should be able to just run a rule and the dbg facility in this repo will be synchronised. This will likely be done with the dyn_array facility and later on the JSON parser as well.

Besides changing all '#include "dbg.h"' to '#include "dbg/dbg.h"' this did involve quite a few changes in the Makefile as well. The main thing is that references to dbg related files now are in dbg/ subdirectory with the exception of in the dependencies (dbg.o: line at the end of the Makefile). That latter part might or might not need to be changed in the future.

One of the things that feels like a hack (at least to me) is that instead of using $@ in all cases sometimes we have to use ../$@ because we switched to the dbg subdirectory which means that $@ would no longer be valid.

I also made an important fix to do with changing directories that also has some safety implications. Specifically lines in the form of

     cd foo; ...

were changed to

    cd foo && ...

This is important because if the directory does not exist it can cause a lot of problems depending on the command that follows. In the case of the dbg cloning rules this is probably more important but even the cd test commands are better if we only do the command if the change in directory succeeds (imagine if the test/ directory was removed or is missing for some reason).

Now as far as what can be done to improve this: the subdirectories probably need their own Makefiles. However with dbg there already exists a Makefile so it might need to be modified in some way to work with this repo or else a new Makefile (in addition - not replacing) should be added. Whether that's added to just this repo or the other is not yet determined. The problem with having it just in this repo is that dbg/ is removed - albeit temporarily - in some rules (maybe that's a problem, maybe it's not) so it might be that the new Makefile (maybe Makefile.dbg ?) will have to be in the main directory but this is also to be determined. One thing that might be useful is to make a dbg rule in the main Makefile which does some of the work of the dbg related rules but this will have to be done at another time as well. This is also yet to be determined.

### CODE REVIEW

**Comment by xexyl** [comment]
With the above commits there is no longer a need in the Makefile to `cd foo; ...` as the main Makefile does it via recursive make. 

We can clean up the 'nothing to be done' messages if need be. I tried different combinations of `make clobber all test` (like `make clobber test all` etc.) and it all seems good. Running `./bug_report.sh` does fine as well.

But with these changes (esp commit https://github.com/ioccc-src/mkiocccentry/pull/413/commits/916db953b9462f395e9be6775bb13ee6cfac5f63) we now have a way to integrate other repos when the time comes.

I'm going to do something else now and I don't anticipate working on anything here again today unless maybe there's a fix that needs to be made (assuming I have the time and energy). 

Good day!

**Comment by xexyl** [comment]
... strangely it's a problem under linux. Investigating it now. Will commit a fix when I have one though I'm not sure if I'll be working on it entirely until it is solved. It's a kind of scattered day.

**Comment by lcn2** [comment]
This is a really good step, @xexyl 

So for things look reasonable.  We will dive into the detains and see.

Good call on changing the `test/` directory due to the _test_ Makefile rule.

A minor suggestion: Submit a pull request to rename `ioccc_test` to `test_ioccc`.

**Comment by xexyl** [comment]
> This is a really good step, @xexyl .. well done so far
> 

Thank you. Discovered the problems under linux .. fixing and then will scp to the Mac.

> So for things look reasonable. We will dive into the detains and see.
> 
Sounds good.

> Good call on changing the `test/` directory due to the _test_ Makefile rule.
> 
> A minor suggestion: Submit a pull request to rename `ioccc_test` to `test_ioccc`.

Sure.

**Comment by xexyl** [comment]
Bugs fixed under linux. Copying over to mac and then will worry about renaming the directory. I might be a bit of time though as I have the feeling to go afk for a bit. Not certain of when or how long but I wouldn't be gone for very long.

**Comment by lcn2** [comment]
> > This is a really good step, @xexyl .. well done so far
> 
> Thank you. Discovered the problems under linux .. fixing and then will scp to the Mac.
> 
> > So for things look reasonable. We will dive into the detains and see.
> 
> Sounds good.
> 
> > Good call on changing the `test/` directory due to the _test_ Makefile rule.
> > A minor suggestion: Submit a pull request to rename `ioccc_test` to `test_ioccc`.
> 
> Sure.

Some issues with a major change like this are to be expected.  

So far, it seems you made some good calls your approach, @xexyl.  Nevertheless this is a good framework, once we have a bit long period to work within it, that can be applied elsewhere.

### UDPATE 0

BTW: Under `make release` on macOS 13.0.1:

```
These test(s) failed:

    ioccc_test/jstr_test.sh non-zero exit code: 45

About to exit: 24
make[2]: *** [test] Error 24
make[1]: *** [test] Error 2

./prep.sh: Warning: EXIT_CODE is now: 25

./prep.sh: ERROR: make -f ./Makefile test exit status: 2

=-=-= FAIL: make test =-=-=

=-=-=-=-= Warning: prep.sh error code: 25 =-=-=-=-=

NOTE: The above details were saved in the file: build.log

make: *** [release] Error 1
```

From `build.log`:

```
RUNNING: ioccc_test/jstr_test.sh

ioccc_test/jstr_test.sh -Z /Users/chongo/bench/ioccc/mkiocccentry
rm -f ioccc_test/jstr_test.out ioccc_test/jstr_test2.out
ioccc_test/jstr_test.sh: about to run test #0
./jstrencode: Beginning jencchk test on code JSON encode/decode functions ...
./jstrencode: ... passed JSON encode/decode test
ioccc_test/jstr_test.sh: test #0 passed
ioccc_test/jstr_test.sh: about to run test #1
./jstrencode -v 0 -n < ./jstrencode | ./jstrdecode -v 0 -n > ioccc_test/jstr_test.out
ioccc_test/jstr_test.sh: test #1 passed
ioccc_test/jstr_test.sh: about to run test #2
./jstrencode -v 0 -n < ./jstrdecode | ./jstrdecode -v 0 -n > ioccc_test/jstr_test.out
ioccc_test/jstr_test.sh: test #2 passed
ioccc_test/jstr_test.sh: about to run test #3
cat $SRC_SET | ./jstrencode -v 0 -n | ./jstrdecode -v 0 -n > ioccc_test/jstr_test.out
cat: ../dbg/dbg.c: No such file or directory
cat: ../dbg/dbg.h: No such file or directory
ioccc_test/jstr_test.sh: test #3 failed
ioccc_test/jstr_test.sh: ERROR: test failure detected, about to exit: 45
./ioccc_test.sh: ERROR: ioccc_test/jstr_test.sh non-zero exit code: 45

RUNNING: ioccc_test/jnum_chk
...
```

**Comment by xexyl** [comment]
> > > This is a really good step, @xexyl .. well done so far
> > 
> > 
> > Thank you. Discovered the problems under linux .. fixing and then will scp to the Mac.
> > > So for things look reasonable. We will dive into the detains and see.
> > 
> > 
> > Sounds good.
> > > Good call on changing the `test/` directory due to the _test_ Makefile rule.
> > > A minor suggestion: Submit a pull request to rename `ioccc_test` to `test_ioccc`.
> > 
> > 
> > Sure.
> 
> Some issues with a major change like this are to be expected.
> 
> So far, it seems you made some good calls in your approach, @xexyl. Nevertheless this is a good framework, once we have a bit long period to work within it, that can be applied elsewhere.
> 
> ### UDPATE 0
> BTW: Under `make release` on macOS 13.0.1:
> 
> ```
> These test(s) failed:
> 
>     ioccc_test/jstr_test.sh non-zero exit code: 45
> 
> About to exit: 24
> make[2]: *** [test] Error 24
> make[1]: *** [test] Error 2
> 
> ./prep.sh: Warning: EXIT_CODE is now: 25
> 
> ./prep.sh: ERROR: make -f ./Makefile test exit status: 2
> 
> =-=-= FAIL: make test =-=-=
> 
> =-=-=-=-= Warning: prep.sh error code: 25 =-=-=-=-=
> 
> NOTE: The above details were saved in the file: build.log
> 
> make: *** [release] Error 1
> ```
> 
> From `build.log`:
> 
> ```
> ...
> RUNNING: ioccc_test/jstr_test.sh
> 
> ioccc_test/jstr_test.sh -Z /Users/chongo/bench/ioccc/mkiocccentry
> rm -f ioccc_test/jstr_test.out ioccc_test/jstr_test2.out
> ioccc_test/jstr_test.sh: about to run test #0
> ./jstrencode: Beginning jencchk test on code JSON encode/decode functions ...
> ./jstrencode: ... passed JSON encode/decode test
> ioccc_test/jstr_test.sh: test #0 passed
> ioccc_test/jstr_test.sh: about to run test #1
> ./jstrencode -v 0 -n < ./jstrencode | ./jstrdecode -v 0 -n > ioccc_test/jstr_test.out
> ioccc_test/jstr_test.sh: test #1 passed
> ioccc_test/jstr_test.sh: about to run test #2
> ./jstrencode -v 0 -n < ./jstrdecode | ./jstrdecode -v 0 -n > ioccc_test/jstr_test.out
> ioccc_test/jstr_test.sh: test #2 passed
> ioccc_test/jstr_test.sh: about to run test #3
> cat $SRC_SET | ./jstrencode -v 0 -n | ./jstrdecode -v 0 -n > ioccc_test/jstr_test.out
> cat: ../dbg/dbg.c: No such file or directory
> cat: ../dbg/dbg.h: No such file or directory
> ioccc_test/jstr_test.sh: test #3 failed
> ioccc_test/jstr_test.sh: ERROR: test failure detected, about to exit: 45
> ./ioccc_test.sh: ERROR: ioccc_test/jstr_test.sh non-zero exit code: 45
> 
> RUNNING: ioccc_test/jnum_chk
> ...
> ```

True. It is expected. I'll check that one too. It's not one I had encountered. Thanks for pointing it out.

And yes I think it's a good way forward too.

**Comment by xexyl** [comment]
Oh that issue is the one I encountered under linux - but not macOS. Strange. Anyway I'll have a fix soon.

**Comment by xexyl** [comment]
I stepped away for a bit. Have what should work now .. just going to test it under linux and then will commit if all is good.

**Comment by xexyl** [comment]
> I stepped away for a bit. Have what should work now .. just going to test it under linux and then will commit if all is good.

Done. See commit 9a131f4834a96682d98c74ce8cbf4282fa66ce30.

**Pull request merged**
