### PR TITLE
Documentation updates + resolve several tarball issues in txzchk

### PR DESCRIPTION
**Pull request by xexyl**
Man pages for the iocccsize(1), fnamchk(1) and txzchk(1) tools have been
added.

README.md now tells the user how to get more information and examples of
the tools by referring to the man pages (this includes mkiocccentry).

### CODE REVIEW

**Comment by xexyl** [comment]
Unfortunately I had some bug fixes with the tools but I got a strange error when pushing the changes. It reported that I was behind in git but my fork is up to date and I already had checked out master first before creating the branch.

I was not ready for some of the changes in the tools though and I had already committed. I'm going to do a checkout of the commit in question and then copy it to the new copy of the fork and hopefully I can commit those changes only. If not I'll have to wait until I'm ready for the other changes to be done.

**Comment by xexyl** [comment]
That's been resolved now. I'll now go back to the current changes and work from there. I do think I need a break though as I had a very difficult night last night.

I will note there's a bug with the finding of the tools when invoked by the `mkiocccentry`. I have this fixed by doing a `chdir("..");` and updating the `cmdprintf` call(s) but this will have to be for another time I'm afraid.

I think with a clearer head I'll be able to go through what I have done and test it better. What it is: I *believe* the checking of special bits should be tested but like I said I need to have a break. I'm hoping I can return to it today but if not it'll be tomorrow. Tomorrow I do have something going on but I should still have some time to work on the tool.

**Comment by lcn2** [comment]
> That's been resolved now. I'll now go back to the current changes and work from there. I do think I need a break though as I had a very difficult night last night.
> 
> I will note there's a bug with the finding of the tools when invoked by the `mkiocccentry`. I have this fixed by doing a `chdir("..");` and updating the `cmdprintf` call(s) but this will have to be for another time I'm afraid.
> 
> I think with a clearer head I'll be able to go through what I have done and test it better. What it is: I _believe_ the checking of special bits should be tested but like I said I need to have a break. I'm hoping I can return to it today but if not it'll be tomorrow. Tomorrow I do have something going on but I should still have some time to work on the tool.
> 
> Edit: Okay I've restored the changes to my local copy of my fork so I can proceed next time. This next commit will have the fix for the tool not being able to always execute the correct utilities due to the fact that `mkiocccentry` uses `chdir()` to move away from the original point and into the working directory.

We plan to fix this chdir issue, but we held back until the issue of `txzchk` calling `fnamchk` was resolved: we figured that such a fix would impact the code surrounding the chdir problem.

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> > That's been resolved now. I'll now go back to the current changes and work from there. I do think I need a break though as I had a very difficult night last night.
> > I will note there's a bug with the finding of the tools when invoked by the `mkiocccentry`. I have this fixed by doing a `chdir("..");` and updating the `cmdprintf` call(s) but this will have to be for another time I'm afraid.
> > I think with a clearer head I'll be able to go through what I have done and test it better. What it is: I _believe_ the checking of special bits should be tested but like I said I need to have a break. I'm hoping I can return to it today but if not it'll be tomorrow. Tomorrow I do have something going on but I should still have some time to work on the tool.
> > Edit: Okay I've restored the changes to my local copy of my fork so I can proceed next time. This next commit will have the fix for the tool not being able to always execute the correct utilities due to the fact that `mkiocccentry` uses `chdir()` to move away from the original point and into the working directory.
> 
> We plan to fix this chdir issue, but we held back until the issue of `txzchk` calling `fnamchk` was resolved: we figured that such a fix would impact the code surrounding the chdir problem.

It might yes. Does this resolve it though? I'm still not sure that there's no way that something could cause it to fail. I've only tested running from one parent directory (above the work directory) and also directly invoking the tools. Or maybe you mean you'll add to this?

**Pull request merged**
