### PR TITLE
Move jparse code to jparse/

### PR DESCRIPTION
**Pull request by xexyl**
This is a major update with a lot of files being moved and many files were also changed. There is some clean up required and some things still need to be done but I wanted these changes in. See below.

New file is the jparse/Makefile. Running make depend in the root directory will run make depend in jparse/.

It needs to be cleaned up! This commit is just so the changes are in. I will do some clean up in the next commit. There are some other things that have to be done yet. Amongst these things is to make jparse into a static library. That can also come later. There are some rules in the main Makefile that need to be cleaned up and some that need to be added as well like for the man pages. These can also come in a future commit.

The bug_report.sh was updated not only for this change but also to fix a recent commit when dyn_test was moved from test_ioccc/ to dyn_array/.

I added to options in jparse.l noinput so that at least one warning was no longer triggered. It might be we can remove the -Wno- warnings in the jparse Makefile but I have to look into this further again at a later time.

### CODE REVIEW

**Comment by xexyl** [comment]
I am back for now and I'm aware of a little problem namely that running `make` after `make` it still compiles everything again (or a lot if not everything). I'm guessing the clean up will help there.

**Comment by xexyl** [comment]
With 747439e7262b0596a207ce800bd3022d15810724 I am afraid that I will have to go do other things for now and probably the rest of the day. I'm going to cite the log in the other thread as there certainly are some things that have to be done yet - some of which should probably be discussed first. But at least now the jparse files are under jparse and the test scripts work (including bug_report.sh).

**Comment by lcn2** [comment]
While we plan to accept the hard work you performed (thank you) in moving the jparse code, we are also planning a combination of improvements and in some cases corrections that relate to overall Makefile best practices AND that related to our target multi-directory Makefile design (this is currently a moving target).

One think to note:  The `.PHONY` Makefile rule should **NOT** have real files on the right had side.  The dependency list of `.PHONY` should only include things that **DO NOT** represent physical files in the file system.

We plan to address the `.PHONY` set for all Makefiles to verify that no physical files in the file system are listed as a decency of `.PHONY` AND we plan to verify that all other left-hand makefile rules that are not related to files in the file system (i.e., clean, clobber, all, tags, etc.) are listed as right-land dependencies of the `.PHONY` rule.   Nevertheless such cleanup will happen later.

**Comment by xexyl** [comment]
Yes please do that. It’s been pretty rough for some days and I KNOW there are things that can be done better. As far as the .PHONY that seems to have been an oversight on my part. 

Going to sleep now. Good night.

**Comment by lcn2** [comment]
> Yes please do that. It’s been pretty rough for some days and I KNOW there are things that can be done better. As far as the .PHONY that seems to have been an oversight on my part.
> 
> Going to sleep now. Good night.

See [comment 1354034525](https://github.com/lcn2/dbg/pull/15#issuecomment-1354034525).

We plan to accept this pull request as is, and then apply updates/improvements to the master branch next.

**Comment by xexyl** [comment]
> > Yes please do that. It’s been pretty rough for some days and I KNOW there are things that can be done better. As far as the .PHONY that seems to have been an oversight on my part.
> > Going to sleep now. Good night.
> 
> See [comment 1354034525](https://github.com/lcn2/dbg/pull/15#issuecomment-1354034525).
> 
> We plan to accept this pull request as is, and then apply updates/improvements to the master branch next.

Tomorrow I will. Hope you have a good night.

**Comment by lcn2** [comment]
Thank you @xexyl this pull request reflects good deal of hard work on your part that we plan to expand on and amplify later on.

We suggest that you might want to minimize edits to Makefiles for the near term as we build on this pull request.

Best wishes for a good rest!

**Comment by xexyl** [comment]
> Thank you @xexyl this pull request reflects good deal of hard work on your part that we plan to expand on and amplify later on.
> 
> We suggest that you might want to minimize edits to Makefiles for the near term as we build on this pull request.
> 
> Best wishes for a good rest!

Thank you for the warning. As luck would have it I have been reading again so it is not a problem to not do much. The rest I think is something you are better fit to do anyway. 

Thank you for the good rest wishes. Really going now. Have a great night too!

**Comment by xexyl** [comment]
> > Thank you @xexyl this pull request reflects good deal of hard work on your part that we plan to expand on and amplify later on.
> > We suggest that you might want to minimize edits to Makefiles for the near term as we build on this pull request.
> > Best wishes for a good rest!
> 
> Thank you for the warning. As luck would have it I have been reading again so it is not a problem to not do much. The rest I think is something you are better fit to do anyway.
> 
> Thank you for the good rest wishes. Really going now. Have a great night too!

Take a guess which book. I bet you know even though I just read it. 

Well anyway bedtime now.

**Comment by lcn2** [comment]
> > Thank you @xexyl this pull request reflects good deal of hard work on your part that we plan to expand on and amplify later on.
> > We suggest that you might want to minimize edits to Makefiles for the near term as we build on this pull request.
> > Best wishes for a good rest!
> 
> Thank you for the warning. As luck would have it I have been reading again so it is not a problem to not do much. The rest I think is something you are better fit to do anyway.
> 
> Thank you for the good rest wishes. Really going now. Have a great night too!

It is too bad that the web site is not closer to having collaboration at this stage: there is lots of stuff to edit there .. but right now we cannot accept any web site changes.  We plan to try and get this Makefile set under some level of control, and then take a pause while we work on getting the web site into a state where we can accept pull requests (but NOT now).

**Comment by xexyl** [comment]
> While we plan to accept the hard work you performed (thank you) in moving the jparse code, we are also planning a combination of improvements and in some cases corrections that relate to overall Makefile best practices AND that related to our target multi-directory Makefile design (this is currently a moving target).
> 
> One think to note: The `.PHONY` Makefile rule should **NOT** have real files on the right had side. The dependency list of `.PHONY` should only include things that **DO NOT** represent physical files in the file system.
> 
> We plan to address the `.PHONY` set for all Makefiles to verify that no physical files in the file system are listed as a decency of `.PHONY` AND we plan to verify that all other left-hand makefile rules that are not related to files in the file system (i.e., clean, clobber, all, tags, etc.) are listed as right-land dependencies of the `.PHONY` rule. Nevertheless such cleanup will happen later.


I remember why I added the man page file names to the `.PHONY`. It's because that way one could do for example:


```sh
make dbg.3
```

and have it update by copying the dbg.3 from dbg/ to man/. Now that's not possible:

```sh
$ make dbg.3
make: `dbg.3' is up to date.
```

There are some other problems with some changes made which I will mention in the other thread in a short bit. Then I'll be doing other things. One of the changes you made (with verge) prevents compilation of the repo. I'll include output of course.

**Comment by xexyl** [comment]
> > > Thank you @xexyl this pull request reflects good deal of hard work on your part that we plan to expand on and amplify later on.
> > > We suggest that you might want to minimize edits to Makefiles for the near term as we build on this pull request.
> > > Best wishes for a good rest!
> > 
> > 
> > Thank you for the warning. As luck would have it I have been reading again so it is not a problem to not do much. The rest I think is something you are better fit to do anyway.
> > Thank you for the good rest wishes. Really going now. Have a great night too!
> 
> It is too bad that the web site is not closer to having collaboration at this stage: there is lots of stuff to edit there .. but right now we cannot accept any web site changes. We plan to try and get this Makefile set under some level of control, and then take a pause while we work on getting the web site into a state where we can accept pull requests (but NOT now).

No worries there - other than the change I referred to above that breaks compilation. Since I'm not sure exactly what you have in mind I'll not really look at fixing it - at least not now .. have other things I want to do.

**Pull request merged**
