### PR TITLE
Makefile update for jparse + typo fixes

### PR DESCRIPTION
**Pull request by xexyl**

### CODE REVIEW

**Comment by xexyl** [comment]
This is almost certainly all I'll be doing. Going to watch a film now and anything after that is uncertain.

Have a nice day!

**Comment by lcn2** [comment]
Hope you enjoy your film and then that you have an effective rest, @xexyl.

**Comment by xexyl** [comment]
> Hope you enjoy your film and then that you have an effective rest, @xexyl.

Thank you! Have a great day as well!

**Comment by lcn2** [comment]
And thanks for the good typos catches, @xexyl.

**Comment by xexyl** [comment]
> And thanks for the good typos catches, @xexyl.

No worries - as always.

**Pull request merged**
