### PR TITLE
Initial extraction and parsing of arrays

### PR DESCRIPTION
**Pull request by xexyl**
Initial parsing of manifest array in jinfochk. I am aware of a few issues and some tests still have to be added.

For jauthchk the keyword is _extraction_: the parsing is NOT done. Instead the array
is extracted into a char * (and a strdup()d copy) for parsing as well
as moving past that point in the file. I am aware (and I noted it in the
comments) that if the array is last in the file there's an error but I
will worry about this later: I just wanted this committed since it's now
cleaned up.

I have added two files to test_JSON and I fixed one as well.

Also: if test mode is true (this does not mean the test mode in the json
files though perhaps that could be considered as well: I mean instead -t
passed to the util) then do not return 1 if issues were found. The
warnings will still be printed but the exit status will be 0.

Comment fixes, clean up and typos fixed.

Insignificant but in jinfochk.c and jauthchk.c: strtok_r(): savefield ->
saveptr.

### CODE REVIEW

**Comment by xexyl** [comment]
I am not sure if I'll finish parsing of arrays today but I have started it and so far it looks good.

**Comment by xexyl** [comment]
Checking values of the fields now ... if this goes well I'll commit and then push. Probably that's all I'll do for the day though. If so tomorrow I can work on clean up as well as hopefully the author arrays.

**Comment by xexyl** [comment]
Success! There are some things that have to be done still but the initial parsing and checking of values is done!

**Comment by lcn2** [comment]
Thanks @xexyl

**Comment by xexyl** [comment]
> Thanks @xexyl

Thank you as well!

**Pull request merged**
