### PR TITLE
JSON parser now reads mkiocccentry json files OK

### PR DESCRIPTION
**Pull request by xexyl**
See the git log for details.

I forgot that I enabled debug information in the first commit and I stated that I did this in the second commit but although this bothers me I have other things I want to attend to so I'll just let the redundant and incorrect change sit there.

### CODE REVIEW

**Comment by xexyl** [comment]
I feel good about what I just did - the commits of today. Will continue reading tomorrow (didn't read any today). I think `jparse` is in a good position though for when the parser actually makes a tree and acts on it. Later we can make the other tools make use of `jparse` functions and go from there. I think I'll rename `parse_file` and `parse_string` to `parse_json_file` and `parse_json_string` but that will come at another time. Might be in a bit or might be later or another day.

Hope everything is okay - whatever the issue you mentioned. Best wishes.

**Comment by lcn2** [comment]
Looks like good progress @xexyl

**Comment by lcn2** [comment]
Wondering about the origin of these source files:

- jparse.c
- jparse.tab.c
- jparse.tab.h
- json_parser.c
- json_parser.tab.c 
- json_parser.tab.h

QUESTION: I.e., what are the commands you use to generate those files?

You might consider adding those commands into the Makefile.

QUESTION: What is the version of flex and bison you are using?

On RHEL7 we have:

$ bison -V
bison (GNU Bison) 3.0.4

$ flex -V
flex 2.5.37

On macOS 12.3 we have:

$ bison -V
bison (GNU Bison) 2.3

$ flex -V
flex 2.6.4 Apple(flex-34)

On macOS 12.3 via HomeBrew we have:

$ /opt/homebrew/opt/bison/bin/bison -V
bison (GNU Bison) 3.8.2

$ /opt/homebrew/opt/flex/bin/flex -V
flex 2.6.4

**Comment by xexyl** [comment]
> Looks like good progress @xexyl

Thank you! I agree there indeed. I'm thinking today I'll read. I'll answer your questions next.

**Comment by xexyl** [comment]
> Wondering about the origin of these source files:
> 
> * jparse.c
> * jparse.tab.c
> * jparse.tab.h
> * json_parser.c
> * json_parser.tab.c
> * json_parser.tab.h
> 
> QUESTION: I.e., what are the commands you use to generate those files?
> 

See `make parser`:

```make
parser: jparse.y jparse.l
        ${BISON} -d jparse.y
        ${FLEX} -o jparse.c jparse.l

```


> You might consider adding those commands into the Makefile.
> 

They are just not required. Well _I_ have to run it but not anyone else. I have to run it whenever I update the `jparse.{y,l}` files.

> QUESTION: What is the version of flex and bison you are using?
> 
> On RHEL7 we have:
> 
> $ bison -V bison (GNU Bison) 3.0.4
> 
> $ flex -V flex 2.5.37
> 
I'm not doing it under linux but I can answer that under CentOS I have:

> bison (GNU Bison) 3.0.4
> flex 2.5.37

So same versions. Like I said I can't check my fedora box right now though I really ought to get that problem resolved as eventually I will have to upgrade lest I get to EOL. Actually I'm setting a reminder to do that in the coming week as I won't ever get to it it seems otherwise.


> On macOS 12.3 we have:
> 
> $ bison -V bison (GNU Bison) 2.3
> 
> $ flex -V flex 2.6.4 Apple(flex-34)
> 

> bison (GNU Bison) 2.3
> flex 2.6.4 Apple(flex-34)



> On macOS 12.3 via HomeBrew we have:
> 
> $ /opt/homebrew/opt/bison/bin/bison -V bison (GNU Bison) 3.8.2
> 
> $ /opt/homebrew/opt/flex/bin/flex -V flex 2.6.4
> 

I use MacPorts and I have:

> bison (GNU Bison) 3.8.2
> flex 2.6.4

> Only the macOS 12.3 via HomeBrew v3.8.2 bison is able to process jparse.y, FYI. We presume that the RHEL7 and the macOS bison version are too old.

Interesting. Well fortunately I do it under macOS and you shouldn't have to do it on any other systems i.e. only I have to.

It probably is too old. I know that some of what I use (maybe the `%define`s?) don't work for POSIX Yacc but I don't use that and I remove default rules in make via:

```makefile
%.c: %.y
%.c: %.l
```

in the Makefile. This is important because if I don't do that then whenever I update the `jparse.y` and run make without running `make parser` first it flex overwrites the bison output. This is because I have flex write to `jparse.c` instead of bison. This should probably be fixed but it requires more thought as to which files to use so for now it doesn't do it. I'll test the flex/bison under CentOS to see if it matches though I suspect that given it's the same version as you have under RH it'll be the same problem.

I hope this answers your questions ?

**Comment by xexyl** [comment]
BTW: Is everything okay now? I refer to you having an issue the other night.

Also I hope you're sleeping by now! Take good care and see you another time! Cheers mate.

**Comment by xexyl** [comment]
Under CentOS:

```shell
$ make parser 
bison -d jparse.y
/usr/share/bison/bison.m4:978: error: invalid error_verbose value: 
/usr/share/bison/bison.m4:978: the top level
jparse.y:49.9-19: error: invalid value for %define variable 'parse.error': 'detailed'
 %define parse.error detailed
         ^^^^^^^^^^^
jparse.y:49.9-19:     accepted value: 'simple'
jparse.y:49.9-19:     accepted value: 'verbose'
make: *** [parser] Error 1
```

So I see indeed what you mean. Well fortunately I won't even need that information later on and I do build under macOS so it won't be a problem the way I have its set up: specifically only I have to run `make parser` and eventually we shouldn't have the need to update the parser/lexer and at that point I'll clean up the output files too (maybe - not sure what you think of that but I'd like to get rid of the `goto`s and maybe some other things).

**Comment by xexyl** [comment]
Ah. I know now why I don't have bison write to `jparse.{c,h}`: it's because I use `jparse.h` for specifics that if bison writes to `jparse.c` it also overwrites `jparse.h`. This might be possible to fix by having the same things in the `jparse.y` (though there are prototypes too) but this can come later - though it still bothers me that the lexer writes to `jparse.c` instead of the parser... I'll work it out. Anyway that's why I do it this way.

**Comment by lcn2** [comment]
We probably want to release the code with the output of `bison` and `flex` as C code that can be compiled.

However we also want to put into the Makefile, the ability to re-generate the C code from the `bison` and `flex` input source.  We can add a warning that their `bison` must be at least version **X.Y** and their `flex` must be at least version **A.B**.

Someone doing a `make clobber all` should be able to compile the repo code without worrying if they have `bison` and `flex`, or even if they have the proper versions.  However someone with such code should be able to rebuild the C code from  `bison` and `flex` input via some special Makefile rule.

How about a `make nuke` that does the job of `make clobber` and deletes the `bison` and `flex` generated C code?

Thus is someone did `make nuke all`, they would revert back to the `bison` and `flex` code and the Makefile dependencies would have to include `bison` and `flex`?

**Comment by xexyl** [comment]
> We probably want to release the code with the output of `bison` and `flex` as C code that can be compiled.
> 

It already can be.

> However we also want to put into the Makefile, the ability to re-generate the C code from the `bison` and `flex` input source. We can add a warning that their `bison` must be at least version **X.Y** and their `flex` must be at least version **A.B**.

That already exists but right now I'm the one doing the generation. I think there might even be an option in the tools that force a required version but I'm not sure of that.

> 
> Someone doing a `make clobber all` should be able to compile the repo code without worrying if they have `bison` and `flex`, or even if they have the proper versions. However someone with such code should be able to rebuild the C code from `bison` and `flex` input via some special Makefile rule.

As I already noted they can do `make clobber all` without flex/bison.


> 
> How about a `make nuke` that does the job of `make clobber` and deletes the `bison` and `flex` generated C code?
> 

Could do though that ruins the possibility of me cleaning up the code after everything is in order. But perhaps that's better anyway as it would take a lot of work and effort that might not be worth it. I just find the use of goto distasteful at best except perhaps in actual IOCCC entries.

> Thus is someone did `make nuke all`, they would revert back to the `bison` and `flex` code and the Makefile dependencies would have to include `bison` and `flex`?

Not sure I follow you entirely here. Ah, maybe you mean if they do this the code would be regenerated? It would have to be a special rule that isn't the normal `all` because anyone without flex and bison would be unable to compile the tools that use it. That's kind of what I have already with `parser` rule. For example I do `make parser all` to regenerate the C files (from the flex/bison input files) and then compile everything. But I don't have it as part of the default since not everyone will have flex and bison.

**Comment by lcn2** [comment]
> Could do though that ruins the possibility of me cleaning up the code after everything is in order. But perhaps that's better anyway as it would take a lot of work and effort that might not be worth it. I just find the use of goto distasteful at best except perhaps in actual IOCCC entries.

This is the problem with code generators.  The code they produce is they code, not your code.  Editing generated code is dangerous and very problematic.  it can make it nearly impossible to modify the `bison` and `flex` input later on.

**Comment by lcn2** [comment]
The output of `bison` and `flex` should be created like assembler output from the C compiler, where possible.  The C code they produced may be compiled against, but it is dangerous and problematic to "_hand edit_" that C code.

Someone who wants or needs to rerun `bison` and/or `flex` will stomp on whatever hand edits you make.

**Comment by lcn2** [comment]
We have an idea for how to work the Makefile in regards to `bison` and `flex`.  This idea involves determining if those programs exist and their version is above a minimum threshold.

If `bison` and `flex` exist and are above a minimum threshold, then those tools along with `jparse.l` and `jparse.y` will be used to generate:

- jparse.tab.h
- jparse.tab.c
- jparse.c

If they are not / don't exist, then a _fallback set of source files_ are moved into place to be used / compiled.

The  _fallback set of source files_ would be generated by a special Makefile rule.

To address the _offensive_ C code generated by  `bison` and `flex`, we have an idea about how to prepend near to top, a single _apology_ / _disclaimer_  C comment along with a `#line` directive to reset the line number back to the line  number that would have been in place had the comment not been added.

We will be happy to work on this method and modify the Makefile accordingly.

**Comment by lcn2** [comment]
QUESTION @xexyl :  What generated these files:

- json_parser.c
- json_parser.tab.c
- json_parser.tab.h

They look like `bison` and `flex` output.  However:

```sh
bison -d jparse.y
flex -o jparse.c jparse.l
```

generates these files:

- jparse.tab.h
- jparse.tab.c
- jparse.c

Moreover, those `json_parser.*` files are not referenced by Makefile. 

Is `json_parser.l` and `json_parser.y` missing from the repo?

**Comment by xexyl** [comment]
> > Could do though that ruins the possibility of me cleaning up the code after everything is in order. But perhaps that's better anyway as it would take a lot of work and effort that might not be worth it. I just find the use of goto distasteful at best except perhaps in actual IOCCC entries.
> 
> This is the problem with code generators. The code they produce is they code, not your code. Editing generated code is dangerous and very problematic. it can make it nearly impossible to modify the `bison` and `flex` input later on.

Yeah definitely agree with the last part! It was only some clean up I had in mind but as you say if the grammar changes or anything else changes it's not going to work.

**Comment by xexyl** [comment]
> The output of `bison` and `flex` should be created like assembler output from the C compiler, where possible. The C code they produced may be compiled against, but it is dangerous and problematic to "_hand edit_" that C code.

Agree esp as said if you need to modify the grammar. It was a 'want' and definitely not a 'need' but honestly I probably don't have the energy anyway and I'll be happy to get it done though I am enjoying working on this repo of course!

> 
> Someone who wants or needs to rerun `bison` and/or `flex` will stomp on whatever hand edits you make.
> 

Indeed true. I had that in mind as well: the thought was that it would get into such a state that modifying it would not be necessary BUT ... that's risky itself because what if some new requirement comes up? Then that effort would be wasted.


> The files:
> 
> * jparse.tab.h
> * jparse.tab.c
> * jparse.c
> 
> That are produced by:
> 
> ```shell
> bison -d jparse.y
> flex -o jparse.c jparse.l
> ```
> 
> Should be consider **read-only** source.

I agree thinking on it.

**Comment by xexyl** [comment]
> QUESTION @xexyl : What generated these files:
> 
> * json_parser.c
> * json_parser.tab.c
> * json_parser.tab.h
> 
Ah. These should have been removed. Sorry for the confusion! I just removed them and committed. I'll do a pull request later.


> They look like `bison` and `flex` output. However:
> 
> ```shell
> bison -d jparse.y
> flex -o jparse.c jparse.l
> ```
> 
> generates these files:
> 
> * jparse.tab.h
> * jparse.tab.c
> * jparse.c
> 

Correct.

> Moreover, those `json_parser.*` files are not referenced by Makefile.
> 
> Is `json_parser.l` and `json_parser.y` missing from the repo?

Nope - it was a mistake on my part as above. Sorry for the confusion!

**Comment by xexyl** [comment]
> We have an idea for how to work the Makefile in regards to `bison` and `flex`. This idea involves determining if those programs exist and their version is above a minimum threshold.
> 
> If `bison` and `flex` exist and are above a minimum threshold, then those tools along with `jparse.l` and `jparse.y` will be used to generate:
> 
> * jparse.tab.h
> * jparse.tab.c
> * jparse.c
> 
> If they are not / don't exist, then a _fallback set of source files_ are moved into place to be used / compiled.
> 
> The _fallback set of source files_ would be generated by a special Makefile rule.
> 
> To address the _offensive_ C code generated by `bison` and `flex`, we have an idea about how to prepend near to top, a single _apology_ / _disclaimer_ C comment along with a `#line` directive to reset the line number back to the line number that would have been in place had the comment not been added.
> 

Funny way of putting it. How do you mean offensive though? What specifics?

> We will be happy to work on this method and modify the Makefile accordingly.

Yes please do! Today would also be a good day to do it as I won't be able to do as much. Excited to see what you have in mind!

Good news too: I might have a way I can sleep in more. Today it worked and I hope I can continue doing that. I slept in till 4:30 so that's progress as well.

**Comment by lcn2** [comment]
> Funny way of putting it. How do you mean offensive though? What specifics?

Oh, something about the code being generated by `bison` and `flex`: that the maintainers of the repo do not endorse type of code produced by those tools.

Something like that ... :-)

**Comment by xexyl** [comment]
> > Funny way of putting it. How do you mean offensive though? What specifics?
> 
> Oh, something about the code being generated by `bison` and `flex`: that the maintainers of the repo do not endorse type of code produced by those tools.
> 
> Something like that ... :-)

Well if you mean _this_ repo I also agree with you. What do you have in mind as far as cleaning it up then? And how will you manage that? I guess in the make rule(s) it'll be some sed/awk or some other tools like that ?

**Comment by lcn2** [comment]
> > > Funny way of putting it. How do you mean offensive though? What specifics?
> 
> > 
> 
> > Oh, something about the code being generated by `bison` and `flex`: that the maintainers of the repo do not endorse type of code produced by those tools.
> 
> > 
> 
> > Something like that ... :-)
> 
> 
> 
> Well if you mean _this_ repo I also agree with you. What do you have in mind as far as cleaning it up then? And how will you manage that? I guess in the make rule(s) it'll be some sed/awk or some other tools like that ?

This injection of a comment will be generated by a Makefile rule.  It can be a comment injection only .. no real code modifications.  And this is only for the copy of the files that will be used to compile if the environment does not have the required `flex` and `bison`.

QUESTION: What version of `flex` and `bison` are you developing with?

We can set those versions as the minimum.  If an environment does not have them, then a copy of the C code (generated by the current `parser` rule, with a comment injected at the front, will be moved into place.

**Comment by lcn2** [comment]
> > QUESTION @xexyl : What generated these files:
> 
> > 
> 
> > * json_parser.c
> 
> > * json_parser.tab.c
> 
> > * json_parser.tab.h
> 
> > 
> 
> Ah. These should have been removed. Sorry for the confusion! I just removed them and committed. I'll do a pull request later.
> 
> 
> 
> 
> 
> > They look like `bison` and `flex` output. However:
> 
> > 
> 
> > ```shell
> 
> > bison -d jparse.y
> 
> > flex -o jparse.c jparse.l
> 
> > ```
> 
> > 
> 
> > generates these files:
> 
> > 
> 
> > * jparse.tab.h
> 
> > * jparse.tab.c
> 
> > * jparse.c
> 
> > 
> 
> 
> 
> Correct.
> 
> 
> 
> > Moreover, those `json_parser.*` files are not referenced by Makefile.
> 
> > 
> 
> > Is `json_parser.l` and `json_parser.y` missing from the repo?
> 
> 
> 
> Nope - it was a mistake on my part as above. Sorry for the confusion!

Thanks for the clarification.

We will ignore that code and will look forward to a future pill request that does the `git rm`.

**Comment by xexyl** [comment]
> > > QUESTION @xexyl : What generated these files:
> > 
> > 
> > > 
> > 
> > 
> > > * json_parser.c
> > 
> > 
> > > * json_parser.tab.c
> > 
> > 
> > > * json_parser.tab.h
> > 
> > 
> > > 
> > 
> > 
> > Ah. These should have been removed. Sorry for the confusion! I just removed them and committed. I'll do a pull request later.
> > > They look like `bison` and `flex` output. However:
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > bison -d jparse.y
> > 
> > 
> > > flex -o jparse.c jparse.l
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > generates these files:
> > 
> > 
> > > 
> > 
> > 
> > > * jparse.tab.h
> > 
> > 
> > > * jparse.tab.c
> > 
> > 
> > > * jparse.c
> > 
> > 
> > > 
> > 
> > 
> > Correct.
> > > Moreover, those `json_parser.*` files are not referenced by Makefile.
> > 
> > 
> > > 
> > 
> > 
> > > Is `json_parser.l` and `json_parser.y` missing from the repo?
> > 
> > 
> > Nope - it was a mistake on my part as above. Sorry for the confusion!
> 
> Thanks for the clarification.

Sure.

> 
> We will ignore that code and will look forward to a future pill request that does the `git rm`.

I already committed but I'm working on other changes - as well as interacting with you of course. :)

**Comment by xexyl** [comment]
> > > > Funny way of putting it. How do you mean offensive though? What specifics?
> > 
> > 
> > > 
> > 
> > 
> > > Oh, something about the code being generated by `bison` and `flex`: that the maintainers of the repo do not endorse type of code produced by those tools.
> > 
> > 
> > > 
> > 
> > 
> > > Something like that ... :-)
> > 
> > 
> > Well if you mean _this_ repo I also agree with you. What do you have in mind as far as cleaning it up then? And how will you manage that? I guess in the make rule(s) it'll be some sed/awk or some other tools like that ?
> 
> This injection of a comment will be generated by a Makefile rule. It can be a comment injection only .. no real code modifications. And this is only for the copy of the files that will be used to compile if the environment does not have the required `flex` and `bison`.

Right. Alternatively I could just add the comments in the .l/.y files if you like?

> 
> QUESTION: What version of `flex` and `bison` are you developing with?
> 
> We can set those versions as the minimum. If an environment does not have them, then a copy of the C code (generated by the current `parser` rule, with a comment injected at the front, will be moved into place.

I'm using:

```shell
$ /opt/local/bin/flex -V
flex 2.6.4
$ /opt/local/bin/bison -V|head -n 1
bison (GNU Bison) 3.8.2
```

I won't submit ever under CentOS as that's only console (the server) but I can check what versions are there if you want? The fedora box (whenever I bring that back up) will of course have recent enough versions so no need to worry about that.

Also should I let you know if the versions are updated?

**Comment by xexyl** [comment]
About to do one more commit and then will do a pull request... found a bug too: you had used `%jd` for `uintmax_t` so I changed those to `%ju`.

QUESTION:

Should the string to unsigned (and the signed) long long, int etc. be just switched to the new `uintmax_t` and `intmax_t` versions? If so I can do that but another day I'm afraid. Or maybe later on today but I'm not sure of that.

**Comment by xexyl** [comment]
Just did the pull request ... have to head off now. Good day!

**Comment by lcn2** [comment]
> About to do one more commit and then will do a pull request... found a bug too: you had used `%jd` for `uintmax_t` so I changed those to `%ju`.

Oops, sorry! (tm Canada :))

> QUESTION:
> 
> 
> 
> Should the string to unsigned (and the signed) long long, int etc. be just switched to the new `uintmax_t` and `intmax_t` versions? If so I can do that but another day I'm afraid. Or maybe later on today but I'm not sure of that.

Perhaps the `uintmax_t` and `intmax_t` types would be a better fit?

You might think about adding some Booleans to the integer return value such as:

```c
bool is_negative;
bool int_sized;
bool long_sized;
bool longlong_sized;
bool maxint_sized;
bool uint_sized;
bool ulong_sized;
bool ulonglong_sized;
bool umaxint_sized;
bool too_large;
char *integer_as_str;
union int_ret {
int as_int;
unsigned int as_uint; 
long as_long;
unsigned long as_ulong;
long long as_longlong;
unsigned long long as_ulonglong;
intmax as_maxint;
Uintmax as_umaxint;
} integer;
```

That was the code calling the JSON parser can look at the booleans and decode if they like the JSON integer value, and how they want to cast it.

**Comment by lcn2** [comment]
> > > > > Funny way of putting it. How do you mean offensive though? What specifics?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Oh, something about the code being generated by `bison` and `flex`: that the maintainers of the repo do not endorse type of code produced by those tools.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Something like that ... :-)
> 
> > > 
> 
> > > 
> 
> > > Well if you mean _this_ repo I also agree with you. What do you have in mind as far as cleaning it up then? And how will you manage that? I guess in the make rule(s) it'll be some sed/awk or some other tools like that ?
> 
> > 
> 
> > This injection of a comment will be generated by a Makefile rule. It can be a comment injection only .. no real code modifications. And this is only for the copy of the files that will be used to compile if the environment does not have the required `flex` and `bison`.
> 
> 
> 
> Right. Alternatively I could just add the comments in the .l/.y files if you like?
> 
> 
> 
> > 
> 
> > QUESTION: What version of `flex` and `bison` are you developing with?
> 
> > 
> 
> > We can set those versions as the minimum. If an environment does not have them, then a copy of the C code (generated by the current `parser` rule, with a comment injected at the front, will be moved into place.
> 
> 
> 
> I'm using:
> 
> 
> 
> ```shell
> 
> $ /opt/local/bin/flex -V
> 
> flex 2.6.4
> 
> $ /opt/local/bin/bison -V|head -n 1
> 
> bison (GNU Bison) 3.8.2
> 
> ```
> 
> 
> 
> I won't submit ever under CentOS as that's only console (the server) but I can check what versions are there if you want? The fedora box (whenever I bring that back up) will of course have recent enough versions so no need to worry about that.
> 
> 
> 
> Also should I let you know if the versions are updated? 
> 
> 
> 
> 
> 
> 
> 
> 

We will put into `version.h` the strings indicating those minimum versions.  That way when `version.sh` is generated, the shell script that the Makefile will use can use those values to determine if the tools are good enough.

So later on, if you want to update the `bison` and `flex` tools, you can simply update the values in `version.h`.

These changes (Makefile and shell script) are pending ... stay tuned.

**Comment by xexyl** [comment]
> > About to do one more commit and then will do a pull request... found a bug too: you had used `%jd` for `uintmax_t` so I changed those to `%ju`.
> 
> Oops, sorry! (tm Canada :))
> 

Happens to everyone.

> > QUESTION:
> > Should the string to unsigned (and the signed) long long, int etc. be just switched to the new `uintmax_t` and `intmax_t` versions? If so I can do that but another day I'm afraid. Or maybe later on today but I'm not sure of that.
> 
> Perhaps the `uintmax_t` and `intmax_t` types would be a better fit?

I was thinking for the entire repo btw - does that change the answer?

> 
> You might think about adding some Booleans to the integer return value such as:
> 
> ```c
> /* Sorry for typos & lack of C comments - typed on iPad */
> bool is_negative;
> bool int_sized;
> bool long_sized;
> bool longlong_sized;
> bool maxint_sized;
> bool uint_sized;
> bool ulong_sized;
> bool ulonglong_sized;
> bool umaxint_sized;
> bool too_large;
> char *integer_as_str;
> union int_ret {
>     int as_int;
>     unsigned int as_uint; 
>     long as_long;
>     unsigned long as_ulong;
>     long long as_longlong;
>     unsigned long long as_ulonglong;
>     intmax_t as_maxint;
>     uintmax_t as_umaxint;
> } integer;
> ```
> 
> That was the code calling the JSON parser can look at the booleans and decode if they like the JSON integer value, and how they want to cast it.
> 
> UPDATE: Sorry for typos and lack of C comments above, I'm typing in an iPad. Hopefully you get the concept.

No worries.

> 
> UPDATE: If you want to respond to this comment @xexyl, we suggest do so in [this other comment](https://github.com/ioccc-src/mkiocccentry/issues/68#issuecomment-1079693424) as that other comment thread contains more context.

Doing that now - or so I think. I'm trying to hurry and there are a number of different tabs I have open now!

**Comment by lcn2** [comment]
> I was thinking for the entire repo btw - does that change the answer?

The entire repo should be consistent and this needs changing.  _sigh_

**Comment by xexyl** [comment]
> > I was thinking for the entire repo btw - does that change the answer?
> 
> The entire repo should be consistent and this needs changing. _sigh_

Yeah. Which brings up the question again of why try determining what the smallest size will work for the JSON parser if it's just going to use the max ones. But I'll work that out.

Yes I think it would require some time and work to get this sorted. There are some places you use specific variable types that are important (8-bit int comes to mind) but in most places it can be updated to use the max. I can work on it if you want but it'll be another day. Tomorrow possibly will be a slow day but we shall see.

Heading off again. Have a great rest of your day!

**Pull request merged**
