### PR TITLE
Various updates and fixes

### PR DESCRIPTION
**Pull request by xexyl**
I don't think I'll be doing any more today (or if I do it won't be much) as I'm not feeling well today.

Hope you're having good sleep (or else good morning)!

### CODE REVIEW

**Comment by xexyl** [comment]
The man page is the last thing I'm planning on doing today. That was the spur of the moment actually. Not feeling so well. Going to watch a film and take it easy.

Good day!

**Comment by lcn2** [comment]
Thanks, and we plan to look at these changes in more detail.

**Comment by xexyl** [comment]
> Thanks, and we plan to look at these changes in more detail.

Mind elaborating here? Not sure I understand since it was only comments/typos and a man page added.

**Comment by lcn2** [comment]
With commit 7f3e9d786af8e1c4f617d310d4b183657281f4da we finished our review and made a very slight change:

    Removed redundant stings from vermod.sh

    Now error messages in vermod.sh of the form:

            echo "$0: ERROR: test_dir does not exist: $JSON_TREE" 1>&2

    The type if item in question ("test_dir" in the above example),
    as well the value in error ("$JSON_TREE" in the above example).

**Comment by xexyl** [comment]
> With commit [7f3e9d7](https://github.com/ioccc-src/mkiocccentry/commit/7f3e9d786af8e1c4f617d310d4b183657281f4da) we finished our review and made a very slight change:
> 
> ```
> Removed redundant stings from vermod.sh
> 
> Now error messages in vermod.sh of the form:
> 
>         echo "$0: ERROR: test_dir does not exist: $JSON_TREE" 1>&2
> 
> The type if item in question ("test_dir" in the above example),
> as well the value in error ("$JSON_TREE" in the above example).
> ```

I like that wording. Good update!

**Comment by lcn2** [comment]
> > With commit [7f3e9d7](https://github.com/ioccc-src/mkiocccentry/commit/7f3e9d786af8e1c4f617d310d4b183657281f4da) we finished our review and made a very slight change:
> > ```
> > Removed redundant stings from vermod.sh
> > 
> > Now error messages in vermod.sh of the form:
> > 
> >         echo "$0: ERROR: test_dir does not exist: $JSON_TREE" 1>&2
> > 
> > The type if item in question ("test_dir" in the above example),
> > as well the value in error ("$JSON_TREE" in the above example).
> > ```
> 
> I like that wording. Good update!

Thanks!

**Comment by xexyl** [comment]
> > > With commit [7f3e9d7](https://github.com/ioccc-src/mkiocccentry/commit/7f3e9d786af8e1c4f617d310d4b183657281f4da) we finished our review and made a very slight change:
> > > ```
> > > Removed redundant stings from vermod.sh
> > > 
> > > Now error messages in vermod.sh of the form:
> > > 
> > >         echo "$0: ERROR: test_dir does not exist: $JSON_TREE" 1>&2
> > > 
> > > The type if item in question ("test_dir" in the above example),
> > > as well the value in error ("$JSON_TREE" in the above example).
> > > ```
> > 
> > 
> > I like that wording. Good update!
> 
> Thanks!

Thank you as well!

**Pull request merged**
